SELECT 
	CTP.COD_CARACTERISTICA, 
	CTP.DES_CARACTERISTICA, 
	CTP.COD_CARACTERISTICA_CONTEO 
FROM 
	GEPR_TCARAC_POR_TIPO_PROCESADO CTP
	INNER JOIN GEPR_TTIPO_PROCESADO TP ON TP.OID_TIPO_PROCESADO = CTP.OID_TIPO_PROCESADO
WHERE
	TP.OID_BULTO = []OID_BULTO	