SELECT R.OID_REMESA,
       R.COD_PRECINTO AS PRECINTO_REMESA,
       B.COD_TRANSPORTE,
       R.FYH_FIN_CONTEO,
       B.DES_CLIENTE,
       B.DES_SUBCLIENTE,
       B.DES_PUNTO_SERVICIO,
	   B.FEC_TRANSPORTE
FROM GEPR_TREMESA R
INNER JOIN GEPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA
WHERE R.COD_ESTADO IN ('PR','EN','SA','NEN','NSA','MS','REN','RSA')