SELECT
        SECT.OID_SECTOR
	   ,SECT.OID_PLANTA
FROM
        SAPR_TFORMULARIO FORM
        INNER JOIN GEPR_TTIPO_SECTORXFORMULARIO TSFO ON FORM.OID_FORMULARIO = TSFO.OID_FORMULARIO
        INNER JOIN GEPR_TSECTOR SECT ON TSFO.OID_TIPO_SECTOR = SECT.OID_TIPO_SECTOR
        INNER JOIN GEPR_TCODIGO_AJENO COAJ ON SECT.OID_SECTOR = COAJ.OID_TABLA_GENESIS
WHERE
        TSFO.COD_RELACION_CON_FORMULARIO = []COD_RELACION_CON_FORMULARIO -- INFORMA QUE E PARA VALIDAR SOMENTE CONFIGURAÇÕES DE DESTINO OU ORIGEN
        AND COAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TSECTOR' -- 
        AND COAJ.COD_IDENTIFICADOR = 'IDPS'                
        AND COAJ.COD_AJENO = []COD_AJENO -- VALOR PARAMETRO CONSULTADO
        AND FORM.OID_FORMULARIO = []OID_FORMULARIO -- VALOR PARAMETRO FORMULARIO DE GESTION DE FONDOS + INTEGRACION SALIDAS
