/* Recupera o setor padre(primeiro nivel) do setor informado.
ObtenerSectorPadrePrimerNivel.sql
*/
SELECT 
      SECT.OID_SECTOR,
   SECT.COD_SECTOR,  
   SECT.DES_SECTOR
FROM
   GEPR_TSECTOR SECT
WHERE SECT.OID_SECTOR_PADRE IS NULL
START WITH SECT.OID_SECTOR = []OID_SECTOR
CONNECT BY NOCYCLE SECT.OID_SECTOR = PRIOR SECT.OID_SECTOR_PADRE