SELECT D.OID_DELEGACION,
       D.COD_DELEGACION,
       D.DES_DELEGACION,
       P.OID_PLANTA,
       P.COD_PLANTA,
       P.DES_PLANTA,
       TS.OID_TIPO_SECTOR,
       TS.COD_TIPO_SECTOR,
       TS.DES_TIPO_SECTOR,
       S.OID_SECTOR,
       S.COD_SECTOR,
       S.DES_SECTOR
  FROM GEPR_TSECTOR S
       INNER JOIN GEPR_TTIPO_SECTOR TS ON TS.OID_TIPO_SECTOR = S.OID_TIPO_SECTOR
       INNER JOIN GEPR_TCARACTTIPOSECTORXTIPOSEC TSS ON TSS.OID_TIPO_SECTOR = TS.OID_TIPO_SECTOR
       INNER JOIN GEPR_TCARACT_TIPOSECTOR CTS ON CTS.OID_CARACT_TIPOSECTOR = TSS.OID_CARACT_TIPOSECTOR
       INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
       INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
  WHERE 
	   S.BOL_ACTIVO = 1 AND P.BOL_ACTIVO = 1 AND TS.BOL_ACTIVO = 1 AND D.BOL_VIGENTE = 1
	   AND P.COD_PLANTA = []COD_PLANTA AND D.COD_DELEGACION = []COD_DELEGACION
    {0}
  ORDER BY    
     D.DES_DELEGACION, P.DES_PLANTA, S.DES_SECTOR