SELECT S.OID_SECTOR,
       S.OID_SECTOR_PADRE,
       S.OID_TIPO_SECTOR,
       S.OID_PLANTA,
       S.COD_SECTOR,
       S.DES_SECTOR,
       S.COD_MIGRACION,
       S.BOL_CENTRO_PROCESO,
       S.BOL_PERMITE_DISPONER_VALOR,
       S.BOL_TESORO,
       S.BOL_CONTEO,
       S.BOL_ACTIVO,
       S.GMT_CREACION,
       S.DES_USUARIO_CREACION,
       S.GMT_MODIFICACION,
       S.DES_USUARIO_MODIFICACION
FROM GEPR_TSECTOR S
WHERE S.OID_SECTOR = (SELECT C.OID_TABLA_GENESIS
                    FROM GEPR_TCODIGO_AJENO C
                    WHERE C.COD_AJENO = []COD_AJENO AND COD_IDENTIFICADOR = 'IDPS' AND COD_TIPO_TABLA_GENESIS = 'GEPR_TSECTOR')