SELECT
   SE.OID_SECTOR
  ,SE.OID_SECTOR_PADRE
  ,SE.COD_SECTOR
  ,SE.DES_SECTOR
  ,SE.BOL_ACTIVO AS SE_BOL_ACTIVO
  ,SE.BOL_CENTRO_PROCESO
  ,SE.BOL_CONTEO
  ,SE.BOL_TESORO
  ,SE.BOL_PERMITE_DISPONER_VALOR
  ,D.OID_DELEGACION
  ,D.COD_PAIS
  ,D.COD_DELEGACION
  ,D.DES_DELEGACION
  ,D.BOL_VIGENTE AS D_BOL_VIGENTE
  ,D.OID_PAIS
  ,D.NEC_GMT_MINUTOS
  ,D.FYH_VERANO_INICIO
  ,D.FYH_VERANO_FIN
  ,D.NEC_VERANO_AJUSTE
  ,D.DES_ZONA
  ,P.OID_PLANTA
  ,P.COD_PLANTA
  ,P.DES_PLANTA
  ,P.BOL_ACTIVO AS P_BOL_ACTIVO
  ,TSE.BOL_ACTIVO AS TSE_BOL_ACTIVO
  ,TSE.COD_TIPO_SECTOR
  ,TSE.DES_TIPO_SECTOR
  ,TSE.OID_TIPO_SECTOR

      FROM GEPR_TSECTOR SE
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SE.OID_PLANTA
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN GEPR_TTIPO_SECTOR TSE ON TSE.OID_TIPO_SECTOR = SE.OID_TIPO_SECTOR
INNER JOIN GEPR_TCARACTTIPOSECTORXTIPOSEC CTSTS ON (CTSTS.OID_TIPO_SECTOR = TSE.OID_TIPO_SECTOR)
INNER JOIN GEPR_TCARACT_TIPOSECTOR CTS ON (CTS.OID_CARACT_TIPOSECTOR = CTSTS.OID_CARACT_TIPOSECTOR)
     WHERE D.COD_DELEGACION = []COD_DELEGACION
       AND P.COD_PLANTA = []COD_PLANTA
