SELECT OID_SECTOR,
       OID_SECTOR_PADRE,
       OID_TIPO_SECTOR,
       OID_PLANTA,
       COD_SECTOR,
       DES_SECTOR,
       COD_MIGRACION,
       BOL_CENTRO_PROCESO,
       BOL_PERMITE_DISPONER_VALOR,
       BOL_TESORO,
       BOL_CONTEO,
       BOL_ACTIVO,
       GMT_CREACION,
       DES_USUARIO_CREACION,
       GMT_MODIFICACION,
       DES_USUARIO_MODIFICACION
  FROM GEPR_TSECTOR
 WHERE OID_SECTOR = []pOID_SECTOR
