SELECT
 S.OID_SECTOR,
S.OID_SECTOR_PADRE,
S.OID_TIPO_SECTOR,
S.OID_PLANTA,
S.COD_SECTOR,
S.DES_SECTOR,
S.COD_MIGRACION,
S.BOL_CENTRO_PROCESO,
S.BOL_PERMITE_DISPONER_VALOR,
S.BOL_TESORO,
S.BOL_CONTEO,
S.BOL_ACTIVO,
S.GMT_CREACION,
S.DES_USUARIO_CREACION,
S.GMT_MODIFICACION,
S.DES_USUARIO_MODIFICACION

  FROM GEPR_TSECTOR S
  INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA 
  INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
  INNER JOIN (SELECT
       S.OID_SECTOR
  FROM
         GEPR_TSECTOR S
         INNER JOIN GEPR_TCARACTTIPOSECTORXTIPOSEC C ON C.OID_TIPO_SECTOR = S.OID_TIPO_SECTOR
          INNER JOIN GEPR_TCARACT_TIPOSECTOR CTS ON C.OID_CARACT_TIPOSECTOR = CTS.OID_CARACT_TIPOSECTOR
  {0}
  GROUP BY S.OID_SECTOR
  HAVING  COUNT(CTS.COD_CARACT_TIPOSECTOR) = {1})CS
  ON CS.OID_SECTOR = S.OID_SECTOR
  WHERE D.COD_DELEGACION = []pCOD_DELEGACION
  AND P.COD_PLANTA = []pCOD_PLANTA