SELECT 
    SECT.COD_SECTOR,
    SECT.DES_SECTOR,
    DELE.COD_DELEGACION,
    TRIM(DELE.DES_DELEGACION) DES_DELEGACION
FROM 
    GEPR_TSECTOR SECT
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION
    INNER JOIN GEPR_TTIPO_SECTOR TSECT ON TSECT.OID_TIPO_SECTOR = SECT.OID_TIPO_SECTOR
    INNER JOIN GEPR_TCARACTTIPOSECTORXTIPOSEC TSS ON TSS.OID_TIPO_SECTOR = TSECT.OID_TIPO_SECTOR
    INNER JOIN GEPR_TCARACT_TIPOSECTOR CTS ON CTS.OID_CARACT_TIPOSECTOR = TSS.OID_CARACT_TIPOSECTOR
WHERE SECT.BOL_ACTIVO = 1 
    AND PLANT.BOL_ACTIVO = 1 
    AND TSECT.BOL_ACTIVO = 1 
    AND DELE.BOL_VIGENTE = 1
    {0}
    AND CTS.COD_CARACT_TIPOSECTOR <> 'PUESTO'
GROUP BY SECT.COD_SECTOR,
    SECT.DES_SECTOR,
    DELE.COD_DELEGACION,
    DELE.DES_DELEGACION, 
    PLANT.DES_PLANTA
ORDER BY TRIM(DELE.DES_DELEGACION), PLANT.DES_PLANTA, SECT.DES_SECTOR