WITH Q AS(
SELECT DISTINCT TS.COD_TIPO_SECTOR FROM ADPR_TDELE_TIPO_ROLE_USR DTRU
INNER JOIN ADPR_TPLANTA_TIPO_SECTOR PTS ON PTS.OID_PLANTA_TIPO_SECTOR = DTRU.OID_PLANTA_TIPO_SECTOR
INNER JOIN ADPR_TUSUARIO U ON U.OID_USUARIO = DTRU.OID_USUARIO
INNER JOIN ADPR_TPLANTA P ON P.OID_PLANTA = PTS.OID_PLANTA
INNER JOIN ADPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN ADPR_TTIPO_SECTOR TS ON TS.OID_TIPO_SECTOR = PTS.OID_TIPO_SECTOR
INNER JOIN ADPR_TROLE ROL ON ROL.OID_ROLE = DTRU.OID_ROLE
INNER JOIN ADPR_TAPLICACION APL ON APL.OID_APLICACION = ROL.OID_APLICACION
WHERE DTRU.OID_PLANTA_TIPO_SECTOR IS NOT NULL AND UPPER(U.DES_LOGIN) = []DES_LOGIN
AND D.COD_DELEGACION = []COD_DELEGACION AND P.COD_PLANTA = []COD_PLANTA AND APL.COD_APLICACION = 'GenesisMovil')
SELECT DISTINCT S.OID_SECTOR,S.COD_SECTOR,S.DES_SECTOR
FROM GEPR_TSECTOR S
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN GEPR_TTIPO_SECTOR TS ON TS.OID_TIPO_SECTOR = S.OID_TIPO_SECTOR
INNER JOIN GEPR_TCARACTTIPOSECTORXTIPOSEC CTST ON CTST.OID_TIPO_SECTOR = TS.OID_TIPO_SECTOR
INNER JOIN GEPR_TCARACT_TIPOSECTOR CTS ON CTS.OID_CARACT_TIPOSECTOR = CTST.OID_CARACT_TIPOSECTOR
INNER JOIN Q ON Q.COD_TIPO_SECTOR = TS.COD_TIPO_SECTOR
WHERE CTS.COD_CARACT_TIPOSECTOR IN('TES','SAL','RECE-DIST') AND S.OID_SECTOR_PADRE IS NULL
AND D.COD_DELEGACION = []COD_DELEGACION AND P.COD_PLANTA = []COD_PLANTA
ORDER BY S.DES_SECTOR