SELECT S.OID_SECTOR,
       S.OID_SECTOR_PADRE,
       S.OID_TIPO_SECTOR,
       S.OID_PLANTA,
       S.COD_SECTOR,
       S.DES_SECTOR,
       S.COD_MIGRACION,
       S.BOL_CENTRO_PROCESO,
       S.BOL_PERMITE_DISPONER_VALOR,
       S.BOL_TESORO,
       S.BOL_CONTEO,
       S.BOL_ACTIVO,
       S.GMT_CREACION,
       S.DES_USUARIO_CREACION,
       S.GMT_MODIFICACION,
       S.DES_USUARIO_MODIFICACION
  FROM GEPR_TSECTOR S
	   INNER JOIN GEPR_TSECTOR SP ON SP.OID_SECTOR = S.OID_SECTOR_PADRE
       INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
       INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
 WHERE SP.COD_SECTOR = []COD_SECTOR_PADRE
	   {0}