SELECT
  DISTINCT
  -- DELEGACIÓN
  DELE.OID_DELEGACION,
  DELE.COD_DELEGACION,
  DELE.DES_DELEGACION,
  -- PLANTA
  PLANT.OID_PLANTA,
  PLANT.COD_PLANTA,
  PLANT.DES_PLANTA,  
  -- SECTOR
  SECT.OID_SECTOR,
  SECT.OID_SECTOR_PADRE,
  SECT.OID_TIPO_SECTOR,
  SECT.COD_SECTOR,
  SECT.DES_SECTOR,
  SECT.BOL_ACTIVO,
  -- TIPO SECTOR Y CARACTERISTICAS
  TISE.OID_TIPO_SECTOR,
  TISE.COD_TIPO_SECTOR,
  TISE.DES_TIPO_SECTOR,
  CARA.OID_CARACT_TIPOSECTOR,
  CARA.COD_CARACT_TIPOSECTOR,
  CARA.DES_CARACT_TIPOSECTOR
FROM
  GEPR_TSECTOR SECT
  INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
  INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION
  INNER JOIN GEPR_TTIPO_SECTOR TISE ON SECT.OID_TIPO_SECTOR = TISE.OID_TIPO_SECTOR
  INNER JOIN GEPR_TCARACTTIPOSECTORXTIPOSEC CATS ON TISE.OID_TIPO_SECTOR = CATS.OID_TIPO_SECTOR
  INNER JOIN GEPR_TCARACT_TIPOSECTOR CARA ON CATS.OID_CARACT_TIPOSECTOR = CARA.OID_CARACT_TIPOSECTOR
  
WHERE
  SECT.BOL_ACTIVO = 1
  AND PLANT.COD_PLANTA = []COD_PLANTA
  AND DELE.COD_DELEGACION = []COD_DELEGACION
  
START WITH SECT.OID_SECTOR_PADRE IS NULL
CONNECT BY NOCYCLE PRIOR SECT.OID_SECTOR = SECT.OID_SECTOR_PADRE

ORDER BY 1, 4, 7, 12, 15
