SELECT DEL.COD_DELEGACION, PLA.COD_PLANTA, SEC.COD_SECTOR,MAQ.OID_MAQUINA
  FROM SAPR_TMAQUINA MAQ
 INNER JOIN GEPR_TSECTOR SEC
    ON SEC.OID_SECTOR = MAQ.OID_SECTOR
 INNER JOIN GEPR_TPLANTA PLA
    ON PLA.OID_PLANTA = SEC.OID_PLANTA
 INNER JOIN GEPR_TDELEGACION DEL
    ON DEL.OID_DELEGACION = PLA.OID_DELEGACION
 WHERE MAQ.COD_IDENTIFICACION = []COD_IDENTIFICACION
