INSERT INTO SAPR_TABONO_SNAPSHOT
(OID_ABONO_SNAPSHOT,OID_ABONO,OID_CLIENTE,OID_SUBCLIENTE,OID_PTO_SERVICIO,
OID_SUBCANAL,OID_DIVISA,NUM_IMPORTE,GMT_CREACION,
DES_USUARIO_CREACION,GMT_MODIFICACION,DES_USUARIO_MODIFICACION)
VALUES
([]OID_ABONO_SNAPSHOT,[]OID_ABONO,[]OID_CLIENTE,[]OID_SUBCLIENTE,[]OID_PTO_SERVICIO,
[]OID_SUBCANAL,[]OID_DIVISA,[]NUM_IMPORTE,FN_GMT_ZERO_###VERSION###,
[]DES_USUARIO_CREACION,FN_GMT_ZERO_###VERSION###,[]DES_USUARIO_MODIFICACION)