WITH VALORES AS (     
     SELECT 
        SAL.OID_ABONO_SNAPSHOT,     
        'EFECTIVO' TIPO_MEDIO_PAGO,
        SAL.OID_CUENTA_SALDO,
        SAL.OID_DIVISA,
        SAL.OID_DENOMINACION OID_DEN_MP,
        SAL.COD_NIVEL_DETALLE,
        SAL.OID_CALIDAD,
        SAL.OID_UNIDAD_MEDIDA,
        SAL.COD_TIPO_EFECTIVO_TOTAL,
        /*CLIENTE*/
        C.OID_CLIENTE,
        C.COD_CLIENTE,
        C.DES_CLIENTE,
        /*SUB_CLIENTE*/
        C.OID_SUBCLIENTE,
        C.COD_SUBCLIENTE,
        C.DES_SUBCLIENTE,
        /*PTO_SERVICIO*/
        C.OID_PTO_SERVICIO,
        C.COD_PTO_SERVICIO,
        C.DES_PTO_SERVICIO,
        /*SUB_CANAL*/
        C.OID_SUBCANAL,
        C.COD_SUBCANAL,
        C.DES_SUBCANAL,
		/*CANAL*/
		C.OID_CANAL,
		C.COD_CANAL,
		C.DES_CANAL,
		SAL.NUM_IMPORTE IMPORTE,
		SAL.NEL_CANTIDAD CANTIDAD,
		0 AS CUANT_CUENTAS
     FROM SAPR_TABONO_SNAPSHOT_EFECTIVO SAL     
     INNER JOIN SAPR_VCUENTA C ON C.OID_CUENTA = SAL.OID_CUENTA_SALDO
     /*GROUP BY SAL.OID_ABONO_SNAPSHOT, SAL.OID_CUENTA_SALDO,SAL.OID_DIVISA,SAL.OID_DENOMINACION,SAL.COD_NIVEL_DETALLE,
  SAL.OID_CALIDAD,SAL.OID_UNIDAD_MEDIDA,SAL.COD_TIPO_EFECTIVO_TOTAL,
  C.OID_CLIENTE,C.COD_CLIENTE,C.DES_CLIENTE,C.OID_SUBCLIENTE,C.COD_SUBCLIENTE,C.DES_SUBCLIENTE,
  C.OID_PTO_SERVICIO,C.COD_PTO_SERVICIO,C.DES_PTO_SERVICIO,C.OID_SUBCANAL,C.COD_SUBCANAL,C.DES_SUBCANAL*/

UNION     

     SELECT 
        SAL.OID_ABONO_SNAPSHOT,
        SAL.COD_TIPO_MEDIO_PAGO TIPO_MEDIO_PAGO,
        SAL.OID_CUENTA_SALDO,
        SAL.OID_DIVISA,
        SAL.OID_MEDIO_PAGO OID_DEN_MP,
        SAL.COD_NIVEL_DETALLE,
        NULL AS OID_CALIDAD,
        SAL.OID_UNIDAD_MEDIDA,
        NULL AS COD_TIPO_EFECTIVO_TOTAL,
        /*CLIENTE*/
        C.OID_CLIENTE,
        C.COD_CLIENTE,
        C.DES_CLIENTE,
        /*SUB_CLIENTE*/
        C.OID_SUBCLIENTE,
        C.COD_SUBCLIENTE,
        C.DES_SUBCLIENTE,
        /*PTO_SERVICIO*/
        C.OID_PTO_SERVICIO,
        C.COD_PTO_SERVICIO,
        C.DES_PTO_SERVICIO,
        /*SUB_CANAL*/
        C.OID_SUBCANAL,
        C.COD_SUBCANAL,
        C.DES_SUBCANAL,
		/*CANAL*/
		C.OID_CANAL,
		C.COD_CANAL,
		C.DES_CANAL,
		SAL.NUM_IMPORTE IMPORTE,
		SAL.NEL_CANTIDAD CANTIDAD,
		0 AS CUANT_CUENTAS
     FROM SAPR_TABONO_SNAPSHOT_MEDIOPAGO SAL
     INNER JOIN SAPR_VCUENTA C ON C.OID_CUENTA = SAL.OID_CUENTA_SALDO
     /*GROUP BY SAL.OID_ABONO_SNAPSHOT, SAL.OID_CUENTA_SALDO,SAL.OID_DIVISA,SAL.COD_TIPO_MEDIO_PAGO,SAL.OID_MEDIO_PAGO,SAL.COD_NIVEL_DETALLE,SAL.OID_UNIDAD_MEDIDA,
	  C.OID_CLIENTE,C.COD_CLIENTE,C.DES_CLIENTE,C.OID_SUBCLIENTE,C.COD_SUBCLIENTE,C.DES_SUBCLIENTE,
      C.OID_PTO_SERVICIO,C.COD_PTO_SERVICIO,C.DES_PTO_SERVICIO,C.OID_SUBCANAL,C.COD_SUBCANAL,C.DES_SUBCANAL*/
)
SELECT
V.*
FROM SAPR_TABONO_SNAPSHOT S
INNER JOIN VALORES V ON V.OID_ABONO_SNAPSHOT = S.OID_ABONO_SNAPSHOT
WHERE S.OID_ABONO = []OID_ABONO