 SELECT
       SALDO.OID_CONFIG_NIVEL_SALDO AS OID_SALDO,
       SALDO.OID_CLIENTE AS OID_CLI_SALDO,
       CLI_SALDO.COD_CLIENTE AS COD_CLI_SALDO,
       CLI_SALDO.DES_CLIENTE AS DES_CLI_SALDO,
       SALDO.OID_SUBCLIENTE AS OID_SUB_CLI_SALDO,
       SUB_CLI_SALDO.COD_SUBCLIENTE AS COD_SUB_CLI_SALDO,
       SUB_CLI_SALDO.DES_SUBCLIENTE AS DES_SUB_CLI_SALDO,
       SALDO.OID_PTO_SERVICIO AS OID_PTO_SERV_SALDO,
       PS_SALDO.COD_PTO_SERVICIO AS COD_PTO_SERV_SALDO,
       PS_SALDO.DES_PTO_SERVICIO AS DES_PTO_SERV_SALDO,
       SALDO.GMT_CREACION AS GMT_CREACION_SALDO,
       SALDO.DES_USUARIO_CREACION AS DES_USUARIO_CREACION_SALDO,
       SALDO.GMT_MODIFICACION AS GMT_MODIFICACION_SALDO,
       SALDO.DES_USUARIO_MODIFICACION AS DES_USUARIO_MODIFICACION_SALDO,
       MOV.OID_CONFIG_NIVEL_MOVIMIENTO AS OID_MOV,
       MOV.OID_CLIENTE AS OID_CLI_MOV,
       CLI_MOV.COD_CLIENTE AS COD_CLI_MOV,
       CLI_MOV.DES_CLIENTE AS DES_CLI_MOV,
       MOV.OID_SUBCLIENTE AS OID_SUB_CLI_MOV,
       SUB_CLI_MOV.COD_SUBCLIENTE AS COD_SUB_CLI_MOV,
       SUB_CLI_MOV.DES_SUBCLIENTE AS DES_SUB_CLI_MOV,
       MOV.OID_PTO_SERVICIO AS OID_PTO_SERV_MOV,
       PS_MOV.COD_PTO_SERVICIO AS COD_PTO_SERV_MOV,
       PS_MOV.DES_PTO_SERVICIO AS DES_PTO_SERV_MOV,
       MOV.OID_SUBCANAL AS OID_SUB_CANAL_MOV,
       SUB_CAN.COD_SUBCANAL AS COD_SUB_CANAL_MOV,
       SUB_CAN.DES_SUBCANAL AS DES_SUB_CANAL_MOV,
       MOV.FYH_VIGENCIA AS FYH_VIGENCIA_MOV,
       MOV.BOL_ACTIVO AS BOL_ACTIVO_MOV,
       MOV.GMT_CREACION AS GMT_CREACION_MOV,
       MOV.DES_USUARIO_CREACION AS DES_USUARIO_CREACION_MOV,
       MOV.GMT_MODIFICACION AS GMT_MODIFICACION_MOV,
       MOV.DES_USUARIO_MODIFICACION AS DES_USUARIO_MODIFICACION_MOV

  FROM SAPR_TCONFIG_NIVEL_MOVIMIENTO MOV
 INNER JOIN SAPR_TCONFIG_NIVEL_SALDO SALDO ON SALDO.OID_CONFIG_NIVEL_SALDO = MOV.OID_CONFIG_NIVEL_SALDO
 INNER JOIN GEPR_TCLIENTE CLI_SALDO ON CLI_SALDO.OID_CLIENTE = SALDO.OID_CLIENTE
 INNER JOIN GEPR_TCLIENTE CLI_MOV ON CLI_MOV.OID_CLIENTE = MOV.OID_CLIENTE
  LEFT JOIN GEPR_TSUBCLIENTE SUB_CLI_SALDO ON SUB_CLI_SALDO.OID_SUBCLIENTE = SALDO.OID_SUBCLIENTE
  LEFT JOIN GEPR_TSUBCLIENTE SUB_CLI_MOV ON SUB_CLI_MOV.OID_SUBCLIENTE = MOV.OID_SUBCLIENTE
  LEFT JOIN GEPR_TPUNTO_SERVICIO PS_SALDO ON PS_SALDO.OID_PTO_SERVICIO = SALDO.OID_PTO_SERVICIO
  LEFT JOIN GEPR_TPUNTO_SERVICIO PS_MOV ON PS_MOV.OID_PTO_SERVICIO = MOV.OID_PTO_SERVICIO
  LEFT JOIN GEPR_TSUBCANAL SUB_CAN ON SUB_CAN.OID_SUBCANAL = MOV.OID_SUBCANAL
  
 WHERE CLI_MOV.COD_CLIENTE = []COD_CLIENTE