INSERT INTO SAPR_TVALOR_IACXREMESA
(OID_VALOR_IACXREMESA
,OID_REMESA
,OID_TERMINO
,DES_VALOR_IAC
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION)
VALUES
([]OID_VALOR_IACXREMESA
,[]OID_REMESA
,[]OID_TERMINO
,[]DES_VALOR_IAC
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_CREACION
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_MODIFICACION)