SELECT TIAC.COD_TERMINO AS COD_TERMINO_IAC,
       IACR.DES_VALOR_IAC
FROM SAPR_TVALOR_IACXREMESA IACR
INNER JOIN GEPR_TTERMINO TIAC ON TIAC.OID_TERMINO = IACR.OID_TERMINO
WHERE IACR.OID_REMESA = []OID_ELEMENTO