SELECT TM.COD_TIPO_MERCANCIA,
       TM.DES_TIPO_MERCANCIA,
       TM.OID_TIPO_MERCANCIA,
	   RTM.OID_REMESA
FROM GEPR_TTIPO_MERCANCIA TM
INNER JOIN GEPR_TREMESA_TIPO_MERCANCIA RTM ON RTM.OID_TIPO_MERCANCIA = TM.OID_TIPO_MERCANCIA
{0}