SELECT TM.COD_TIPO_MERCANCIA,
       TM.DES_TIPO_MERCANCIA,
       TM.OID_TIPO_MERCANCIA,
	   BTM.OID_BULTO 
FROM GEPR_TTIPO_MERCANCIA TM
INNER JOIN GEPR_TBULTO_TIPO_MERCANCIA BTM ON BTM.OID_TIPO_MERCANCIA = TM.OID_TIPO_MERCANCIA
{0}