SELECT 
	CLI.COD_CLIENTE, 
	CLI.DES_CLIENTE, 
	SUB.COD_SUBCLIENTE, 
	SUB.DES_SUBCLIENTE, 
	PSERV.COD_PTO_SERVICIO, 
	PSERV.DES_PTO_SERVICIO, 
	CAJ.OID_CAJERO, 
	CAJ.COD_CAJERO, 
	MCAJ.DES_MODELO_CAJERO, 
	RED.DES_RED	
FROM 
	GEPR_TCLIENTE CLI 
	INNER JOIN GEPR_TSUBCLIENTE SUB ON CLI.OID_CLIENTE = SUB.OID_CLIENTE 
	INNER JOIN GEPR_TPUNTO_SERVICIO PSERV ON SUB.OID_SUBCLIENTE = PSERV.OID_SUBCLIENTE 
	INNER JOIN GEPR_TCAJERO CAJ ON CAJ.OID_PTO_SERVICIO = PSERV.OID_PTO_SERVICIO 
	LEFT OUTER JOIN GEPR_TMODELO_CAJERO MCAJ ON MCAJ.OID_MODELO_CAJERO = CAJ.OID_MODELO_CAJERO 
	LEFT OUTER JOIN GEPR_TRED RED ON CAJ.OID_RED = RED.OID_RED 
WHERE 
	CLI.COD_CLIENTE = []COD_CLIENTE 
	AND SUB.COD_SUBCLIENTE = []COD_SUBCLIENTE 
	AND PSERV.COD_PTO_SERVICIO = []COD_PTO_SERVICIO