SELECT  GEPR_TCAJERO.OID_CAJERO,
       GEPR_TCAJERO.COD_CAJERO,
       GEPR_TRED.COD_RED,
       GEPR_TMODELO_CAJERO.COD_MODELO_CAJERO,
       GEPR_TGRUPO.OID_GRUPO,
       GEPR_TCAJERO.BOL_REGISTRO_TIRA,
       GEPR_TCLIENTE.COD_CLIENTE,
       GEPR_TCLIENTE.DES_CLIENTE,
       GEPR_TSUBCLIENTE.COD_SUBCLIENTE,
       GEPR_TSUBCLIENTE.DES_SUBCLIENTE,
       GEPR_TPUNTO_SERVICIO.COD_PTO_SERVICIO,
       GEPR_TPUNTO_SERVICIO.DES_PTO_SERVICIO,
       GEPR_TCAJERO.BOL_VIGENTE,
       GEPR_TCAJERO.FYH_ACTUALIZACION,
	   GEPR_TCAJEROXMORFOLOGIA.OID_MORFOLOGIA,
	   GEPR_TCAJEROXMORFOLOGIA.FEC_INICIO,
	   GEPR_TMORFOLOGIA.BOL_VIGENTE AS BOL_VIGENTE_MORFOLOGIA,
	   GEPR_TMORFOLOGIA.NEC_MODALIDAD_RECOGIDA
  FROM GEPR_TCAJERO
  LEFT JOIN GEPR_TPUNTO_SERVICIO ON (GEPR_TCAJERO.OID_PTO_SERVICIO = GEPR_TPUNTO_SERVICIO.OID_PTO_SERVICIO)
  LEFT JOIN GEPR_TRED ON (GEPR_TCAJERO.OID_RED = GEPR_TRED.OID_RED)
  LEFT JOIN GEPR_TMODELO_CAJERO ON (GEPR_TCAJERO.OID_MODELO_CAJERO = GEPR_TMODELO_CAJERO.OID_MODELO_CAJERO)
  LEFT JOIN GEPR_TGRUPO ON (GEPR_TCAJERO.OID_GRUPO = GEPR_TGRUPO.OID_GRUPO)
  LEFT JOIN GEPR_TSUBCLIENTE ON (GEPR_TPUNTO_SERVICIO.OID_SUBCLIENTE = GEPR_TSUBCLIENTE.OID_SUBCLIENTE)
  LEFT JOIN GEPR_TCLIENTE ON (GEPR_TSUBCLIENTE.OID_CLIENTE = GEPR_TCLIENTE.OID_CLIENTE)
  LEFT JOIN GEPR_TCAJEROXMORFOLOGIA ON (GEPR_TCAJEROXMORFOLOGIA.OID_CAJERO = GEPR_TCAJERO.OID_CAJERO)
  LEFT JOIN GEPR_TMORFOLOGIA ON (GEPR_TMORFOLOGIA.OID_MORFOLOGIA = GEPR_TCAJEROXMORFOLOGIA.OID_MORFOLOGIA)

 WHERE GEPR_TCAJERO.COD_DELEGACION = []COD_DELEGACION
 		AND GEPR_TCAJERO.BOL_VIGENTE = 1
   {0}
