SELECT 
	GEPR_TRED.COD_RED, 
	GEPR_TRED.DES_RED,
	GEPR_TRED.OID_RED, 
	GEPR_TMODELO_CAJERO.OID_MODELO_CAJERO, 
	GEPR_TMODELO_CAJERO.COD_MODELO_CAJERO,
	GEPR_TMODELO_CAJERO.DES_MODELO_CAJERO, 
	GEPR_TGRUPO.OID_GRUPO,
	GEPR_TGRUPO.COD_GRUPO,
	GEPR_TGRUPO.DES_GRUPO,
	GEPR_TCAJERO.OID_CAJERO,
	GEPR_TCAJERO.BOL_REGISTRO_TIRA,
	GEPR_TCAJERO.FYH_ACTUALIZACION,
	GEPR_TCAJERO.COD_DELEGACION,
	GEPR_TCAJEROXMORFOLOGIA.OID_MORFOLOGIA,
	GEPR_TMORFOLOGIA.COD_MORFOLOGIA,
	GEPR_TMORFOLOGIA.DES_MORFOLOGIA,
	GEPR_TCAJEROXMORFOLOGIA.OID_CAJEROXMORFOLOGIA,
	GEPR_TCAJEROXMORFOLOGIA.FEC_INICIO,
	GEPR_TPROCESO_POR_PSERVICIO.OID_PROCESO,
	GEPR_TCAJERO.COD_CAJERO,
	GEPR_TCLIENTE.COD_CLIENTE,
	GEPR_TSUBCLIENTE.COD_SUBCLIENTE,
	GEPR_TSUBCANAL.COD_SUBCANAL,
	GEPR_TPUNTO_SERVICIO.COD_PTO_SERVICIO 
FROM 
	GEPR_TCAJERO 
	LEFT JOIN GEPR_TMODELO_CAJERO ON GEPR_TCAJERO.OID_MODELO_CAJERO = GEPR_TMODELO_CAJERO.OID_MODELO_CAJERO 
	LEFT JOIN GEPR_TRED ON GEPR_TCAJERO.OID_RED = GEPR_TRED.OID_RED 
	LEFT JOIN GEPR_TGRUPO ON GEPR_TCAJERO.OID_GRUPO = GEPR_TGRUPO.OID_GRUPO 
	LEFT JOIN GEPR_TCAJEROXMORFOLOGIA ON GEPR_TCAJERO.OID_CAJERO = GEPR_TCAJEROXMORFOLOGIA.OID_CAJERO 
	LEFT JOIN GEPR_TMORFOLOGIA ON GEPR_TCAJEROXMORFOLOGIA.OID_MORFOLOGIA = GEPR_TMORFOLOGIA.OID_MORFOLOGIA 
	LEFT JOIN GEPR_TPROCESO_POR_PSERVICIO ON GEPR_TCAJERO.OID_PTO_SERVICIO = GEPR_TPROCESO_POR_PSERVICIO.OID_PTO_SERVICIO AND GEPR_TPROCESO_POR_PSERVICIO.BOL_VIGENTE = 1 
	LEFT JOIN GEPR_TCLIENTE ON GEPR_TPROCESO_POR_PSERVICIO.OID_CLIENTE = GEPR_TCLIENTE.OID_CLIENTE 
	LEFT JOIN GEPR_TSUBCLIENTE ON GEPR_TPROCESO_POR_PSERVICIO.OID_SUBCLIENTE = GEPR_TSUBCLIENTE.OID_SUBCLIENTE 
	LEFT JOIN GEPR_TPUNTO_SERVICIO ON GEPR_TPROCESO_POR_PSERVICIO.OID_PTO_SERVICIO = GEPR_TPUNTO_SERVICIO.OID_PTO_SERVICIO 
	LEFT JOIN GEPR_TPROCESO_SUBCANAL ON GEPR_TPROCESO_POR_PSERVICIO.OID_PROCESO_POR_PSERVICIO = GEPR_TPROCESO_SUBCANAL.OID_PROCESO_POR_PSERVICIO 
	LEFT JOIN GEPR_TSUBCANAL ON GEPR_TPROCESO_SUBCANAL.OID_SUBCANAL = GEPR_TSUBCANAL.OID_SUBCANAL