SELECT GEPR_TCAJERO.OID_CAJERO,
       GEPR_TCAJERO.COD_CAJERO,
       GEPR_TRED.COD_RED,
       GEPR_TRED.DES_RED,
       GEPR_TMODELO_CAJERO.COD_MODELO_CAJERO,
       GEPR_TMODELO_CAJERO.DES_MODELO_CAJERO,
       GEPR_TGRUPO.OID_GRUPO,
       GEPR_TGRUPO.COD_GRUPO,
       GEPR_TGRUPO.DES_GRUPO,
       GEPR_TCAJERO.BOL_REGISTRO_TIRA,
       GEPR_TCLIENTE.COD_CLIENTE,
       GEPR_TCLIENTE.DES_CLIENTE,
       GEPR_TSUBCLIENTE.COD_SUBCLIENTE,
       GEPR_TSUBCLIENTE.DES_SUBCLIENTE,
       GEPR_TPUNTO_SERVICIO.COD_PTO_SERVICIO,
       GEPR_TPUNTO_SERVICIO.DES_PTO_SERVICIO,
       GEPR_TCAJERO.BOL_VIGENTE,
       GEPR_TCAJERO.FYH_ACTUALIZACION,
       GEPR_TMORFOLOGIA.OID_MORFOLOGIA,
       GEPR_TMORFOLOGIA.DES_MORFOLOGIA,
	   GEPR_TMORFOLOGIA.NEC_MODALIDAD_RECOGIDA
  FROM GEPR_TCAJERO
  LEFT JOIN GEPR_TPROCESO_POR_PSERVICIO ON GEPR_TCAJERO.OID_PTO_SERVICIO =
                                           GEPR_TPROCESO_POR_PSERVICIO.OID_PTO_SERVICIO
  LEFT JOIN GEPR_TRED ON GEPR_TCAJERO.OID_RED = GEPR_TRED.OID_RED
  LEFT JOIN GEPR_TMODELO_CAJERO ON GEPR_TCAJERO.OID_MODELO_CAJERO =
                                   GEPR_TMODELO_CAJERO.OID_MODELO_CAJERO
  LEFT JOIN GEPR_TGRUPO ON GEPR_TCAJERO.OID_GRUPO = GEPR_TGRUPO.OID_GRUPO
  LEFT JOIN GEPR_TCLIENTE ON GEPR_TPROCESO_POR_PSERVICIO.OID_CLIENTE =
                             GEPR_TCLIENTE.OID_CLIENTE
  LEFT JOIN GEPR_TSUBCLIENTE ON GEPR_TPROCESO_POR_PSERVICIO.OID_SUBCLIENTE =
                                GEPR_TSUBCLIENTE.OID_SUBCLIENTE
  LEFT JOIN GEPR_TPUNTO_SERVICIO ON GEPR_TPROCESO_POR_PSERVICIO.OID_PTO_SERVICIO =
                                    GEPR_TPUNTO_SERVICIO.OID_PTO_SERVICIO
  LEFT JOIN GEPR_TCAJEROXMORFOLOGIA ON GEPR_TCAJERO.OID_CAJERO =
                                       GEPR_TCAJEROXMORFOLOGIA.OID_CAJERO
  LEFT JOIN GEPR_TMORFOLOGIA ON GEPR_TCAJEROXMORFOLOGIA.OID_MORFOLOGIA =
                                GEPR_TMORFOLOGIA.OID_MORFOLOGIA
                            --AND GEPR_TMORFOLOGIA.BOL_VIGENTE = 1
                            AND GEPR_TCAJEROXMORFOLOGIA.FEC_INICIO <= SYSDATE
 WHERE GEPR_TCAJERO.BOL_VIGENTE = []BOL_VIGENTE
   AND GEPR_TCAJERO.COD_DELEGACION = []COD_DELEGACION
   {0}
 ORDER BY GEPR_TCAJERO.OID_CAJERO, GEPR_TCAJEROXMORFOLOGIA.FEC_INICIO DESC