insert into gepr_tcajero
  (oid_cajero,
   oid_modelo_cajero,
   oid_red,
   oid_pto_servicio,
   oid_grupo,
   cod_cajero,
   cod_delegacion,
   bol_registro_tira,
   bol_vigente,
   cod_usuario,
   fyh_actualizacion)
values
  ([]oid_cajero,
   []oid_modelo_cajero,
   []oid_red,
   []oid_pto_servicio,
   []oid_grupo,
   []cod_cajero,
   []cod_delegacion,
   []bol_registro_tira,
   []bol_vigente,
   []cod_usuario,
   []fyh_actualizacion)