SELECT 

D.OID_DIRECCION
,D.OID_TABLA_GENESIS
,D.COD_TIPO_TABLA_GENESIS
,D.DES_PAIS
,D.DES_PROVINCIA
,D.DES_CIUDAD
,D.DES_NUMERO_TELEFONO
,D.DES_EMAIL
,D.COD_FISCAL
,D.COD_POSTAL
,D.DES_DIRECCION_LINEA_1
,D.DES_DIRECCION_LINEA_2
,D.DES_CAMPO_ADICIONAL_1
,D.DES_CAMPO_ADICIONAL_2
,D.DES_CAMPO_ADICIONAL_3
,D.DES_CATEGORIA_ADICIONAL_1
,D.DES_CATEGORIA_ADICIONAL_2
,D.DES_CATEGORIA_ADICIONAL_3
,D.GMT_CREACION
,D.DES_USUARIO_CREACION
,D.GMT_MODIFICACION
,D.DES_USUARIO_MODIFICACION

FROM GEPR_TDIRECCION D 
{0}
WHERE 
D.COD_TIPO_TABLA_GENESIS = []COD_TIPO_TABLA_GENESIS
{1}