INSERT INTO SAPR_TRESULTADO_REPORTE
(OID_RESULTADO_REPORTE,
 OID_CONFIG_REPORTE,
 OID_ENTIDAD_REPORTE,
 COD_SITUACION_REPORTE,
 FYH_INICIO_EJECUCION,
 OID_SUBCANAL)
 VALUES
 ([]OID_RESULTADO_REPORTE,
  []OID_CONFIG_REPORTE,
  []OID_ENTIDAD_REPORTE,
  []COD_SITUACION_REPORTE,
  []FYH_INICIO_EJECUCION,
  []OID_SUBCANAL)