UPDATE SAPR_TRESULTADO_REPORTE
SET
COD_SITUACION_REPORTE = []COD_SITUACION_REPORTE
{0}
WHERE
OID_ENTIDAD_REPORTE = []OID_ENTIDAD_REPORTE AND
OID_CONFIG_REPORTE = []OID_CONFIG_REPORTE AND
OID_SUBCANAL = []OID_SUBCANAL