SELECT OID_MODELO,
	    OID_FABRICANTE,
		COD_MODELO, 
		DES_MODELO, 
		NEL_CAPACIDAD_BILLETES, 
		NEL_CAPACIDAD_MONEDAS,
		BOL_ACTIVO,
		GMT_CREACION,
		DES_USUARIO_CREACION,
		GMT_CREACION, 
		GMT_MODIFICACION, 
		DES_USUARIO_MODIFICACION 
FROM SAPR_TMODELO
