SELECT 
   IM.OID_IMPORTE_MAXIMO,
   IM.OID_CLIENTE,
   IM.OID_DIVISA,
   IM.OID_SUBCANAL,
   IM.OID_SECTOR,
   IM.OID_PLANTA,
   IM.NUM_IMPORTE_MAXIMO,
   IM.BOL_ACTIVO,
   IM.GMT_CREACION,
   IM.DES_USUARIO_CREACION,
   IM.GMT_MODIFICACION,
   C.COD_CANAL, SC.COD_SUBCANAL , SC.DES_SUBCANAL
FROM GEPR_TIMPORTE_MAXIMO IM
LEFT JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = IM.OID_SUBCANAL
LEFT JOIN GEPR_TCANAL C ON C.OID_CANAL = SC.OID_CANAL
WHERE OID_PLANTA = []OID_PLANTA

