UPDATE GEPR_TIMPORTE_MAXIMO
   SET OID_CLIENTE = []OID_CLIENTE,
       OID_DIVISA = []OID_DIVISA,
       OID_SUBCANAL = []OID_SUBCANAL,
       OID_SECTOR = []OID_SECTOR,  
       OID_PLANTA = []OID_PLANTA,
	   NUM_IMPORTE_MAXIMO = []NUM_IMPORTE_MAXIMO,
	   BOL_ACTIVO = []BOL_ACTIVO,
       GMT_CREACION = []GMT_CREACION,
       DES_USUARIO_CREACION = []DES_USUARIO_CREACION,
       GMT_MODIFICACION = []GMT_MODIFICACION,
       DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
 WHERE OID_IMPORTE_MAXIMO = []OID_IMPORTE_MAXIMO



