UPDATE GEPR_TPARAMETRO_VALOR
SET DES_VALOR_PARAMETRO = []DES_VALOR_PARAMETRO , 
    COD_USUARIO = []COD_USUARIO , 
    FYH_ACTUALIZACION = []FYH_ACTUALIZACION
WHERE  OID_PARAMETRO_VALOR = []OID_PARAMETRO_VALOR 