INSERT INTO GEPR_TPARAMETRO_VALOR
(OID_PARAMETRO_VALOR,
 OID_PARAMETRO,
 COD_IDENTIFICADOR_NIVEL,
 DES_VALOR_PARAMETRO,
 COD_USUARIO,
 FYH_ACTUALIZACION)
 VALUES
 ([]OID_PARAMETRO_VALOR,
 []OID_PARAMETRO,
 []COD_IDENTIFICADOR_NIVEL,
 []DES_VALOR_PARAMETRO,
 []COD_USUARIO,
 []FYH_ACTUALIZACION)