SELECT DISTINCT 
P.COD_PARAMETRO,
P.BOL_OBLIGATORIO, 
P.NEC_TIPO_COMPONENTE,
PV.DES_VALOR_PARAMETRO
FROM GEPR_TAPLICACION AP
INNER JOIN GEPR_TGRUPO_PARAMETRO GP ON GP.OID_APLICACION = AP.OID_APLICACION
INNER JOIN GEPR_TNIVEL_PARAMETRO NV ON NV.OID_NIVEL_PARAMETRO = GP.OID_NIVEL_PARAMETRO
INNER JOIN GEPR_TPARAMETRO P ON P.OID_GRUPO_PARAMETRO = GP.OID_GRUPO_PARAMETRO
LEFT JOIN GEPR_TPARAMETRO_VALOR PV ON PV.OID_PARAMETRO = P.OID_PARAMETRO
WHERE AP.COD_APLICACION = []COD_APLICACION AND NV.COD_NIVEL_PARAMETRO IN ([]COD_NIVEL_PARAMETRO_D,[]COD_NIVEL_PARAMETRO_P)
              AND (PV.COD_IDENTIFICADOR_NIVEL IN ([]OID_DELEGACION,[]COD_PAIS))