SELECT 1
FROM GEPR_TPARAMETRO_VALOR PV
INNER JOIN GEPR_TPARAMETRO P ON P.OID_PARAMETRO = PV.OID_PARAMETRO
INNER JOIN GEPR_TAPLICACION AP ON AP.OID_APLICACION = P.OID_APLICACION
WHERE PV.OID_PARAMETRO = []OID_PARAMETRO AND AP.COD_APLICACION = []COD_APLICACION AND PV.COD_IDENTIFICADOR_NIVEL = []COD_IDENTIFICADOR_NIVEL