SELECT 
 UM.OID_UNIDAD_MEDIDA
,UM.COD_UNIDAD_MEDIDA
,UM.DES_UNIDAD_MEDIDA
,UM.COD_TIPO_UNIDAD_MEDIDA
,UM.NUM_VALOR_UNIDAD
,UM.BOL_DEFECTO
FROM GEPR_TUNIDAD_MEDIDA UM
WHERE 1 = 1 {0}
UNION
SELECT 
 UM.OID_UNIDAD_MEDIDA
,UM.COD_UNIDAD_MEDIDA
,UM.DES_UNIDAD_MEDIDA
,UM.COD_TIPO_UNIDAD_MEDIDA
,UM.NUM_VALOR_UNIDAD
,UM.BOL_DEFECTO
FROM GEPR_TUNIDAD_MEDIDA UM
WHERE BOL_DEFECTO = 1