SELECT IAC.OID_IAC,
       IAC.COD_IAC,
       IAC.DES_IAC,
       IAC.OBS_IAC,
       IAC.BOL_VIGENTE,
       IAC.BOL_INVISIBLE,
       IAC.COD_USUARIO,
       IAC.FYH_ACTUALIZACION,
       IAC.BOL_COPIA_DECLARADOS,
	   TPIAC.OID_TERMINO_IAC
FROM GEPR_TINFORM_ADICIONAL_CLIENTE IAC
INNER JOIN GEPR_TTERMINO_POR_IAC TPIAC ON TPIAC.OID_IAC = IAC.OID_IAC
WHERE IAC.COD_IAC = []COD_IAC