/* Nueva query para obterner GrupoIAC ObtenerGrupoIAC_v2.sql */

SELECT 
 IAC.OID_IAC
,IAC.COD_IAC
,IAC.DES_IAC
,IAC.OBS_IAC
,IAC.BOL_VIGENTE
,IAC.BOL_INVISIBLE
,IAC.BOL_COPIA_DECLARADOS

FROM GEPR_TINFORM_ADICIONAL_CLIENTE IAC
WHERE 1 = 1 {0}