INSERT INTO GEPR_TPROCESO_SUBCANAL
(OID_PROCESO_SUBCANAL,
OID_SUBCANAL,
OID_PROCESO_POR_PSERVICIO,
OBS_PROCESO_SUBCANAL,
BOL_VIGENTE,
COD_USUARIO,
FYH_ACTUALIZACION)
SELECT	[]OID_PROCESO_SUBCANAL ,
		OID_SUBCANAL,
		[]OID_PROCESO_POR_PSERVICIO,
		[]OBS_PROCESO_SUBCANAL,
		1,
		[]COD_USUARIO,
		[]FYH_ACTUALIZACION
FROM GEPR_TSUBCANAL
WHERE COD_SUBCANAL = []COD_SUBCANAL