UPDATE 
(SELECT PRSUB.BOL_VIGENTE, PRSUB.COD_USUARIO, PRSUB.FYH_ACTUALIZACION
FROM GEPR_TPROCESO_SUBCANAL PRSUB
INNER JOIN GEPR_TSUBCANAL SUB ON PRSUB.OID_SUBCANAL = SUB.OID_SUBCANAL
WHERE SUB.COD_SUBCANAL = []COD_SUBCANAL
		AND OID_PROCESO_POR_PSERVICIO = []OID_PROCESO_POR_PSERVICIO  
		)LSTA SET LSTA.BOL_VIGENTE = 0, LSTA.COD_USUARIO = []COD_USUARIO, LSTA.FYH_ACTUALIZACION = []FYH_ACTUALIZACION
