UPDATE GEPR_TMEDIO_PAGO_POR_AGRUPACIO
SET
COD_USUARIO = []COD_USUARIO,
FYH_ACTUALIZACION = []FYH_ACTUALIZACION,
BOL_VIGENTE = []BOL_VIGENTE
WHERE
OID_MEDIO_PAGO_AGRUPACION = []OID_MEDIO_PAGO_AGRUPACION