INSERT INTO GEPR_TMEDIO_PAGO_POR_AGRUPACIO
  (OID_MEDIO_PAGO_AGRUPACION,
   OID_AGRUPACION,
   OID_MEDIO_PAGO,
   COD_USUARIO,
   FYH_ACTUALIZACION)
VALUES
  ([]OID_MEDIO_PAGO_AGRUPACION,
   []OID_AGRUPACION,
   []OID_MEDIO_PAGO,
   []COD_USUARIO,
   []FYH_ACTUALIZACION)