SELECT  TD.DES_VALOR,
		T.OID_TERMINO,
        T.COD_TERMINO
FROM SAPR_TVALOR_TERMINOXDOCUMENTO TD
  INNER JOIN GEPR_TTERMINO T ON (TD.OID_TERMINO = T.OID_TERMINO)
WHERE TD.OID_DOCUMENTO = []OID_DOCUMENTO
