INSERT INTO SAPR_TVALOR_TERMINOXDOCUMENTO
(OID_VALOR_TERMINOXDOCUMENTO
,OID_DOCUMENTO
,OID_TERMINO
,DES_VALOR
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION)
VALUES
([]OID_VALOR_TERMINOXDOCUMENTO
,[]OID_DOCUMENTO
,[]OID_TERMINO
,[]DES_VALOR
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_CREACION
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_MODIFICACION)
