SELECT P.COD_MIGRACION
FROM GEPR_TDELEGACION DEL INNER JOIN GEPR_TPLANTA P ON DEL.OID_DELEGACION = P.OID_DELEGACION
WHERE P.COD_MIGRACION IS NOT NULL {0} --DEL.COD_DELEGACION IN ('AR', 'BH')
ORDER BY 1