SELECT OID_PLANTA,
       OID_DELEGACION,
       COD_PLANTA,
       DES_PLANTA,
       COD_MIGRACION,
       BOL_ACTIVO,
       GMT_CREACION,
       DES_USUARIO_CREACION,
       GMT_MODIFICACION,
       DES_USUARIO_MODIFICACION
  FROM GEPR_TPLANTA
  WHERE OID_PLANTA = []pOID_PLANTA