SELECT P.OID_PLANTA,
       P.OID_DELEGACION,
       P.COD_PLANTA,
       P.DES_PLANTA,
       P.COD_MIGRACION,
       P.BOL_ACTIVO,
       P.GMT_CREACION,
       P.DES_USUARIO_CREACION,
       P.GMT_MODIFICACION,
       P.DES_USUARIO_MODIFICACION
  FROM GEPR_TPLANTA P
  INNER JOIN GEPR_TDELEGACION D ON (D.OID_DELEGACION = P.OID_DELEGACION)
  WHERE D.COD_DELEGACION = []pCOD_DELEGACION