SELECT distinct GEPR_TCLIENTE.COD_CLIENTE,
       GEPR_TCLIENTE.DES_CLIENTE,
       GEPR_TCLIENTE.OID_CLIENTE,
       GEPR_TSUBCLIENTE.COD_SUBCLIENTE,
       GEPR_TSUBCLIENTE.DES_SUBCLIENTE,
       GEPR_TPUNTO_SERVICIO.OID_PTO_SERVICIO,
       GEPR_TPUNTO_SERVICIO.COD_PTO_SERVICIO,
       GEPR_TPUNTO_SERVICIO.Des_Pto_Servicio,
       GEPR_TCAJERO.OID_CAJERO,
       GEPR_TCAJERO.COD_CAJERO,
	   GEPR_TCAJERO.FYH_ACTUALIZACION
  FROM GEPR_TCAJERO
  LEFT JOIN GEPR_TPROCESO_POR_PSERVICIO ON GEPR_TCAJERO.OID_PTO_SERVICIO =
                                           GEPR_TPROCESO_POR_PSERVICIO.OID_PTO_SERVICIO
  LEFT JOIN GEPR_TCLIENTE ON GEPR_TPROCESO_POR_PSERVICIO.OID_CLIENTE =
                             GEPR_TCLIENTE.OID_CLIENTE
  LEFT JOIN GEPR_TSUBCLIENTE ON GEPR_TPROCESO_POR_PSERVICIO.OID_SUBCLIENTE =
                                GEPR_TSUBCLIENTE.OID_SUBCLIENTE
  LEFT JOIN GEPR_TPUNTO_SERVICIO ON GEPR_TPROCESO_POR_PSERVICIO.OID_PTO_SERVICIO =
                                    GEPR_TPUNTO_SERVICIO.OID_PTO_SERVICIO
 WHERE GEPR_TCAJERO.OID_GRUPO = []OID_GRUPO
 ORDER BY GEPR_TCLIENTE.OID_CLIENTE