UPDATE GEPR_TSECTOR
SET
COD_SECTOR               = []COD_SECTOR,
DES_SECTOR               = []DES_SECTOR,
OID_SECTOR_PADRE         = []OID_SECTOR_PADRE,
OID_TIPO_SECTOR          = []OID_TIPO_SECTOR,
OID_PLANTA               = []OID_PLANTA,
BOL_CENTRO_PROCESO       = []BOL_CENTRO_PROCESO,
BOL_PERMITE_DISPONER_VALOR    = []BOL_PERMITE_DISPONER_VALOR,
BOL_TESORO               = []BOL_TESORO,
BOL_CONTEO               = []BOL_CONTEO,
COD_MIGRACION            = []COD_MIGRACION,
BOL_ACTIVO               = []BOL_ACTIVO,
GMT_CREACION             = []GMT_CREACION,
DES_USUARIO_CREACION     = []DES_USUARIO_CREACION,
GMT_MODIFICACION         = []GMT_MODIFICACION,
DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE
  OID_SECTOR             = []OID_SECTOR