SELECT TS.BOL_PERMITE_DISPONER_VALOR, TS.BOL_ACTIVO, TS.BOL_CENTRO_PROCESO,  TS.BOL_CONTEO, TS.BOL_TESORO, TS.COD_MIGRACION,
TS.COD_SECTOR "FILHO", TS.DES_SECTOR "DESC_SECTOR_FILHO",
TSS.COD_SECTOR "PAI", TP.DES_PLANTA,  TSS.DES_SECTOR "DESC_SECTOR_PAI", TTS.DES_TIPO_SECTOR,
TS.GMT_CREACION, TS.DES_USUARIO_CREACION, TS.GMT_MODIFICACION, TS.DES_USUARIO_MODIFICACION,  TP.OID_PLANTA, 
TSS.OID_SECTOR "OIDSECTOR_PAI" , TTS.OID_TIPO_SECTOR, TS.OID_SECTOR,
DEL.OID_DELEGACION, DEL.COD_DELEGACION, DEL.DES_DELEGACION
from GEPR_TSECTOR TS 
  LEFT JOIN GEPR_TSECTOR TSS on TS.oid_sector_padre = tss.oid_sector
  INNER JOIN GEPR_TPLANTA TP ON TS.OID_PLANTA = TP.OID_PLANTA
  INNER JOIN GEPR_TTIPO_SECTOR TTS ON TTS.OID_TIPO_SECTOR = TS.OID_TIPO_SECTOR
  INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = TP.OID_DELEGACION
WHERE 1=1



