SELECT SECTOR.BOL_PERMITE_DISPONER_VALOR
	  ,SECTOR.BOL_ACTIVO
	  ,SECTOR.BOL_CENTRO_PROCESO
      ,SECTOR.BOL_CONTEO
      ,SECTOR.BOL_TESORO
      ,SECTOR.COD_MIGRACION
      ,SECTOR.COD_SECTOR "FILHO"
      ,SECTOR.DES_SECTOR "DESC_SECTOR_FILHO"
      ,SECTOR_PADRE.COD_SECTOR "PAI"
      ,SECTOR.GMT_CREACION
      ,SECTOR.DES_USUARIO_CREACION
      ,SECTOR.GMT_MODIFICACION
      ,SECTOR.DES_USUARIO_MODIFICACION
      ,SECTOR_PADRE.OID_SECTOR "OIDSECTOR_PAI"
      ,SECTOR_PADRE.OID_TIPO_SECTOR
      ,SECTOR.OID_SECTOR
      ,SECTOR_PADRE.DES_SECTOR "DESC_SECTOR_PAI"
      ,TTS.DES_TIPO_SECTOR
      ,PL.DES_PLANTA
      ,PL.OID_PLANTA 
      ,DEL.OID_DELEGACION
      ,DEL.COD_DELEGACION
      ,DEL.DES_DELEGACION
FROM
      GEPR_TSECTOR SECTOR
      LEFT JOIN GEPR_TSECTOR SECTOR_PADRE on SECTOR.OID_SECTOR_PADRE = SECTOR_PADRE.OID_SECTOR
      INNER JOIN GEPR_TPLANTA PL ON SECTOR.OID_PLANTA = PL.OID_PLANTA
      INNER JOIN GEPR_TTIPO_SECTOR TTS ON TTS.OID_TIPO_SECTOR = SECTOR.OID_TIPO_SECTOR
      INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = PL.OID_DELEGACION
      INNER JOIN GEPR_TTIPO_SECTORXFORMULARIO TSFO ON TSFO.OID_TIPO_SECTOR = TTS.OID_TIPO_SECTOR
      INNER JOIN SAPR_TFORMULARIO FORM ON FORM.OID_FORMULARIO = TSFO.OID_FORMULARIO

WHERE
      TSFO.COD_RELACION_CON_FORMULARIO = []COD_RELACION_CON_FORMULARIO
	  AND DEL.COD_DELEGACION = []COD_DELEGACION
      AND PL.COD_PLANTA = []COD_PLANTA
      AND FORM.COD_FORMULARIO = []COD_FORMULARIO
      AND SECTOR.BOL_ACTIVO = 1
	  AND FORM.BOL_ACTIVO = 1
	  AND PL.BOL_ACTIVO = 1
      AND DEL.BOL_VIGENTE = 1
      AND TTS.BOL_ACTIVO = 1
ORDER BY 
	  SECTOR.COD_SECTOR, SECTOR.DES_SECTOR