SELECT DISTINCT S.OID_SECTOR,S.COD_SECTOR,S.DES_SECTOR
FROM GEPR_TSECTOR S
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN GEPR_TTIPO_SECTOR TS ON TS.OID_TIPO_SECTOR = S.OID_TIPO_SECTOR
INNER JOIN GEPR_TCARACTTIPOSECTORXTIPOSEC CTST ON CTST.OID_TIPO_SECTOR = TS.OID_TIPO_SECTOR
INNER JOIN GEPR_TCARACT_TIPOSECTOR CTS ON CTS.OID_CARACT_TIPOSECTOR = CTST.OID_CARACT_TIPOSECTOR
WHERE CTS.COD_CARACT_TIPOSECTOR = 'TES' AND S.OID_SECTOR_PADRE IS NULL
AND D.COD_DELEGACION = []COD_DELEGACION AND P.COD_PLANTA = []COD_PLANTA
AND TS.COD_TIPO_SECTOR = []COD_TIPO_SECTOR