SELECT
        COUNT(1) POSIBLE
FROM
        GEPR_TTIPO_SECTORXFORMULARIO TSFO
        INNER JOIN GEPR_TSECTOR SECT ON TSFO.OID_TIPO_SECTOR = SECT.OID_TIPO_SECTOR
WHERE
        TSFO.COD_RELACION_CON_FORMULARIO = []COD_RELACION_CON_FORMULARIO /* INFORMA QUE E PARA VALIDAR SOMENTE CONFIGURAÇÕES DE ORIGEM(O) OUR DESTINO(D) (SETOR PODE CRIAR DOCUMENTOS)*/
        AND TSFO.OID_FORMULARIO = []OID_FORMULARIO
        AND SECT.OID_SECTOR = []OID_SECTOR
