UPDATE SAPR_TFORMULARIO SET
OID_IAC_INDIVIDUAL = []OID_IAC_INDIVIDUAL
,OID_ACCION_CONTABLE =[]OID_ACCION_CONTABLE
,OID_IAC_GRUPO =[]OID_IAC_GRUPO
,OID_FILTRO_FORMULARIO =[]OID_FILTRO_FORMULARIO
,OID_TIPO_DOCUMENTO = []OID_TIPO_DOCUMENTO
,COD_FORMULARIO = []COD_FORMULARIO
,DES_FORMULARIO = []DES_FORMULARIO
,COD_COLOR = []COD_COLOR
,BIN_ICONO_FORMULARIO = []BIN_ICONO_FORMULARIO
,BOL_ACTIVO = []BOL_ACTIVO
,GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###
,DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE OID_FORMULARIO = []OID_FORMULARIO