DECLARE
  EXISTE NUMBER;
  IDENTIFICADOR_FORM VARCHAR2(50) := '##OID_FORM##';
BEGIN
 
  --SE O FORMULÁRIO NÃO POSSUI NENHUM DOCUMENTO
  SELECT COUNT(*) INTO EXISTE FROM SAPR_TDOCUMENTO D
  WHERE D.OID_FORMULARIO = IDENTIFICADOR_FORM;
  
  IF EXISTE = 0 THEN

      DELETE GEPR_TTIPO_SECTORXFORMULARIO WHERE OID_FORMULARIO = IDENTIFICADOR_FORM;
      DELETE SAPR_TCARACTFORMXFORMULARIO WHERE OID_FORMULARIO = IDENTIFICADOR_FORM;
      DELETE SAPR_TCOPIA WHERE OID_FORMULARIO = IDENTIFICADOR_FORM;
      DELETE SAPR_TSECUENCIA_COMPROBANTE WHERE OID_FORMULARIO = IDENTIFICADOR_FORM;	       
      
      DELETE SAPR_TFORMULARIOXTIPO_BULTO TF WHERE TF.OID_FORMULARIO = IDENTIFICADOR_FORM;
      DELETE SAPR_TFORMULARIO FORM WHERE FORM.OID_FORMULARIO = IDENTIFICADOR_FORM;
      
	  --VERIFICA SE A AÇÃO CONTÁBIL DO FORMULARIO EXISTE EM MAIS DE UM FORMULÁRIO
      SELECT COUNT(F.OID_ACCION_CONTABLE) INTO EXISTE FROM SAPR_TFORMULARIO F
      WHERE F.OID_ACCION_CONTABLE IN(SELECT FORM.OID_ACCION_CONTABLE FROM SAPR_TFORMULARIO FORM
      WHERE FORM.OID_FORMULARIO = IDENTIFICADOR_FORM);
      
      IF EXISTE = 1 THEN
       
         DELETE SAPR_TESTADOXACCION_CONTABLE T WHERE T.OID_ACCION_CONTABLE
         IN (SELECT FORM.OID_ACCION_CONTABLE FROM SAPR_TFORMULARIO FORM WHERE FORM.OID_FORMULARIO = IDENTIFICADOR_FORM);
         
         DELETE SAPR_TACCION_CONTABLE AC WHERE AC.OID_ACCION_CONTABLE 
         IN (SELECT FORM.OID_ACCION_CONTABLE FROM SAPR_TFORMULARIO FORM WHERE FORM.OID_FORMULARIO = IDENTIFICADOR_FORM);
        
      END IF;

  END IF;
  
EXCEPTION   
      WHEN OTHERS THEN
           ROLLBACK;
           RAISE_APPLICATION_ERROR(SQLCODE, SQLERRM);
END;
