SELECT
    FORM.OID_FORMULARIO,
    FORM.DES_FORMULARIO,
    FORM.COD_FORMULARIO
FROM
        SAPR_TFORMULARIO FORM
WHERE  
        FORM.OID_FORMULARIO IN ({0})
ORDER BY
        FORM.GMT_CREACION DESC