SELECT  CAFO.OID_FORMULARIO 
        FROM SAPR_TCARACTFORMXFORMULARIO CAFO
             INNER JOIN SAPR_TCARACT_FORMULARIO CARA ON CAFO.OID_CARACT_FORMULARIO = CARA.OID_CARACT_FORMULARIO
        WHERE
             {0}
        GROUP BY
              CAFO.OID_FORMULARIO
        HAVING
              COUNT(CAFO.OID_CARACT_FORMULARIO) = {1}