/* Nueva query para obterner Accion Contable ObtenerAccionContable_v2.sql */
SELECT
 EAC.OID_ESTADOXACCION_CONTABLE
,EAC.OID_ACCION_CONTABLE
,EAC.COD_ESTADO
,EAC.COD_ACCION_ORIGEN_DISPONIBLE
,EAC.COD_ACCION_ORIGEN_NODISP
,EAC.COD_ACCION_DESTINO_DISPONIBLE
,EAC.COD_ACCION_DESTINO_NODISP

FROM SAPR_TESTADOXACCION_CONTABLE EAC
INNER JOIN SAPR_TFORMULARIO F ON F.OID_ACCION_CONTABLE = EAC.OID_ACCION_CONTABLE
WHERE 1 = 1 {0}