/* Nueva query para obterner Formulario ObtenerFormularios_v2.sql */
SELECT 
 F.OID_FORMULARIO
,F.OID_ACCION_CONTABLE
,F.OID_IAC_INDIVIDUAL
,F.OID_IAC_GRUPO
,F.OID_FILTRO_FORMULARIO
,F.OID_TIPO_DOCUMENTO
,F.COD_FORMULARIO
,F.DES_FORMULARIO
,F.COD_COLOR
,F.BIN_ICONO_FORMULARIO
,F.BOL_ACTIVO

,AC.OID_ACCION_CONTABLE
,AC.COD_ACCION_CONTABLE
,AC.DES_ACCION_CONTABLE
,AC.BOL_ACTIVO AS AC_BOL_ACTIVO

,TD.COD_TIPO_DOCUMENTO
,TD.DES_TIPO_DOCUMENTO
,TD.NEC_ORDEN
,TD.BOL_ACTIVO AS TD_BOL_ACTIVO
,TD.BOL_CERTIFICACION

FROM SAPR_TFORMULARIO F
INNER JOIN SAPR_TACCION_CONTABLE AC ON F.OID_ACCION_CONTABLE = AC.OID_ACCION_CONTABLE
INNER JOIN SAPR_TTIPO_DOCUMENTO TD ON F.OID_TIPO_DOCUMENTO = TD.OID_TIPO_DOCUMENTO

WHERE 1 = 1 {0}


