/* Nueva query para obterner Caracteristicas del Formulario ObtenerCaracteristicas_v2.sql */
SELECT
 F.OID_FORMULARIO
,CF.COD_CARACT_FORMULARIO

FROM SAPR_TCARACT_FORMULARIO CF 
INNER JOIN SAPR_TCARACTFORMXFORMULARIO CFF ON CFF.OID_CARACT_FORMULARIO = CF.OID_CARACT_FORMULARIO
INNER JOIN SAPR_TFORMULARIO F ON F.OID_FORMULARIO = CFF.OID_FORMULARIO
WHERE COD_TIPO_CARACTERISTICA = 'F' {0}