/* Nueva query para obterner GrupoTerminosIAC del Formulario ObtenerIAC_v2.sql */

SELECT 
 IAC.OID_IAC
,IAC.COD_IAC
,IAC.DES_IAC
,IAC.OBS_IAC
,IAC.BOL_VIGENTE
,IAC.BOL_INVISIBLE
,IAC.BOL_COPIA_DECLARADOS

FROM GEPR_TINFORM_ADICIONAL_CLIENTE IAC
INNER JOIN SAPR_TFORMULARIO F ON F.OID_IAC_INDIVIDUAL = IAC.OID_IAC
WHERE 1 = 1 {0}

UNION

SELECT 
 IAC.OID_IAC
,IAC.COD_IAC
,IAC.DES_IAC
,IAC.OBS_IAC
,IAC.BOL_VIGENTE
,IAC.BOL_INVISIBLE
,IAC.BOL_COPIA_DECLARADOS

FROM GEPR_TINFORM_ADICIONAL_CLIENTE IAC
INNER JOIN SAPR_TFORMULARIO F ON F.OID_IAC_GRUPO = IAC.OID_IAC
WHERE 1 = 1 {0}