SELECT  F.OID_FORMULARIO
,F.OID_ACCION_CONTABLE
,F.OID_IAC_INDIVIDUAL
,F.OID_IAC_GRUPO
,F.OID_FILTRO_FORMULARIO
,F.OID_TIPO_DOCUMENTO
,F.COD_FORMULARIO
,F.DES_FORMULARIO
,F.COD_MIGRACION
,F.COD_COLOR
,F.BIN_ICONO_FORMULARIO
,F.BOL_ACTIVO
,F.GMT_CREACION
,F.DES_USUARIO_CREACION
,F.GMT_MODIFICACION
,F.DES_USUARIO_MODIFICACION
FROM SAPR_TFORMULARIO F
     inner join GEPR_TTIPO_SECTORXFORMULARIO SF on SF.OID_FORMULARIO = F.OID_FORMULARIO
     inner join GEPR_TTIPO_SECTOR TS on TS.OID_TIPO_SECTOR = SF.OID_TIPO_SECTOR
     inner join GEPR_TSECTOR S on S.OID_TIPO_SECTOR = TS.OID_TIPO_SECTOR
WHERE S.OID_SECTOR = []OIDSECTOR AND SF.COD_RELACION_CON_FORMULARIO = []COD_RELACION_CON_FORMULARIO
{0}
ORDER BY F.DES_FORMULARIO