SELECT  F.OID_FORMULARIO
,F.OID_ACCION_CONTABLE
,F.OID_IAC_INDIVIDUAL
,F.OID_IAC_GRUPO
,F.OID_FILTRO_FORMULARIO
,F.OID_TIPO_DOCUMENTO
,F.COD_FORMULARIO
,F.DES_FORMULARIO
,F.COD_MIGRACION
,F.COD_COLOR
,F.BIN_ICONO_FORMULARIO
,F.BOL_ACTIVO
,F.GMT_CREACION
,F.DES_USUARIO_CREACION
,F.GMT_MODIFICACION
,F.DES_USUARIO_MODIFICACION
FROM SAPR_TFORMULARIO F
ORDER BY F.DES_FORMULARIO