UPDATE IAPR_TCONFIG_GENERAL_REPORTES
SET 
   COD_REPORTE				= []COD_REPORTE
   ,NEC_FORMATO_ARCHIVO		= []NEC_FORMATO_ARCHIVO
   ,DES_EXTENSION_ARCHIVO	= []DES_EXTENSION_ARCHIVO
   ,COD_SEPARADOR			= []COD_SEPARADOR
   ,COD_USUARIO				= []COD_USUARIO
   ,FYH_ACTUALIZACION		= []FYH_ACTUALIZACION
WHERE OID_CONFIGURACION_GENERAL =[]OID_CONFIGURACION_GENERAL
