INSERT INTO IAPR_TCONFIG_GENERAL_REPORTES
(	OID_CONFIGURACION_GENERAL
   ,DES_REPORTE
   ,COD_REPORTE
   ,NEC_FORMATO_ARCHIVO
   ,DES_EXTENSION_ARCHIVO
   ,COD_SEPARADOR
   ,COD_USUARIO
   ,FYH_ACTUALIZACION)
VALUES
(
	[]OID_CONFIGURACION_GENERAL
   ,[]DES_REPORTE
   ,[]COD_REPORTE
   ,[]NEC_FORMATO_ARCHIVO
   ,[]DES_EXTENSION_ARCHIVO
   ,[]COD_SEPARADOR
   ,[]COD_USUARIO
   ,[]FYH_ACTUALIZACION
)
