SELECT OID_CONFIGURACION_GENERAL
   ,DES_REPORTE
   ,COD_REPORTE
   ,NEC_FORMATO_ARCHIVO
   ,DES_EXTENSION_ARCHIVO
   ,COD_SEPARADOR
   ,COD_USUARIO
   ,FYH_ACTUALIZACION
FROM IAPR_TCONFIG_GENERAL_REPORTES
WHERE OID_CONFIGURACION_GENERAL = []OID_CONFIGURACION_GENERAL
