SELECT DISTINCT(G.OID_CONFIGURACION_GENERAL), G.DES_REPORTE, G.NEC_FORMATO_ARCHIVO 
FROM IAPR_TREPORTES_CONFIGURACION T 
INNER JOIN IAPR_TCONFIG_GENERAL_REPORTES G 
ON T.OID_CONFIGURACION_GENERAL = G.OID_CONFIGURACION_GENERAL