UPDATE 
	GEPR_TTERMINO
SET 
    DES_TERMINO					= []DES_TERMINO,
    OBS_TERMINO					= []OBS_TERMINO,
    NEC_LONGITUD				= []NEC_LONGITUD,
    OID_FORMATO					= []OID_FORMATO,
    OID_ALGORITMO_VALIDACION	= []OID_ALGORITMO_VALIDACION,
    OID_MASCARA					= []OID_MASCARA,
    BOL_MOSTRAR_CODIGO			= []BOL_MOSTRAR_CODIGO,
    BOL_VALORES_POSIBLES		= []BOL_VALORES_POSIBLES,
    BOL_VIGENTE					= []BOL_VIGENTE,
    COD_USUARIO					= []COD_USUARIO,
    FYH_ACTUALIZACION			= []FYH_ACTUALIZACION
WHERE 
	COD_TERMINO					= []COD_TERMINO
	                
