UPDATE GEPR_TTERMINO_POR_IAC
SET BOL_BUSQUEDA_PARCIAL = []BOL_BUSQUEDA_PARCIAL, BOL_CAMPO_CLAVE = []BOL_CAMPO_CLAVE, BOL_ES_OBLIGATORIO = []BOL_ES_OBLIGATORIO, NEC_ORDEN = []NEC_ORDEN, COD_USUARIO = []COD_USUARIO, FYH_ACTUALIZACION = []FYH_ACTUALIZACION, BOL_ES_PROTEGIDO = []BOL_ES_PROTEGIDO, BOL_ES_INVISIBLEREPORTE = []BOL_ES_INVISIBLEREPORTE
WHERE OID_IAC IN (SELECT IAC.OID_IAC
FROM GEPR_TINFORM_ADICIONAL_CLIENTE IAC INNER JOIN GEPR_TTERMINO_POR_IAC TERIAC ON IAC.OID_IAC = TERIAC.OID_IAC
WHERE IAC.COD_IAC = []COD_IAC)