SELECT TER.COD_TERMINO, 
TERIAC.BOL_VIGENTE, 
TER.DES_TERMINO,
TERIAC.BOL_BUSQUEDA_PARCIAL,
TERIAC.BOL_CAMPO_CLAVE,
TERIAC.BOL_ES_OBLIGATORIO,
TERIAC.BOL_ES_PROTEGIDO,
TERIAC.NEC_ORDEN
FROM GEPR_TTERMINO TER
INNER JOIN GEPR_TTERMINO_POR_IAC TERIAC ON TERIAC.OID_TERMINO = TER.OID_TERMINO
WHERE OID_IAC = []OID_IAC