SELECT 
             TER.COD_TERMINO,
             TER.DES_TERMINO,
             TER.OBS_TERMINO,
             TER.NEC_LONGITUD,
             TER.BOL_MOSTRAR_CODIGO,
             TER.BOL_VALORES_POSIBLES,
             TER.BOL_VIGENTE,
			 TER.BOL_ACEPTAR_DIGITACION,
             MAS.COD_MASCARA,
             MAS.DES_MASCARA,
             MAS.DES_EXP_REGULAR,
             ALG.COD_ALGORITMO_VALIDACION,
             ALG.DES_ALGORITMO_VALIDACION,
             FRM.COD_FORMATO,
             FRM.DES_FORMATO
FROM 
             GEPR_TTERMINO TER

INNER JOIN   GEPR_TFORMATO FRM ON
             FRM.OID_FORMATO = TER.OID_FORMATO
             
LEFT JOIN   GEPR_TMASCARA MAS ON
             TER.OID_MASCARA=MAS.OID_MASCARA
             
LEFT JOIN   GEPR_TALGORITMO_VALIDACION ALG ON
             TER.OID_ALGORITMO_VALIDACION = ALG.OID_ALGORITMO_VALIDACION
