UPDATE GEPR_TTERMINO_POR_IAC
SET
BOL_BUSQUEDA_PARCIAL = []BOL_BUSQUEDA_PARCIAL,
BOL_CAMPO_CLAVE = []BOL_CAMPO_CLAVE,
NEC_ORDEN = []NEC_ORDEN,
BOL_ES_OBLIGATORIO = []BOL_ES_OBLIGATORIO,
BOL_ES_PROTEGIDO = []BOL_ES_PROTEGIDO,
COD_USUARIO = []COD_USUARIO,
FYH_ACTUALIZACION = []FYH_ACTUALIZACION,
BOL_VIGENTE = []BOL_VIGENTE
WHERE
OID_TERMINO_IAC = []OID_TERMINO_IAC