SELECT TERIAC.OID_TERMINO_IAC
FROM GEPR_TTERMINO_POR_IAC TERIAC
INNER JOIN GEPR_TTERMINO TER ON TER.OID_TERMINO = TERIAC.OID_TERMINO
INNER JOIN GEPR_TINFORM_ADICIONAL_CLIENTE IAC ON IAC.OID_IAC = TERIAC.OID_IAC
WHERE IAC.COD_IAC = []COD_IAC AND TER.COD_TERMINO = []COD_TERMINO