SELECT 
	SUM(NUMREGISTRO) 
FROM 
(
	SELECT 
		COUNT(*) AS NUMREGISTRO 
	FROM 
		GEPR_TTERMINO TER 
		INNER JOIN GEPR_TTERMINO_POR_IAC TPI ON TER.OID_TERMINO = TPI.OID_TERMINO 
		INNER JOIN GEPR_TINFORM_ADICIONAL_CLIENTE IAC ON TPI.OID_IAC = IAC.OID_IAC 
	WHERE 
		IAC.BOL_VIGENTE = 1 
		AND TER.COD_TERMINO = []COD_TERMINO
) 