UPDATE GEPR_TTIPO_SUBCLIENTE
    SET DES_TIPO_SUBCLIENTE = []DES_TIPO_SUBCLIENTE,
        BOL_ACTIVO = []BOL_ACTIVO,
        GMT_CREACION = []GMT_CREACION,
        DES_USUARIO_CREACION = []DES_USUARIO_CREACION,
        GMT_MODIFICACION = []GMT_MODIFICACION,
        DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE COD_TIPO_SUBCLIENTE = []COD_TIPO_SUBCLIENTE