INSERT INTO GEPR_TTIPO_SUBCLIENTE
(OID_TIPO_SUBCLIENTE, COD_TIPO_SUBCLIENTE, DES_TIPO_SUBCLIENTE, BOL_ACTIVO, GMT_CREACION, DES_USUARIO_CREACION,
GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
VALUES
([]OID_TIPO_SUBCLIENTE, []COD_TIPO_SUBCLIENTE, []DES_TIPO_SUBCLIENTE, []BOL_ACTIVO, []GMT_CREACION,
[]DES_USUARIO_CREACION, []GMT_MODIFICACION, []DES_USUARIO_MODIFICACION)