INSERT INTO SAPR_THIST_MOV_GRUPO_DOCUMENTO
(OID_HIST_MOV_GRUPO_DOCUMENTO,
OID_GRUPO_DOCUMENTO,
COD_ESTADO,
GMT_CREACION,
DES_USUARIO_CREACION,
GMT_MODIFICACION,
DES_USUARIO_MODIFICACION)
VALUES
([]OID_HIST_MOV_GRUPO_DOCUMENTO,
[]OID_GRUPO_DOCUMENTO,
[]COD_ESTADO,
FN_GMT_ZERO_###VERSION###,
[]DES_USUARIO_CREACION,
FN_GMT_ZERO_###VERSION###,
[]DES_USUARIO_MODIFICACION)