INSERT INTO SAPR_TCERTIFICADOXDELEGACION
(OID_CERTIFICADOXDELEGACION,
 OID_CERTIFICADO,
 OID_DELEGACION,
 GMT_CREACION,
 DES_USUARIO_CREACION,
 GMT_MODIFICACION,
 DES_USUARIO_MODIFICACION)
SELECT DISTINCT SYS_GUID() OID_CERTIFICADOXDELEGACION,
                []OID_CERTIFICADO OID_CERTIFICADO,
                OID_DELEGACION,
                FN_GMT_ZERO_###VERSION### GMT_CREACION,
                []DES_USUARIO_CREACION DES_USUARIO_CREACION,
                FN_GMT_ZERO_###VERSION###,
                []DES_USUARIO_MODIFICACION DES_USUARIO_MODIFICACION
FROM GEPR_TDELEGACION