'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InventarioContenedoresConsultar

    '''<summary>
    '''lblSubTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upSector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upSector As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''phSector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phSector As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''upCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCliente As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''phCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phCliente As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblCodInventario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodInventario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCodInventario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodInventario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dvFechadesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFechadesde As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFechaInventarioDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaInventarioDesde As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFechaInventarioDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInventarioDesde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dvFechaHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFechaHasta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFechaInventarioHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaInventarioHasta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFechaInventarioHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInventarioHasta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkNoConsiderarHijos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNoConsiderarHijos As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ucDiscriminarPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDiscriminarPor As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.ucRadioButtonList

    '''<summary>
    '''ucFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucFormato As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.ucRadioButtonList

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dvResultadoBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvResultadoBusqueda As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblResultadosBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultadosBusqueda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gdvContenedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvContenedor As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnGenerarReporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerarReporte As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Master
        Get
            Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Master)
        End Get
    End Property
End Class
