UPDATE GEPR_TMEDIO_PAGO
SET    
       OID_TIPO_MEDIO_PAGO = []OID_TIPO_MEDIO_PAGO,
       OID_DIVISA = []OID_DIVISA,
       DES_MEDIO_PAGO = []DES_MEDIO_PAGO,
       OBS_MEDIO_PAGO = []OBS_MEDIO_PAGO,
	   BOL_MERCANCIA = []BOL_MERCANCIA,
       BOL_VIGENTE = []BOL_VIGENTE,
       COD_USUARIO = []COD_USUARIO,
       FYH_ACTUALIZACION = []FYH_ACTUALIZACION
 WHERE OID_MEDIO_PAGO = []OID_MEDIO_PAGO