INSERT INTO GEPR_TMEDIO_PAGO
  (OID_MEDIO_PAGO,
   COD_TIPO_MEDIO_PAGO,
   OID_DIVISA,
   COD_MEDIO_PAGO,
   DES_MEDIO_PAGO,
   OBS_MEDIO_PAGO,
   BOL_MERCANCIA,
   BOL_VIGENTE,
   COD_USUARIO,
   FYH_ACTUALIZACION,
   COD_ACCESO)
VALUES
   ([]OID_MEDIO_PAGO,
	[]COD_TIPO_MEDIO_PAGO,
	[]OID_DIVISA,
	[]COD_MEDIO_PAGO,
	[]DES_MEDIO_PAGO,
	[]OBS_MEDIO_PAGO,
	[]BOL_MERCANCIA,
	[]BOL_VIGENTE,
	[]COD_USUARIO,
	[]FYH_ACTUALIZACION,
	[]COD_ACCESO)
	
	 