SELECT 
	MP.COD_MEDIO_PAGO,
	MP.DES_MEDIO_PAGO
FROM
    GEPR_TDIVISA DIV 
    INNER JOIN GEPR_TMEDIO_PAGO MP ON (DIV.OID_DIVISA = MP.OID_DIVISA)
WHERE
    MP.COD_TIPO_MEDIO_PAGO = []COD_TIPO_MEDIO_PAGO
	AND MP.BOL_VIGENTE = 1