SELECT 
	SUM(NUMREGISTRO) 
FROM 
(
	SELECT 
		COUNT(*) AS NUMREGISTRO 
	FROM 
		GEPR_TMEDIO_PAGO MPG 
		INNER JOIN GEPR_TMEDIO_PAGO_POR_AGRUPACIO MPA ON MPG.OID_MEDIO_PAGO = MPA.OID_MEDIO_PAGO 
		INNER JOIN GEPR_TAGRUPACION AGP ON AGP.OID_AGRUPACION = MPA.OID_AGRUPACION 
	WHERE 
		MPG.OID_MEDIO_PAGO = []OID_MEDIO_PAGO 
	UNION ALL 
	SELECT 
		COUNT(*) AS NUMREGISTRO 
	FROM 
		GEPR_TMEDIO_PAGO MPG 
		INNER JOIN GEPR_TMEDIO_PAGO_POR_PROCESO MPP ON MPG.OID_MEDIO_PAGO = MPP.OID_MEDIO_PAGO 
		INNER JOIN GEPR_TPROCESO PRC ON MPP.OID_PROCESO = PRC.OID_PROCESO 
		INNER JOIN GEPR_TPROCESO_POR_PSERVICIO PPS ON PRC.OID_PROCESO = PPS.OID_PROCESO 
	WHERE 
		MPG.OID_MEDIO_PAGO = []OID_MEDIO_PAGO
)