SELECT 
	COUNT(0) AS QUANTIDADE
FROM 
	GEPR_TTERMINO_MEDIO_PAGO TMP
	INNER JOIN GEPR_TMEDIO_PAGO MP ON
		TMP.OID_MEDIO_PAGO = MP.OID_MEDIO_PAGO
WHERE 
	TMP.COD_TERMINO = []COD_TERMINO AND
	MP.COD_MEDIO_PAGO = []COD_MEDIO_PAGO