SELECT DISTINCT CNS.OID_CONFIG_NIVEL_SALDO
FROM SAPR_TCONFIG_NIVEL_SALDO CNS
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CNS.OID_CLIENTE AND CNS.OID_SUBCLIENTE IS NULL AND CNS.OID_PTO_SERVICIO IS NULL
WHERE CL.COD_CLIENTE = []COD_CLIENTE AND ROWNUM = 1