Public Class Constantes
    '### REPORTING SERVICE ###'
    Public Const wsdl2010 As String = "/ReportService2010.asmx"
    Public Const wsdl2005 As String = "/ReportService2005.asmx"
    Public Const wsdlreportExecution As String = "/ReportExecution2005.asmx"

    ' Extensão do arquivo
    Public Const extensao_xls As String = "xls"
    Public Const extensao_xlsx As String = "xlsx"
    Public Const extensao_mhtml As String = "mhtml"
    Public Const extensao_csv As String = "csv"
    Public Const extensao_pdf As String = "pdf"
    Public Const extensao_txt As String = "txt"

    ' Limitadores no nome do arquivo extensão
    Public Const limitador_data_abertura As String = "{"
    Public Const limitador_data_fechamento As String = "}"
    Public Const limitador_parametro_abertura As String = "@"
    Public Const limitador_parametro_fechamento As String = "@"
    Public Const limitador_quantidade_abertura As String = "#"
    Public Const limitador_quantidade_fechamento As String = "#"
    Public Const limitador_fixo_abertura As String = "["
    Public Const limitador_fixo_fechamento As String = "]"
    Public Const limitador_depara_abertura As String = "("
    Public Const limitador_depara_fechamento As String = ")"
    Public Const limitador_substituicao_abertura As String = "^"
    Public Const limitador_substituicao_fechamento As String = "^"

    ' Prefixo estensão arquivo
    Public Const prefixo_data_mm As String = "MM"
    Public Const prefixo_data_dd As String = "DD"
    Public Const prefixo_data_aa As String = "AA"
    Public Const prefixo_data_aaaa As String = "AAAA"
    Public Const prefixo_data_ddmmaa As String = "DDMMAA"
    Public Const prefixo_data_ddmmaaaa As String = "DDMMAAAA"
    Public Const prefixo_data_l As String = "L"
    Public Const prefixo_data_atual As String = "FAC"
    Public Const prefixo_data_conteo As String = "FFC"
    Public Const prefixo_data_transporte As String = "FTR"
    Public Const prefixo_codigo_delegacao As String = "DEL"
    Public Const prefixo_id_reporte As String = "ID"
    Public Const prefixo_nome_reporte As String = "NR"
    Public Const prefixo_codigo_ajeno_cliente As String = "CLIENTE"
    Public Const prefixo_codigo_ajeno_subcliente As String = "SUBCLIENTE"
    Public Const prefixo_codigo_ajeno_pontoServico As String = "PUNTOSERVICIO"
    Public Const prefixo_codigo_cliente As String = "CLIENTEG"
    Public Const prefixo_codigo_subcliente As String = "SUBCLIENTEG"
    Public Const prefixo_codigo_pontoServico As String = "PUNTOSERVICIOG"
    Public Const prefixo_quantidade_direita As String = "R"
    Public Const prefixo_quantidade_esquerda As String = "L"
    Public Const prefixo_hora_minuto As String = "HHMM"
    Public Const prefixo_hora_minuto1 As String = "HH_MM"
    Public Const prefixo_hora_minuto2 As String = "HH-MM"

    '### MESES EM NÚMEROS ###'
    Public Const numero_mes_janeiro As String = "01"
    Public Const numero_mes_fevereiro As String = "02"
    Public Const numero_mes_marco As String = "03"
    Public Const numero_mes_abril As String = "04"
    Public Const numero_mes_maio As String = "05"
    Public Const numero_mes_junho As String = "06"
    Public Const numero_mes_julho As String = "07"
    Public Const numero_mes_agosto As String = "08"
    Public Const numero_mes_setembro As String = "09"
    Public Const numero_mes_outubro As String = "10"
    Public Const numero_mes_novembro As String = "11"
    Public Const numero_mes_dezembro As String = "12"

    '### EQUIVALÊNCIA DOS MESES EM LETRAS ###'
    Public Const letra_mes_janeiro As String = "A"
    Public Const letra_mes_fevereiro As String = "B"
    Public Const letra_mes_marco As String = "C"
    Public Const letra_mes_abril As String = "D"
    Public Const letra_mes_maio As String = "E"
    Public Const letra_mes_junho As String = "F"
    Public Const letra_mes_julho As String = "G"
    Public Const letra_mes_agosto As String = "H"
    Public Const letra_mes_setembro As String = "I"
    Public Const letra_mes_outubro As String = "J"
    Public Const letra_mes_novembro As String = "K"
    Public Const letra_mes_dezembro As String = "L"

    '### CODIGOS PARAMETROS ###'
    Public Const CONST_P_CODIGO_CLIENTE As String = "P_COM_CLIENTE"
    Public Const CONST_P_FECHA_CONTEO_DESDE As String = "P_FYH_CONTEO_DESDE"
    Public Const CONST_P_FECHA_CONTEO_HASTA As String = "P_FYH_CONTEO_HASTA"
    Public Const CONST_P_FECHA_TRANSPORTE_DESDE As String = "P_FEC_TRANSPORTE_DESDE"
    Public Const CONST_P_FECHA_TRANSPORTE_HASTA As String = "P_FEC_TRANSPORTE_HASTA"
    Public Const CONST_P_CODIGO_SUBCLIENTE As String = "P_COM_SUBCLIENTE"
    Public Const CONST_P_CODIGO_PUNTO_SERVICIO As String = "P_COM_PUNTOSERVICIO"
    Public Const CONST_P_CODIGO_GRUPO_CLIENTES As String = "P_COM_GRUPO"
    Public Const CONST_P_CODIGO_DELEGACION As String = "P_COM_DELEGACION"
    Public Const CONST_P_CODIGO_DELEGACION_USUARIO As String = "P_COM_DELEGACION_USUARIO"
    Public Const CONST_P_NOMBRE_ARCHIVO As String = "P_NOMBRE_ARCHIVO"
    Public Const CONST_P_DE_PARA As String = "DE_PARA"
    Public Const CONST_P_CODIGO_INVENTARIO As String = "P_COM_INVENTARIO"
    Public Const CONST_P_ORDENACAO As String = "P_ORDENACAO"
    Public Const CONST_P_LOGIN As String = "P_LOGIN"

End Class
