UPDATE GEPR_TLISTA_VALOR LV SET
LV.DES_VALOR = []DES_VALOR,
LV.GMT_MODIFICACION = []GMT_MODIFICACION,
LV.DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION,
LV.BOL_DEFECTO = []BOL_DEFECTO,
LV.BOL_ACTIVO = []BOL_ACTIVO
WHERE LV.COD_VALOR = []COD_VALOR 
AND LV.OID_LISTA_TIPO = []OID_LISTA_TIPO