SELECT LT.COD_TIPO,
LV.OID_LISTA_VALOR,
LV.COD_VALOR,
LV.DES_VALOR,
LV.BOL_ACTIVO,
LV.BOL_DEFECTO,
LV.GMT_CREACION,
LV.DES_USUARIO_CREACION,
LV.GMT_MODIFICACION,
LV.DES_USUARIO_MODIFICACION
FROM GEPR_TLISTA_TIPO LT
INNER JOIN GEPR_TLISTA_VALOR LV ON LV.OID_LISTA_TIPO = LT.OID_LISTA_TIPO
WHERE 0 = 0