SELECT
          TS.COD_SECTOR
          ,TS.DES_SECTOR
          ,TS.OID_SECTOR  
          from RPGE_YSECTOR TS
            LEFT JOIN RPGE_YSECTOR TSS on TS.oid_sector_padre = tss.oid_sector
            INNER JOIN RPGE_YPLANTA TP ON TS.OID_PLANTA = TP.OID_PLANTA
            INNER JOIN RPGE_YTIPO_SECTOR TTS ON TTS.OID_TIPO_SECTOR = TS.OID_TIPO_SECTOR
            INNER JOIN RPGE_YDELEGACION DEL ON DEL.OID_DELEGACION = TP.OID_DELEGACION
            WHERE DEL.COD_DELEGACION =[]COD_DELEGACION
        order by TS.DES_SECTOR