trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 1

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'IAC/Prosegur.Global.GesEfectivo.IAC/Prosegur.Global.GesEfectivo.IAC.Web.vbproj'

- task: VSBuild@1
  inputs:
    solution: 'IAC/Prosegur.Global.GesEfectivo.IAC/Prosegur.Global.GesEfectivo.IAC.Web.vbproj'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:TargetFrameworkVersion=v4.8'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'IAC/Prosegur.Global.GesEfectivo.IAC/Web/bin/Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/iac_build'

