SELECT DISTINCT
	MP.COD_TIPO_MEDIO_PAGO,
	NULL AS DES_TIPO_MEDIO_PAGO
FROM
    GEPR_TDIVISA DIV 
    INNER JOIN GEPR_TMEDIO_PAGO MP ON (DIV.OID_DIVISA = MP.OID_DIVISA)
WHERE
    DIV.COD_ISO_DIVISA = []COD_ISO_DIVISA
	AND MP.BOL_VIGENTE = 1