SELECT 
	TBILLETAJEXSUC.SUCURSAL AS ESTACION, 
	TBILLETAJEXSUC.DESC_SUCURSAL AS DES_ESTACION, 
	TBILLETAJEXSUC.DIVISA AS DIVISA, 
	TBILLETAJEXSUC.DES_DIVISA AS DES_DIVISA, 
	TBILLETAJEXSUC.COD_TIPO AS COD_TIPO, 
	TBILLETAJEXSUC.DES_TIPO AS DES_TIPO, 
	TBILLETAJEXSUC.ES_BILLETE AS ES_BILLETE, 
	TBILLETAJEXSUC.UNIDAD_MOEDA AS UNIDAD_MOEDA,
	SUM(TBILLETAJEXSUC.UNIDADES) AS UNIDADES, 
	SUM(TBILLETAJEXSUC.VALOR_RECONTADO) AS VALOR_RECONTADO, 
	TBILLETAJEXSUC.DES_MEDIO_PAGO AS DES_MEDIO_PAGO, 
	TBILLETAJEXSUC.OID_REMESA_ORI AS OID_REMESA_ORI, 
	TBILLETAJEXSUC.COD_SUBCLIENTE AS COD_SUBCLIENTE, 
	TBILLETAJEXSUC.COD_TRANSPORTE AS CODIGO_TRANSPORTE,
	TBILLETAJEXSUC.COD_DENOMINACION	AS COD_DENOMINACION,  
	TBILLETAJEXSUC.COD_CALIDAD
FROM 
	( 
	-- MEDIOS DE PAGO 
	SELECT 
		TBULT.COD_PUNTO_SERVICIO AS SUCURSAL, 
		TBULT.DES_PUNTO_SERVICIO AS DESC_SUCURSAL, 
		TREGI.OID_REMESA_ORI AS OID_REMESA_ORI, 
		TBULT.COD_SUBCLIENTE AS COD_SUBCLIENTE, 
		TMEDI.COD_ISO_DIVISA AS DIVISA, 
		TDIVI.DES_DIVISA AS DES_DIVISA, 
		TMEDI.COD_TIPO_MEDIO_PAGO AS COD_TIPO, 
		TMEDI.DES_TIPO_MEDIO_PAGO AS DES_TIPO, 
		0 AS ES_BILLETE, 
		0 AS UNIDAD_MOEDA, 
		TMEDI.NUM_UNIDADES AS UNIDADES, 
		TMEDI.NUM_IMPORTE AS VALOR_RECONTADO, 
		CASE WHEN TMEDI.COD_TIPO_MEDIO_PAGO = 'codtipoa' 
		THEN TMEDI.DES_MEDIO_PAGO 
		ELSE NULL 
		END AS DES_MEDIO_PAGO, 
		TBULT.COD_TRANSPORTE,
		'' COD_DENOMINACION,
		NULL AS COD_CALIDAD  
	FROM 
		GEPR_TBULTO TBULT 
		INNER JOIN GEPR_TREGISTRO_MOVIMIENTO TREGI ON TBULT.OID_BULTO = TREGI.OID_BULTO 
		INNER JOIN GEPR_TMEDIO_PAGO TMEDI ON TREGI.OID_REGISTRO_MOVIMIENTO = TMEDI.OID_REGISTRO_MOVIMIENTO 
		INNER JOIN GEPR_TDIVISA TDIVI ON TMEDI.COD_ISO_DIVISA = TDIVI.COD_ISO_DIVISA 
	WHERE 
		TBULT.COD_CLIENTE = []COD_CLIENTE 
		AND TBULT.COD_DELEGACION = []COD_DELEGACION 
		[FEC_TRANSPORTE] 
		[FEC_PROCESO] 
		[FYH_FIN_CONTEO] 
		[FILTRO_PROCESO] 
		AND TREGI.COD_TIPO_MOVIMIENTO = []COD_TIPO_MOVIMENTO 
		AND TMEDI.NEC_SECUENCIA = 0 
	UNION ALL 
	--  Efectivo 
	SELECT 
		TBULT.COD_PUNTO_SERVICIO AS ESTACION, 
		TBULT.DES_PUNTO_SERVICIO AS DES_ESTACION, 
		TREGI.OID_REMESA_ORI AS OID_REMESA_ORI, 
		TBULT.COD_SUBCLIENTE AS COD_SUBCLIENTE, 
		TEFEC.COD_ISO_DIVISA AS DIVISA, 
		TDIVI.DES_DIVISA AS DES_DIVISA, 
		'Efectivo' AS COD_TIPO, 
		TDIVI.DES_DIVISA AS DES_TIPO, 
		TDENO.BOL_BILLETE AS ES_BILLETE, 
		TDENO.NUM_VALOR AS UNIDAD_MOEDA, 
		TEFEC.NEL_UNIDADES_MANUAL + TEFEC.NEL_UNIDADES_MAQUINA AS UNIDADES, 
		(TEFEC.NEL_UNIDADES_MANUAL + TEFEC.NEL_UNIDADES_MAQUINA) * TDENO.NUM_VALOR AS VALOR_RECONTADO, 
		NULL AS DES_MEDIO_PAGO, 
		TBULT.COD_TRANSPORTE,
		TEFEC.COD_DENOMINACION COD_DENOMINACION,
		CASE WHEN TEFEC.COD_CALIDAD = 'D' THEN TEFEC.COD_CALIDAD ELSE NULL END
	FROM 
		GEPR_TBULTO TBULT 
		INNER JOIN GEPR_TREGISTRO_MOVIMIENTO TREGI ON TBULT.OID_BULTO = TREGI.OID_BULTO 
		INNER JOIN GEPR_TEFECTIVO TEFEC ON TREGI.OID_REGISTRO_MOVIMIENTO = TEFEC.OID_REGISTRO_MOVIMIENTO 
		INNER JOIN GEPR_TDENOMINACION TDENO ON TEFEC.COD_DENOMINACION = TDENO.COD_DENOMINACION 
		INNER JOIN GEPR_TDIVISA TDIVI ON TDENO.OID_DIVISA = TDIVI.OID_DIVISA 
	WHERE 
		TBULT.COD_CLIENTE = []COD_CLIENTE 
		AND TBULT.COD_DELEGACION = []COD_DELEGACION 
		[FEC_TRANSPORTE] 
		[FEC_PROCESO] 
		[FYH_FIN_CONTEO] 
		[FILTRO_PROCESO] 
		AND TREGI.COD_TIPO_MOVIMIENTO = []COD_TIPO_MOVIMENTO
	) TBILLETAJEXSUC 
GROUP BY 
	TBILLETAJEXSUC.SUCURSAL, 
	TBILLETAJEXSUC.DESC_SUCURSAL, 
	TBILLETAJEXSUC.OID_REMESA_ORI, 
	TBILLETAJEXSUC.COD_SUBCLIENTE, 
	TBILLETAJEXSUC.DIVISA, 
	TBILLETAJEXSUC.DES_DIVISA, 
	TBILLETAJEXSUC.COD_TIPO, 
	TBILLETAJEXSUC.DES_TIPO, 
	TBILLETAJEXSUC.ES_BILLETE, 
	TBILLETAJEXSUC.UNIDAD_MOEDA, 
	TBILLETAJEXSUC.DES_MEDIO_PAGO, 
	TBILLETAJEXSUC.COD_TRANSPORTE,
    TBILLETAJEXSUC.COD_DENOMINACION,
	TBILLETAJEXSUC.COD_CALIDAD  
ORDER BY 
	DES_ESTACION, 
	ESTACION, 
	COD_TRANSPORTE, 
	DES_DIVISA, 
	DES_TIPO, 
	UNIDAD_MOEDA DESC