SELECT OID_TIPO_CONTENEDOR,
       COD_TIPO_CONTENEDOR,
       DES_TIPO_CONTENEDOR,
       NUM_MAXIMO_IMPORTE,
       BOL_ACEPTA_MEZCLA,
       BOL_ACEPTA_PICO,
       BOL_ACTIVO,
	   DES_USUARIO_CREACION,
	   DES_USUARIO_MODIFICACION,
	   GMT_CREACION,
	   GMT_MODIFICACION
FROM SAPR_TTIPO_CONTENEDOR