SELECT 
          OID_TIPO_MAQUINA,
          COD_TIPO_MAQUINA,
          DES_TIPO_MAQUINA,
          OBS_TIPO_MAQUINA,
          BOL_ACTIVO,
          GMT_CREACION,
          DES_USUARIO_CREACION,
          GMT_MODIFICACION,
          DES_USUARIO_MODIFICACION
FROM SAPR_TTIPO_MAQUINA