Namespace Permisos_v2.Codigos

    Public Class ATM
        Public Const asignarFormatoModeloRed As String = "ASIGNAR_FORMATO_MODELO_RED"
        Public Const editarTira As String = "EDITAR_TIRA"
        Public Const eliminarTira As String = "ELIMINAR_TIRA"
        Public Const mantenerFormatoTira As String = "MANTENER_FORMATO_TIRA"
        Public Const registrarTira As String = "REGISTRAR_TIRA"
        Public Const supervisor As String = "SUPERVISOR"
        Public Const validarDiferencias As String = "VALIDARDIFERENCIAS"
    End Class

    Public Class CargaPrevia
        Public Const cargarFichero As String = "CARGAR_FICHERO"
    End Class

    Public Class Conteo
        Public Const administrarDelegacion As String = "ADMINISTRAR_DELEGACION"
        Public Const administrarPuesto As String = "ADMINISTRAR_PUESTO"
        Public Const asignarTrabajos As String = "ASIGNAR TRABAJOS"
        Public Const ATMS As String = "ATMS"
        Public Const clasificar As String = "CLASIFICAR"
        Public Const contar As String = "CONTAR"
        Public Const conteoLibrePorParcial As String = "CONTEOLIBREPORPARCIAL"
        Public Const cuadrarDiferencias As String = "CUADRAR DIFERENCIAS"
        Public Const entregarValorMecanizado As String = "ENTREGARVALORMECANIZADO"
        Public Const gestiónOffline As String = "GESTIÓN OFFLINE"
        Public Const gestionarRecuentoMecanizado As String = "GESTIONAR_RECUENTO_MECANIZADO"
        Public Const ingresarCargaPrevia As String = "INGRESAR CARGA PREVIA"
        Public Const ingresarRemesaConteo As String = "INGRESAR REMESA CONTEO"
        Public Const ingresarRemesaSaldos As String = "INGRESAR REMESA SALDOS"
        Public Const prepararSalidas As String = "PREPARAR SALIDAS"
        Public Const supervisar As String = "SUPERVISAR"
    End Class

    Public Class EmuladorATM
        Public Const ingresarRemesaATM As String = "INGRESAR_REMESA_ATM"
    End Class

    Public Class EmuladorConteo
        Public Const ingresarRemesaConteo As String = "INGRESAR REMESA CONTEO"
        Public Const ingresarRemesaSaldos As String = "INGRESAR REMESA SALDOS"
    End Class

    Public Class Genesis
        Public Const parametrosConfigurarGenesis As String = "PARAMETROS_CONFIGURAR_GENESIS"
    End Class

    Public Class GenesisDashboard
        Public Const dashboardConteo As String = "DASHBOARD_CONTEO"
        Public Const dashboardMAE As String = "DASHBOARD_MAE"
        Public Const dashboardSaldos As String = "DASHBOARD_SALDOS"
        Public Const dashboardSalidas As String = "DASHBOARD_SALIDAS"
    End Class

    Public Class GenesisSaldos
        Public Const certificadosDocumentosPendientes As String = "CERTIFICADOS_DOCUMENTOS_PENDIENTES"
        Public Const certificadosDocumentosPendientesModificar As String = "CERTIFICADOS_DOCUMENTOS_PENDIENTES_MODIFICAR"
        Public Const certificadosGenerarConsultar As String = "CERTIFICADOS_GENERAR_CONSULTAR"
        Public Const certificadosReporteConfigurar As String = "CERTIFICADOS_REPORTE_CONFIGURAR"
        Public Const configuracionFormularios As String = "CONFIGURACION_FORMULARIOS"
        Public Const consultarSaldo As String = "CONSULTAR_SALDO"
        Public Const documento As String = "DOCUMENTO"
        Public Const documentos As String = "DOCUMENTOS"
        Public Const formularios As String = "FORMULARIOS"
        Public Const grupoDocumento As String = "GRUPO_DOCUMENTO"
        Public Const historicoInventarioBultoConsultar As String = "HISTORICO_INVENTARIO_BULTO_CONSULTAR"
        Public Const inventarioBultoConsultar As String = "INVENTARIO_BULTO_CONSULTAR"
        Public Const listadoCertificadoConsultar As String = "LISTADO_CERTIFICADO_CONSULTAR"
        Public Const mantenimientoDocumentosHijos As String = "MANTENIMIENTO_DOCUMENTOS_HIJOS"
        Public Const nivelSaldosConsultar As String = "NIVEL_SALDOS_CONSULTAR"
        Public Const permiteSustitucion As String = "PERMITE_SUSTITUCION"
        Public Const relatorioHistoricoSaldos As String = "RELATORIO_HISTORICO_SALDOS"
        Public Const relatorioSaldosCliente As String = "RELATORIO_SALDOS_CLIENTE"
        Public Const relatorioSeguimientoBultos As String = "RELATORIO_SEGUIMIENTO_BULTOS"
        Public Const relatorioTransacciones As String = "RELATORIO_TRANSACCIONES"
        Public Const resultadoCertificadoConsultar As String = "RESULTADO_CERTIFICADO_CONSULTAR"
        Public Const seleccionSector As String = "SELECCION_SECTOR"
    End Class

    Public Class GenesisSalidas
        Public Const aperturarPrecintosRecibidos As String = "APERTURAR_PRECINTOS_RECIBIDOS"
        Public Const armarBultosRemesas As String = "ARMAR_BULTOS_REMESAS"
        Public Const asignarTrabajoPuesto As String = "ASIGNAR_TRABAJO_PUESTO"
        Public Const cerrarRemesaATM As String = "CERRAR_REMESA_ATM"
        Public Const enviarEfectivoExpuesto As String = "ENVIAR_EFECTIVO_EXPUESTO"
        Public Const enviarEfectivoPrecintado As String = "ENVIAR_EFECTIVO_PRECINTADO"
        Public Const enviarExpuestoOtrosPuestos As String = "ENVIAR_EXPUESTO_OTROS_PUESTOS"
        Public Const imprimirReciboTransporte As String = "IMPRIMIR_RECIBO_TRANSPORTE"
        Public Const modificarDesglose As String = "MODIFICAR_DESGLOSE"
        Public Const parametrosConfigurarGenesis As String = "PARAMETROS_CONFIGURAR_GENESIS"
        Public Const recibirEfectivoExpuesto As String = "RECIBIR_EFECTIVO_EXPUESTO"
        Public Const recibirEfectivoPrecintado As String = "RECIBIR_EFECTIVO_PRECINTADO"
        Public Const registrarPrecintos As String = "REGISTRAR_PRECINTOS"
        Public Const romperPrecintosArmados As String = "ROMPER_PRECINTOS_ARMADOS"
        Public Const solicitaFondos As String = "SOLICITAR_FONDOS"
        Public Const supervisar As String = "SUPERVISAR"
        Public Const validarDiferencias As String = "VALIDAR_DIFERENCIAS"
    End Class

    Public Class IAC
        Public Const agrupacionesConsultar As String = "AGRUPACIONES_CONSULTAR"
        Public Const agrupacionesDarAlta As String = "AGRUPACIONES_DAR_ALTA"
        Public Const agrupacionesDarBaja As String = "AGRUPACIONES_DAR_BAJA"
        Public Const agrupacionesModificar As String = "AGRUPACIONES_MODIFICAR"
        Public Const agrupacionesParametroConsultar As String = "AGRUPACIONES_PARAMETRO_CONSULTAR"
        Public Const agrupacionesParametroDarAlta As String = "AGRUPACIONES_PARAMETRO_DAR_ALTA"
        Public Const agrupacionesParametroDarBaja As String = "AGRUPACIONES_PARAMETRO_DAR_BAJA"
        Public Const agrupacionesParametroModificar As String = "AGRUPACIONES_PARAMETRO_MODIFICAR"
        Public Const agrupConteoBultoInternoDel As String = "AGRUP_CONTEO_BULTO_INTERNO_DEL"
        Public Const agrupConteoBultoInternoPais As String = "AGRUP_CONTEO_BULTO_INTERNO_PAIS"
        Public Const agrupConteoBultoInternoPuesto As String = "AGRUP_CONTEO_BULTO_INTERNO_PUESTO"
        Public Const agrupConteoConfigAplicacionDel As String = "AGRUP_CONTEO_CONFIG_APLICACION_DEL"
        Public Const agrupConteoConfigAplicacionPais As String = "AGRUP_CONTEO_CONFIG_APLICACION_PAIS"
        Public Const agrupConteoConfigAplicacionPuesto As String = "AGRUP_CONTEO_CONFIG_APLICACION_PUESTO"
        Public Const agrupConteoConfigContadoraDel As String = "AGRUP_CONTEO_CONFIG_CONTADORA_DEL"
        Public Const agrupConteoConfigContadoraPais As String = "AGRUP_CONTEO_CONFIG_CONTADORA_PAIS"
        Public Const agrupConteoConfigContadoraPuesto As String = "AGRUP_CONTEO_CONFIG_CONTADORA_PUESTO"
        Public Const agrupConteoConfigImpresionDel As String = "AGRUP_CONTEO_CONFIG_IMPRESION_DEL"
        Public Const agrupConteoConfigImpresionPais As String = "AGRUP_CONTEO_CONFIG_IMPRESION_PAIS"
        Public Const agrupConteoConfigImpresionPuesto As String = "AGRUP_CONTEO_CONFIG_IMPRESION_PUESTO"
        Public Const agrupConteoConfigVideoDel As String = "AGRUP_CONTEO_CONFIG_VIDEO_DEL"
        Public Const agrupConteoConfigVideoPais As String = "AGRUP_CONTEO_CONFIG_VIDEO_PAIS"
        Public Const agrupConteoConfigVideoPuesto As String = "AGRUP_CONTEO_CONFIG_VIDEO_PUESTO"
        Public Const agrupConteoDatosOperativosDel As String = "AGRUP_CONTEO_DATOS_OPERATIVOS_DEL"
        Public Const agrupConteoDatosOperativosPais As String = "AGRUP_CONTEO_DATOS_OPERATIVOS_PAIS"
        Public Const agrupConteoDatosOperativosPuesto As String = "AGRUP_CONTEO_DATOS_OPERATIVOS_PUESTO"
        Public Const agrupConteoOtrosDatosDel As String = "AGRUP_CONTEO_OTROS_DATOS_DEL"
        Public Const agrupConteoOtrosDatosPais As String = "AGRUP_CONTEO_OTROS_DATOS_PAIS"
        Public Const agrupConteoOtrosDatosPuesto As String = "AGRUP_CONTEO_OTROS_DATOS_PUESTO"
        Public Const agrupConteoSaldosDel As String = "AGRUP_CONTEO_SALDOS_DEL"
        Public Const agrupConteoSaldosPais As String = "AGRUP_CONTEO_SALDOS_PAIS"
        Public Const agrupConteoSaldosPuesto As String = "AGRUP_CONTEO_SALDOS_PUESTO"
        Public Const agrupConteoServicioDel As String = "AGRUP_CONTEO_SERVICIO_DEL"
        Public Const agrupConteoServicioPais As String = "AGRUP_CONTEO_SERVICIO_PAIS"
        Public Const agrupConteoServicioPuesto As String = "AGRUP_CONTEO_SERVICIO_PUESTO"
        Public Const agrupNsalidasConfigVideoPuesto As String = "AGRUP_NSALIDAS_CONFIG_VIDEO_PUESTO"
        Public Const agrupRyeConfigVideoPuesto As String = "AGRUP_RYE_CONFIG_VIDEO_PUESTO"
        Public Const agrupSalidasConfigAplicacionPuesto As String = "AGRUP_SALIDAS_CONFIG_APLICACION_PUESTO"
        Public Const agrupSalidasConfigContadoraPuesto As String = "AGRUP_SALIDAS_CONFIG_CONTADORA_PUESTO"
        Public Const agrupSalidasDatosIntegracionDel As String = "AGRUP_SALIDAS_DATOS_INTEGRACION_DEL"
        Public Const agrupSalidasDatosIntegracionPais As String = "AGRUP_SALIDAS_DATOS_INTEGRACION_PAIS"
        Public Const agrupSalidasDatosOperativosDel As String = "AGRUP_SALIDAS_DATOS_OPERATIVOS_DEL"
        Public Const agrupSalidasDatosOperativosPais As String = "AGRUP_SALIDAS_DATOS_OPERATIVOS_PAIS"
        Public Const atmConsultar As String = "ATM_CONSULTAR"
        Public Const atmDarAlta As String = "ATM_DAR_ALTA"
        Public Const atmDarBaja As String = "ATM_DAR_BAJA"
        Public Const atmModificar As String = "ATM_MODIFICAR"
        Public Const canalesConsultar As String = "CANALES_CONSULTAR"
        Public Const canalesDarAlta As String = "CANALES_DAR_ALTA"
        Public Const canalesDarBaja As String = "CANALES_DAR_BAJA"
        Public Const canalesModificar As String = "CANALES_MODIFICAR"
        Public Const caracteristicasConsultar As String = "CARACTERISTICAS_CONSULTAR"
        Public Const caracteristicasDarAlta As String = "CARACTERISTICAS_DAR_ALTA"
        Public Const caracteristicasDarBaja As String = "CARACTERISTICAS_DAR_BAJA"
        Public Const caracteristicasModificar As String = "CARACTERISTICAS_MODIFICAR"
        Public Const clientesBuscar As String = "CLIENTES_BUSCAR"
        Public Const clientesConsultar As String = "CLIENTES_CONSULTAR"
        Public Const clientesDarAlta As String = "CLIENTES_DAR_ALTA"
        Public Const clientesDarBaja As String = "CLIENTES_DAR_BAJA"
        Public Const clientesModificar As String = "CLIENTES_MODIFICAR"
        Public Const configuracionParametroModificar As String = "CONFIGURACION_PARAMETRO_MODIFICAR"
        Public Const delegacionConsultar As String = "DELEGACION_CONSULTAR"
        Public Const delegacionDarAlta As String = "DELEGACION_DAR_ALTA"
        Public Const delegacionDarBaja As String = "DELEGACION_DAR_BAJA"
        Public Const delegacionModificar As String = "DELEGACION_MODIFICAR"
        Public Const divisasConsultar As String = "DIVISAS_CONSULTAR"
        Public Const divisasDarAlta As String = "DIVISAS_DAR_ALTA"
        Public Const divisasDarBaja As String = "DIVISAS_DAR_BAJA"
        Public Const divisasModificar As String = "DIVISAS_MODIFICAR"
        Public Const divisasSincronizar As String = "DIVISAS_SINCRONIZAR"
        Public Const grupoClienteConsultar As String = "GRUPO_CLIENTE_CONSULTAR"
        Public Const grupoClienteDarAlta As String = "GRUPO_CLIENTE_DAR_ALTA"
        Public Const grupoClienteDarBaja As String = "GRUPO_CLIENTE_DAR_BAJA"
        Public Const grupoClienteModificar As String = "GRUPO_CLIENTE_MODIFICAR"
        Public Const informacionAdicionalClienteConsultar As String = "INFORMACION_ADICIONAL_CLIENTE_CONSULTAR"
        Public Const informacionAdicionalClienteDarAlta As String = "INFORMACION_ADICIONAL_CLIENTE_DAR_ALTA"
        Public Const informacionAdicionalClienteDarBaja As String = "INFORMACION_ADICIONAL_CLIENTE_DAR_BAJA"
        Public Const informacionAdicionalClienteModificar As String = "INFORMACION_ADICIONAL_CLIENTE_MODIFICAR"
        Public Const integracionBoIacConsultar As String = "INTEGRACION_BO_IAC_CONSULTAR"
        Public Const integracionBoIacDarAlta As String = "INTEGRACION_BO_IAC_DAR_ALTA"
        Public Const integracionBoIacDarBaja As String = "INTEGRACION_BO_IAC_DAR_BAJA"
        Public Const integracionBoIacModificacion As String = "INTEGRACION_BO_IAC_MODIFICACION"
        Public Const integracionIacBoEnviarDatos As String = "INTEGRACION_IAC_BO_ENVIAR_DATOS"
        Public Const loginIac As String = "LOGIN_IAC"
        Public Const medioDePagoConsultar As String = "MEDIO_DE_PAGO_CONSULTAR"
        Public Const medioDePagoDarAlta As String = "MEDIO_DE_PAGO_DAR_ALTA"
        Public Const medioDePagoDarBaja As String = "MEDIO_DE_PAGO_DAR_BAJA"
        Public Const medioDePagoDuplicar As String = "MEDIO_DE_PAGO_DUPLICAR"
        Public Const medioDePagoModificar As String = "MEDIO_DE_PAGO_MODIFICAR"
        Public Const modalidadRecuentoConsultar As String = "MODALIDAD_RECUENTO_CONSULTAR"
        Public Const modalidadRecuentoDarAlta As String = "MODALIDAD_RECUENTO_DAR_ALTA"
        Public Const modalidadRecuentoDarBaja As String = "MODALIDAD_RECUENTO_DAR_BAJA"
        Public Const modalidadRecuentoModificar As String = "MODALIDAD_RECUENTO_MODIFICAR"
        Public Const morfologiaConsultar As String = "MORFOLOGIA_CONSULTAR"
        Public Const morfologiaDarAlta As String = "MORFOLOGIA_DAR_ALTA"
        Public Const morfologiaDarBaja As String = "MORFOLOGIA_DAR_BAJA"
        Public Const parametroConsultar As String = "PARAMETRO_CONSULTAR"
        Public Const parametroDarAlta As String = "PARAMETRO_DAR_ALTA"
        Public Const parametroDarBaja As String = "PARAMETRO_DAR_BAJA"
        Public Const parametroModificar As String = "PARAMETRO_MODIFICAR"
        Public Const parametrosConfigurarAtm As String = "PARAMETROS_CONFIGURAR_ATM"
        Public Const parametrosConfigurarConteo As String = "PARAMETROS_CONFIGURAR_CONTEO"
        Public Const parametrosConfigurarDelegacion As String = "PARAMETROS_CONFIGURAR_DELEGACION"
        Public Const parametrosConfigurarEmulador As String = "PARAMETROS_CONFIGURAR_EMULADOR"
        Public Const parametrosConfigurarGenesis As String = "PARAMETROS_CONFIGURAR_GENESIS"
        Public Const parametrosConfigurarNuevoSaldos As String = "PARAMETROS_CONFIGURAR_NUEVO_SALDOS"
        Public Const parametrosConfigurarNuevoSalidas As String = "PARAMETROS_CONFIGURAR_NUEVO_SALIDAS"
        Public Const parametrosConfigurarPais As String = "PARAMETROS_CONFIGURAR_PAIS"
        Public Const parametrosConfigurarPuesto As String = "PARAMETROS_CONFIGURAR_PUESTO"
        Public Const parametrosConfigurarRecepcionyEnvio As String = "PARAMETROS_CONFIGURAR_RECEPCION_Y_ENVIO"
        Public Const parametrosConfigurarReportes As String = "PARAMETROS_CONFIGURAR_REPORTES"
        Public Const parametrosConfigurarSaldos As String = "PARAMETROS_CONFIGURAR_SALDOS"
        Public Const parametrosConfigurarSalidas As String = "PARAMETROS_CONFIGURAR_SALIDAS"
        Public Const procedenciasConsultar As String = "PROCEDENCIAS_CONSULTAR"
        Public Const procedenciasDarAlta As String = "PROCEDENCIAS_DAR_ALTA"
        Public Const procedenciasDarBaja As String = "PROCEDENCIAS_DAR_BAJA"
        Public Const procedenciasModificar As String = "PROCEDENCIAS_MODIFICAR"
        Public Const procesosAsignarFechas As String = "PROCESOS_ASIGNAR_FECHAS"
        Public Const procesosBuscar As String = "PROCESOS_BUSCAR"
        Public Const procesosConsultar As String = "PROCESOS_CONSULTAR"
        Public Const procesosConsultarDetalle As String = "PROCESOS_CONSULTAR_DETALLE"
        Public Const procesosDarAlta As String = "PROCESOS_DAR_ALTA"
        Public Const procesosDarBaja As String = "PROCESOS_DAR_BAJA"
        Public Const procesosDuplicar As String = "PROCESOS_DUPLICAR"
        Public Const procesosModificar As String = "PROCESOS_MODIFICAR"
        Public Const procesosModificarFechas As String = "PROCESOS_MODIFICAR_FECHAS"
        Public Const productosConsultar As String = "PRODUCTOS_CONSULTAR"
        Public Const puestosConsultar As String = "PUESTOS_CONSULTAR"
        Public Const puestosDarAlta As String = "PUESTOS_DAR_ALTA"
        Public Const puestosDarBaja As String = "PUESTOS_DAR_BAJA"
        Public Const puestosDuplicar As String = "PUESTOS_DUPLICAR"
        Public Const puestosModificar As String = "PUESTOS_MODIFICAR"
        Public Const puntoServicioConsultar As String = "PUNTO_SERVICIO_CONSULTAR"
        Public Const puntoServicioDarAlta As String = "PUNTO_SERVICIO_DAR_ALTA"
        Public Const puntoServicioDarBaja As String = "PUNTO_SERVICIO_DAR_BAJA"
        Public Const puntoServicioModificar As String = "PUNTO_SERVICIO_MODIFICAR"
        Public Const sectorConsultar As String = "SECTOR_CONSULTAR"
        Public Const sectorDarAlta As String = "SECTOR_DAR_ALTA"
        Public Const sectorDarBaja As String = "SECTOR_DAR_BAJA"
        Public Const sectorModificar As String = "SECTOR_MODIFICAR"
        Public Const subClientesConsultar As String = "SUB_CLIENTES_CONSULTAR"
        Public Const subClientesDarAlta As String = "SUB_CLIENTES_DAR_ALTA"
        Public Const subClientesDarBaja As String = "SUB_CLIENTES_DAR_BAJA"
        Public Const subClientesModificar As String = "SUB_CLIENTES_MODIFICAR"
        Public Const terminosIacConsultar As String = "TERMINOS_IAC_CONSULTAR"
        Public Const terminosIacDarAlta As String = "TERMINOS_IAC_DAR_ALTA"
        Public Const terminosIacDarBaja As String = "TERMINOS_IAC_DAR_BAJA"
        Public Const terminosIacGestionarValoresTermino As String = "TERMINOS_IAC_GESTIONAR_VALORES_TERMINO"
        Public Const terminosIacModificar As String = "TERMINOS_IAC_MODIFICAR"
        Public Const tipoclienteConsultar As String = "TIPOCLIENTE_CONSULTAR"
        Public Const tipoclienteDarAlta As String = "TIPOCLIENTE_DAR_ALTA"
        Public Const tipoclienteDarBaja As String = "TIPOCLIENTE_DAR_BAJA"
        Public Const tipoclienteModificar As String = "TIPOCLIENTE_MODIFICAR"
        Public Const tipoprocedenciaConsultar As String = "TIPOPROCEDENCIA_CONSULTAR"
        Public Const tipoprocedenciaDarAlta As String = "TIPOPROCEDENCIA_DAR_ALTA"
        Public Const tipoprocedenciaDarBaja As String = "TIPOPROCEDENCIA_DAR_BAJA"
        Public Const tipoprocedenciaModificar As String = "TIPOPROCEDENCIA_MODIFICAR"
        Public Const tipoProcesadoConsultar As String = "TIPO_PROCESADO_CONSULTAR"
        Public Const tipoProcesadoDarAlta As String = "TIPO_PROCESADO_DAR_ALTA"
        Public Const tipoProcesadoDarBaja As String = "TIPO_PROCESADO_DAR_BAJA"
        Public Const tipoProcesadoModificar As String = "TIPO_PROCESADO_MODIFICAR"
        Public Const tipopuntoservicioConsultar As String = "TIPOPUNTOSERVICIO_CONSULTAR"
        Public Const tipopuntoservicioDarAlta As String = "TIPOPUNTOSERVICIO_DAR_ALTA"
        Public Const tipopuntoservicioDarBaja As String = "TIPOPUNTOSERVICIO_DAR_BAJA"
        Public Const tipopuntoservicioModificar As String = "TIPOPUNTOSERVICIO_MODIFICAR"
        Public Const tiposectorConsultar As String = "TIPOSECTOR_CONSULTAR"
        Public Const tiposectorDarAlta As String = "TIPOSECTOR_DAR_ALTA"
        Public Const tiposectorDarBaja As String = "TIPOSECTOR_DAR_BAJA"
        Public Const tiposectorModificar As String = "TIPOSECTOR_MODIFICAR"
        Public Const tiposubclienteConsultar As String = "TIPOSUBCLIENTE_CONSULTAR"
        Public Const tiposubclienteDarAlta As String = "TIPOSUBCLIENTE_DAR_ALTA"
        Public Const tiposubclienteDarBaja As String = "TIPOSUBCLIENTE_DAR_BAJA"
        Public Const tiposubclienteModificar As String = "TIPOSUBCLIENTE_MODIFICAR"
        Public Const valoresPosiblesConsultar As String = "VALORES_POSIBLES_CONSULTAR"
        Public Const valoresPosiblesDarAlta As String = "VALORES_POSIBLES_DAR_ALTA"
        Public Const valoresPosiblesDarBaja As String = "VALORES_POSIBLES_DAR_BAJA"
        Public Const valoresPosiblesModificar As String = "VALORES_POSIBLES_MODIFICAR"
    End Class

    Public Class RecepcionyEnvio
        Public Const recibirRuta As String = "Recibir_Ruta"
        Public Const registrarRemesa As String = "Registrar_Remesa"
        Public Const alocarRemesa As String = "Alocar_Remesa"
        Public Const liberarRuta As String = "Liberar_Ruta"
        Public Const registrarPedidoExterno As String = "Registrar_Pedido_Externo"
        Public Const liberarPedidoExterno As String = "Liberar_Pedido_Externo"

    End Class

    Public Class PackModular
        Public Const ContenedorArmar As String = "CONTENEDOR_ARMAR"
        Public Const ContenedorConsultar As String = "CONTENEDOR_CONSULTAR"
        Public Const ContenedorMoverClientes As String = "CONTENEDOR_MOVER_CLIENTES"
        Public Const ContenedorMoverSectores As String = "CONTENEDOR_MOVER_SECTORES"
        Public Const ContenedorRecepcionar As String = "CONTENEDOR_RECEPCIONAR"
        Public Const ContenedorExtrair As String = "CONTENEDOR_EXTRAIR"
        Public Const ContenedorDesarmar As String = "CONTENEDOR_DESARMAR"

    End Class

    Public Class Reportes
        Public Const billetajeSucursalConsultar As String = "BILLETAJE_SUCURSAL_CONSULTAR"
        Public Const contadoPuestoConsultar As String = "CONTADO_PUESTO_CONSULTAR"
        Public Const corteParcialConsultar As String = "CORTE_PARCIAL_CONSULTAR"
        Public Const detalleParcialesConsultar As String = "DETALLE_PARCIALES_CONSULTAR"
        Public Const informeRsultadoContajeConsultar As String = "INFORME_RESULTADO_CONTAJE_CONSULTAR"
        Public Const loginReportes As String = "LOGIN_REPORTES"
        Public Const parteDiferenciasConsultar As String = "PARTE_DIFERENCIAS_CONSULTAR"
        Public Const reciboFRespaldoConsultar As String = "RECIBO_F_RESPALDO_CONSULTAR"
        Public Const relacionHabilitacionTiraConteoConsultar As String = "RELACION_HABILITACION_TIRA_CONTEO_CONSULTAR"
        Public Const reportesConsultar As String = "REPORTES_CONSULTAR"
        Public Const reportesModificar As String = "REPORTES_MODIFICAR"
        Public Const respaldoCompletoConsultar As String = "RESPALDO_COMPLETO_CONSULTAR"
    End Class

    Public Class Saldos
        Public Const SaldosAcceso As String = "SALDOS_ACCESO"
    End Class

    Public Class Salidas
        Public Const armar As String = "Armar"
        Public Const configurarTiposBulto As String = "Configurar_Tipos_Bulto"
        Public Const controlar As String = "Controlar"
        Public Const preparar As String = "Preparar"
        Public Const supervisar As String = "Supervisar"
    End Class

    Public Class SupervisorConteo
        Public Const cuadrarDiferencias As String = "Cuadrar diferencias"
        Public Const ingresarCargaPrevia As String = "Ingresar carga previa"
        Public Const supervisar As String = "Supervisar"
    End Class

End Namespace

