Namespace Parametros_v2.Codigos

    Namespace Genesis
        Public Class Delegacion
            Public Const direccionActualizacionGenesis As String = "DIRECCIONACTUALIZACIONGENESIS"
            Public Const integracionNuevoSaldosURLWeb As String = "INTEGRACIONNUEVOSALDOSURLWEB"
            Public Const urlServicioIntegracionSol As String = "URLSERVICIOINTEGRACIONSOL"
            Public Const AgruparModulos As String = "AGRUPARMODULOS"
            Public Const codigoClienteCuentaCero As String = "CODIGOCLIENTECUENTACERO"
        End Class
        Public Class Pais
            Public Const canalesValoresDepositadosMAE As String = "CANALESVALORESDEPOSITADOSMAE"
            Public Const canalesValoresValidadosMAE As String = "CANALESVALORESVALIDADOSMAE"
            Public Const codigoCanalATM As String = "CODIGOCANALATM"
            Public Const codigoCanalCambios As String = "CODIGOCANALCAMBIOS"
            Public Const codigoCanalSaldos As String = "CODIGOCANALSALDOS"
            Public Const codigoFormatoBolsonaGrupador As String = "CODIGOFORMATOBOLSONAGRUPADOR"
            Public Const codigosFormulariosShipoutMAE As String = "CODIGOSFORMULARIOSSHIPOUTMAE"
            Public Const mantenimientoClientesDivisasporPantalla As String = "MANTENIMIENTOCLIENTESDIVISASPORPANTALLA"
            Public Const tiposSectoresMAE As String = "TIPOSSECTORESMAE"
        End Class
    End Namespace

    Namespace RecepcionyEnvio
        Public Class Puesto
            Public Const estadoSistemaVideo2 As String = "ESTADOSISTEMAVIDEO2"
            Public Const portaSocketDVR As String = "PORTASOCKETDVR"
            Public Const utilizarReglaAutomata As String = "UTILIZARREGLAAUTOMATA"
            Public Const videoHost As String = "VIDEOHOST"
            Public Const videoIP As String = "VIDEOIP"
            Public Const videoIP2 As String = "VIDEOIP2"
            Public Const videoModelo As String = "VIDEOMODELO"
            Public Const videoModelo2 As String = "VIDEOMODELO2"
            Public Const videoNumeroCamara As String = "VIDEONUMEROCAMARA"
            Public Const videoNumeroCamara2 As String = "VIDEONUMEROCAMARA2"
            Public Const videoPassword As String = "VIDEOPASSWORD"
            Public Const videoPassword2 As String = "VIDEOPASSWORD2"
            Public Const videoUsuario As String = "VIDEOUSUARIO"
            Public Const videoUsuario2 As String = "VIDEOUSUARIO2"
        End Class
        Public Class Pais
            Public Const buscaAutomaticaRemesasnoEnviadasSOL As String = "BUSCAAUTOMATICAREMESASNOENVIADASSOL"
            Public Const calculoAutomaticoDeclaradoBulto As String = "CALCULOAUTOMATICODECLARADOBULTO"
            Public Const calculoAutomaticoDeclaradoTotal As String = "CALCULOAUTOMATICODECLARADOTOTAL"
            Public Const codigoEmbalajePorDefecto As String = "CODIGOEMBALAJEPORDEFECTO"
            Public Const codigoEmisorExternoPorDefecto As String = "CODIGOEMISOREXTERNOPORDEFECTO"
            Public Const codigoEmisorPorDefecto As String = "CODIGOEMISORPORDEFECTO"
            Public Const codigoSectorConteoPorDefecto As String = "CODIGOSECTORCONTEOPORDEFECTO"
            Public Const codigoSectorRecepcionPorDefecto As String = "CODIGOSECTORRECEPCIONPORDEFECTO"
            Public Const codigoSectorSalidaPorDefecto As String = "CODIGOSECTORSALIDAPORDEFECTO"
            Public Const codigoServicioPorDefecto As String = "CODIGOSERVICIOPORDEFECTO"
            Public Const codigoCanalPorDefecto As String = "CODIGOCANALPORDEFECTO"
            Public Const codigoDivisaPorDefecto As String = "CODIGODIVISAPORDEFECTO"
            Public Const codigoDenominacionPorDefecto As String = "CODIGODENOMINACIONPORDEFECTO"
            Public Const codigoSubCanalPorDefecto As String = "CODIGOSUBCANALPORDEFECTO"
            Public Const exhibeReporte As String = "EXHIBEREPORTE"
            Public Const grabaDeclaradoSimplificado As String = "GRABADECLARADOSIMPLIFICADO"
            Public Const grabaRemesaAutomatico As String = "GRABAREMESAAUTOMATICO"
            Public Const imprimirSolamenteDocTransferenciaResponsabilidad As String = "IMPRIMIRSOLAMENTEDOCTRANSFERENCIARESPONSABILIDAD"
            Public Const ingresarBultoSimplificado As String = "INGRESARBULTOSIMPLIFICADO"
            Public Const ingresoRemesaExternaSaldosI As String = "INGRESOREMESAEXTERNASALDOSI"
            Public Const integracionNuevoSaldosURLWeb As String = "INTEGRACIONNUEVOSALDOSURLWEB"
            Public Const integracionSOLURLServicio As String = "INTEGRACIONSOLURLSERVICIO"
            Public Const obligatorioLeerPrecinto As String = "OBLIGATORIOLEERPRECINTO"
            Public Const obligatorioLeerRemesa As String = "OBLIGATORIOLEERREMESA"
            Public Const seleccionAutomaticaBulto As String = "SELECCIONAUTOMATICABULTO"
            Public Const turnoPeriodo As String = "TURNOPERIODO"
            Public Const cargarBultosAutomaticamente As String = "CARGARBULTOSAUTOMATICAMENTE"
            Public Const cargarPuntoServicio As String = "CARGARPUNTOSERVICIO"
            Public Const codigoSectorTransitoSinCustodia As String = "CODIGOSECTORTRANSITOSINCUSTODIA"
        End Class
        Public Class Delegacion
            Public Const TraspaseResponsabilidad As String = "TraspaseResponsabilidad"
            Public Const TenerVariosFormatosEnRemesa As String = "TenerVariosFormatosEnRemesa"
            Public Const GenerarPrecintoModuloAutomatico As String = "GenerarPrecintoModuloAutomatico"
            Public Const AgruparModulos As String = "AgruparModulos"
            Public Const CrearPrecintoAutomáticoModulo As String = "CrearPrecintoAutomáticoModulo"
            Public Const DireccionProgramacionServicios As String = "DireccionProgramacionServicios"
            Public Const DireccionDocumentos As String = "DireccionDocumentos"
            Public Const DireccionRutas As String = "DireccionRutas"
            Public Const DireccionOTs As String = "DireccionOTs"
            Public Const DireccionModulos As String = "DireccionModulos"
            Public Const DireccionServicios As String = "DireccionServicios"
            Public Const CodigosProdutosTransitoSOL As String = "CODPRODUTOSTRANSITOSOL"
            Public Const CodigosProdutosInterplantasSOL As String = "CODPRODUTOSINTERPLANTASSOL"
        End Class
    End Namespace

    Namespace PackModular
        Public Class Pais
            Public Const imprimirSolamenteDocTransferenciaResponsabilidad As String = "IMPRIMIRSOLAMENTEDOCTRANSFERENCIARESPONSABILIDAD"
        End Class
        Public Class Delegacion
            Public Const CodigoServicioPorDefecto As String = "CODIGOSERVICIOPORDEFECTO"
            Public Const CodigoCanalPorDefecto As String = "CODIGOCANALPORDEFECTO"
            Public Const CodigoDivisaPorDefecto As String = "CODIGODIVISAPORDEFECTO"
            Public Const CodigoDenominacionPorDefecto As String = "CODIGODENOMINACIONPORDEFECTO"
            Public Const CodigoSubCanalPorDefecto As String = "CODIGOSUBCANALPORDEFECTO"
            Public Const ImprimirEtiquetaTodosPrecintosContenedor As String = "ImprimirEtiquetaTodosPrecintosContenedor"
            Public Const InformarDivisaPackModular As String = "InformarDivisaPackModular"
            Public Const CodFormularioArmarContPack As String = "CodFormularioArmarContPack"
            Public Const CodFormuarioReenvioEntreSectores As String = "CodFormularioMoverContPMEntreSectores"
            Public Const CodFormularioMoverContPMEntreClientes As String = "CodFormularioMoverContPMEntreClientes"
            Public Const CodFormularioMoverContPMContaProsegur As String = "CodFormularioMoverContPMContaProsegur"
            Public Const CodFormularioDesarmarContenedoresPM As String = "CodFormularioDesarmarContenedoresPM"
            Public Const DireccionImpresoraEtiqueta As String = "DireccionImpresoraEtiqueta"
            Public Const CodFormularioDesarmarContenedores As String = "CodFormularioDesarmarContenedores"
        End Class
    End Namespace

    Namespace Conteo
        Public Class Puesto
            Public Const contadoraBilleteHost As String = "CONTADORABILLETEHOST"
            Public Const contadoraBilleteLink As String = "CONTADORABILLETELINK"
            Public Const contadoraBilleteModelo As String = "CONTADORABILLETEMODELO"
            Public Const contadoraMonedaHost As String = "CONTADORAMONEDAHOST"
            Public Const contadoraMonedaLink As String = "CONTADORAMONEDALINK"
            Public Const contadoraMonedaModelo As String = "CONTADORAMONEDAMODELO"
            Public Const direccionImpresoraEtiqueta As String = "DIRECCIONIMPRESORAETIQUETA"
            Public Const esMecanizado As String = "ESMECANIZADO"
            Public Const estadoSistemaVideo2 As String = "ESTADOSISTEMAVIDEO2"
            Public Const impresoraModelo As String = "IMPRESORAMODELO"
            Public Const impresoraNome As String = "IMPRESORANOME"
            Public Const impresoraNomeReporte As String = "IMPRESORANOMEREPORTE"
            Public Const layoutTicketEntregarValores As String = "LAYOUTTICKETENTREGARVALORES"
            Public Const noCuadrarBilletesValorMenor As String = "NOCUADRARBILLETESVALORMENOR"
            Public Const noCuadrarMonedasValorMenor As String = "NOCUADRARMONEDASVALORMENOR"
            Public Const nombreMaquinaContadora As String = "NOMBREMAQUINACONTADORA"
            Public Const noValidarCantidadParcialesCP As String = "NOVALIDARCANTIDADPARCIALESCP"
            Public Const permitiRefectuarSalida As String = "PERMITIREFECTUARSALIDA"
            Public Const portaSocketContadora As String = "PORTASOCKETCONTADORA"
            Public Const portaSocketDVR As String = "PORTASOCKETDVR"
            Public Const sector As String = "SECTOR"
            Public Const supervisorSeleccionaTira As String = "SUPERVISORSELECCIONATIRA"
            Public Const supervisorValidaHabilitacion As String = "SUPERVISORVALIDAHABILITACION"
            Public Const utilizarGridDeComposicionManual As String = "UTILIZARGRIDDECOMPOSICIONMANUAL"
            Public Const videoHost As String = "VIDEOHOST"
            Public Const videoIP As String = "VIDEOIP"
            Public Const videoIP2 As String = "VIDEOIP2"
            Public Const videoModelo As String = "VIDEOMODELO"
            Public Const videoMdelo2 As String = "VIDEOMODELO2"
            Public Const videoNumeroCamara As String = "VIDEONUMEROCAMARA"
            Public Const videoNumeroCamara2 As String = "VIDEONUMEROCAMARA2"
            Public Const videoPassword As String = "VIDEOPASSWORD"
            Public Const videoPassword2 As String = "VIDEOPASSWORD2"
            Public Const videoUsuario As String = "VIDEOUSUARIO"
            Public Const videoUsuario2 As String = "VIDEOUSUARIO2"
        End Class
        Public Class Delegacion
            Public Const categorizacionManual As String = "CATEGORIZACIONMANUAL"
            Public Const codigoCanal As String = "CODIGOCANAL"
            Public Const codigoClasificacion As String = "CODIGOCLASIFICACION"
            Public Const codigoCliente As String = "CODIGOCLIENTE"
            Public Const codigoFormato As String = "CODIGOFORMATO"
            Public Const codigoISODivisa As String = "CODIGOISODIVISA"
            Public Const codigoPuntoServicio As String = "CODIGOPUNTOSERVICIO"
            Public Const codigorecuento As String = "CODIGORECUENTO"
            Public Const codigoSectorSalidas As String = "CODIGOSECTORSALIDAS"
            Public Const codigoSubCanal As String = "CODIGOSUBCANAL"
            Public Const codigoSubCliente As String = "CODIGOSUBCLIENTE"
            Public Const codigoTransporte As String = "CODIGOTRANSPORTE"
            Public Const colorFondoCampo As String = "COLORFONDOCAMPO"
            Public Const comprobarPrecintoHabilitacion As String = "COMPROBARPRECINTOHABILITACION"
            Public Const confirmarImpresionEntregaValores As String = "CONFIRMARIMPRESIONENTREGAVALORES"
            Public Const contadorAceptaDiferencias As String = "CONTADORACEPTADIFERENCIAS"
            Public Const cuadraDeclTotalSinDeclMedioPago As String = "CUADRADECLTOTALSINDECLMEDIOPAGO"
            Public Const cuadrarBultoDeclaradoCero As String = "CUADRARBULTODECLARADOCERO"
            Public Const cuadrarParcialDeclaradoCero As String = "CUADRARPARCIALDECLARADOCERO"
            Public Const cuadrarRemesaDeclaradoCero As String = "CUADRARREMESADECLARADOCERO"
            Public Const cuentabilletemonedadeteriorados As String = "CUENTABILLETEMONEDADETERIORADOS"
            Public Const declaradosIAC As String = "DECLARADOSIAC"
            Public Const direcciónArchivoMapeo As String = "DIRECCIÓNARCHIVOMAPEO"
            Public Const direccionArchivosImportados As String = "DIRECCIONARCHIVOSIMPORTADOS"
            Public Const dividirRemesaATM As String = "DIVIDIRREMESAATM"
            Public Const entregarFalsos As String = "ENTREGARFALSOS"
            Public Const entregasParciales As String = "ENTREGASPARCIALES"
            Public Const enviarValoresPorCuentaUnica As String = "ENVIARVALORESPORCUENTAUNICA"
            Public Const esfuentegrande As String = "ESFUENTEGRANDE"
            Public Const exhibirComentarioTicket As String = "EXHIBIRCOMENTARIOTICKET"
            Public Const exhibirListaImpresoras As String = "EXHIBIRLISTAIMPRESORAS"
            Public Const exhibirPreguntaImprimirReporte As String = "EXHIBIRPREGUNTAIMPRIMIRREPORTE"
            Public Const fechaBaseBusquedaRemesa As String = "FECHABASEBUSQUEDAREMESA"
            Public Const fechaBaseTransporteRemesa As String = "FECHABASETRANSPORTEREMESA"
            Public Const generarCodigoPrecinto As String = "GENERARCODIGOPRECINTO"
            Public Const generarReporteTipo As String = "GENERARREPORTETIPO"
            Public Const importarNumeroSerie As String = "IMPORTARNUMEROSERIE"
            Public Const informacionRemesaVisible As String = "INFORMACIONREMESAVISIBLE"
            Public Const informarCategorizacionManual As String = "INFORMARCATEGORIZACIONMANUAL"
            Public Const informarClaveSupervisorAntigua As String = "INFORMARCLAVESUPERVISORANTIGUA"
            Public Const introduccionCliente As String = "INTRODUCCIONCLIENTE"
            Public Const limitereIntentos As String = "LIMITEREINTENTOS"
            Public Const lineasPorPagina As String = "LINEASPORPAGINA"
            Public Const listaImpresoras As String = "LISTAIMPRESORAS"
            Public Const modificarDeclaradosLegacy As String = "MODIFICARDECLARADOSLEGACY"
            Public Const mostrarCliente As String = "MOSTRARCLIENTE"
            Public Const mostrarTotaleSenDif As String = "MOSTRARTOTALESENDIF"
            Public Const noCuentaBultoInterno As String = "NOCUENTABULTOINTERNO"
            Public Const noExibirMedioPagoTotal As String = "NOEXIBIRMEDIOPAGOTOTAL"
            Public Const nombreCanal As String = "NOMBRECANAL"
            Public Const nombreCliente As String = "NOMBRECLIENTE"
            Public Const nombrePuntoServicio As String = "NOMBREPUNTOSERVICIO"
            Public Const nombreSubCanal As String = "NOMBRESUBCANAL"
            Public Const nombreSubCliente As String = "NOMBRESUBCLIENTE"
            Public Const numConfecBultoxDelegacion As String = "NUMCONFECBULTOXDELEGACION"
            Public Const pantallaComentariosSupervisor As String = "PANTALLACOMENTARIOSSUPERVISOR"
            Public Const pantallaCuadrarDiferencias As String = "PANTALLACUADRARDIFERENCIAS"
            Public Const pathXMLCalidades As String = "PATHXMLCALIDADES"
            Public Const pathXMLDivisas As String = "PATHXMLDIVISAS"
            Public Const pathXMLSupervisores As String = "PATHXMLSUPERVISORES"
            Public Const pathXMLUsuarios As String = "PATHXMLUSUARIOS"
            Public Const permitirSalvarDifPropias As String = "PERMITIRSALVARDIFPROPIAS"
            Public Const retirarValoresMientrasCuenta As String = "RETIRARVALORESMIENTRASCUENTA"
            Public Const rutaSaldo As String = "RUTASALDO"
            Public Const showContado As String = "SHOWCONTADO"
            Public Const showDeclaradosTotales As String = "SHOWDECLARADOSTOTALES"
            Public Const showDifDecremdecBulto As String = "SHOWDIFDECREMDECBULTO"
            Public Const showDifDecremdecBultoSinParc As String = "SHOWDIFDECREMDECBULTOSINPARC"
            Public Const showDifDecremdecParc As String = "SHOWDIFDECREMDECPARC"
            Public Const subCanalDeposito As String = "SUBCANALDEPOSITO"
            Public Const subCanalDispensador As String = "SUBCANALDISPENSADOR"
            Public Const subCanalIngresador As String = "SUBCANALINGRESADOR"
            Public Const supervisorRealizaParcializacion As String = "SUPERVISORREALIZAPARCIALIZACION"
            Public Const supervisorValidaParciales As String = "SUPERVISORVALIDAPARCIALES"
            Public Const telaConteo As String = "TELACONTEO"
            Public Const tipoControleCuadre As String = "TIPOCONTROLECUADRE"
            Public Const tipoeTiquetaMecanizado As String = "TIPOETIQUETAMECANIZADO"
            Public Const tiposDiferencias As String = "TIPOSDIFERENCIAS"
            Public Const ubicacionDestino As String = "UBICACIONDESTINO"
            Public Const ubicacionDestinoClasificacion As String = "UBICACIONDESTINOCLASIFICACION"
            Public Const verEntregarTodo As String = "VERENTREGARTODO"
        End Class
        Public Class Pais
            Public Const buscarSoloRemesasNoContadas As String = "BUSCARSOLOREMESASNOCONTADAS"
            Public Const exhibirPantallaBloquearPuesto As String = "EXHIBIRPANTALLABLOQUEARPUESTO"
            Public Const idInformesMecanizado As String = "IDINFORMESMECANIZADO"
        End Class
    End Namespace

    Namespace ATM
        Public Class Delegacion
            Public Const exhibirPantallaCuadre As String = "EXHIBIRPANTALLACUADRE"
            Public Const permitirSalvarDifPropias As String = "PERMITIRSALVARDIFPROPIAS"
            Public Const resaltarDiferencias As String = "RESALTARDIFERENCIAS"
            Public Const validarCargaHabilitacion As String = "VALIDARCARGAHABILITACION"
        End Class
    End Namespace

    Namespace GenesisSaldos
        Public Class Delegacion
            Public Const sectorCustodiaBancoCentral As String = "SECTORCUSTODIABANCOCENTRAL"
            Public Const sectorEfectivo As String = "SECTOREFECTIVO"
            Public Const sectorRecuentoATM As String = "SECTORRECUENTOATM"
        End Class
        Public Class Pais
            Public Const bolGestionaPorBulto As String = "BOLGESTIONAPORBULTO"
            Public Const codigoComprovanteBasadoenReglas As String = "CODIGOCOMPROVANTEBASADOENREGLAS"
            Public Const codigoISODivisaDefecto As String = "CODIGOISODIVISADEFECTO"
            Public Const configNivelDetalle As String = "CONFIGNIVELDETALLE"
            Public Const crearConfiguiracionNivelSaldo As String = "CREARCONFIGUIRACIONNIVELSALDO"
            Public Const desgloseDetalleCertificado As String = "DESGLOSEDETALLECERTIFICADO"
            Public Const notaCertificado As String = "NOTACERTIFICADO"
            Public Const reporteDocumentoDomicilioTelefono As String = "ReporteDocumentoDomicilioTelefono"
            Public Const reporteDocumentoNegocio As String = "ReporteDocumentoNegocio"
        End Class
    End Namespace

    Namespace GenesisSalidas
        Public Class Puesto
            Public Const codigoCanalCuentaCero As String = "CODIGOCANALCUENTACERO"
            Public Const codigoSubCanalCuentaCero As String = "CODIGOSUBCANALCUENTACERO"
            Public Const contadoraBilleteHost As String = "CONTADORABILLETEHOST"
            Public Const contadoraBilleteLink As String = "CONTADORABILLETELINK"
            Public Const contadoraBilleteModelo As String = "CONTADORABILLETEMODELO"
            Public Const contadoraMonedaHost As String = "CONTADORAMONEDAHOST"
            Public Const contadoraMonedaLink As String = "CONTADORAMONEDALINK"
            Public Const contadoraMonedaModelo As String = "CONTADORAMONEDAMODELO"
            Public Const estadoSistemaVideo2 As String = "ESTADOSISTEMAVIDEO2"
            Public Const filtrarDatosPorSectorPadre As String = "FILTRARDATOSPORSECTORPADRE"
            Public Const gestionaSaldoPorPuesto As String = "GESTIONASALDOPORPUESTO"
            Public Const portaSocketContadora As String = "PORTASOCKETCONTADORA"
            Public Const portaSocketDVR As String = "PORTASOCKETDVR"
            Public Const prepararyArmar As String = "PREPARARYARMAR"
            Public Const saldoInicialSumaTodosPuestos As String = "SALDOINICIALSUMATODOSPUESTOS"
            Public Const videoHost As String = "VIDEOHOST"
            Public Const videoIP As String = "VIDEOIP"
            Public Const videoIP2 As String = "VIDEOIP2"
            Public Const videoModelo As String = "VIDEOMODELO"
            Public Const videoModelo2 As String = "VIDEOMODELO2"
            Public Const videoNumeroCamara As String = "VIDEONUMEROCAMARA"
            Public Const videoNumeroCamara2 As String = "VIDEONUMEROCAMARA2"
            Public Const videoPassword As String = "VIDEOPASSWORD"
            Public Const videoPassword2 As String = "VIDEOPASSWORD2"
            Public Const videoUsuario As String = "VIDEOUSUARIO"
            Public Const videoUsuario2 As String = "VIDEOUSUARIO2"
        End Class
        Public Class Delegacion
            Public Const cantBultosCuadrar As String = "CANTBULTOSCUADRAR"
            Public Const cantRemesasCuadrar As String = "CANTREMESASCUADRAR"
            Public Const codigoCanalSaldos As String = "CODIGOCANALSALDOS"
            Public Const codigoClienteCuentaCero As String = "CODIGOCLIENTECUENTACERO"
            Public Const codigoSectorTesoro As String = "CODIGOSECTORTESORO"
            Public Const codigoSubCanalDefecto As String = "CODIGOSUBCANALDEFECTO"
            Public Const codSectorSalidas As String = "CODSECTORSALIDAS"
            Public Const condicionesTransporte As String = "CONDICIONESTRANSPORTE"
            Public Const crearPrecintoModulo As String = "CREARPRECINTOMODULO"
            Public Const cuadrarPuesto As String = "CUADRARPUESTO"
            Public Const cuentaProsegurCodigoCliente As String = "CUENTAPROSEGURCODIGOCLIENTE"
            Public Const cuentaProsegurCodigoPuntoServicio As String = "CUENTAPROSEGURCODIGOPUNTOSERVICIO"
            Public Const cuentaProsegurCodigoSubCliente As String = "CUENTAPROSEGURCODIGOSUBCLIENTE"
            Public Const direccionDelegacion As String = "DIRECCIONDELEGACION"
            Public Const generarDiferenciasenLaCuentaProsegur As String = "GENERARDIFERENCIASENLACUENTAPROSEGUR"
            Public Const generarNumeroReciboTransporte As String = "GENERARNUMERORECIBOTRANSPORTE"
            Public Const localidadRemitoF22 As String = "LOCALIDADREMITOF22"
            Public Const mezclarBilleteMoneda As String = "MEZCLARBILLETEMONEDA"
            Public Const mezclarDenominacion As String = "MEZCLARDENOMINACION"
            Public Const nombreImpEtiqueta As String = "NOMBREIMPETIQUETA"
            Public Const obligarEntregarValorRespuesto As String = "OBLIGARENTREGARVALORESPUESTO"
            Public Const plantaConfeccionRemitoF22 As String = "PLANTACONFECCIONREMITOF22"
            Public Const razonSocialClienteServicioF22 As String = "RAZONSOCIALCLIENTESERVICIOF22"
            Public Const razonSocialEmpresaF22 As String = "RAZONSOCIALEMPRESAF22"
            Public Const reciboTransporteTipo As String = "RECIBOTRANSPORTETIPO"
            Public Const trabajaPorCuentaCero As String = "TRABAJAPORCUENTACERO"
        End Class
        Public Class Pais
            Public Const codigoClienteProsegur As String = "CODIGOCLIENTEPROSEGUR"
            Public Const codigoConfiguracionAutoDesglose As String = "CODIGOCONFIGURACIONAUTODESGLOSE"
            Public Const codigoISODivisaLocal As String = "CODIGOISODIVISALOCAL"
            Public Const controlaNumerarioPorBulto As String = "CONTROLANUMERARIOPORBULTO"
            Public Const copiasReciboTransporte As String = "COPIASRECIBOTRANSPORTE"
            Public Const tipoEtiquetaBulto As String = "TIPOETIQUETABULTO"
            Public Const tipoReciboRemesa As String = "TIPORECIBOREMESA"
            Public Const trabajarConCodigoBolsa As String = "TRABAJARCONCODIGOBOLSA"
        End Class
    End Namespace

    Namespace Reportes
        Public Class Pais
            Public Const carpeta As String = "CARPETAREPORTES"
            Public Const ServicesURL As String = "REPORTSERVICESURL"
            Public Const domain As String = "RS_A_DOMAIN"
            Public Const clave As String = "RS_A_PASS"
            Public Const usuario As String = "RS_A_USER"
        End Class
    End Namespace

End Namespace

