UPDATE SAPR_TPLANXMAQUINA 
SET FYH_VIGENCIA_INICIO = (

SELECT FN_CALCULAR_GMT_0_###VERSION###(PLAN.OID_DELEGACION , []FYH_VIGENCIA_INICIO)
  FROM GEPR_TSECTOR SECT
 INNER JOIN GEPR_TPLANTA PLAN ON PLAN.OID_PLANTA = SECT.OID_PLANTA
      WHERE SECT.OID_SECTOR = []OID_SECTOR),

    FYH_VIGENCIA_FIN = (

SELECT FN_CALCULAR_GMT_0_###VERSION###(PLAN.OID_DELEGACION , []FYH_VIGENCIA_FIN)
  FROM GEPR_TSECTOR SECT
 INNER JOIN GEPR_TPLANTA PLAN ON PLAN.OID_PLANTA = SECT.OID_PLANTA
      WHERE SECT.OID_SECTOR = []OID_SECTOR),
	
	GMT_MODIFICACION = sys_extract_utc(current_timestamp) || ' +00:00',
	DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION,
	OID_SUBCLIENTE_TESORERIA = []OID_SUBCLIENTE_TESORERIA,
	OID_PTO_SERVICIO_TESORERIA = []OID_PTO_SERVICIO_TESORERIA,
	NUM_PORCENT_COMISION = []NUM_PORCENT_COMISION

WHERE OID_MAQUINA = []OID_MAQUINA
  AND OID_PLANIFICACION = []OID_PLANIFICACION
  AND BOL_ACTIVO = 1