SELECT 
rownum,
          P.OID_PLANIFICACION,
          P.NUM_PORCENT_COMISION COMISION_PLANIFICACION,        
        SUBCLIDELE.OID_SUBCLIENTE OID_SUBCLIENTE,
         SUBCLIDELE.COD_SUBCLIENTE COD_SUBCLIENTE,
        SUBCLIDELE.DES_SUBCLIENTE DES_SUBCLIENTE,
        PTO_DELE.OID_PTO_SERVICIO OID_PTO_SERVICIO,
        PTO_DELE.COD_PTO_SERVICIO COD_PTO_SERVICIO,
        PTO_DELE.DES_PTO_SERVICIO DES_PTO_SERVICIO,
		BOL_CONTROLA_FACTURACION
  FROM SAPR_TPLANIFICACION P
  LEFT JOIN GEPR_TDELEGACIONXCONFIG_FACTUR DELCONFIG ON DELCONFIG.OID_CLIENTE_CAPITAL = P.OID_CLIENTE
  LEFT JOIN GEPR_TSUBCLIENTE SUBCLIDELE ON DELCONFIG.OID_SUBCLIENTE_TESORERIA = SUBCLIDELE.OID_SUBCLIENTE
  LEFT JOIN GEPR_TPUNTO_SERVICIO PTO_DELE ON DELCONFIG.OID_PTO_SERVICIO_TESORERIA = PTO_DELE.OID_PTO_SERVICIO
  WHERE P.OID_PLANIFICACION = []OID_PLANIFICACION 
  AND (DELCONFIG.OID_DELEGACION IS NULL OR DELCONFIG.OID_DELEGACION =  []OID_DELEGACION)
  AND rownum = 1 
  ORDER BY 
   P.OID_PLANIFICACION,
    P.NUM_PORCENT_COMISION ,        
  SUBCLIDELE.OID_SUBCLIENTE ,
   SUBCLIDELE.COD_SUBCLIENTE ,
  SUBCLIDELE.DES_SUBCLIENTE ,
  PTO_DELE.OID_PTO_SERVICIO ,
  PTO_DELE.COD_PTO_SERVICIO ,
  PTO_DELE.DES_PTO_SERVICIO 
  
  
  
  