UPDATE SAPR_TPLANXMAQUINA 
SET BOL_ACTIVO = 0
  , FYH_VIGENCIA_FIN = sys_extract_utc(current_timestamp)
  , GMT_MODIFICACION = sys_extract_utc(current_timestamp) || ' +00:00'
  , DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE OID_MAQUINA = []OID_MAQUINA
  AND OID_PLANIFICACION = []OID_PLANIFICACION
AND BOL_ACTIVO = 1