    SELECT D.COD_DELEGACION
      FROM GEPR_TDELEGACION D
INNER JOIN GEPR_TCODIGO_AJENO CA ON CA.COD_TIPO_TABLA_GENESIS = 'GEPR_TDELEGACION'
                                AND CA.OID_TABLA_GENESIS = D.OID_DELEGACION
     WHERE D.BOL_VIGENTE = 1
       AND CA.COD_AJENO = []COD_AJENO
       AND CA.COD_IDENTIFICADOR = []COD_IDENTIFICADOR