SELECT OID_DELEGACION,
       COD_PAIS,
       COD_DELEGACION,
       DES_DELEGACION,
       BOL_VIGENTE,
       OID_PAIS,
       NEC_GMT_MINUTOS,
       FYH_VERANO_INICIO,
       FYH_VERANO_FIN,
       NEC_VERANO_AJUSTE,
       DES_ZONA,
       GMT_CREACION,
       DES_USUARIO_CREACION,
       GMT_MODIFICACION,
       DES_USUARIO_MODIFICACION
  FROM GEPR_TDELEGACION
  WHERE OID_DELEGACION = []pOID_DELEGACION
