SELECT
       SUCL.OID_SUBCLIENTE,
       SUCL.COD_SUBCLIENTE,
       SUCL.DES_SUBCLIENTE,
       SUCL.BOL_VIGENTE,
       SUCL.COD_USUARIO,
       SUCL.FYH_ACTUALIZACION,
       SUCL.BOL_ENVIADO_SALDOS,
       SUCL.COD_MIGRACION,
       SUCL.BOL_TOTALIZADOR_SALDO,
       TISC.OID_TIPO_SUBCLIENTE TPSU_OID_TIPO_SUBCLIENTE,
       TISC.COD_TIPO_SUBCLIENTE TPSU_COD_TIPO_SUBCLIENTE,
       TISC.DES_TIPO_SUBCLIENTE TPSU_DES_TIPO_SUBCLIENTE,
       TISC.BOL_ACTIVO TPSU_BOL_ACTIVO,
       TISC.GMT_CREACION TPSU_GMT_CREACION,
       TISC.DES_USUARIO_CREACION TPSU_DES_USUARIO_CREACION,
       TISC.GMT_MODIFICACION TPSU_GMT_MODIFICACION,
       TISC.DES_USUARIO_MODIFICACION TPSU_DES_USUARIO_MODIFICACION
FROM
       GEPR_TSUBCLIENTE SUCL
       LEFT OUTER JOIN GEPR_TTIPO_SUBCLIENTE TISC ON SUCL.OID_TIPO_SUBCLIENTE = TISC.OID_TIPO_SUBCLIENTE
WHERE
       SUCL.COD_SUBCLIENTE = []COD_SUBCLIENTE