SELECT
       S.OID_SUBCLIENTE
FROM
       GEPR_TSUBCLIENTE S INNER JOIN GEPR_TCLIENTE C ON S.OID_CLIENTE = C.OID_CLIENTE
WHERE
       C.OID_CLIENTE = []OID_CLIENTE AND
       S.COD_SUBCLIENTE = []COD_SUBCLIENTE