INSERT INTO GEPR_TGRUPO_PARAMETRO 
	(COD_USUARIO, 
	DES_DESCRIPCION_CORTO, 
	DES_DESCRIPCION_LARGA, 
	FYH_ACTUALIZACION,
	NEC_ORDEN,
	OID_APLICACION, 
	OID_GRUPO_PARAMETRO, 
	OID_NIVEL_PARAMETRO) 
VALUES 
	([]COD_USUARIO , 
	[]DES_DESCRIPCION_CORTO , 
	[]DES_DESCRIPCION_LARGA , 
	[]FYH_ACTUALIZACION , 
	[]NEC_ORDEN , 
	[]OID_APLICACION , 
	[]OID_GRUPO_PARAMETRO , 
	[]OID_NIVEL_PARAMETRO)