SELECT GEPR_TGRUPO_PARAMETRO.OID_GRUPO_PARAMETRO
FROM GEPR_TGRUPO_PARAMETRO INNER JOIN GEPR_TAPLICACION ON
  GEPR_TGRUPO_PARAMETRO.OID_APLICACION = GEPR_TAPLICACION.OID_APLICACION
INNER JOIN GEPR_TNIVEL_PARAMETRO ON 
  GEPR_TGRUPO_PARAMETRO.OID_NIVEL_PARAMETRO = GEPR_TNIVEL_PARAMETRO.OID_NIVEL_PARAMETRO
INNER JOIN GEPR_TPARAMETRO ON
  GEPR_TPARAMETRO.OID_GRUPO_PARAMETRO = GEPR_TGRUPO_PARAMETRO.OID_GRUPO_PARAMETRO
WHERE GEPR_TAPLICACION.COD_APLICACION = []COD_APLICACION
  AND GEPR_TNIVEL_PARAMETRO.COD_NIVEL_PARAMETRO = []COD_NIVEL_PARAMETRO
  AND GEPR_TGRUPO_PARAMETRO.DES_DESCRIPCION_CORTO = []DES_DESCRIPCION_CORTO
