Public Enum Metodo
    EjecutarLogin
    EjecutarLogin2
    ObtenerDelegaciones
    ObtenerDelegaciones2
    CrearTokenAcceso
    CrearTokenAcceso2
    ConsumirTokenAcceso
    ConsumirTokenAcceso2
    ObtenerAplicaciones
    ObtenerAplicaciones2
    ObtenerPermisos
    ObtenerPermisos2
    ObtenerAplicacionVersion
    LogarErro
    GetDelegacionesUsuario
    InserirSesion
    EjecutarLoginAplicacion
    AddIntervencionSupervisor
    Login
    RecuperarMotivos
    SetIntervencionSupervisor
    AutenticarUsuarioAplicacionLoginUnificado
    AutenticarUsuarioAplicacion
    ObtenerEmisoresDocumento
    ObtenerPermisosUsuario
    ObtenerDelegacionesDelUsuario
    ObtenerVersiones
    ' RecepcionyEnvio
    GrabarDocumentosSalidasConIntegracionSol
    GrabarDocumentosSalidas
    obtenerRutas
    BuscarDocumentosNaoAlocados
    GrabarIngresoDocumentosSaldosySol
    GrabaryReenviarGrupoDocumentos
    CrearDocumento
    obtenerDocumentosSustituidos
    AlocarDesalocarDocumento
    ObtenerPaises
    ObtenerInformacionLogin
End Enum
