INSERT INTO SAPR_TACCION_CONTABLE
(OID_ACCION_CONTABLE
,COD_ACCION_CONTABLE
,DES_ACCION_CONTABLE
,BOL_ACTIVO
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION)
VALUES
([]OID_ACCION_CONTABLE
,[]COD_ACCION_CONTABLE
,[]DES_ACCION_CONTABLE
,[]BOL_ACTIVO
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_CREACION
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_MODIFICACION)