SELECT
      A.OID_ACCION_CONTABLE,
      A.COD_ACCION_CONTABLE,
      A.DES_ACCION_CONTABLE,
      A.BOL_ACTIVO,
      A.GMT_CREACION,
      A.DES_USUARIO_CREACION,
      A.GMT_MODIFICACION,
      A.DES_USUARIO_MODIFICACION
FROM SAPR_TACCION_CONTABLE A
WHERE A.BOL_ACTIVO = 1
ORDER BY A.DES_ACCION_CONTABLE