SELECT
OID_ACCION_CONTABLE
,COD_ACCION_CONTABLE
,DES_ACCION_CONTABLE
,COD_MIGRACION
,BOL_ACTIVO
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION
FROM SAPR_TACCION_CONTABLE
WHERE OID_ACCION_CONTABLE = []OID_ACCION_CONTABLE