/*ConteoRecuperarDatosParcializacionErronea*/
WITH REMESAS AS (
SELECT B.OID_REMESA, B.OID_BULTO
FROM GEPR_TBULTO B
INNER JOIN (SELECT RM.OID_REMESA, COUNT(DISTINCT RM.OID_BULTO)
  FROM GEPR_TREMESA REME
  INNER JOIN GEPR_TREGISTRO_MOVIMIENTO RM ON RM.OID_REMESA = REME.OID_REMESA
   AND RM.COD_TIPO_MOVIMIENTO = 'C'
 WHERE REME.COD_ESTADO IN ('PR','NEN','NSA','SA', 'EN', 'MS')
   AND REME.FYH_FIN_CONTEO between SYSDATE - []CANTIDAD_DIAS_BUSCAR_DATOS and SYSDATE + 1
 GROUP BY RM.OID_REMESA
HAVING COUNT(DISTINCT RM.OID_BULTO) > 1) R ON R.OID_REMESA = B.OID_REMESA),
RANGO_FECHAS AS (SELECT RM.OID_REMESA, MIN(RM.FYH_ACTUALIZACION) FECHA_MIN, MAX(RM.FYH_ACTUALIZACION) FECHA_MAX
              FROM GEPR_TREGISTRO_MOVIMIENTO RM
              INNER JOIN REMESAS R ON R.OID_REMESA = RM.OID_REMESA
              WHERE RM.COD_TIPO_MOVIMIENTO = 'C'
              GROUP BY RM.OID_REMESA),
BULTOS_PARCIALIZADOS AS (SELECT R.OID_REMESA, R.OID_BULTO, BP.OID_BULTO_PARCIALIZADO
                         FROM REMESAS R
                         LEFT JOIN GEPR_TBULTO_PARCIALIZADO BP ON R.OID_BULTO = BP.OID_BULTO_PADRE)
SELECT BP1.OID_REMESA, BP1.OID_BULTO, BP1.OID_BULTO_PARCIALIZADO, RF.FECHA_MIN, RF.FECHA_MAX
FROM BULTOS_PARCIALIZADOS BP1
INNER JOIN RANGO_FECHAS RF ON RF.OID_REMESA = BP1.OID_REMESA