UPDATE 
	   GEPR_TTERMINO_MEDIO_PAGO
SET        
       DES_TERMINO = []DES_TERMINO,
       OBS_TERMINO = []OBS_TERMINO,
       DES_VALOR_INICIAL = []DES_VALOR_INICIAL,
       NEC_LONGITUD = []NEC_LONGITUD,
       OID_FORMATO = []OID_FORMATO,
       OID_MASCARA = []OID_MASCARA,
       OID_ALGORITMO_VALIDACION = []OID_ALGORITMO_VALIDACION,
       BOL_MOSTRAR_CODIGO = []BOL_MOSTRAR_CODIGO,
       NEC_ORDEN = []NEC_ORDEN,
       BOL_VIGENTE = []BOL_VIGENTE,
       COD_USUARIO = []COD_USUARIO,
       FYH_ACTUALIZACION = []FYH_ACTUALIZACION
 WHERE 
	   COD_TERMINO = []COD_TERMINO
AND	   OID_MEDIO_PAGO = []OID_MEDIO_PAGO