INSERT INTO GEPR_TTERMINO_MED_PAGO_POR_PRO
(OID_TERMINO_PROCESO, 
OID_TERMINO, 
COD_DELEGACION, 
COD_USUARIO, 
FYH_ACTUALIZACION, 
OID_PROCESO_SUBCANAL,
BOL_ES_OBLIGATORIO
)
VALUES
([]OID_TERMINO_PROCESO, 
[]OID_TERMINO, 
[]COD_DELEGACION, 
[]COD_USUARIO, 
[]FYH_ACTUALIZACION, 
[]OID_PROCESO_SUBCANAL,
[]BOL_ES_OBLIGATORIO)