SELECT 
  TMP.OID_TERMINO
FROM 
  GEPR_TTERMINO_MEDIO_PAGO TMP
  INNER JOIN GEPR_TMEDIO_PAGO MP ON
    TMP.OID_MEDIO_PAGO = MP.OID_MEDIO_PAGO
  INNER JOIN GEPR_TDIVISA D ON
    MP.OID_DIVISA = D.OID_DIVISA
WHERE 
  TMP.COD_TERMINO = :COD_TERMINO AND
  MP.COD_MEDIO_PAGO = :COD_MEDIO_PAGO AND
  D.COD_ISO_DIVISA = :COD_ISO_DIVISA AND
  MP.COD_TIPO_MEDIO_PAGO = :COD_TIPO_MEDIO_PAGO