SELECT 
        DPD.OID_DOC_PARTE_DIFERENCIAS, 
        DPD.OID_REMESA,         
        DPD.NEL_NUMERO_DOCUMENTO,         
        B.DES_CLIENTE,
        B.DES_SUBCLIENTE,
        B.DES_PUNTO_SERVICIO,                                
        R.COD_PRECINTO,        
        B.COD_TRANSPORTE,
        B.FEC_TRANSPORTE,
        DPD.FYH_CONTEO, 
        DPD.FYH_ACTUALIZACION,
        CASE WHEN DPD.BIN_DOCUMENTO_GENERAL IS NOT NULL THEN 1 ELSE 0 END HAY_GENERAL,
        CASE WHEN DPD.BIN_DOCUMENTO_COMENTARIO IS NOT NULL THEN 1 ELSE 0 END HAY_INCIDENCIA,
        CASE WHEN DPD.BIN_DOCUMENTO_JUSTIFICATIVA IS NOT NULL THEN 1 ELSE 0 END HAY_JUSTIFICATIVA 
FROM 
        GEPR_TDOC_PARTE_DIFERENCIAS DPD
        INNER JOIN GEPR_TREMESA R ON DPD.OID_REMESA = R.OID_REMESA
        INNER JOIN GEPR_TBULTO B ON R.OID_REMESA = B.OID_REMESA 
        INNER JOIN (SELECT OID_REMESA, OID_BULTO, COD_USUARIO, COD_SUPERVISOR FROM GEPR_TREGISTRO_MOVIMIENTO GROUP BY OID_REMESA, OID_BULTO, COD_USUARIO, COD_SUPERVISOR) RM ON R.OID_REMESA = RM.OID_REMESA AND B.OID_BULTO = RM.OID_BULTO
WHERE
        1 = 1
		[FILTROS]
GROUP BY
        DPD.OID_DOC_PARTE_DIFERENCIAS, 
        DPD.OID_REMESA,         
        DPD.NEL_NUMERO_DOCUMENTO,         
        B.DES_CLIENTE,
        B.DES_SUBCLIENTE,
        B.DES_PUNTO_SERVICIO,                                
        R.COD_PRECINTO,        
        B.COD_TRANSPORTE,
        B.FEC_TRANSPORTE,
        DPD.FYH_CONTEO, 
        DPD.FYH_ACTUALIZACION,
        CASE WHEN DPD.BIN_DOCUMENTO_GENERAL IS NOT NULL THEN 1 ELSE 0 END,
        CASE WHEN DPD.BIN_DOCUMENTO_COMENTARIO IS NOT NULL THEN 1 ELSE 0 END,
        CASE WHEN DPD.BIN_DOCUMENTO_JUSTIFICATIVA IS NOT NULL THEN 1 ELSE 0 END