SELECT 
        DPD.OID_DOC_PARTE_DIFERENCIAS
		[DOCUMENTOS]        
FROM 
        GEPR_TDOC_PARTE_DIFERENCIAS DPD
WHERE
        DPD.OID_DOC_PARTE_DIFERENCIAS = []OID_DOC_PARTE_DIFERENCIAS
		[FILTROS]