SELECT 
       TB.OID_TIPO_BULTO,
       TB.COD_TIPO_BULTO,
       TB.DES_TIPO_BULTO,
       TB.BOL_ACTIVO,
       TB.GMT_CREACION,
       TB.DES_USUARIO_CREACION,
       TB.GMT_MODIFICACION,
       TB.DES_USUARIO_MODIFICACION
FROM SAPR_TTIPO_BULTO TB
WHERE TB.BOL_ACTIVO = 1