SELECT 
       TB.OID_TIPO_BULTO,
       TB.COD_TIPO_BULTO,
       TB.DES_TIPO_BULTO,
       TB.BOL_ACTIVO,
       TB.GMT_CREACION,
       TB.DES_USUARIO_CREACION,
       TB.GMT_MODIFICACION,
       TB.DES_USUARIO_MODIFICACION
FROM SAPR_TTIPO_BULTO TB
INNER JOIN SAPR_TFORMULARIOXTIPO_BULTO TBF
ON TB.OID_TIPO_BULTO = TBF.OID_TIPO_BULTO
WHERE TB.BOL_ACTIVO = 1
AND TBF.OID_FORMULARIO = []OID_FORMULARIO