INSERT INTO SAPR_TFORMULARIOXTIPO_BULTO
(OID_FORMULARIOXTIPO_BULTO
,OID_FORMULARIO
,OID_TIPO_BULTO
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION)
VALUES
([]OID_FORMULARIOXTIPO_BULTO
,[]OID_FORMULARIO
,[]OID_TIPO_BULTO
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_CREACION
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_MODIFICACION)