SELECT PRC.OID_PROCESO
FROM  GEPR_TPROCESO_POR_PSERVICIO PPSRV
      INNER JOIN GEPR_TCLIENTE CLI ON PPSRV.OID_CLIENTE = CLI.OID_CLIENTE
      LEFT OUTER JOIN GEPR_TSUBCLIENTE SBCLI ON PPSRV.OID_SUBCLIENTE = SBCLI.OID_SUBCLIENTE
      LEFT OUTER JOIN GEPR_TPUNTO_SERVICIO PTSRV ON PTSRV.OID_PTO_SERVICIO = PPSRV.OID_PTO_SERVICIO
      INNER JOIN GEPR_TPROCESO_SUBCANAL PRSUB ON PPSRV.OID_PROCESO_POR_PSERVICIO = PRSUB.OID_PROCESO_POR_PSERVICIO
      INNER JOIN GEPR_TSUBCANAL SUB ON PRSUB.OID_SUBCANAL = SUB.OID_SUBCANAL
      INNER JOIN GEPR_TPROCESO PRC ON PPSRV.OID_PROCESO = PRC.OID_PROCESO
      INNER JOIN GEPR_TPRODUCTO PRD ON PRC.OID_PRODUCTO = PRD.OID_PRODUCTO
      INNER JOIN GEPR_TCANAL CNL ON SUB.OID_CANAL = CNL.OID_CANAL
      WHERE PRSUB.BOL_VIGENTE = 1 
		AND PRC.COD_DELEGACION = []COD_DELEGACION
		AND SUB.COD_SUBCANAL = []COD_SUBCANAL
		AND CLI.COD_CLIENTE = []COD_CLIENTE