SELECT PRPSRV.OID_PROCESO_POR_PSERVICIO
FROM GEPR_TPROCESO_POR_PSERVICIO PRPSRV
INNER JOIN GEPR_TCLIENTE CLI ON PRPSRV.OID_CLIENTE = CLI.OID_CLIENTE
LEFT OUTER JOIN GEPR_TSUBCLIENTE SUBCLI ON PRPSRV.OID_SUBCLIENTE = SUBCLI.OID_SUBCLIENTE
LEFT OUTER JOIN GEPR_TPUNTO_SERVICIO PTO ON PRPSRV.OID_PTO_SERVICIO = PTO.OID_PTO_SERVICIO
