 SELECT DISTINCT 
	PROC.OID_PRODUCTO, 
	PROC.OID_PROCESO, 
	PROC.DES_PROCESO, 
	PSUB.OBS_PROCESO_SUBCANAL, 
	PROC.BOL_CONTAR_CHEQUES_TOTAL, 
	PROC.BOL_CONTAR_TICKETS_TOTAL, 
	PROC.BOL_CONTAR_OTROS_TOTAL, 
	PROC.BOL_MEDIOS_PAGO, 
	PSUB.BOL_VIGENTE, 
	PSUB.FYH_ACTUALIZACION, 
	TPROC.COD_TIPO_PROCESADO, 
	TPROC.DES_TIPO_PROCESADO, 
	TPROC.BOL_CONTAR_CIEGO, 
	TPROC.BOL_ADMITE_IAC, 
	TPROC.BOL_VIGENTE AS VIGENTE_MOD_RECUENTO,
	TPROC.OID_TIPO_PROCESADO
FROM 
	GEPR_TPROCESO PROC 
	INNER JOIN GEPR_TPROCESO_POR_PSERVICIO PSER ON PSER.OID_PROCESO = PROC.OID_PROCESO 
	INNER JOIN GEPR_TPROCESO_SUBCANAL PSUB ON PSUB.OID_PROCESO_POR_PSERVICIO = PSER.OID_PROCESO_POR_PSERVICIO 
	INNER JOIN GEPR_TTIPO_PROCESADO TPROC ON TPROC.OID_TIPO_PROCESADO = PROC.OID_TIPO_PROCESADO
WHERE 
PSUB.FYH_ACTUALIZACION BETWEEN []FECHA_INICIAL AND []FECHA_FINAL 