SELECT  
	PRC.DES_PROCESO,
    PRC.COD_DELEGACION,
    PRC.BOL_MEDIOS_PAGO,
    PRC.BOL_CONTAR_CHEQUES_TOTAL,
    PRC.BOL_CONTAR_TICKETS_TOTAL,
    PRC.BOL_CONTAR_OTROS_TOTAL,
	PRC.BOL_CONTAR_TARJETAS_TOTAL,
    PRSUB.OBS_PROCESO_SUBCANAL,
    PRSUB.BOL_VIGENTE,
    CNL.COD_CANAL,
    CNL.DES_CANAL,
    SUBCNL.COD_SUBCANAL,
    SUBCNL.DES_SUBCANAL,
    CLI.COD_CLIENTE,
    CLI.DES_CLIENTE,
    SUBCLI.COD_SUBCLIENTE,
    SUBCLI.DES_SUBCLIENTE,
    PTSRV.COD_PTO_SERVICIO,
    PTSRV.DES_PTO_SERVICIO,
    IAC_P.COD_IAC,
    IAC_P.DES_IAC,
    TPPRC.COD_TIPO_PROCESADO,
    TPPRC.DES_TIPO_PROCESADO,
    PRD.COD_PRODUCTO,
    PRD.DES_PRODUCTO,
    PRD.DES_CLASE_BILLETE,
    CLIFACT.COD_CLIENTE AS COD_CLIENTE_FACTURACION,
    CLIFACT.DES_CLIENTE AS DES_CLIENTE_FACTURACION,
    PRC.OID_PROCESO,
    PRSUB.OID_PROCESO_SUBCANAL,
	IAC_B.COD_IAC AS COD_IAC_BULTO,
	IAC_R.COD_IAC AS COD_IAC_REMESA
FROM    
	GEPR_TPROCESO PRC
    INNER JOIN GEPR_TPROCESO_POR_PSERVICIO PRPSRV ON  PRC.OID_PROCESO = PRPSRV.OID_PROCESO
    INNER JOIN GEPR_TPROCESO_SUBCANAL PRSUB ON PRPSRV.OID_PROCESO_POR_PSERVICIO = PRSUB.OID_PROCESO_POR_PSERVICIO
    INNER JOIN GEPR_TSUBCANAL SUBCNL ON PRSUB.OID_SUBCANAL = SUBCNL.OID_SUBCANAL
    INNER JOIN GEPR_TCANAL CNL ON SUBCNL.OID_CANAL = CNL.OID_CANAL
    INNER JOIN GEPR_TCLIENTE CLI ON PRPSRV.OID_CLIENTE = CLI.OID_CLIENTE
    LEFT OUTER JOIN GEPR_TSUBCLIENTE SUBCLI ON PRPSRV.OID_SUBCLIENTE = SUBCLI.OID_SUBCLIENTE
    LEFT OUTER JOIN GEPR_TPUNTO_SERVICIO PTSRV ON PRPSRV.OID_PTO_SERVICIO = PTSRV.OID_PTO_SERVICIO
    LEFT OUTER JOIN GEPR_TINFORM_ADICIONAL_CLIENTE IAC_P ON PRPSRV.OID_IAC = IAC_P.OID_IAC
	LEFT OUTER JOIN GEPR_TINFORM_ADICIONAL_CLIENTE IAC_B ON PRPSRV.OID_IAC_BULTO = IAC_B.OID_IAC
	LEFT OUTER JOIN GEPR_TINFORM_ADICIONAL_CLIENTE IAC_R ON PRPSRV.OID_IAC_REMESA = IAC_R.OID_IAC
    INNER JOIN GEPR_TTIPO_PROCESADO TPPRC ON PRC.OID_TIPO_PROCESADO = TPPRC.OID_TIPO_PROCESADO
    INNER JOIN GEPR_TPRODUCTO PRD ON PRC.OID_PRODUCTO = PRD.OID_PRODUCTO
    LEFT OUTER JOIN GEPR_TCLIENTE CLIFACT ON PRPSRV.OID_CLIENTE_FACTURACION = CLIFACT.OID_CLIENTE
WHERE PRC.OID_PROCESO = []OID_PROCESO