DELETE SAPR_TCALCULO_MEDIO_PAGO CAMP 
WHERE CAMP.OID_PERIODO IN ( Select PERI.OID_PERIODO from SAPR_TPERIODO PERI
INNER JOIN SAPR_TESTADO_PERIODO TEPE
ON PERI.OID_ESTADO_PERIODO = TEPE.OID_ESTADO_PERIODO
INNER JOIN SAPR_TTIPO_PERIODO TTIPO
ON PERI.OID_TIPO_PERIODO = TTIPO.OID_TIPO_PERIODO AND TTIPO.COD_TIPO_PERIODO = 'AC'
WHERE PERI.OID_MAQUINA = []OID_MAQUINA {0})
