UPDATE SAPR_TBULTO B SET B.COD_ESTADO_ABONO = []COD_ESTADO_ABONO
WHERE B.OID_REMESA IN (SELECT AE.OID_REMESA
                       FROM SAPR_TABONO_ELEMENTO AE
                       INNER JOIN SAPR_TABONO_VALOR AV ON AV.OID_ABONO_VALOR = AE.OID_ABONO_VALOR
                       WHERE AV.OID_ABONO = []OID_ABONO)