INSERT INTO SAPR_TABONO_ELEMENTO
  (OID_ABONO_ELEMENTO, OID_ABONO_VALOR, OID_REMESA, OID_BULTO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION, COD_ABONO_ELEMENTO)
VALUES
  ([]OID_ABONO_ELEMENTO, []OID_ABONO_VALOR, []OID_REMESA, []OID_BULTO, FN_GMT_ZERO_###VERSION###, []DES_USUARIO_CREACION, FN_GMT_ZERO_###VERSION###, []DES_USUARIO_MODIFICACION, []COD_ABONO_ELEMENTO)
