'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Abono

    Partial Public Class Busqueda

        '''<summary>
        '''UcBanco control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UcBanco As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.ucBusqueda

        '''<summary>
        '''UcCliente control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UcCliente As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.ucBusqueda

        '''<summary>
        '''ucBusquedaAvanzada control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucBusquedaAvanzada As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.ucBusquedaAvanzada

        '''<summary>
        '''litDicionario control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDicionario As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litCargaInicial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCargaInicial As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Master
            Get
                Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Master)
            End Get
        End Property
    End Class
End Namespace
