'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Abono

    Partial Public Class PantallaVisualizar

        '''<summary>
        '''lblBanco control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBanco As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTipoAbono control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTipoAbono As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dvValores control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvValores As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblValores control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblValores As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEstado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEstado As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTituloAbonos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTituloAbonos As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dvAbonos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvAbonos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litAbonosHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAbonosHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litAbonosBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAbonosBody As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litReporteError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReporteError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litDicionario control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDicionario As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litScript control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litScript As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litBotones control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBotones As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Master
            Get
                Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Master)
            End Get
        End Property
    End Class
End Namespace
