
WITH SECD AS (
    SELECT 
       SECT.OID_SECTOR,  
       SECT.COD_SECTOR,  
       SECT.OID_PLANTA
    FROM
       GEPR_TSECTOR SECT
    START WITH SECT.COD_SECTOR = []COD_SECTOR
    CONNECT BY NOCYCLE PRIOR SECT.OID_SECTOR = SECT.OID_SECTOR_PADRE
    ORDER SIBLINGS BY SECT.DES_SECTOR)
SELECT 
       REM.OID_REMESA,
       REM.COD_EXTERNO,
       REM.COD_RUTA,
       REM.FYH_TRANSPORTE,
       VTIAC.DES_VALOR AS HORASALIDA,
       CLI.DES_CLIENTE, 
       SUBCLI.DES_SUBCLIENTE, 
       PTO.COD_PTO_SERVICIO,
       DECEFECTIVOREM.OID_BULTO AS idBultoDeclaradoEfectivo,
       REM.BOL_COMPROBADO REM_COMPROBADO,
       REM.BOL_GESTION_BULTO REM_TRABAJA_BULTO,
       BUL.BOL_COMPROBADO BUL_COMPROBADO,
       BUL.BOL_GESTION_BULTO BUL_TRABAJA_BULTO,
       REM.GMT_MODIFICACION FECHA_MODIFICACION_REM,
       BUL.GMT_MODIFICACION FECHA_MODIFICACION_BUL,
       
       -- REMESA EFECTIVO
       DIVISADECREM.DES_DIVISA AS DIVISA_REMESA_EFECTIVO, 
       DENREM.OID_DENOMINACION AS OID_DENOMINACION_REMESA,
       DENREM.DES_DENOMINACION AS DES_DENOMINACION_REMESA,
       DENREM.BOL_BILLETE AS BOL_BILLETE_REMESA,
       DECEFECTIVOREM.NEL_CANTIDAD CANTIDAD_DENOMINACION_REMESA,
       DECEFECTIVOREM.NUM_IMPORTE IMPORTE_DENOMINACION_REMESA,
       DECEFECTIVOREM.COD_NIVEL_DETALLE REM_COD_NIVEL_DETALLE,
       
       -- BULTO EFECTIVO
       BUL.OID_BULTO,
       BUL.COD_PRECINTO,
       DIVISADECBUL.DES_DIVISA AS DIVISA_BULTO_EFECTIVO,
       DENBUL.OID_DENOMINACION AS OID_DENOMINACION_BULTO,
       DENBUL.DES_DENOMINACION AS DES_DENOMINACION_BULTO,
       DENBUL.BOL_BILLETE AS BOL_BILLETE_BULTO,
       DECEFECTIVOBUL.NEL_CANTIDAD CANTIDAD_DENOMINACION_BULTO,
       DECEFECTIVOBUL.NUM_IMPORTE IMPORTE_DENOMINACION_BULTO,
       DECEFECTIVOBUL.COD_NIVEL_DETALLE BUL_COD_NIVEL_DETALLE,

       -- REMESA MEDIOPAGO
       DIVISAMPREM.DES_DIVISA AS DIVISA_REMESA_MEDIOPAGO,
       DECMPREM.COD_TIPO_MEDIO_PAGO AS MEDIOPAGO_REMESA,
       DECMPREM.NEL_CANTIDAD AS CANTIDAD_TOTAL_REMESA_MP,
       DECMPREM.NUM_IMPORTE AS IMPORTE_TOTAL_REMESA_MP,
       
       -- BULTO MEDIOPAGO
       DIVISAMPBUL.DES_DIVISA AS DIVISA_BULTO_MEDIOPAGO,
       DECMPBUL.COD_TIPO_MEDIO_PAGO AS MEDIOPAGO_BULTO,
       DECMPBUL.NEL_CANTIDAD AS CANTIDAD_TOTAL_BULTO_MEDIOPAGO,
       DECMPBUL.NUM_IMPORTE AS IMPORTE_TOTAL_BULTO_MEDIOPAGO
FROM
       SAPR_TDOCUMENTO DOC
       INNER JOIN SAPR_TFORMULARIO F ON F.OID_FORMULARIO = DOC.OID_FORMULARIO
     INNER JOIN SAPR_TCARACTFORMXFORMULARIO CFF ON CFF.OID_FORMULARIO = F.OID_FORMULARIO
       INNER JOIN SAPR_TCARACT_FORMULARIO CF ON CF.OID_CARACT_FORMULARIO = CFF.OID_CARACT_FORMULARIO
     INNER JOIN SAPR_TTIPO_DOCUMENTO TD ON TD.OID_TIPO_DOCUMENTO = DOC.OID_TIPO_DOCUMENTO
       INNER JOIN SAPR_TDOCUMENTOXELEMENTO DE ON DOC.OID_DOCUMENTO = DE.OID_DOCUMENTO
       INNER JOIN SAPR_TREMESA REM ON DE.OID_REMESA = REM.OID_REMESA
       LEFT  JOIN SAPR_TBULTO BUL ON REM.OID_REMESA = BUL.OID_REMESA
       INNER JOIN GEPR_TSECTOR SECO ON SECO.OID_SECTOR = DOC.OID_SECTOR_ORIGEN
       INNER JOIN GEPR_TPLANTA PLO ON PLO.OID_PLANTA = SECO.OID_PLANTA
       INNER JOIN GEPR_TDELEGACION DELO ON DELO.OID_DELEGACION = PLO.OID_DELEGACION
       INNER JOIN SECD ON SECD.OID_SECTOR = DOC.OID_SECTOR_DESTINO
       INNER JOIN GEPR_TPLANTA PLD ON PLD.OID_PLANTA = SECD.OID_PLANTA
       INNER JOIN GEPR_TDELEGACION DELD ON DELD.OID_DELEGACION = PLD.OID_DELEGACION
       LEFT JOIN GEPR_TINFORM_ADICIONAL_CLIENTE IAC ON IAC.OID_IAC = F.OID_IAC_GRUPO
       LEFT JOIN GEPR_TTERMINO_POR_IAC TIAC ON TIAC.OID_IAC = IAC.OID_IAC
       LEFT JOIN GEPR_TTERMINO TER ON TER.OID_TERMINO = TIAC.OID_TERMINO AND TER.COD_TERMINO = 'horaSalida'
       LEFT JOIN GEPR_TVALOR_TERMINO_IAC VTIAC ON VTIAC.OID_TERMINO = TER.OID_TERMINO
       INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = REM.OID_CUENTA
       INNER JOIN GEPR_TCLIENTE CLI ON CLI.OID_CLIENTE = CU.OID_CLIENTE
       INNER JOIN GEPR_TSUBCLIENTE SUBCLI ON SUBCLI.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
       INNER JOIN GEPR_TPUNTO_SERVICIO PTO ON CU.OID_PTO_SERVICIO = PTO.OID_PTO_SERVICIO
       LEFT JOIN SAPR_TDECLARADO_EFECTIVO DECEFECTIVOREM ON REM.OID_REMESA = DECEFECTIVOREM.OID_REMESA
       LEFT JOIN GEPR_TDIVISA DIVISADECREM ON DECEFECTIVOREM.OID_DIVISA = DIVISADECREM.OID_DIVISA
       LEFT JOIN SAPR_TDECLARADO_EFECTIVO DECEFECTIVOBUL ON BUL.OID_REMESA = DECEFECTIVOBUL.OID_REMESA AND BUL.OID_BULTO = DECEFECTIVOBUL.OID_BULTO
       LEFT JOIN GEPR_TDIVISA DIVISADECBUL ON DECEFECTIVOBUL.OID_DIVISA = DIVISADECBUL.OID_DIVISA
       LEFT JOIN SAPR_TDECLARADO_MEDIO_PAGO DECMPREM ON REM.OID_REMESA = DECMPREM.OID_REMESA
       LEFT JOIN GEPR_TDIVISA DIVISAMPREM ON DECMPREM.OID_DIVISA = DIVISAMPREM.OID_DIVISA
       LEFT JOIN SAPR_TDECLARADO_MEDIO_PAGO DECMPBUL ON BUL.OID_REMESA = DECMPBUL.OID_REMESA AND BUL.OID_BULTO = DECMPBUL.OID_BULTO
       LEFT JOIN GEPR_TDIVISA DIVISAMPBUL ON DECMPBUL.OID_DIVISA = DIVISAMPBUL.OID_DIVISA
       LEFT JOIN GEPR_TDENOMINACION DENREM ON DIVISADECREM.OID_DIVISA = DENREM.OID_DIVISA AND DECEFECTIVOREM.OID_DENOMINACION = DENREM.OID_DENOMINACION
       LEFT JOIN GEPR_TDENOMINACION DENBUL ON DIVISADECBUL.OID_DIVISA = DENBUL.OID_DIVISA AND DECEFECTIVOBUL.OID_DENOMINACION = DENBUL.OID_DENOMINACION
WHERE 
       REM.BOL_ANULADO = 0  AND
       DOC.COD_ESTADO <> 'SU' AND 
       REM.FYH_TRANSPORTE >= []FECHA_RUTA_INICIO AND REM.FYH_TRANSPORTE <= []FECHA_RUTA_FIN AND
     DE.COD_ESTADO_DOCXELEMENTO = []COD_ESTADO_DOCXELEMENTO AND
       (DELO.COD_DELEGACION = []COD_DELEGACION OR DELD.COD_DELEGACION = []COD_DELEGACION)
     AND (CF.COD_CARACT_FORMULARIO IN ('ACCION_ALTAS','ACCION_REENVIOS')
            AND TD.COD_TIPO_DOCUMENTO IN ('MOVBULTOS','INGR','REGPROC'))
       {0} 
GROUP BY 
      
       REM.OID_REMESA,
       REM.COD_EXTERNO,
       REM.COD_RUTA,
       REM.FYH_TRANSPORTE,
       VTIAC.DES_VALOR,
       CLI.DES_CLIENTE, 
       SUBCLI.DES_SUBCLIENTE, 
       PTO.COD_PTO_SERVICIO,
       DECEFECTIVOREM.OID_BULTO,
       REM.BOL_COMPROBADO,
       REM.BOL_GESTION_BULTO,
       BUL.BOL_COMPROBADO,
       BUL.BOL_GESTION_BULTO,
       REM.GMT_MODIFICACION,
       BUL.GMT_MODIFICACION,
       REM.DES_USUARIO_MODIFICACION,
       BUL.DES_USUARIO_MODIFICACION,
       
       -- REMESA EFECTIVO
       DIVISADECREM.DES_DIVISA, 
       DENREM.OID_DENOMINACION,
       DENREM.DES_DENOMINACION,
       DENREM.BOL_BILLETE,
       DECEFECTIVOREM.NEL_CANTIDAD,
       DECEFECTIVOREM.NUM_IMPORTE,
       DECEFECTIVOREM.COD_NIVEL_DETALLE,
       
       -- BULTO EFECTIVO
       BUL.OID_BULTO,
       BUL.COD_PRECINTO,
       DIVISADECBUL.DES_DIVISA,
       DENBUL.OID_DENOMINACION,
       DENBUL.DES_DENOMINACION,
       DENBUL.BOL_BILLETE,
       DECEFECTIVOBUL.NEL_CANTIDAD,
       DECEFECTIVOBUL.NUM_IMPORTE,
       DECEFECTIVOBUL.COD_NIVEL_DETALLE,

       -- REMESA MEDIOPAGO
       DIVISAMPREM.DES_DIVISA,
       DECMPREM.COD_TIPO_MEDIO_PAGO,
       DECMPREM.NEL_CANTIDAD,
       DECMPREM.NUM_IMPORTE,
       
       -- BULTO MEDIOPAGO
       DIVISAMPBUL.DES_DIVISA,
       DECMPBUL.COD_TIPO_MEDIO_PAGO,
       DECMPBUL.NEL_CANTIDAD,
       DECMPBUL.NUM_IMPORTE
       
ORDER BY
      REM.FYH_TRANSPORTE,
      REM.COD_RUTA,
      REM.COD_EXTERNO,
      BUL.COD_PRECINTO