SELECT * FROM (
SELECT C.OID_CLIENTE IDENTIFICADOR, C.COD_CLIENTE CODIGO, C.DES_CLIENTE DESCRICION , 'C' TIPO FROM GEPR_TCLIENTE C
WHERE 1 = []CARGAR_CLIENTE AND C.BOL_TOTALIZADOR_SALDO = 1 
UNION
SELECT CA.OID_CANAL, CA.COD_CANAL, CA.DES_CANAL, 'CA' FROM GEPR_TCANAL CA
WHERE 1 = []CARGAR_CANAL
UNION 
SELECT SUBCA.OID_SUBCANAL, SUBCA.COD_SUBCANAL, SUBCA.DES_SUBCANAL, 'SUBCA' FROM GEPR_TSUBCANAL SUBCA
WHERE 1 = []CARGAR_SUBCANAL AND SUBCA.OID_CANAL = []OID_CANAL
UNION 
SELECT DIV.OID_DIVISA, DIV.COD_ISO_DIVISA, DIV.DES_DIVISA, 'DIV' FROM GEPR_TDIVISA DIV
WHERE 1 = []CARGAR_DIVISA
UNION
SELECT D.OID_DENOMINACION, D.COD_DENOMINACION, D.DES_DENOMINACION, 'D' FROM GEPR_TDENOMINACION D
WHERE 1 = []CARGAR_DENOMINACION AND D.OID_DIVISA = []OID_DIVISA
UNION 
SELECT T.OID_TIPO_CONTENEDOR, T.COD_TIPO_CONTENEDOR, T.DES_TIPO_CONTENEDOR, 'T' FROM SAPR_TTIPO_CONTENEDOR T
WHERE 1 = []CARGAR_TIPO_CONTENEDOR) 
ORDER BY TIPO, DESCRICION ASC