SELECT DISTINCT PRO.COD_PRODUCTO, 
PRO.DES_PRODUCTO, 
PRO.DES_CLASE_BILLETE, 
PRO.NUM_FACTOR_CORRECCION, 
PRO.BOL_MANUAL, 
PRO.BOL_VIGENTE,
MAQ.DES_MAQUINA
FROM GEPR_TPRODUCTO PRO LEFT JOIN GEPR_TMAQUINA_POR_PRODUCTO MAQ ON (PRO.OID_PRODUCTO = MAQ.OID_PRODUCTO)