SELECT 
OID_VALOR_TERMINOXGRUPODOC
,OID_GRUPO_DOCUMENTO
,OID_TERMINO
,COD_MIGRACION
,DES_VALOR
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION
FROM SAPR_TVALOR_TERMINOXGRUPODOC
WHERE OID_GRUPO_DOCUMENTO = []OID_GRUPO_DOCUMENTO
