SELECT DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       D.COD_DENOMINACION,
       D.DES_DENOMINACION,
       SE.BOL_DISPONIBLE,
       SE.NUM_IMPORTE,
       SE.NUM_IMPORTE_ACUMULADO,
       SE.NEL_CANTIDAD,
	   SE.NEL_CANTIDAD_ACUMULADO,
	   SE.COD_NIVEL_DETALLE,
	   SE.COD_TIPO_EFECTIVO_TOTAL,
	   SE.OID_CALIDAD,
	   SE.OID_UNIDAD_MEDIDA,
	   SE.OID_CERT_SALDO_EFECTIVO,
	   SE.OID_DIVISA,
	   SE.OID_CERT_SALDO_EFECTIVO, 
	   SE.OID_CERTIFICADO_ANTERIOR
FROM SAPR_TCERT_SALDO_EFECTIVO SE 
LEFT JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = SE.OID_DENOMINACION
LEFT JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = SE.OID_DIVISA
WHERE OID_CERT_SALDO_EFECTIVO = []OID_CERT_SALDO_EFECTIVO