SELECT CU.OID_CUENTA,
	   CSE.BOL_DISPONIBLE,
       CSE.NUM_IMPORTE,
       CSE.NUM_IMPORTE_ACUMULADO,
       CSE.NEL_CANTIDAD,
	   CSE.NEL_CANTIDAD_ACUMULADO,
	   CSE.COD_NIVEL_DETALLE,
	   CSE.OID_UNIDAD_MEDIDA,
	   CSE.OID_CALIDAD, 
	   CSE.COD_TIPO_EFECTIVO_TOTAL,
       D.COD_ISO_DIVISA,
       D.DES_DIVISA,
       DN.COD_DENOMINACION,
       DN.DES_DENOMINACION,
	   CSE.OID_DIVISA,
	   CSE.OID_CERTIFICADO_ANTERIOR,
	   CSE.OID_DENOMINACION
FROM SAPR_TCUENTA CU 
INNER JOIN SAPR_TCERT_SALDO_EFECTIVO CSE ON CSE.OID_CUENTA_SALDO = CU.OID_CUENTA
LEFT JOIN GEPR_TDIVISA D ON D.OID_DIVISA = CSE.OID_DIVISA
LEFT JOIN GEPR_TDENOMINACION DN ON DN.OID_DENOMINACION = CSE.OID_DENOMINACION
WHERE CSE.OID_CERTIFICADO = []OID_CERTIFICADO
ORDER BY CU.OID_CUENTA