INSERT INTO SAPR_TCERT_SALDO_EFECTIVO
(OID_CERT_SALDO_EFECTIVO,
 OID_CUENTA_SALDO,
 OID_CERTIFICADO,
 OID_DENOMINACION,
 OID_CALIDAD,
 OID_UNIDAD_MEDIDA,
 BOL_DISPONIBLE,
 NUM_IMPORTE,
 NUM_IMPORTE_ACUMULADO,
 NEL_CANTIDAD,
 NEL_CANTIDAD_ACUMULADO,
 GMT_CREACION,
 DES_USUARIO_CREACION,
 GMT_MODIFICACION,
 DES_USUARIO_MODIFICACION,
 OID_DIVISA,
 COD_NIVEL_DETALLE,
 COD_TIPO_EFECTIVO_TOTAL,
 OID_CERTIFICADO_ANTERIOR)
 VALUES
 ([]OID_CERT_SALDO_EFECTIVO,
 []OID_CUENTA_SALDO,
 []OID_CERTIFICADO,
 (SELECT DISTINCT D.OID_DENOMINACION 
  FROM GEPR_TDIVISA DIV 
  INNER JOIN GEPR_TDENOMINACION D ON D.OID_DIVISA = DIV.OID_DIVISA 
  WHERE DIV.COD_ISO_DIVISA = []COD_ISO_DIVISA AND D.COD_DENOMINACION = []COD_DENOMINACION AND ROWNUM = 1),
 []OID_CALIDAD,
 []OID_UNIDAD_MEDIDA,
 []BOL_DISPONIBLE,
 []NUM_IMPORTE,
 []NUM_IMPORTE_ACUMULADO,
 []NEL_CANTIDAD,
 []NEL_CANTIDAD_ACUMULADO,
 FN_GMT_ZERO_###VERSION###,
 []DES_USUARIO_CREACION,
 FN_GMT_ZERO_###VERSION###,
 []DES_USUARIO_MODIFICACION,
 (SELECT DISTINCT OID_DIVISA
  FROM GEPR_TDIVISA
  WHERE COD_ISO_DIVISA = []COD_ISO_DIVISA AND ROWNUM = 1),
 []COD_NIVEL_DETALLE,
 []COD_TIPO_EFECTIVO_TOTAL, 
 []OID_CERTIFICADO_ANTERIOR)