UPDATE GEPR_TSUBCANAL
SET BOL_VIGENTE = []BOL_VIGENTE, 
DES_SUBCANAL = []DES_SUBCANAL, 
OBS_SUBCANAL = []OBS_SUBCANAL,
COD_USUARIO = []COD_USUARIO,
FYH_ACTUALIZACION = []FYH_ACTUALIZACION  
WHERE COD_SUBCANAL = []COD_SUBCANAL