INSERT INTO GEPR_TSUBCANAL (OID_SUBCANAL, COD_SUBCANAL, OID_CANAL, DES_SUBCANAL, OBS_SUBCANAL, BOL_VIGENTE, COD_USUARIO, FYH_ACTUALIZACION) 
VALUES 
([]OID_SUBCANAL, []COD_SUBCANAL, []OID_CANAL, []DES_SUBCANAL, []OBS_SUBCANAL, []BOL_VIGENTE, []COD_USUARIO, []FYH_ACTUALIZACION)