SELECT COD_SUBCANAL, DES_SUBCANAL, OID_CANAL, OBS_SUBCANAL, BOL_VIGENTE
FROM GEPR_TSUBCANAL
WHERE OID_CANAL IN (SELECT CAN.OID_CANAL 
FROM GEPR_TCANAL CAN INNER JOIN GEPR_TSUBCANAL SUBC ON CAN.OID_CANAL = SUBC.OID_CANAL
WHERE CAN.COD_CANAL = []COD_CANAL)