SELECT CAN.COD_CANAL, CAN.DES_CANAL, CAN.OBS_CANAL, CAN.BOL_VIGENTE, SUBC.COD_SUBCANAL, SUBC.DES_SUBCANAL, 
CAN.OID_CANAL, SUBC.OBS_SUBCANAL, SUBC.BOL_VIGENTE as BOL_VIGENTE_SUBCANAL, SUBC.OID_SUBCANAL, CAN.FYH_ACTUALIZACION,
CAN.COD_USUARIO FROM GEPR_TCANAL CAN 
LEFT JOIN GEPR_TSUBCANAL SUBC ON CAN.OID_CANAL = SUBC.OID_CANAL 

