SELECT SC.COD_SUBCANAL,SC.OID_SUBCANAL, SC.DES_SUBCANAL 
FROM SAPR_TCERTIFICADOXSUBCANAL CSC
INNER JOIN SAPR_TCERTIFICADO C ON C.OID_CERTIFICADO = CSC.OID_CERTIFICADO
INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = CSC.OID_SUBCANAL
WHERE C.COD_CERTIFICADO = []COD_CERTIFICADO