SELECT 
	SUB.OID_SUBCANAL, 
	SUB.COD_SUBCANAL 
FROM 
	GEPR_TPROCESO_SUBCANAL PSUB 
	INNER JOIN GEPR_TSUBCANAL SUB ON SUB.OID_SUBCANAL = PSUB.OID_SUBCANAL 
WHERE 
	PSUB.OID_PROCESO_POR_PSERVICIO = []OID_PROCESO_POR_PSERVICIO