SELECT DISTINCT DOC.OID_DOCUMENTO IDENTIFICADOR_DOCUMENTO,
       DOCE.OID_REMESA IDENTIFICADOR_REMESA,
       DOCE.OID_BULTO IDENTIFICADOR_BULTO,
       DOCE.COD_ESTADO_DOCXELEMENTO ESTADO_DOCXELEMENTO,
       DOC.COD_ESTADO ESTADO_DOCUMENTO,
       S.OID_SECTOR IDENTIFICADOR_SECTOR,
       S.COD_SECTOR COD_SECTOR,
       S.DES_SECTOR DES_SECTOR,
       R.BOL_GESTION_BULTO R_BOL_GESTION_BULTO,
       B.BOL_GESTION_BULTO B_BOL_GESTION_BULTO
FROM SAPR_TDOCUMENTO DOC INNER JOIN SAPR_TDOCUMENTOXELEMENTO DOCE ON DOC.OID_DOCUMENTO = DOCE.OID_DOCUMENTO
     INNER JOIN SAPR_TCUENTA C ON C.OID_CUENTA = DOC.OID_CUENTA_ORIGEN
     INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = C.OID_SECTOR
     INNER JOIN SAPR_TREMESA R ON R.OID_REMESA = DOCE.OID_REMESA
     LEFT JOIN SAPR_TBULTO B ON B.OID_BULTO = DOCE.OID_BULTO
WHERE {0}
	  OR
      {1}
ORDER BY IDENTIFICADOR_REMESA,IDENTIFICADOR_BULTO


