INSERT INTO SAPR_TDOCUMENTOXELEMENTO
(OID_DOCUMENTOXELEMENTO
,OID_DOCUMENTO
,OID_REMESA
,OID_BULTO
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION)
VALUES
([]OID_DOCUMENTOXELEMENTO
,[]OID_DOCUMENTO
,[]OID_REMESA
,[]OID_BULTO
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_CREACION
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_MODIFICACION)