/* SAPR_TDOCUMENTOXELEMENTO = Actualizar registros en la tabla */

UPDATE SAPR_TDOCUMENTOXELEMENTO
   SET GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###
      ,DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
      ,COD_ESTADO_DOCXELEMENTO = []COD_ESTADO_DOCXELEMENTO
 WHERE OID_DOCUMENTO = []OID_DOCUMENTO
 {0}