SELECT 
	OID_ITEM_PROCESO, 
	COD_PROCESO, 
	OBS_PARAMETROS, 
	COD_ESTADO, 
	NEL_INTENTOS_ENVIO, 
	COD_USUARIO, 
	FYH_CREACION, 
	FYH_ACTUALIZACION, 
	COD_DELEGACION
FROM GEPR_TITEM_PROCESO
WHERE 
	COD_PROCESO = []COD_PROCESO AND 
	OBS_PARAMETROS = []OBS_PARAMETROS AND
	COD_ESTADO = []COD_ESTADO AND
	COD_DELEGACION = []COD_DELEGACION