SELECT TMP.OID_TERMINO,
       TMP.COD_TERMINO,
       TMP.DES_TERMINO,
       TMP.OBS_TERMINO,
       TMP.DES_VALOR_INICIAL,
       TMP.NEC_LONGITUD,
       TMP.BOL_MOSTRAR_CODIGO,
       TMP.NEC_ORDEN,
       TMP.BOL_VIGENTE AS TERMINO_ACTIVO,
       TMP.COD_USUARIO AS USUARIO_TERMINO,
       TMP.FYH_ACTUALIZACION AS FYH_TERMINO,
       F.OID_FORMATO,
       F.COD_FORMATO,
       F.DES_FORMATO,
       F.COD_USUARIO AS USUARIO_FORMATO,
       F.FYH_ACTUALIZACION AS FYH_FORMATO,
       M.OID_MASCARA,
       M.COD_MASCARA,
       M.DES_MASCARA,
       M.DES_EXP_REGULAR,
       M.BOL_APLICA_TERM_MEDIO_PAGO AS MASC_APLIC_TERM_MP,
       M.BOL_APLICA_TERM_IAC AS MASC_APLIC_TERM_IAC,
       M.COD_USUARIO AS USUARIO_MASCARA,
       M.FYH_ACTUALIZACION AS FYH_MASCARA,
       AV.OID_ALGORITMO_VALIDACION,
       AV.COD_ALGORITMO_VALIDACION,
       AV.DES_ALGORITMO_VALIDACION,
       AV.OBS_ALGORITMO_VALIDACION,
       AV.BOL_APLICA_TERM_MEDIO_PAGO AS ALG_VAL_APLIC_TERM_MP,
       AV.BOL_APLICA_TERM_IAC AS ALG_VAL_APLIC_TERM_IAC,
       AV.COD_USUARIO AS USUARIO_ALGORITMO,
       AV.FYH_ACTUALIZACION AS FYH_ALGORITMO
FROM GEPR_TTERMINO_MEDIO_PAGO TMP
INNER JOIN GEPR_TFORMATO F ON F.OID_FORMATO = TMP.OID_FORMATO
LEFT JOIN GEPR_TMASCARA M ON M.OID_MASCARA = TMP.OID_MASCARA
LEFT JOIN GEPR_TALGORITMO_VALIDACION AV ON AV.OID_ALGORITMO_VALIDACION = TMP.OID_ALGORITMO_VALIDACION
WHERE TMP.OID_MEDIO_PAGO = []OID_MEDIO_PAGO

