SELECT OID_DIRECCION, OID_TABLA_GENESIS, COD_TIPO_TABLA_GENESIS, DES_PAIS, DES_PROVINCIA, DES_CIUDAD, DES_NUMERO_TELEFONO, 
DES_EMAIL, COD_FISCAL, COD_POSTAL, DES_DIRECCION_LINEA_1, DES_DIRECCION_LINEA_2, DES_CAMPO_ADICIONAL_1, DES_CAMPO_ADICIONAL_2, 
DES_CAMPO_ADICIONAL_3, DES_CATEGORIA_ADICIONAL_1, DES_CATEGORIA_ADICIONAL_2, DES_CATEGORIA_ADICIONAL_3, GMT_CREACION, 
DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION FROM GEPR_TDIRECCION