UPDATE GEPR_TMODULO TM SET
TM.OID_LISTA_VALOR = []OID_LISTA_VALOR,
TM.DES_MODULO = []DES_MODULO,
TM.OID_CLIENTE = []OID_CLIENTE,
TM.BOL_ACTIVO = []BOL_ACTIVO,
TM.GMT_MODIFICACION = []GMT_MODIFICACION,
TM.DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE TM.OID_MODULO = []OID_MODULO