UPDATE GEPR_TMODULO_DESGLOSE TMD SET
TMD.NEL_UNIDADES = []NEL_UNIDADES,
TMD.GMT_MODIFICACION = []GMT_MODIFICACION,
TMD.DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE TMD.OID_MODULO_DESGLOSE = []OID_MODULO_DESGLOSE