INSERT INTO GEPR_TMODULO_DESGLOSE TMD
(TMD.OID_MODULO_DESGLOSE,
TMD.OID_MODULO,
TMD.OID_DENOMINACION,
TMD.NEL_UNIDADES,
TMD.GMT_CREACION,
TMD.DES_USUARIO_CREACION,
TMD.GMT_MODIFICACION,
TMD.DES_USUARIO_MODIFICACION)
VALUES
([]OID_MODULO_DESGLOSE,
[]OID_MODULO,
[]OID_DENOMINACION,
[]NEL_UNIDADES,
[]GMT_CREACION,
[]DES_USUARIO_CREACION,
[]GMT_MODIFICACION,
[]DES_USUARIO_MODIFICACION)