SELECT 
LV.COD_VALOR COD_EMBALAJE,
TM.OID_MODULO,
TM.COD_MODULO,
TM.DES_MODULO,
TM.BOL_ACTIVO,
TM.GMT_CREACION,
TM.DES_USUARIO_CREACION,
TM.GMT_MODIFICACION,
TM.DES_USUARIO_MODIFICACION,
CLI.COD_CLIENTE
FROM GEPR_TMODULO TM
INNER JOIN GEPR_TLISTA_VALOR LV ON LV.OID_LISTA_VALOR = TM.OID_LISTA_VALOR
LEFT JOIN GEPR_TCLIENTE CLI ON CLI.OID_CLIENTE = TM.OID_CLIENTE
WHERE 0 = 0 