SELECT 
PD.OID_DOCUMENTO
,PD.OID_MEDIO_PAGO
,TM.OID_TERMINO
,TMP.DES_VALOR
,TMP.NEC_INDICE_GRUPO

  FROM SAPR_TVALOR_TERMINO_MEDIO_PAGO TMP
 INNER JOIN SAPR_TMEDIO_PAGOXDOCUMENTO PD ON (TMP.OID_MEDIO_PAGOXDOCUMENTO = PD.OID_MEDIO_PAGOXDOCUMENTO)
 INNER JOIN GEPR_TTERMINO_MEDIO_PAGO TM ON TM.OID_TERMINO = TMP.OID_TERMINO_MEDIO_PAGO
 WHERE 1 = 1 
 {0}
ORDER BY TMP.NEC_INDICE_GRUPO