DELETE SAPR_TVALOR_TERMINO_MEDIO_PAGO
 WHERE OID_MEDIO_PAGOXDOCUMENTO IN
       (SELECT OID_MEDIO_PAGOXDOCUMENTO
          FROM SAPR_TMEDIO_PAGOXDOCUMENTO
         WHERE OID_DOCUMENTO = []OID_DOCUMENTO)