INSERT INTO SAPR_TABONO_VALOR
  (OID_ABONO_VALOR, OID_ABONO, OID_CLIENTE, OID_SUBCLIENTE, OID_PTO_SERVICIO, OID_DIVISA, COD_TIPO_CUENTA_BANCARIA, COD_CUENTA_BANCARIA, COD_DOCUMENTO, DES_TITULARIDAD, DES_OBSERVACIONES, NUM_IMPORTE, GMT_CREACION, GMT_MODIFICACION, DES_USUARIO_CREACION, DES_USUARIO_MODIFICACION, OID_BANCO)
VALUES
  ([]OID_ABONO_VALOR, []OID_ABONO, []OID_CLIENTE, []OID_SUBCLIENTE, []OID_PTO_SERVICIO, []OID_DIVISA, []COD_TIPO_CUENTA_BANCARIA, []COD_CUENTA_BANCARIA, []COD_DOCUMENTO, []DES_TITULARIDAD, []DES_OBSERVACIONES, []NUM_IMPORTE, FN_GMT_ZERO_###VERSION###, FN_GMT_ZERO_###VERSION###, []DES_USUARIO_CREACION, []DES_USUARIO_MODIFICACION, []OID_BANCO)
