SELECT DIV.OID_DIVISA,
	   DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       DEN.COD_DENOMINACION,
       DEN.DES_DENOMINACION,
       DEN.BOL_BILLETE,
       DEN.NUM_VALOR_FACIAL,
       SUM(EFE.NEL_CANTIDAD) NEL_CANTIDAD
  FROM GEPR_TREMESA REM
 LEFT JOIN GEPR_TLISTA_TRABAJO LST ON LST.OID_REMESA = REM.OID_REMESA
 LEFT JOIN GEPR_TPUESTO PUE ON PUE.OID_PUESTO = LST.OID_PUESTO
 INNER JOIN GEPR_TBULTO BUL ON REM.OID_REMESA = BUL.OID_REMESA
 INNER JOIN GEPR_TEFECTIVO_BULTO EFE ON BUL.OID_BULTO = EFE.OID_BULTO
 INNER JOIN GEPR_TDENOMINACION DEN ON EFE.OID_DENOMINACION = DEN.OID_DENOMINACION
 INNER JOIN GEPR_TDIVISA DIV ON DEN.OID_DIVISA = DIV.OID_DIVISA
 WHERE REM.COD_DELEGACION = :COD_DELEGACION
	   {0}
 GROUP BY DIV.OID_DIVISA,
		  DIV.COD_ISO_DIVISA,
          DIV.DES_DIVISA,
          DEN.COD_DENOMINACION,
          DEN.DES_DENOMINACION,
          DEN.BOL_BILLETE,
          DEN.NUM_VALOR_FACIAL
UNION

SELECT DIV.OID_DIVISA,
	   DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       DEN.COD_DENOMINACION,
       DEN.DES_DENOMINACION,
       DEN.BOL_BILLETE,
       DEN.NUM_VALOR_FACIAL,
       SUM(EFE.NEL_CANTIDAD) NEL_CANTIDAD
       
  FROM GEPR_TBULTO BUL
 LEFT JOIN GEPR_TLISTA_TRABAJO LST ON LST.OID_BULTO = BUL.OID_BULTO
 LEFT JOIN GEPR_TPUESTO PUE ON PUE.OID_PUESTO = LST.OID_PUESTO
 INNER JOIN GEPR_TREMESA REM ON REM.OID_REMESA = BUL.OID_REMESA
 INNER JOIN GEPR_TEFECTIVO_BULTO EFE ON BUL.OID_BULTO = EFE.OID_BULTO
 INNER JOIN GEPR_TDENOMINACION DEN ON EFE.OID_DENOMINACION = DEN.OID_DENOMINACION
 INNER JOIN GEPR_TDIVISA DIV ON DEN.OID_DIVISA = DIV.OID_DIVISA
 WHERE REM.COD_DELEGACION = :COD_DELEGACION
	   {1}
 GROUP BY DIV.OID_DIVISA,
		  DIV.COD_ISO_DIVISA,
          DIV.DES_DIVISA,
          DEN.COD_DENOMINACION,
          DEN.DES_DENOMINACION,
          DEN.BOL_BILLETE,
          DEN.NUM_VALOR_FACIAL