INSERT INTO	SAPR_TLISTA_VALORXELEMENTO
(
	OID_LISTA_VALORXELEMENTO,
	OID_REMESA,
	OID_BULTO,
	OID_PARCIAL,
	OID_LISTA_TIPO,
	OID_LISTA_VALOR,
	GMT_CREACION,
	DES_USUARIO_CREACION,
	GMT_MODIFICACION,
	DES_USUARIO_MODIFICACION
)
SELECT
	[]OID_LISTA_VALORXELEMENTO,
	[]OID_REMESA,
	[]OID_BULTO,
	[]OID_PARCIAL,
	LV.OID_LISTA_TIPO,
	[]OID_LISTA_VALOR,
	FN_GMT_ZERO_###VERSION###,
	[]DES_USUARIO_CREACION,
	FN_GMT_ZERO_###VERSION###,
	[]DES_USUARIO_MODIFICACION
FROM
	GEPR_TLISTA_VALOR LV
WHERE
	LV.OID_LISTA_VALOR = []OID_LISTA_VALOR
