SELECT 
     LV.OID_LISTA_VALOR, 
	   LV.COD_VALOR,
	   LV.DES_VALOR,
	   LV.BOL_DEFECTO,
     NULL AS OID_MODULO,
     NULL AS OID_DENOMINACION,
     NULL AS COD_DENOMINACION,
    0 ES_MODULO, 0 NUM_VALOR, 0  NEL_UNIDADES,
     NULL AS OID_DIVISA, NULL AS COD_ISO_DIVISA
FROM
  GEPR_TLISTA_VALOR LV
  INNER JOIN GEPR_TLISTA_TIPO LT ON LV.OID_LISTA_TIPO = LT.OID_LISTA_TIPO
 WHERE
  LT.COD_TIPO = []COD_TIPO
  {0}
   AND NOT EXISTS(SELECT OID_MODULO FROM GEPR_TMODULO M1 WHERE LV.OID_LISTA_VALOR = M1.OID_LISTA_VALOR)
 UNION
SELECT LV.OID_LISTA_VALOR, 
       LV.COD_VALOR,
       LV.DES_VALOR,
       LV.BOL_DEFECTO,
       M.OID_MODULO,
      DE.OID_DENOMINACION,
      DE.COD_DENOMINACION,
     1 ES_MODULO, DE.NUM_VALOR, TMD.NEL_UNIDADES,
     DIV.OID_DIVISA, DIV.COD_ISO_DIVISA
FROM
  GEPR_TLISTA_VALOR LV
  INNER JOIN GEPR_TLISTA_TIPO LT ON LV.OID_LISTA_TIPO = LT.OID_LISTA_TIPO
  INNER JOIN GEPR_TMODULO M ON LV.OID_LISTA_VALOR = M.OID_LISTA_VALOR
  INNER JOIN GEPR_TMODULO_DESGLOSE TMD ON TMD.OID_MODULO = M.OID_MODULO
INNER JOIN GEPR_TDENOMINACION DE ON DE.OID_DENOMINACION = TMD.OID_DENOMINACION
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = DE.OID_DIVISA
WHERE
 LT.COD_TIPO = []COD_TIPO
 {0}
 