SELECT
	LV.OID_LISTA_VALOR,
	LV.COD_VALOR,
	LV.DES_VALOR,
	LV.BOL_DEFECTO
FROM
	GEPR_TLISTA_VALOR LV
	INNER JOIN GEPR_TLISTA_TIPO LT ON LV.OID_LISTA_TIPO = LT.OID_LISTA_TIPO
WHERE
	LT.COD_TIPO = []COD_TIPO
ORDER BY
	LV.DES_VALOR