SELECT D.COD_DENOMINACION,
       D.COD_USUARIO,
       D.DES_DENOMINACION,
       D.BOL_BILLETE,
       D.BOL_VIGENTE,
       D.FYH_ACTUALIZACION,
       D.OID_DENOMINACION,
       D.NUM_VALOR,
       D.OID_DIVISA,
       DIV.COD_ISO_DIVISA
FROM GEPR_TDENOMINACION D
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = D.OID_DIVISA
WHERE 1 = 1
 {0}