SELECT D.COD_DENOMINACION,
       D.COD_USUARIO,
       D.DES_DENOMINACION,
       D.BOL_BILLETE,
       D.BOL_VIGENTE,
       D.FYH_ACTUALIZACION,
       D.OID_DENOMINACION,
       D.NUM_VALOR
FROM GEPR_TDENOMINACION D
WHERE D.OID_DENOMINACION = []OID_DENOMINACION