SELECT D.OID_DENOMINACION,
	   D.COD_DENOMINACION,
       D.DES_DENOMINACION,
	   D.NUM_VALOR,
       D.BOL_BILLETE,
       D.BOL_VIGENTE,
       D.FYH_ACTUALIZACION,
	   D.COD_USUARIO
FROM GEPR_TDENOMINACION D
WHERE 0 = 0