SELECT
'DECLARADO_EFECTIVO' AS TIPO
,DECEF.OID_REMESA
,DECEF.OID_BULTO
,DECEF.OID_PARCIAL
,D.OID_DIVISA
,DECEF.OID_DENOMINACION
,SUM(DECEF.NUM_IMPORTE) AS IMPORTE
,SUM(DECEF.NEL_CANTIDAD) AS CANTIDAD
     
FROM SAPR_TDECLARADO_EFECTIVO DECEF
INNER JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = DECEF.OID_DENOMINACION
     WHERE DECEF.OID_DENOMINACION IS NOT NULL {0}
  GROUP BY DECEF.OID_REMESA, DECEF.OID_BULTO, DECEF.OID_PARCIAL, D.OID_DIVISA, DECEF.OID_DENOMINACION
