SELECT
 'CONTADO_EFECTIVO' AS TIPO
,CONEF.OID_REMESA
,CONEF.OID_BULTO
,CONEF.OID_PARCIAL
,D.OID_DIVISA
,CONEF.OID_DENOMINACION
,SUM(CONEF.NUM_IMPORTE) AS IMPORTE
,SUM(CONEF.NEL_CANTIDAD) AS CANTIDAD
,CONEF.OID_CALIDAD
,CONEF.OID_UNIDAD_MEDIDA

      FROM SAPR_TCONTADO_EFECTIVO CONEF
INNER JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = CONEF.OID_DENOMINACION
     WHERE CONEF.OID_DENOMINACION IS NOT NULL {0}
  GROUP BY CONEF.OID_REMESA, CONEF.OID_BULTO, CONEF.OID_PARCIAL, D.OID_DIVISA, CONEF.OID_DENOMINACION, 
           CONEF.OID_CALIDAD, CONEF.OID_UNIDAD_MEDIDA

UNION

SELECT
 'DIFERENCIA_EFECTIVO' AS TIPO
,DIFEF.OID_REMESA
,DIFEF.OID_BULTO
,DIFEF.OID_PARCIAL
,D.OID_DIVISA
,DIFEF.OID_DENOMINACION
,SUM(DIFEF.NUM_IMPORTE) AS IMPORTE
,SUM(DIFEF.NEL_CANTIDAD) AS CANTIDAD
,NULL AS OID_CALIDAD
,DIFEF.OID_UNIDAD_MEDIDA

      FROM SAPR_TDIFERENCIA_EFECTIVO DIFEF
INNER JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = DIFEF.OID_DENOMINACION
     WHERE DIFEF.OID_DENOMINACION IS NOT NULL {0}
  GROUP BY DIFEF.OID_REMESA, DIFEF.OID_BULTO, DIFEF.OID_PARCIAL, D.OID_DIVISA, DIFEF.OID_DENOMINACION,
           DIFEF.OID_UNIDAD_MEDIDA

UNION

SELECT
'DECLARADO_EFECTIVO' AS TIPO
,DECEF.OID_REMESA
,DECEF.OID_BULTO
,DECEF.OID_PARCIAL
,D.OID_DIVISA
,DECEF.OID_DENOMINACION
,SUM(DECEF.NUM_IMPORTE) AS IMPORTE
,SUM(DECEF.NEL_CANTIDAD) AS CANTIDAD
,NULL AS OID_CALIDAD
,DECEF.OID_UNIDAD_MEDIDA
     
      FROM SAPR_TDECLARADO_EFECTIVO DECEF
INNER JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = DECEF.OID_DENOMINACION
     WHERE DECEF.OID_DENOMINACION IS NOT NULL {0}
  GROUP BY DECEF.OID_REMESA, DECEF.OID_BULTO, DECEF.OID_PARCIAL, D.OID_DIVISA, DECEF.OID_DENOMINACION,
           DECEF.OID_UNIDAD_MEDIDA
