SELECT
 'CONTADO_EFECTIVO' AS TIPO
,EFEC.OID_REMESA
,EFEC.OID_BULTO
,EFEC.OID_PARCIAL
,D.OID_DIVISA
,EFEC.OID_DENOMINACION
,SUM(EFEC.NUM_IMPORTE) AS IMPORTE
,SUM(EFEC.NEL_CANTIDAD) AS CANTIDAD
,EFEC.OID_CALIDAD
,EFEC.OID_UNIDAD_MEDIDA

      FROM SAPR_TCONTADO_EFECTIVO EFEC
INNER JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = EFEC.OID_DENOMINACION
     WHERE EFEC.OID_DENOMINACION IS NOT NULL {0}
  GROUP BY EFEC.OID_REMESA, EFEC.OID_BULTO, EFEC.OID_PARCIAL, D.OID_DIVISA, EFEC.OID_DENOMINACION, 
           EFEC.OID_CALIDAD, EFEC.OID_UNIDAD_MEDIDA
