'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucAcciones

    '''<summary>
    '''upBotones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upBotones As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnGuardarConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarConfirmar As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmar As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnAceptar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptar As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnRechazar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRechazar As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnAnular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnular As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnModificar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModificar As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnModificarTermino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModificarTermino As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnSalvarTerminos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarTerminos As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnImprimir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImprimir As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnVisualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVisualizar As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnAgregarDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarDocumento As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton

    '''<summary>
    '''btnConfigurarNovoReporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfigurarNovoReporte As Global.Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Boton
End Class
