UPDATE GEPR_TTIPO_PUNTO_SERVICIO
    SET COD_TIPO_PUNTO_SERVICIO = []COD_TIPO_PUNTO_SERVICIO,
        DES_TIPO_PUNTO_SERVICIO = []DES_TIPO_PUNTO_SERVICIO,
        BOL_ACTIVO = []BOL_ACTIVO,
        GMT_CREACION = []GMT_CREACION,
        DES_USUARIO_CREACION = []DES_USUARIO_CREACION,
        GMT_MODIFICACION = []GMT_MODIFICACION,
        DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION,
		BOL_MAQUINA = []BOL_MAQUINA,
		BOL_MAE = []BOL_MAE
WHERE OID_TIPO_PUNTO_SERVICIO = []OID_TIPO_PUNTO_SERVICIO