SELECT 
OID_TIPO_PUNTO_SERVICIO, 
COD_TIPO_PUNTO_SERVICIO , 
DES_TIPO_PUNTO_SERVICIO, 
BOL_ACTIVO, 
GMT_CREACION, 
DES_USUARIO_CREACION, 
GMT_MODIFICACION, 
DES_USUARIO_MODIFICACION,
BOL_MAQUINA,
BOL_MAE
FROM GEPR_TTIPO_PUNTO_SERVICIO TPS
WHERE TPS.COD_TIPO_PUNTO_SERVICIO = []COD_TIPO_PUNTO_SERVICIO