INSERT INTO GEPR_TEFECTIVO_LEGADO (
OID_EFECTIVO_LEGADO, 
OID_REMESA, 
OID_DIVISA, 
OID_DENOMINACION, 
NEL_CANTIDAD, 
NEL_IMPORTE_EFECTIVO, 
COD_USUARIO, 
FYH_ACTUALIZACION
) VALUES ( 
[]OID_EFECTIVO_LEGADO
,[]OID_REMESA
,[]OID_DIVISA
,[]OID_DENOMINACION
,[]NEL_CANTIDAD
,[]NEL_IMPORTE_EFECTIVO
,[]COD_USUARIO
,[]FYH_ACTUALIZACION
)