/*QT REMESA SETOR SALIDAS*/
SELECT TMP.*,   NULL AS DES_SECTOR
 FROM (
        SELECT
		  REME.COD_SECTOR,  
		  REME.COD_ESTADO_REMESA,  
		  COUNT(DISTINCT REME.OID_REMESA) TOTAL
		FROM
		  GEPR_TREMESA REME
		WHERE REME.FYH_ACTUALIZACION > []DATA_INI
			{0}
		GROUP BY
		  REME.COD_SECTOR,
		  REME.COD_ESTADO_REMESA
		ORDER BY 1
) TMP
