UPDATE 
  GEPR_TREMESA 
SET 
  COD_ESTADO_REMESA = []COD_ESTADO_REMESA, 
  COD_USUARIO = []COD_USUARIO, 
  FYH_ACTUALIZACION = []FYH_ACTUALIZACION 
WHERE 
  OID_REMESA = []OID_REMESA AND 
  NOT EXISTS (SELECT NULL FROM GEPR_TBULTO WHERE COD_ESTADO_BULTO = []COD_ESTADO_BULTO AND OID_REMESA = []OID_REMESA)
