UPDATE
  GEPR_TLISTA_TRABAJO LT
SET
  LT.OID_PUESTO = (SELECT OID_PUESTO FROM GEPR_TPUESTO P WHERE P.COD_PUESTO = []COD_PUESTO AND P.COD_DELEGACION = []COD_DELEGACION),
  LT.COD_USUARIO = []COD_USUARIO,
  LT.FYH_ACTUALIZACION = []FYH_ACTUALIZACION
WHERE
  LT.OID_REMESA = []OID_REMESA 