WITH REMESAS AS
(SELECT *
 FROM GEPR_TREMESA R
 WHERE R.OID_OT = []OID_OT),
 CANTIDAD_REMESAS AS
 (SELECT RE.OID_OT, CASE WHEN COUNT(*) <> []CANTIDAD_REMESAS THEN 1 ELSE 0 END PUEDE_MODIFICAR
  FROM REMESAS RE
  WHERE RE.COD_ESTADO_REMESA IN ('PE','AS','DV') AND RE.OID_REMESA_PADRE IS NULL
  GROUP BY RE.OID_OT),
  REMESAS_PROCESADAS AS
  (SELECT RE.OID_OT, 1 HAY_REMESAS_PROCESADAS
  FROM REMESAS RE
  WHERE RE.COD_ESTADO_REMESA NOT IN ('PE','AS','DV','MD','AN')
  GROUP BY RE.OID_OT)
  SELECT CR.PUEDE_MODIFICAR, RP.HAY_REMESAS_PROCESADAS
  FROM CANTIDAD_REMESAS CR
  LEFT JOIN REMESAS_PROCESADAS RP ON RP.OID_OT = CR.OID_OT
      