/*QT DENOMINAÇÃO SALIDAS*/
SELECT
  DENO.DES_DENOMINACION,
  DENO.NUM_VALOR_FACIAL NUM_VALOR,
  SUM(EFE.NEL_CANTIDAD) TOTAL
FROM
  GEPR_TREMESA REME
  INNER JOIN GEPR_TBULTO BULT ON REME.OID_REMESA = BULT.OID_REMESA
  INNER JOIN GEPR_TEFECTIVO_BULTO EFE ON BULT.OID_BULTO = EFE.OID_BULTO
  INNER JOIN GEPR_TDENOMINACION DENO ON EFE.OID_DENOMINACION = DENO.OID_DENOMINACION
WHERE REME.FYH_ACTUALIZACION BETWEEN []DATA_INI AND  []DATA_FIN
	{0}
GROUP BY
  DENO.DES_DENOMINACION,
  DENO.NUM_VALOR_FACIAL
ORDER BY 1
