SELECT COUNT(1) 
FROM GEPR_TREMESA R
WHERE R.OID_OT = []OID_OT AND R.COD_ESTADO_REMESA NOT IN('DV','AN','MD')
 UNION
SELECT COUNT(1) 
FROM GEPR_TREMESA R
WHERE R.OID_OT = []OID_OT AND R.COD_ESTADO_REMESA = 'PR' AND R.BOL_ENVIADO_SOL = 1