SELECT 
  COUNT(R.OID_REMESA)
  ,R.OID_OT
FROM GEPR_TREMESA R
WHERE 
((R.COD_ESTADO_REMESA = 'PR' AND R.BOL_ENVIADO_SOL = 0) -- NÃO ENVIADA (OU) NÃO PROCESSADA
    OR R.COD_ESTADO_REMESA NOT IN ('AN','PR','MD','DV'))
{0}
GROUP BY R.OID_OT
HAVING COUNT(R.OID_REMESA) > 0