SELECT 1
FROM (
SELECT (SELECT SUM(IMPORTE_REMESA) IMPORTE_REMESA
FROM (SELECT ML.NUM_IMPORTE_EFECTIVO IMPORTE_REMESA
FROM GEPR_TREMESA R
INNER JOIN GEPR_TMODULO_LEGADO ML ON ML.OID_REMESA = R.OID_REMESA
WHERE R.OID_REMESA = []OID_REMESA
UNION
SELECT EL.NEL_IMPORTE_EFECTIVO IMPORTE_REMESA
FROM GEPR_TREMESA R
INNER JOIN GEPR_TEFECTIVO_LEGADO EL ON EL.OID_REMESA = R.OID_REMESA
WHERE R.OID_REMESA = []OID_REMESA)) IMPORTE_REMESA,
(SELECT SUM((D.NUM_VALOR_FACIAL * EB.NEL_CANTIDAD)) IMPORTE_BULTO
FROM GEPR_TREMESA R
INNER JOIN GEPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA
INNER JOIN GEPR_TEFECTIVO_BULTO EB ON EB.OID_BULTO = B.OID_BULTO
INNER JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = EB.OID_DENOMINACION
WHERE R.OID_REMESA = []OID_REMESA) IMPORTE_BULTO
FROM DUAL) T
WHERE T.IMPORTE_REMESA = T.IMPORTE_BULTO