  UPDATE GEPR_TREMESA R SET R.COD_ESTADO_REMESA = []COD_ESTADO_REMESA, 
						    R.COD_USUARIO = []COD_USUARIO, 
							R.FYH_ACTUALIZACION = []FYH_ACTUALIZACION
							{0}
  WHERE R.OID_REMESA = []OID_REMESA