WITH Q AS (
           SELECT R.COD_ESTADO_REMESA AS COD_ESTADO_REMESA,
                  R.OID_REMESA AS OID_REMESA  
             FROM GEPR_TREMESA R
            WHERE R.COD_DELEGACION = []COD_DELEGACION 
              AND R.COD_ESTADO_REMESA IN ('PE', 'AS', 'PR')
          )
SELECT Q.COD_ESTADO_REMESA, 
       COUNT(1) AS CANTIDAD
  FROM Q
INNER JOIN GEPR_TBULTO B 
    ON Q.OID_REMESA = B.OID_REMESA
WHERE Q.COD_ESTADO_REMESA IN ('PE', 'AS', 'PR')
GROUP BY Q.COD_ESTADO_REMESA
UNION
SELECT 'ND' AS COD_ESTADO_REMESA,
       COUNT(1) AS CANTIDAD
  FROM Q
  LEFT JOIN GEPR_TBULTO B 
    ON Q.OID_REMESA = B.OID_REMESA
WHERE Q.COD_ESTADO_REMESA IN ('PE')
   AND B.OID_REMESA IS NULL
GROUP BY 'ND'