UPDATE GEPR_TREMESA R 
SET R.COD_RUTA_REMESA = []COD_RUTA_REMESA,
	R.COD_SECUENCIA = []COD_SECUENCIA, 
	R.FYH_SALIDA = []FYH_SALIDA, 
	R.FEC_SERVICIO  = []FEC_SERVICIO,
	R.DES_COMENTARIO = []DES_COMENTARIO,
	R.NEL_CONTROL_LEGADO = []NEL_CONTROL_LEGADO,
	R.NEL_PEDIDO_LEGADO = []NEL_PEDIDO_LEGADO {0}
WHERE R.OID_REMESA = []OID_REMESA