UPDATE GEPR_TREMESA R 
SET R.COD_ESTADO_REMESA = []COD_ESTADO_REMESA,
	R.OID_REMESA_LEGADO = []OID_REMESA_LEGADO, 
	R.COD_USUARIO = []COD_USUARIO, 
	R.FYH_ACTUALIZACION = []FYH_ACTUALIZACION 
WHERE R.OID_REMESA = []OID_REMESA