UPDATE GEPR_TREMESA R
SET R.NEL_INTENTOS_SOL = []NEL_INTENTOS_SOL, 
	R.BOL_ENVIADO_SOL = []BOL_ENVIADO_SOL_NUEVO, 
	R.FYH_ACTUALIZACION = []FECHA_MODIFICACION
WHERE R.OID_REMESA = []OID_REMESA AND 
      R.COD_ESTADO_REMESA = []COD_ESTADO_REMESA