SELECT REM.COD_ESTADO_REMESA
    , COUNT(BUL.OID_BULTO) QTD_BULTOS
FROM GEPR_TREMESA REM 
LEFT JOIN GEPR_TBULTO BUL ON REM.OID_REMESA = BUL.OID_REMESA 
AND BUL.COD_ESTADO_BULTO IN ('PR', 'SA', 'EN', 'EC') 
    WHERE REM.OID_REMESA = []OID_REMESA
GROUP BY REM.COD_ESTADO_REMESA
