SELECT 
	 R.FYH_INICIO
	 ,R.OID_REMESA_PADRE
	 ,R.OID_REMESA 
	 ,R.OID_REMESA_LEGADO
	 ,R.COD_DELEGACION
	 ,R.COD_ESTADO_REMESA
	 ,R.FYH_INICIO_ARMADO
	 ,R.FYH_FIN_ARMADO
	 ,R.COD_CLIENTE_FACTURACION
	 ,R.DES_CLIENTE_FACTURACION
	 ,R.COD_CLIENTE_DESTINO
	 ,R.DES_CLIENTE_DESTINO
     ,R.COD_SUBCLIENTE
     ,R.DES_SUBCLIENTE
     ,R.COD_PUNTO_SERVICIO
     ,R.DES_PUNTO_SERVICIO
     ,R.COD_RUTA_REMESA
     ,R.NEL_PARADA
     ,R.COD_EMPRESA_TRANSPORTE
     ,R.COD_CANAL
	 ,R.COD_SUBCANAL
     ,R.DES_REF_CLIENTE
     ,R.COD_CAJA_CENTRALIZADA
     ,R.COD_SECTOR
     ,R.DES_DIRECCION_ENTREGA
     ,R.DES_LOCALIDAD_ENTREGA
     ,R.FYH_PROCESO
     ,R.FEC_SERVICIO
     ,R.FYH_SALIDA
     ,R.NEL_PEDIDO_LEGADO
     ,R.NEL_CONTROL_LEGADO
     ,R.DES_COMENTARIO
     ,R.BOL_ATM
     ,R.DES_MODELO_CAJERO
     ,R.DES_RED
     ,R.NEC_MOD_HAB_REC
     ,R.COD_RECIBO_REMESA
     ,R.COD_USUARIO
     ,R.FYH_ACTUALIZACION FECHA_MODIFICACION_REMESA
	 ,R.BOL_TRABAJA_POR_BULTO
	 ,R.COD_USUARIO_BLOQUEO
	 ,R.OID_OT
	 ,R.COD_SERVICIO
	 ,R.COD_SECUENCIA
	 ,B.OID_BULTO
     ,B.COD_PRECINTO_BULTO 
	 ,B.COD_BOLSA
     ,B.COD_ESTADO_BULTO
     ,B.BOL_CUADRADO 
     ,B.COD_USUARIO
     ,B.FYH_ACTUALIZACION AS FECHA_MODIFICACION_BULTO
     ,B.OID_MORFOLOGIA_COMPONENTE
     ,TIB.COD_TIPO_BULTO
     ,B.BOL_PICOS
     ,B.BOL_PREPARADO
     ,B.COD_USUARIO_BLOQUEO
     ,B.OID_TIPO_BULTO
	 ,B.COD_FORMATO
     ,PST.COD_PUESTO
	 ,R.COD_CLIENTE_SALDO
	 ,R.DES_CLIENTE_SALDO
	 ,R.DES_CONTACTO1
	 ,R.DES_CONTACTO2
	 ,R.DES_CONTACTO3
	 ,R.DES_CONTACTO4
FROM GEPR_TREMESA R 
LEFT JOIN GEPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA
LEFT JOIN GEPR_TTIPO_BULTO TIB ON B.OID_TIPO_BULTO = TIB.OID_TIPO_BULTO 
LEFT JOIN GEPR_TLISTA_TRABAJO LT ON ((R.BOL_TRABAJA_POR_BULTO = 1 AND LT.OID_REMESA = R.OID_REMESA AND LT.OID_BULTO = B.OID_BULTO) OR 
                                     ((R.BOL_TRABAJA_POR_BULTO = 0 OR []AGRUPA_BULTOS = 1) AND LT.OID_REMESA = R.OID_REMESA AND LT.OID_BULTO IS NULL))
LEFT JOIN GEPR_TPUESTO PST ON LT.OID_PUESTO = PST.OID_PUESTO
{0}
UNION
SELECT 
	R.FYH_INICIO
    ,R.OID_REMESA_PADRE
    ,R.OID_REMESA 
	,R.OID_REMESA_LEGADO
	,R.COD_DELEGACION
	,R.COD_ESTADO_REMESA
	,R.FYH_INICIO_ARMADO
	,R.FYH_FIN_ARMADO
	,R.COD_CLIENTE_FACTURACION
	,R.DES_CLIENTE_FACTURACION
	,R.COD_CLIENTE_DESTINO
	,R.DES_CLIENTE_DESTINO
    ,R.COD_SUBCLIENTE
    ,R.DES_SUBCLIENTE
    ,R.COD_PUNTO_SERVICIO
    ,R.DES_PUNTO_SERVICIO
    ,R.COD_RUTA_REMESA
    ,R.NEL_PARADA
    ,R.COD_EMPRESA_TRANSPORTE
    ,R.COD_CANAL
	,R.COD_SUBCANAL
    ,R.DES_REF_CLIENTE
    ,R.COD_CAJA_CENTRALIZADA
    ,R.COD_SECTOR
    ,R.DES_DIRECCION_ENTREGA
    ,R.DES_LOCALIDAD_ENTREGA
    ,R.FYH_PROCESO
    ,R.FEC_SERVICIO
    ,R.FYH_SALIDA
    ,R.NEL_PEDIDO_LEGADO
    ,R.NEL_CONTROL_LEGADO
    ,R.DES_COMENTARIO
    ,R.BOL_ATM
    ,R.DES_MODELO_CAJERO
    ,R.DES_RED
    ,R.NEC_MOD_HAB_REC
    ,R.COD_RECIBO_REMESA
    ,R.COD_USUARIO
    ,R.FYH_ACTUALIZACION FECHA_MODIFICACION_REMESA
	,R.BOL_TRABAJA_POR_BULTO
	,R.COD_USUARIO_BLOQUEO
	,R.OID_OT
	,R.COD_SERVICIO
	,R.COD_SECUENCIA
	,B.OID_BULTO
    ,B.COD_PRECINTO_BULTO 
	,B.COD_BOLSA
    ,B.COD_ESTADO_BULTO
    ,B.BOL_CUADRADO 
    ,B.COD_USUARIO
    ,B.FYH_ACTUALIZACION
    ,B.OID_MORFOLOGIA_COMPONENTE
    ,TIB.COD_TIPO_BULTO
    ,B.BOL_PICOS
    ,B.BOL_PREPARADO
    ,B.COD_USUARIO_BLOQUEO
    ,B.OID_TIPO_BULTO
	,B.COD_FORMATO
    ,PST.COD_PUESTO
	,R.COD_CLIENTE_SALDO
	,R.DES_CLIENTE_SALDO
	,R.DES_CONTACTO1
	,R.DES_CONTACTO2
	,R.DES_CONTACTO3
	,R.DES_CONTACTO4
FROM GEPR_TREMESA R 
LEFT JOIN GEPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA
LEFT JOIN GEPR_TTIPO_BULTO TIB ON B.OID_TIPO_BULTO = TIB.OID_TIPO_BULTO 
LEFT JOIN GEPR_TLISTA_TRABAJO LT ON ((R.BOL_TRABAJA_POR_BULTO = 1 AND LT.OID_REMESA = R.OID_REMESA AND LT.OID_BULTO = B.OID_BULTO) OR 
                                     (R.BOL_TRABAJA_POR_BULTO = 0 AND LT.OID_REMESA = R.OID_REMESA AND LT.OID_BULTO IS NULL))
LEFT JOIN GEPR_TPUESTO PST ON LT.OID_PUESTO = PST.OID_PUESTO
{1}