UPDATE GEPR_TREMESA R
SET R.NEL_INTENTOS_LEGADO = []NEL_INTENTOS_LEGADO, 
	R.BOL_ENVIADO_LEGADO = []BOL_ENVIADO_LEGADO_NUEVO, 
	R.FYH_ACTUALIZACION = []FECHA_MODIFICACION
WHERE R.OID_REMESA = []OID_REMESA AND 
      R.COD_ESTADO_REMESA = []COD_ESTADO_REMESA