SELECT
	R.OID_PEDIDO,
	R.OID_REMESA,
	R.COD_TIPO_MERCANCIA,
	R.OID_DIVISA,
	R.OID_DENOMINACION,
	R.COD_NIVEL_IMPORTE,
	R.COD_MERCANCIA,
	R.NEL_CANTIDAD,
	R.NEL_IMPORTE,
	R.COD_USUARIO,
	R.FYH_ACTUALIZACION,
	DIV.COD_ISO_DIVISA,
	DEN.COD_DENOMINACION
FROM GEPR_TPEDIDO_REMESA R
LEFT JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = R.OID_DIVISA
LEFT JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = R.OID_DENOMINACION
WHERE R.OID_REMESA = []OID_REMESA