/*BILLETES SETOR SALIDAS*/
SELECT
  REME.COD_SECTOR,  
  NULL AS DES_SECTOR,
  SUM(EFE.NEL_CANTIDAD) TOTAL
FROM
  GEPR_TREMESA REME
  INNER JOIN GEPR_TBULTO BULT ON REME.OID_REMESA = BULT.OID_REMESA
  INNER JOIN GEPR_TEFECTIVO_BULTO EFE ON BULT.OID_BULTO = EFE.OID_BULTO
  INNER JOIN GEPR_TDENOMINACION DENO ON EFE.OID_DENOMINACION = DENO.OID_DENOMINACION
WHERE DENO.BOL_BILLETE = 1
  AND REME.FYH_ACTUALIZACION BETWEEN []DATA_INI AND  []DATA_FIN
  {0}
GROUP BY
  REME. COD_SECTOR
ORDER BY 1
