UPDATE GEPR_TREMESA 
SET COD_ESTADO_REMESA = []COD_ESTADO_REMESA 
	,FYH_INICIO_ARMADO = []FYH_INICIO_ARMADO 
	,COD_USUARIO = []COD_USUARIO  
	,FYH_ACTUALIZACION =[]FYH_ACTUALIZACION 
WHERE OID_REMESA = []OID_REMESA