SELECT
	OID_REMESA,
	OID_REMESA_LEGADO,
	COD_ESTADO_REMESA,
	COD_RECIBO_REMESA,
	FYH_INICIO_ARMADO,
	NEL_INTENTOS_SOL,
	NVL(BOL_ENVIADO_SOL,0) BOL_ENVIADO_SOL,
	COD_SECTOR,
	COD_DELEGACION,
	OID_REMESA_PADRE,
    COD_USUARIO_BLOQUEO
FROM GEPR_TREMESA
WHERE
 	OID_OT = []OID_OT AND COD_ESTADO_REMESA NOT IN ('AN','MD','DV')