UPDATE 
	GEPR_TDIVISA
SET 
    DES_DIVISA = []DES_DIVISA,
	COD_SIMBOLO = []COD_SIMBOLO,
    BOL_VIGENTE = []BOL_VIGENTE,
    COD_USUARIO = []COD_USUARIO,
    FYH_ACTUALIZACION = []FYH_ACTUALIZACION
WHERE 
	COD_ISO_DIVISA = []COD_ISO_DIVISA