SELECT DIV.COD_ISO_DIVISA, 
       DIV.DES_DIVISA,
	   DIV.COD_ACCESO AS COD_ACCESO_DIVISA,
	   DIV.COD_COLOR,
	   DEN.COD_ACCESO AS COD_ACCESO_DENOMINACION,
       DEN.COD_DENOMINACION,
       DEN.DES_DENOMINACION,
       DEN.NUM_VALOR,
       DEN.BOL_BILLETE,
	   DEN.OID_DENOMINACION,
	   DIV.OID_DIVISA,
	   DIV.COD_SIMBOLO,
	   DIV.BOL_VIGENTE
FROM GEPR_TDIVISA DIV
INNER JOIN GEPR_TDENOMINACION DEN ON DIV.OID_DIVISA = DEN.OID_DIVISA 
ORDER BY DIV.COD_ISO_DIVISA