SELECT 
     DISTINCT
     DIV.COD_ISO_DIVISA,
     DIV.DES_DIVISA
FROM GEPR_TMEDIO_PAGO MP 
     INNER JOIN GEPR_TDIVISA DIV ON (MP.OID_DIVISA = DIV.OID_DIVISA)
WHERE
     MP.BOL_VIGENTE = 1
     AND MP.COD_TIPO_MEDIO_PAGO = []COD_TIPO_MEDIO_PAGO