SELECT 
    DIV.COD_ISO_DIVISA,
    DIV.DES_DIVISA,
    MP.COD_TIPO_MEDIO_PAGO,
    NULL AS DES_TIPO_MEDIO_PAGO,
    MP.COD_MEDIO_PAGO,
    MP.DES_MEDIO_PAGO,
    MP.BOL_VIGENTE AS MP_VIGENTE
FROM 
	GEPR_TDIVISA DIV 
	LEFT JOIN GEPR_TMEDIO_PAGO MP ON (DIV.OID_DIVISA = MP.OID_DIVISA)
WHERE 
	DIV.BOL_VIGENTE = 1
ORDER BY 
	DIV.COD_ISO_DIVISA, 
	MP.COD_TIPO_MEDIO_PAGO, 
	MP.COD_MEDIO_PAGO