SELECT
      DIV.COD_ISO_DIVISA,
      DIV.DES_DIVISA,
      DIVPR.NUM_TOLERANCIA_PARCIAL_MIN,
      DIVPR.NUM_TOLERANCIA_PARCIAL_MAX,
      DIVPR.NUM_TOLERANCIA_BULTO_MIN,
      DIVPR.NUM_TOLERANCIA_BULTO_MAX,
      DIVPR.NUM_TOLERANCIA_REMESA_MIN,
      DIVPR.NUM_TOLERANCIA_REMESA_MAX,
      DIVPR.NEC_NUM_ORDEN, 
      DEN.COD_DENOMINACION,
      DEN.DES_DENOMINACION,
      DEN.BOL_BILLETE,
      DEN.NUM_VALOR,
      DEN.NUM_PESO
FROM  GEPR_TDIVISA_POR_PROCESO DIVPR
      INNER JOIN GEPR_TDIVISA DIV ON DIVPR.OID_DIVISA = DIV.OID_DIVISA
      INNER JOIN GEPR_TDENOMINACION DEN ON DIV.OID_DIVISA = DEN.OID_DIVISA
WHERE DIVPR.OID_PROCESO = []OID_PROCESO
ORDER BY DIVPR.NEC_NUM_ORDEN