--Borra GEPR_TPREFERENCIAS_USUARIO para la aplicación
DELETE FROM GEPR_TPREFERENCIAS_USUARIO
WHERE OID_APLICACION = (
      SELECT OID_APLICACION
      FROM GEPR_TAPLICACION
      WHERE COD_APLICACION = []COD_APLICACION)
AND COD_USUARIO = []COD_USUARIO