--Exclui GEPR_TPREFERENCIAS_USUARIO
DELETE FROM GEPR_TPREFERENCIAS_USUARIO
WHERE OID_APLICACION = (
      SELECT OID_APLICACION
      FROM GEPR_TAPLICACION
      WHERE COD_APLICACION = []pCOD_APLICACION)
AND COD_USUARIO = []pCOD_USUARIO
AND COD_FUNCIONALIDAD = []pCOD_FUNCIONALIDAD
AND NVL(COD_COMPONENTE, '-') = NVL([]pCOD_COMPONENTE, '-') 
AND NVL(COD_PROPRIEDAD, '-') = NVL([]pCOD_PROPRIEDAD, '-')
