MERGE INTO GEPR_TPREFERENCIAS_USUARIO Q1
using (SELECT APP.OID_APLICACION,
              []pCOD_USUARIO AS COD_USUARIO,
              []pCOD_FUNCIONALIDAD AS COD_FUNCIONALIDAD,
              []pCOD_COMPONENTE AS COD_COMPONENTE,
              []pCOD_PROPRIEDAD AS COD_PROPRIEDAD
         FROM GEPR_TAPLICACION APP
        WHERE APP.COD_APLICACION = []pCOD_APLICACION) Q2
ON (Q1.OID_APLICACION = Q2.OID_APLICACION 
   AND Q1.COD_USUARIO = Q2.COD_USUARIO 
   AND Q1.COD_FUNCIONALIDAD = Q2.COD_FUNCIONALIDAD 
   AND NVL(Q1.COD_COMPONENTE, '-') = NVL(Q2.COD_COMPONENTE, '-') 
   AND NVL(Q1.COD_PROPRIEDAD, '-') = NVL(Q2.COD_PROPRIEDAD, '-'))
WHEN MATCHED THEN
  UPDATE
     SET Q1.VALOR              = []pVALOR,
         Q1.VALOR_BINARIO      = []pVALOR_BINARIO,
         Q1.VALOR_BINARIO_TIPO = []pVALOR_BINARIO_TIPO,
         Q1.GMT_ACTUALIZACION  = FN_GMT_ZERO_###VERSION###
  

WHEN NOT MATCHED THEN
  INSERT
    (Q1.OID_PREFERENCIAS_USUARIO,
     Q1.OID_APLICACION,
     Q1.COD_USUARIO,
     Q1.COD_FUNCIONALIDAD,
     Q1.COD_COMPONENTE,
     Q1.COD_PROPRIEDAD,
     Q1.VALOR,
     Q1.VALOR_BINARIO,
     Q1.VALOR_BINARIO_TIPO,
     Q1.GMT_CREACION,
     Q1.GMT_ACTUALIZACION)
  VALUES
    (SYS_GUID(),
     Q2.OID_APLICACION,
    []pCOD_USUARIO,
	[]pCOD_FUNCIONALIDAD,
	[]pCOD_COMPONENTE,
	[]pCOD_PROPRIEDAD,
	[]pVALOR,
	[]pVALOR_BINARIO,
	[]pVALOR_BINARIO_TIPO,
    FN_GMT_ZERO_###VERSION###,
	FN_GMT_ZERO_###VERSION###)
     