--Insere GEPR_TPREFERENCIAS_USUARIO
INSERT INTO GEPR_TPREFERENCIAS_USUARIO
    (OID_PREFERENCIAS_USUARIO,
     OID_APLICACION,
     COD_USUARIO,
     COD_FUNCIONALIDAD,
     COD_COMPONENTE,
     COD_PROPRIEDAD,
     VALOR,
     VALOR_BINARIO,
     VALOR_BINARIO_TIPO,
     GMT_CREACION,
     GMT_ACTUALIZACION)
  VALUES
    (SYS_GUID(),
     (SELECT OID_APLICACION
      FROM GEPR_TAPLICACION
      WHERE COD_APLICACION = []pCOD_APLICACION),
    []pCOD_USUARIO,
    []pCOD_FUNCIONALIDAD,
    []pCOD_COMPONENTE,
    []pCOD_PROPRIEDAD,
    []pVALOR,
    []pVALOR_BINARIO,
    []pVALOR_BINARIO_TIPO,
    FN_GMT_ZERO_###VERSION###,
    FN_GMT_ZERO_###VERSION###)
