SELECT PU.OID_PREFERENCIAS_USUARIO,
       AP.COD_APLICACION,
       PU.COD_USUARIO,
       PU.COD_FUNCIONALIDAD,
       PU.COD_COMPONENTE,
       PU.COD_PROPRIEDAD,
       PU.VALOR,
       PU.VALOR_BINARIO,
       PU.VALOR_BINARIO_TIPO,
       PU.GMT_CREACION,
       PU.GMT_ACTUALIZACION
  FROM GEPR_TPREFERENCIAS_USUARIO PU
  INNER JOIN GEPR_TAPLICACION AP
        ON AP.OID_APLICACION = PU.OID_APLICACION