/*DASHBOARD MAE QUADRANTE4*/ 
WITH 
CLIENTE_MAE_DIVISA AS (
  SELECT
    CLIE.OID_CLIENTE,
    CLIE.COD_CLIENTE,
    CLIE.DES_CLIENTE,
    SECT.OID_SECTOR,
    SECT.COD_SECTOR,
    SECT.DES_SECTOR,    
    DIVI.OID_DIVISA,
    DIVI.COD_ISO_DIVISA,
    DIVI.DES_DIVISA
  FROM
    GEPR_TSECTOR SECT
    INNER JOIN GEPR_TTIPO_SECTOR TISE ON SECT.OID_TIPO_SECTOR = SECT.OID_TIPO_SECTOR
    INNER JOIN SAPR_TCUENTA CUEN ON SECT.OID_SECTOR = CUEN.OID_SECTOR
    INNER JOIN GEPR_TCLIENTE CLIE ON CUEN.OID_CLIENTE = CLIE.OID_CLIENTE
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION
    CROSS JOIN GEPR_TDIVISA DIVI
  WHERE 1=1
    {3} /*TIPOS SECTORES MAE*/
    {0} /*FILTRO DELEGACIÓN*/
    {1} /*FILTRO DIVISAS*/   
  GROUP BY
    CLIE.OID_CLIENTE,
    CLIE.COD_CLIENTE,
    CLIE.DES_CLIENTE,
    SECT.OID_SECTOR,
    SECT.COD_SECTOR,
    SECT.DES_SECTOR,    
    DIVI.OID_DIVISA,    
    DIVI.COD_ISO_DIVISA,
    DIVI.DES_DIVISA
),
SALDO_CERTIFICADO AS (
  SELECT
    MAX(CERT.FYH_CERTIFICADO) FYH_CERTIFICADO,
    CESE.OID_CUENTA_SALDO,
    SECT.OID_SECTOR,
    CLIE.OID_CLIENTE,    
    CESE.OID_DIVISA,
    CESE.OID_DENOMINACION,
    CESE.COD_NIVEL_DETALLE,
    CESE.COD_TIPO_EFECTIVO_TOTAL,
    CESE.BOL_DISPONIBLE,
    CESE.OID_UNIDAD_MEDIDA,
    CESE.OID_CALIDAD,
    SUM(NVL(CESE.NUM_IMPORTE, 0) + NVL(CESE.NUM_IMPORTE_ACUMULADO, 0)) NUM_IMPORTE    
  FROM
    SAPR_TCERTIFICADO CERT 
    INNER JOIN SAPR_TCERT_SALDO_EFECTIVO CESE ON CERT.OID_CERTIFICADO = CESE.OID_CERTIFICADO
    INNER JOIN SAPR_TCUENTA CUEN ON CESE.OID_CUENTA_SALDO = CUEN.OID_CUENTA    
    INNER JOIN GEPR_TCLIENTE CLIE ON CUEN.OID_CLIENTE = CLIE.OID_CLIENTE    
    INNER JOIN GEPR_TSUBCANAL SUCA ON CUEN.OID_SUBCANAL = SUCA.OID_SUBCANAL
    INNER JOIN GEPR_TCANAL CANA ON SUCA.OID_CANAL = CANA.OID_CANAL 
    INNER JOIN GEPR_TDIVISA DIVI ON CESE.OID_DIVISA = DIVI.OID_DIVISA
    INNER JOIN GEPR_TSECTOR SECT ON CUEN.OID_SECTOR = SECT.OID_SECTOR
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION
  WHERE 1=1
    {4} /*FILTRO PARÁMETRO IAC GÉNESIS: CanalesValoresValidadosMAE*/
    {2} /*SECTORES*/
    {1} /*FILTRO DIVISAS*/    
    {0} /*FILTRO DELEGACIÓN*/
  GROUP BY
    CESE.OID_CUENTA_SALDO,
    SECT.OID_SECTOR,
    CLIE.OID_CLIENTE,    
    CESE.OID_DIVISA,
    CESE.OID_DENOMINACION,
    CESE.COD_NIVEL_DETALLE,
    CESE.COD_TIPO_EFECTIVO_TOTAL,
    CESE.BOL_DISPONIBLE,
    CESE.OID_UNIDAD_MEDIDA,
    CESE.OID_CALIDAD    
),
SALDO_VALIDADO AS (
  SELECT
    SECT.OID_SECTOR,
    CLIE.OID_CLIENTE,
    TREF.OID_DIVISA,
    SUM(NVL(TREF.NUM_IMPORTE, 0)) NUM_IMPORTE
  FROM
    SAPR_TDOCUMENTO DOCU
    INNER JOIN SAPR_TTRANSACCION_EFECTIVO TREF ON DOCU.OID_DOCUMENTO = TREF.OID_DOCUMENTO
    INNER JOIN SAPR_TCUENTA CUEN ON TREF.OID_CUENTA_SALDO = CUEN.OID_CUENTA
    INNER JOIN GEPR_TCLIENTE CLIE ON CUEN.OID_CLIENTE = CLIE.OID_CLIENTE
    INNER JOIN GEPR_TSUBCANAL SUCA ON CUEN.OID_SUBCANAL = SUCA.OID_SUBCANAL
    INNER JOIN GEPR_TCANAL CANA ON SUCA.OID_CANAL = CANA.OID_CANAL     
    INNER JOIN GEPR_TDIVISA DIVI ON TREF.OID_DIVISA = DIVI.OID_DIVISA
    INNER JOIN GEPR_TSECTOR SECT ON CUEN.OID_SECTOR = SECT.OID_SECTOR
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION    
    LEFT OUTER JOIN SAPR_TCERTIFICADO CERT ON TREF.OID_CERTIFICADO = CERT.OID_CERTIFICADO AND CERT.COD_ESTADO <> 'DE'
  WHERE 1=1
    {4} /*FILTRO PARÁMETRO IAC GÉNESIS: CanalesValoresValidadosMAE*/
    {2} /*SECTORES*/
    {1} /*FILTRO DIVISAS*/    
    {0} /*FILTRO DELEGACIÓN*/     
  GROUP BY
    SECT.OID_SECTOR,
    CLIE.OID_CLIENTE,
    TREF.OID_DIVISA
),
SALDO_DEPOSITADO AS (
  SELECT
    SECT.OID_SECTOR,
    CLIE.OID_CLIENTE,
    TREF.OID_DIVISA,
    SUM(NVL(TREF.NUM_IMPORTE, 0)) NUM_IMPORTE
  FROM
    SAPR_TDOCUMENTO DOCU
    INNER JOIN SAPR_TTRANSACCION_EFECTIVO TREF ON DOCU.OID_DOCUMENTO = TREF.OID_DOCUMENTO
    INNER JOIN SAPR_TCUENTA CUEN ON TREF.OID_CUENTA_SALDO = CUEN.OID_CUENTA
    INNER JOIN GEPR_TCLIENTE CLIE ON CUEN.OID_CLIENTE = CLIE.OID_CLIENTE
    INNER JOIN GEPR_TSUBCANAL SUCA ON CUEN.OID_SUBCANAL = SUCA.OID_SUBCANAL
    INNER JOIN GEPR_TCANAL CANA ON SUCA.OID_CANAL = CANA.OID_CANAL     
    INNER JOIN GEPR_TDIVISA DIVI ON TREF.OID_DIVISA = DIVI.OID_DIVISA
    INNER JOIN GEPR_TSECTOR SECT ON CUEN.OID_SECTOR = SECT.OID_SECTOR
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION 
    LEFT OUTER JOIN SAPR_TCERTIFICADO CERT ON TREF.OID_CERTIFICADO = CERT.OID_CERTIFICADO AND CERT.COD_ESTADO <> 'DE'
  WHERE 1=1
    {5} /*FILTRO PARÁMETRO IAC GÉNESIS: CanalesValoresDepositadosMAE*/
    {2} /*SECTORES*/
    {1} /*FILTRO DIVISAS*/    
    {0} /*FILTRO DELEGACIÓN*/         
  GROUP BY
    SECT.OID_SECTOR,
    CLIE.OID_CLIENTE,
    TREF.OID_DIVISA
),
SHIPOUT AS (
  SELECT
    CLIE.OID_CLIENTE,
    SECT.OID_SECTOR,
    EFDO.OID_DIVISA,
    MAX(DOCU.FYH_GESTION) FECHA_ULTIMO_SHIPOUT,
    SUM(EFDO.NUM_IMPORTE) IMPORTE_ULTIMO_SHIPOUT,
	DELE.OID_DELEGACION
  FROM
    SAPR_TDOCUMENTO DOCU
    INNER JOIN SAPR_TFORMULARIO FORM ON DOCU.OID_FORMULARIO = FORM.OID_FORMULARIO
    INNER JOIN SAPR_TEFECTIVOXDOCUMENTO EFDO ON DOCU.OID_DOCUMENTO = EFDO.OID_DOCUMENTO
    INNER JOIN GEPR_TDIVISA DIVI ON EFDO.OID_DIVISA = DIVI.OID_DIVISA  
    INNER JOIN SAPR_TCUENTA CUEN ON DOCU.OID_CUENTA_SALDO_ORIGEN = CUEN.OID_CUENTA
    INNER JOIN GEPR_TSECTOR SECT ON CUEN.OID_SECTOR = SECT.OID_SECTOR
    INNER JOIN GEPR_TTIPO_SECTOR TISE ON SECT.OID_TIPO_SECTOR = SECT.OID_TIPO_SECTOR
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION  
    INNER JOIN GEPR_TSUBCANAL SUCA ON CUEN.OID_SUBCANAL = SUCA.OID_SUBCANAL
    INNER JOIN GEPR_TCANAL CANA ON SUCA.OID_CANAL = CANA.OID_CANAL 
    INNER JOIN GEPR_TCLIENTE CLIE ON CUEN.OID_CLIENTE = CLIE.OID_CLIENTE  
  WHERE 1=1
    {3} /*TIPOS SECTORES MAE*/
    {2} /*SECTORES*/
    {0} /*FILTRO DELEGACIÓN*/
    {1} /*FILTRO DIVISAS*/ 
    {4} /*FILTRO PARÁMETRO IAC GÉNESIS: CanalesValoresValidadosMAE*/
    {6} /*FILTRO PARÁMETRO IAC GÉNESIS: CodigosFormulariosShipOutMAE*/
  GROUP BY
    CLIE.OID_CLIENTE,
    SECT.OID_SECTOR,
    EFDO.OID_DIVISA,
	DELE.OID_DELEGACION
)
SELECT
  CMDI.OID_CLIENTE,
  CMDI.COD_CLIENTE,
  CMDI.DES_CLIENTE,
  CMDI.OID_SECTOR,
  CMDI.COD_SECTOR,
  CMDI.DES_SECTOR,
  CMDI.OID_DIVISA,
  CMDI.COD_ISO_DIVISA,
  CMDI.DES_DIVISA,
  SUM(NVL(SACE.NUM_IMPORTE, 0)) IMPORTE_CERTIFICADO,
  NVL(SAVA.NUM_IMPORTE, 0) IMPORTE_VALIDADO,
  NVL(SADE.NUM_IMPORTE, 0)  IMPORTE_DEPOSITADO,
  FN_GMT_DELEGACION_###VERSION###(SHIP.OID_DELEGACION, SHIP.FECHA_ULTIMO_SHIPOUT) FECHA_ULTIMO_SHIPOUT,
  SHIP.IMPORTE_ULTIMO_SHIPOUT
FROM
  CLIENTE_MAE_DIVISA CMDI
  LEFT OUTER JOIN SALDO_CERTIFICADO SACE ON CMDI.OID_CLIENTE = SACE.OID_CLIENTE AND
                                            CMDI.OID_SECTOR = SACE.OID_SECTOR AND
                                            CMDI.OID_DIVISA = SACE.OID_DIVISA
  LEFT OUTER JOIN SALDO_VALIDADO SAVA ON CMDI.OID_CLIENTE = SAVA.OID_CLIENTE AND
                                         CMDI.OID_SECTOR = SAVA.OID_SECTOR AND
                                         CMDI.OID_DIVISA = SAVA.OID_DIVISA
  LEFT OUTER JOIN SALDO_DEPOSITADO SADE ON CMDI.OID_CLIENTE = SADE.OID_CLIENTE AND
                                           CMDI.OID_SECTOR = SADE.OID_SECTOR AND
                                           CMDI.OID_DIVISA = SADE.OID_DIVISA  
  LEFT OUTER JOIN SHIPOUT SHIP ON CMDI.OID_CLIENTE = SHIP.OID_CLIENTE AND
                                  CMDI.OID_SECTOR = SHIP.OID_SECTOR AND
                                  CMDI.OID_DIVISA = SHIP.OID_DIVISA
GROUP BY
  CMDI.OID_CLIENTE,
  CMDI.COD_CLIENTE,
  CMDI.DES_CLIENTE,
  CMDI.OID_SECTOR,
  CMDI.COD_SECTOR,
  CMDI.DES_SECTOR,
  CMDI.OID_DIVISA,
  CMDI.COD_ISO_DIVISA,
  CMDI.DES_DIVISA,
  NVL(SAVA.NUM_IMPORTE, 0),
  NVL(SADE.NUM_IMPORTE, 0),
  SHIP.FECHA_ULTIMO_SHIPOUT,
  SHIP.IMPORTE_ULTIMO_SHIPOUT,
  SHIP.OID_DELEGACION
HAVING
  SUM(NVL(SACE.NUM_IMPORTE, 0)) <> 0 OR                           
  NVL(SAVA.NUM_IMPORTE, 0) <> 0 OR
  NVL(SADE.NUM_IMPORTE, 0) <> 0    
  
