/*DASHBOARD MAE QUADRANTE1*/
WITH 
SALDO_CERTIFICADO AS (
  SELECT
    MAX(CERT.FYH_CERTIFICADO) FYH_CERTIFICADO,
    CESE.OID_CUENTA_SALDO,
    CLIE.COD_CLIENTE CODIGO,
    CLIE.DES_CLIENTE CLIENTE,    
    CESE.OID_DIVISA,
    DIVI.COD_ISO_DIVISA,
    DIVI.DES_DIVISA,
    CESE.OID_DENOMINACION,
    CESE.COD_NIVEL_DETALLE,
    CESE.COD_TIPO_EFECTIVO_TOTAL,
    CESE.BOL_DISPONIBLE,
    CESE.OID_UNIDAD_MEDIDA,
    CESE.OID_CALIDAD,
    SUM(NVL(CESE.NUM_IMPORTE, 0) + NVL(CESE.NUM_IMPORTE_ACUMULADO, 0)) NUM_IMPORTE    
  FROM
    SAPR_TCERTIFICADO CERT 
    INNER JOIN SAPR_TCERT_SALDO_EFECTIVO CESE ON CERT.OID_CERTIFICADO = CESE.OID_CERTIFICADO
    INNER JOIN SAPR_TCUENTA CUEN ON CESE.OID_CUENTA_SALDO = CUEN.OID_CUENTA    
    INNER JOIN GEPR_TCLIENTE CLIE ON CUEN.OID_CLIENTE = CLIE.OID_CLIENTE    
    INNER JOIN GEPR_TSUBCANAL SUCA ON CUEN.OID_SUBCANAL = SUCA.OID_SUBCANAL
    INNER JOIN GEPR_TCANAL CANA ON SUCA.OID_CANAL = CANA.OID_CANAL 
    INNER JOIN GEPR_TDIVISA DIVI ON CESE.OID_DIVISA = DIVI.OID_DIVISA
    INNER JOIN GEPR_TSECTOR SECT ON CUEN.OID_SECTOR = SECT.OID_SECTOR
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION
  WHERE CERT.COD_ESTADO = 'DE'
     {3} /*-- FILTRO PARÁMETRO IAC GÉNESIS: CanalesValoresValidadosMAE*/
     {2} /*-- FILTRO SECTORES*/
     {1} /*-- FILTRO DIVISAS    */
     {0} /*-- FILTRO DELEGACIÓN*/
  GROUP BY
    CESE.OID_CUENTA_SALDO,
    CLIE.COD_CLIENTE,
    CLIE.DES_CLIENTE,        
    CESE.OID_DIVISA,
    DIVI.COD_ISO_DIVISA,
    DIVI.DES_DIVISA,
    CESE.OID_DENOMINACION,
    CESE.COD_NIVEL_DETALLE,
    CESE.COD_TIPO_EFECTIVO_TOTAL,
    CESE.BOL_DISPONIBLE,
    CESE.OID_UNIDAD_MEDIDA,
    CESE.OID_CALIDAD    
),
SALDO_VALIDADO AS (
  SELECT
    TREF.OID_CUENTA_SALDO,
    CLIE.COD_CLIENTE CODIGO,
    CLIE.DES_CLIENTE CLIENTE,        
    TREF.OID_DIVISA,
    DIVI.COD_ISO_DIVISA,
    DIVI.DES_DIVISA,    
    SUM(NVL(TREF.NUM_IMPORTE, 0)) NUM_IMPORTE
  FROM
    SAPR_TDOCUMENTO DOCU
    INNER JOIN SAPR_TTRANSACCION_EFECTIVO TREF ON DOCU.OID_DOCUMENTO = TREF.OID_DOCUMENTO
    INNER JOIN SAPR_TCUENTA CUEN ON TREF.OID_CUENTA_SALDO = CUEN.OID_CUENTA
    INNER JOIN GEPR_TCLIENTE CLIE ON CUEN.OID_CLIENTE = CLIE.OID_CLIENTE
    INNER JOIN GEPR_TSUBCANAL SUCA ON CUEN.OID_SUBCANAL = SUCA.OID_SUBCANAL
    INNER JOIN GEPR_TCANAL CANA ON SUCA.OID_CANAL = CANA.OID_CANAL     
    INNER JOIN GEPR_TDIVISA DIVI ON TREF.OID_DIVISA = DIVI.OID_DIVISA
    INNER JOIN GEPR_TSECTOR SECT ON CUEN.OID_SECTOR = SECT.OID_SECTOR
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION    
    LEFT OUTER JOIN SAPR_TCERTIFICADO CERT ON TREF.OID_CERTIFICADO = CERT.OID_CERTIFICADO AND CERT.COD_ESTADO <> 'DE'
  WHERE 1 = 1     
     {3} /*-- FILTRO PARÁMETRO IAC GÉNESIS: CanalesValoresValidadosMAE*/
     {2} /*-- FILTRO SECTORES*/
     {1} /*-- FILTRO DIVISAS    */
     {0} /*-- FILTRO DELEGACIÓN*/
  GROUP BY
    TREF.OID_CUENTA_SALDO,
    CLIE.COD_CLIENTE,
    CLIE.DES_CLIENTE,        
    TREF.OID_DIVISA,
    DIVI.COD_ISO_DIVISA,
    DIVI.DES_DIVISA
),
SALDO_DEPOSITADO AS (
  SELECT
    TREF.OID_CUENTA_SALDO,
    CLIE.COD_CLIENTE CODIGO,
    CLIE.DES_CLIENTE CLIENTE,        
    TREF.OID_DIVISA,
    DIVI.COD_ISO_DIVISA,
    DIVI.DES_DIVISA,
    SUM(NVL(TREF.NUM_IMPORTE, 0)) NUM_IMPORTE
  FROM
    SAPR_TDOCUMENTO DOCU
    INNER JOIN SAPR_TTRANSACCION_EFECTIVO TREF ON DOCU.OID_DOCUMENTO = TREF.OID_DOCUMENTO
    INNER JOIN SAPR_TCUENTA CUEN ON TREF.OID_CUENTA_SALDO = CUEN.OID_CUENTA
    INNER JOIN GEPR_TCLIENTE CLIE ON CUEN.OID_CLIENTE = CLIE.OID_CLIENTE
    INNER JOIN GEPR_TSUBCANAL SUCA ON CUEN.OID_SUBCANAL = SUCA.OID_SUBCANAL
    INNER JOIN GEPR_TCANAL CANA ON SUCA.OID_CANAL = CANA.OID_CANAL     
    INNER JOIN GEPR_TDIVISA DIVI ON TREF.OID_DIVISA = DIVI.OID_DIVISA
    INNER JOIN GEPR_TSECTOR SECT ON CUEN.OID_SECTOR = SECT.OID_SECTOR
    INNER JOIN GEPR_TPLANTA PLANT ON SECT.OID_PLANTA = PLANT.OID_PLANTA
    INNER JOIN GEPR_TDELEGACION DELE ON PLANT.OID_DELEGACION = DELE.OID_DELEGACION 
    LEFT OUTER JOIN SAPR_TCERTIFICADO CERT ON TREF.OID_CERTIFICADO = CERT.OID_CERTIFICADO AND CERT.COD_ESTADO <> 'DE'
  WHERE 1 = 1     
     {4} /*-- FILTRO PARÁMETRO IAC GÉNESIS: CanalesValoresDepositadosMAE*/
     {2} /*-- FILTRO SECTORES*/
     {1} /*-- FILTRO DIVISAS    */
     {0} /*-- FILTRO DELEGACIÓN*/
  GROUP BY
    TREF.OID_CUENTA_SALDO,
    CLIE.COD_CLIENTE,
    CLIE.DES_CLIENTE,        
    TREF.OID_DIVISA,
    DIVI.COD_ISO_DIVISA,
    DIVI.DES_DIVISA
)
SELECT
  'SALDO_CERTIFICADO' TIPO_SALDO,
  COD_ISO_DIVISA,
  DES_DIVISA,
  SUM(NUM_IMPORTE) NUM_IMPORTE
FROM
  SALDO_CERTIFICADO
GROUP BY 
  'SALDO_CERTIFICADO',
  COD_ISO_DIVISA,
  DES_DIVISA
UNION ALL
SELECT
  'SALDO_VALIDADO' TIPO_SALDO,
  COD_ISO_DIVISA,
  DES_DIVISA,
  SUM(NUM_IMPORTE) NUM_IMPORTE
FROM
  SALDO_VALIDADO
GROUP BY 
  'SALDO_VALIDADO',
  COD_ISO_DIVISA,
  DES_DIVISA
UNION ALL
SELECT
  'SALDO_DEPOSITADO' TIPO_SALDO,
  COD_ISO_DIVISA,
  DES_DIVISA,
  SUM(NUM_IMPORTE) NUM_IMPORTE
FROM
  SALDO_DEPOSITADO
GROUP BY 
  'SALDO_DEPOSITADO',
  COD_ISO_DIVISA,
  DES_DIVISA    