SELECT C.OID_CLIENTE FROM GEPR_TCLIENTE C WHERE 
C.OID_CLIENTE IN([]OID_CLIENTE)
AND
(
C.BOL_TOTALIZADOR_SALDO =1
OR (C.OID_CLIENTE IN(SELECT S.OID_CLIENTE FROM GEPR_TSUBCLIENTE S WHERE S.BOL_TOTALIZADOR_SALDO =1 AND S.OID_CLIENTE IN([]OID_CLIENTE)))
OR (C.OID_CLIENTE IN (SELECT S1.OID_CLIENTE FROM GEPR_TSUBCLIENTE S1 
   INNER JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_SUBCLIENTE = S1.OID_SUBCLIENTE
   WHERE PS.BOL_TOTALIZADOR_SALDO =1 AND S1.OID_CLIENTE IN([]OID_CLIENTE))
   )
)
