SELECT C.OID_CLIENTE, 
	   C.COD_CLIENTE, 
	   C.DES_CLIENTE, 
	   C.BOL_VIGENTE, 
	   C.COD_USUARIO, 
	   C.FYH_ACTUALIZACION, 
	   C.BOL_ENVIADO_SALDOS,
	   C.OID_TIPO_CLIENTE,
	   C.COD_MIGRACION,
	   C.BOL_TOTALIZADOR_SALDO
FROM GEPR_TCLIENTE C
INNER JOIN GEPR_TSUBCLIENTE SC  ON SC.OID_CLIENTE = C.OID_CLIENTE
WHERE SC.OID_SUBCLIENTE = []OID_SUBCLIENTE
