SELECT C.OID_CLIENTE, 
	   C.COD_CLIENTE, 
	   C.DES_CLIENTE, 
	   C.BOL_VIGENTE, 
	   C.COD_USUARIO, 
	   C.FYH_ACTUALIZACION, 
	   C.BOL_ENVIADO_SALDOS,
	   C.OID_TIPO_CLIENTE,COD_MIGRACION,
	   C.BOL_TOTALIZADOR_SALDO,
	   C.BOL_SALDO_HISTORICO,
	   C.COD_FECHA_SALDO_HISTORICO
FROM GEPR_TCLIENTE C
WHERE C.COD_CLIENTE = []COD_CLIENTE
