SELECT C.OID_CLIENTE, 
	   C.COD_CLIENTE, 
	   C.DES_CLIENTE, 
	   C.BOL_VIGENTE, 
	   C.COD_USUARIO, 
	   C.FYH_ACTUALIZACION, 
	   C.BOL_ENVIADO_SALDOS,
	   C.OID_TIPO_CLIENTE,COD_MIGRACION,
	   C.BOL_TOTALIZADOR_SALDO
FROM GEPR_TCLIENTE C
 {0}
WHERE 1 = 1
 {1}
