UPDATE GEPR_TCANAL
SET DES_CANAL = []DES_CANAL, OBS_CANAL = []OBS_CANAL, BOL_VIGENTE = []BOL_VIGENTE, COD_USUARIO = []COD_USUARIO, FYH_ACTUALIZACION = []FYH_ACTUALIZACION 
WHERE COD_CANAL = []COD_CANAL
