INSERT INTO GEPR_TCANAL (OID_CANAL, COD_CANAL, DES_CANAL, OBS_CANAL, BOL_VIGENTE, COD_USUARIO, FYH_ACTUALIZACION) 
VALUES 
([]OID_CANAL, []COD_CANAL, []DES_CANAL, []OBS_CANAL, []BOL_VIGENTE, []COD_USUARIO, []FYH_ACTUALIZACION)