SELECT 
  INV.OID_INVENTARIO
  ,INV.COD_INVENTARIO
  ,FN_GMT_DELEGACION_###VERSION###(DEL.OID_DELEGACION, INV.GMT_CREACION) AS GMT_CREACION
  ,DEL.DES_DELEGACION
  ,PLA.DES_PLANTA
  ,SEC.DES_SECTOR
  ,DEL.OID_DELEGACION
FROM SAPR_TINVENTARIO INV
INNER JOIN GEPR_TSECTOR SEC
      ON SEC.OID_SECTOR = INV.OID_SECTOR
INNER JOIN GEPR_TPLANTA PLA
      ON PLA.OID_PLANTA = SEC.OID_PLANTA      
INNER JOIN GEPR_TDELEGACION DEL
      ON DEL.OID_DELEGACION = PLA.OID_DELEGACION