'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusquedaParametros

    '''<summary>
    '''hiddenCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenCodigo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenCodigoForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenCodigoForm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanelGeral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGeral As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblSubTitulosCriteriosBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosCriteriosBusqueda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAplicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAplicacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelAplicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAplicacion As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlAplicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAplicacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCodigoParametro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoParametro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCodigoParametro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoParametro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNivel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelNivel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNivel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblDescricaoAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescricaoAgrupacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescricaoAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoAgrupacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblParametros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParametros As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGrid As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ProsegurGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProsegurGridView1 As Global.Prosegur.Web.ProsegurGridView

    '''<summary>
    '''UpdatePanelGridSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGridSemRegistro As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSemRegistro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updForm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSubTitulosCriteriosBusquedaForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosCriteriosBusquedaForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAplicacionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAplicacionForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAplicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAplicacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTipoDado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoDado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblValueTipoDado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValueTipoDado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObligatorio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblValueObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValueObligatorio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNivelForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNivelForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNivel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgrupacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelDdlAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDdlAgrupacion As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgrupacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvDdlAgrupacionObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDdlAgrupacionObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblCodParametro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodParametro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCodParametro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodParametro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDescripcionCorto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcionCorto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTxtDescripcionCorto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTxtDescripcionCorto As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDescripcionCorto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcionCorto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvTxtDescripcionCortoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTxtDescripcionCortoObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblDescripcionLarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcionLarga As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTxtDescripcionLarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTxtDescripcionLarga As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDescripcionLarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcionLarga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvTxtDescripcionLargaObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTxtDescripcionLargaObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblTipoComponent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoComponent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTipoComponent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoComponent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrden As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTxtOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTxtOrden As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrden As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvTxtOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTxtOrden As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnlOpciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOpciones As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSubTituloOpciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTituloOpciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updGridForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updGridForm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ProsegurGridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProsegurGridView2 As Global.Prosegur.Web.ProsegurGridView

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnABMAgrapaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnABMAgrapaciones As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConsomeParametroOpcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsomeParametroOpcion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBajaOpcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBajaOpcion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.IAC.Web.Master.Master
        Get
            Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.IAC.Web.Master.Master)
        End Get
    End Property
End Class
