'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusquedaDelegaciones
    
    '''<summary>
    '''hiddenCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenCodigo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''UpdatePanelGeral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGeral As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblSubTitulosCriteriosBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosCriteriosBusqueda As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCodDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodDelegaciones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCodDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodDelegaciones As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDesDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesDelegaciones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDesDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesDelegaciones As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCodigoPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoPais As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPais As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''csvPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvPais As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblVigente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVigente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkVigente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVigente As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblSubTitulosDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosDelegaciones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanelGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGrid As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''GdvResultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GdvResultado As Global.Prosegur.Web.ProsegurGridView
    
    '''<summary>
    '''UpdatePanelGridSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGridSemRegistro As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSemRegistro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemRegistro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''updForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updForm As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnForm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblTituloDelegacione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloDelegacione As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPais As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlPaisForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPaisForm As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''csvPaisForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvPaisForm As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblVigenteForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVigenteForm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkVigenteForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVigenteForm As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblCodigoDelegacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoDelegacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCodigoDelegacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoDelegacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''csvCodigoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCodigoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''csvCodigoExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCodigoExistente As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblDescricaoDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescricaoDelegaciones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDescricaoDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoDelegaciones As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''csvDescricaoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDescricaoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoAjeno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoAjeno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDesCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesCodigoAjeno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDesCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesCodigoAjeno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAltaAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAltaAjeno As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblConfiguracionesRegionales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfiguracionesRegionales As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGmtMinutos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGmtMinutos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGmtMinutos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGmtMinutos As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''csvGmtMinutosObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvGmtMinutosObrigatorio As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblCantidadMinAjuste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCantidadMinAjuste As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCantidadMinAjuste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCantidadMinAjuste As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''csvCantiAjuste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCantiAjuste As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblFechaVeranoInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaVeranoInicio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFechaVeranoInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaVeranoInicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''csvFechaVeranoInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFechaVeranoInicio As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblFechaVeranoFim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaVeranoFim As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFechaVeranoFim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaVeranoFim As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''csvFechaVeranoFim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFechaVeranoFim As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''csvFechaVeranoInicioInvalida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFechaVeranoInicioInvalida As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblZona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZona As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtZona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZona As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''csvZona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvZona As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblTotasDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotasDelegaciones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkTodasDelegaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTodasDelegaciones As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblFaturacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFaturacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divAddPtoServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddPtoServ As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''updUcClientesPtoServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updUcClientesPtoServ As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phClientesPtoServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phClientesPtoServ As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''btnAddPtoServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPtoServ As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''csvAddPtoServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvAddPtoServ As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid As Global.DevExpress.Web.ASPxGridView.ASPxGridView
    
    '''<summary>
    '''upDatosBanc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDatosBanc As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phDatosBanc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phDatosBanc As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''btnNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGrabar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnBajaConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBajaConfirm As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCamposExtras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCamposExtras As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConsomeTotalizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsomeTotalizador As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnBaja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBaja As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConsomeCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsomeCodigoAjeno As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAlertaNao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlertaNao As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.IAC.Web.Master.Master
        Get
            Return CType(MyBase.Master,Prosegur.[Global].GesEfectivo.IAC.Web.Master.Master)
        End Get
    End Property
End Class
