'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusquedaProcesos

    '''<summary>
    '''hiddenCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenCodigo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanelGeral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGeral As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTitulosBusquedaProcesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulosBusquedaProcesos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updUcClienteUc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updUcClienteUc As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''phCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phCliente As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblCanal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCanal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstCanal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCanal As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblSubCanal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubCanal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstSubCanais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSubCanais As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblDelegacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDelegacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstDelegacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDelegacion As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProducto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstProducto As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblVigente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVigente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkVigente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVigente As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSubTitulosBusquedaProcesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosBusquedaProcesos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGrid As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ProsegurGridViewProcesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProsegurGridViewProcesso As Global.Prosegur.Web.ProsegurGridView

    '''<summary>
    '''UpdatePanelGridSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGridSemRegistro As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSemRegistro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updForm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTituloProcesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloProcesos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updUcClientForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updUcClientForm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''phClienteForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phClienteForm As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblCanalForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCanalForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstCanalForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCanalForm As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblSubCanalForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubCanalForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelSubCanal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelSubCanal As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstSubCanaisForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSubCanaisForm As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''csvSubCanalObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvSubCanalObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblDelegacionForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDelegacionForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDelegacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDelegacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDescricaoProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescricaoProceso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDescricao As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDescricaoProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoProceso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvDescricaoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDescricaoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''csvDescripcionExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDescripcionExistente As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblProductoForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductoForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelProduto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelProduto As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProducto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvProductoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvProductoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblModalidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelModalidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelModalidad As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlModalidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlModalidad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvModalidadObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvModalidadObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblIACParcial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIACParcial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelIACParcial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelIACParcial As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlIACParcial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIACParcial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblIACBulto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIACBulto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelIACBulto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelIACBulto As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlIACBulto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIACBulto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblIACRemesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIACRemesa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelIACRemesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelIACRemesa As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlIACRemesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIACRemesa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''upUcClienteFatu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upUcClienteFatu As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''phClienteFatu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phClienteFatu As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''vigenteLinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vigenteLinha As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblVigenteForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVigenteForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkVigenteForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVigenteForm As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''updForm2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updForm2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnForm2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnForm2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanelInformacionDeclarado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelInformacionDeclarado As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblSubTitulosInformacionDelDeclarado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosInformacionDelDeclarado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''csvInformacioDeclaradoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvInformacioDeclaradoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rdbPorAgrupaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbPorAgrupaciones As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbPorMedioPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbPorMedioPago As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''pnlAgrupacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAgrupacao As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSubTitulosAgrupaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosAgrupaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Td1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanelAgrupacionesPossibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAgrupacionesPossibles As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstAgrupacionesPosibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAgrupacionesPosibles As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''imgBtnAgrupacionesIncluirTodas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnAgrupacionesIncluirTodas As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnAgrupacionesIncluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnAgrupacionesIncluir As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnAgrupacionesExcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnAgrupacionesExcluir As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnAgrupacionesExcluirTodas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnAgrupacionesExcluirTodas As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''UpdatePanelAgrupacionCompoenProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAgrupacionCompoenProceso As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstAgrupacionesCompoenProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAgrupacionesCompoenProceso As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''csvAgrupacionesCompoenProcesoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvAgrupacionesCompoenProcesoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''pnlMediosPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMediosPago As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSubTitulosMediosPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosMediosPago As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTreeView As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TdTreeViewDivisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdTreeViewDivisa As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TrvDivisas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrvDivisas As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''imgBtnIncluirTreeview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnIncluirTreeview As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnExcluirTreeview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnExcluirTreeview As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''TrvProcesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrvProcesos As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''lblNota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNota As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''csvTrvProcesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTrvProcesos As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblSubTitulosModoContaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosModoContaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkContarChequeTotales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContarChequeTotales As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkContarTicketTotales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContarTicketTotales As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkContarOtrosValoresTotales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContarOtrosValoresTotales As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkContarTarjetaTotales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContarTarjetaTotales As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblObservaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtObservaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservaciones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTerminoMedioPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTerminoMedioPago As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTolerancia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTolerancia As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBajaConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBajaConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBaja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBaja As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConsomeMediosPagos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsomeMediosPagos As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConsomeTerminos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsomeTerminos As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.IAC.Web.Master.Master
        Get
            Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.IAC.Web.Master.Master)
        End Get
    End Property
End Class
