'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MantenimientoAgrupaciones

    '''<summary>
    '''lblTituloAgrupaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloAgrupaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoAgrupacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelCodigo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtCodigoAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoAgrupacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvCodigoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCodigoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''csvCodigoAgrupacionExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCodigoAgrupacionExistente As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''UpdateProgressCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressCodigo As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''lblDescricaoAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescricaoAgrupacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDescricao As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDescricaoAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoAgrupacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvDescricaoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDescricaoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''csvDescripcionExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDescripcionExistente As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''UpdateProgressDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressDescricao As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''lblObservaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtObservaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservaciones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVigente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVigente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkVigente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVigente As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSubTitulosAgrupaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosAgrupaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTreeView As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TdTreeViewDivisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdTreeViewDivisa As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TrvDivisas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrvDivisas As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''TdBtnInEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdBtnInEx As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''imgBtnIncluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnIncluir As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnExcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnExcluir As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''TrvAgrupaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrvAgrupaciones As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''UpdateProgressTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressTreeView As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UpdatePanelCsvTreeViewAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelCsvTreeViewAgrupacion As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''csvTrvAgrupaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTrvAgrupaciones As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''pnlSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSemRegistro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelAcaoPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAcaoPagina As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGrabar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabar As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVolver As Global.Prosegur.Web.Botao

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.IAC.Web.Principal
        Get
            Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.IAC.Web.Principal)
        End Get
    End Property
End Class
