'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MantenimientoParametro

    '''<summary>
    '''UpdatePanelGeral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGeral As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblSubTitulosCriteriosBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTitulosCriteriosBusqueda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAplicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAplicacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAplicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAplicacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTipoDado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoDado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblValueTipoDado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValueTipoDado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObligatorio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblValueObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValueObligatorio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNivel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNivel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgrupacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelDdlAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDdlAgrupacion As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlAgrupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgrupacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvDdlAgrupacionObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDdlAgrupacionObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblCodParametro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodParametro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCodParametro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodParametro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDescripcionCorto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcionCorto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTxtDescripcionCorto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTxtDescripcionCorto As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDescripcionCorto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcionCorto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvTxtDescripcionCortoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTxtDescripcionCortoObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblDescripcionLarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcionLarga As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTxtDescripcionLarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTxtDescripcionLarga As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDescripcionLarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcionLarga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvTxtDescripcionLargaObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTxtDescripcionLargaObrigatorio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblTipoComponent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoComponent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTipoComponent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoComponent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrden As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTxtOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTxtOrden As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrden As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvTxtOrden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTxtOrden As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnlOpciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOpciones As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSubTituloOpciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTituloOpciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGrid As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ProsegurGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProsegurGridView1 As Global.Prosegur.Web.ProsegurGridView

    '''<summary>
    '''pnlSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSemRegistro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSemRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAltaOpcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAltaOpcion As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnBajaOpcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBajaOpcion As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnModificacionOpcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModificacionOpcion As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnConsultarOpcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultarOpcion As Global.Prosegur.Web.Botao

    '''<summary>
    '''UpdatePanelAcaoPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAcaoPagina As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGrabar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabar As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVolver As Global.Prosegur.Web.Botao

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.IAC.Web.Principal
        Get
            Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.IAC.Web.Principal)
        End Get
    End Property
End Class
