'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MantenimientoComponente

    '''<summary>
    '''lblTituloComponente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloComponente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updatePanelFuncion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanelFuncion As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvCodigoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCodigoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''csvCodigoUnico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCodigoUnico As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblFuncion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuncion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFuncion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFuncion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvFuncionObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvFuncionObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''updatePanelTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanelTipo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvTipoObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTipoObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''updatePanelDivisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanelDivisa As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlDivisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDivisa As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDivisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivisa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDivisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDivisa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvDivisaObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDivisaObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''pnlDenominacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDenominacion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDenominacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDenominacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updatePanelDenominacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanelDenominacion As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlDenominacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDenominacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvDenominacionObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDenominacionObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''pnlMediosPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMediosPago As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMediosPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMediosPago As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTreeView As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TdTreeViewDivisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdTreeViewDivisa As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TrvDivisas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrvDivisas As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''imgBtnIncluirTreeview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnIncluirTreeview As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBtnExcluirTreeview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnExcluirTreeview As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''TrvMediosPagosSelecionados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrvMediosPagosSelecionados As Global.System.Web.UI.WebControls.TreeView

    '''<summary>
    '''csvTrvMediosPagosSelecionados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTrvMediosPagosSelecionados As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''csvTrvMedioPagoUnico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTrvMedioPagoUnico As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''UpdatePanelAcaoPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAcaoPagina As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGrabar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLimpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpiar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.IAC.Web.Master.MasterModal
        Get
            Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.IAC.Web.Master.MasterModal)
        End Get
    End Property
End Class
