'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MantenimientoPuntoServicio

    '''<summary>
    '''lblTituloPuntoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloPuntoServicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvClienteObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvClienteObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnBuscarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarCliente As Global.Prosegur.Web.Botao

    '''<summary>
    '''lblSubCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtSubCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvSubClienteObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvSubClienteObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnBuscarSubCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarSubCliente As Global.Prosegur.Web.Botao

    '''<summary>
    '''lblCodPuntoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodPuntoServicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelCodigo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtCodigoPuntoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoPuntoServicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvCodPuntoServicioObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCodPuntoServicioObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''csvCodPuntoServicioExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvCodPuntoServicioExistente As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''UpdateProgressCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressCodigo As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''lblDescPuntoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescPuntoServicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDescricao As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDescPuntoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescPuntoServicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''csvDescPuntoServicioObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDescPuntoServicioObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''csvDescPuntoServicioExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvDescPuntoServicioExistente As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''UpdateProgressDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressDescricao As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''btnDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDireccion As Global.Prosegur.Web.Botao

    '''<summary>
    '''lblCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoAjeno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigoAjeno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDesCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesCodigoAjeno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDesCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesCodigoAjeno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCodigoAjeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCodigoAjeno As Global.Prosegur.Web.Botao

    '''<summary>
    '''lblTipoPuntoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoPuntoServicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlTipoPuntoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoPuntoServicio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csvTipoPuntoServicioObrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csvTipoPuntoServicioObrigatorio As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotSaldo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upChkTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upChkTotSaldo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''chkTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTotSaldo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblVigente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVigente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkVigente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVigente As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblProprioTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProprioTotSaldo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upChkProprioTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upChkProprioTotSaldo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''chkProprioTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkProprioTotSaldo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblTituloTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloTotSaldo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upTotSaldo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''phTotSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phTotSaldo As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblTituloDatosBanc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloDatosBanc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ucDatosBanc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDatosBanc As Global.Prosegur.[Global].GesEfectivo.IAC.Web.ucDatosBanc

    '''<summary>
    '''UpdatePanelAcaoPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAcaoPagina As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGrabar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabar As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnAnadirTotalizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnadirTotalizador As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnAnadirCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnadirCuenta As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.Prosegur.Web.Botao

    '''<summary>
    '''btnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVolver As Global.Prosegur.Web.Botao

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.IAC.Web.Principal
        Get
            Return CType(MyBase.Master, Prosegur.[Global].GesEfectivo.IAC.Web.Principal)
        End Get
    End Property
End Class
