SELECT 
	UCP.IDCENTROPROCESO, CP.DESCRIPCION
FROM 
	PD_CENTROPROCESO  CP, PD_USUARIOCENTROPROCESO UCP
WHERE 
	UCP.IDCENTROPROCESO = CP.IDCENTROPROCESO
	AND UCP.IDUSUARIO = :IDUSUARIO
ORDER BY CP.DESCRIPCION, CP.IDPS