INSERT INTO GEPR_TAGRUPACION
  (OID_AGRUPACION,
   COD_AGRUPACION,
   DES_AGRUPACION,
   OBS_AGRUPACION,
   BOL_VIGENTE,
   COD_USUARIO,
   FYH_ACTUALIZACION)
VALUES
  ([]OID_AGRUPACION,
   []COD_AGRUPACION,
   []DES_AGRUPACION,
   []OBS_AGRUPACION,
   []BOL_VIGENTE,
   []COD_USUARIO,
   []FYH_ACTUALIZACION)