SELECT 
      AGR.COD_AGRUPACION,
      AGR.DES_AGRUPACION,
      AGR.OBS_AGRUPACION,
      AGRPR.NUM_TOLERANCIA_PARCIAL_MIN,
      AGRPR.NUM_TOLERANCIA_PARCIAL_MAX,
      AGRPR.NUM_TOLERANCIA_BULTO_MIN,
      AGRPR.NUM_TOLERANCIA_BULTO_MAX,
      AGRPR.NUM_TOLERANCIA_REMESA_MIN,
      AGRPR.NUM_TOLERANCIA_REMESA_MAX,
      AGR.OID_AGRUPACION
FROM  GEPR_TAGRUPACION_POR_PROCESO AGRPR
      INNER JOIN GEPR_TAGRUPACION AGR ON AGRPR.OID_AGRUPACION = AGR.OID_AGRUPACION
WHERE AGRPR.OID_PROCESO = []OID_PROCESO 
AND AGR.BOL_VIGENTE = 1
