SELECT 
	COUNT(*) AS QTDEVIGENTE
FROM 
	GEPR_TAGRUPACION AG
	INNER JOIN GEPR_TAGRUPACION_POR_PROCESO AGP ON AG.OID_AGRUPACION = AGP.OID_AGRUPACION
	INNER JOIN GEPR_TPROCESO P ON AGP.OID_PROCESO = P.OID_PROCESO
	INNER JOIN GEPR_TPROCESO_POR_PSERVICIO PPS ON P.OID_PROCESO = PPS.OID_PROCESO
WHERE 
	PPS.BOL_VIGENTE = 1  
	AND AG.COD_AGRUPACION = []COD_AGRUPACION