SELECT 
	ED.OID_EMISOR_DOCUMENTO,
	ED.COD_EMISOR_DOCUMENTO,
    ED.DES_EMISOR_DOCUMENTO,
	ED.COD_VALIDACION_DOCUMENTO,
    ED.COD_TIPO_ORIGEN,
	ED.BOL_ACTIVO,
	ED.OID_IAC
FROM 
	GEPR_TEMISOR_DOCUMENTO ED