DECLARE
    OWNER_OBJECTS VARCHAR2(30) := sys_context('userenv', 'current_schema');
    var$existe NUMBER;
BEGIN    
    SELECT COUNT(1) INTO var$existe FROM ALL_TABLES A WHERE UPPER(A.OWNER) = UPPER(OWNER_OBJECTS) AND UPPER(A.TABLE_NAME) = 'SAPR_TTEMP_UPDATE_FECHAS_MOV';

    IF var$existe = 0 THEN 
        EXECUTE IMMEDIATE 'CREATE TABLE SAPR_TTEMP_UPDATE_FECHAS_MOV (
        FEC_MOVIMIENTO DATE NOT NULL,
        NUM_TOTAL_MOVIMIENTOS NUMBER NULL,
        GMT_MODIFICACION TIMESTAMP(6) WITH TIME ZONE NOT NULL,
        PRIMARY KEY(FEC_MOVIMIENTO)
        )';
    ELSE
       EXECUTE IMMEDIATE 'TRUNCATE TABLE SAPR_TTEMP_UPDATE_FECHAS_MOV';
    END IF;

END;
/