/*PGP-2358*/

ALTER TABLE SAPR_TMOVIMIENTO ENABLE ROW MOVEMENT;
ALTER TABLE SAPR_TMOVIMIENTO_DETALLE ENABLE ROW MOVEMENT;
ALTER TABLE SAPR_TMOVIMIENTO_CAMPO_EXTRA ENABLE ROW MOVEMENT;

DECLARE
    V_TOTAL_MOVIMIENTOS NUMBER := 0;
    V_CANT_DIAS NUMBER := 30;

    CURSOR cur$c_Fechas IS
      SELECT TEMP.FEC_MOVIMIENTO FROM SAPR_TTEMP_UPDATE_FECHAS_MOV TEMP WHERE TEMP.NUM_TOTAL_MOVIMIENTOS = '0'
      AND TEMP.FEC_MOVIMIENTO >= (SELECT MAX(FEC_MOVIMIENTO)FROM SAPR_TTEMP_UPDATE_FECHAS_MOV TEMP WHERE TEMP.NUM_TOTAL_MOVIMIENTOS = '0' 
                                    AND TEMP.FEC_MOVIMIENTO <= SYSDATE) - V_CANT_DIAS 
      ORDER BY 1 DESC;

BEGIN
    FOR R_FECHA IN cur$c_Fechas
    LOOP
        V_TOTAL_MOVIMIENTOS := 0;
        FOR R_MOVIMIENTO IN (
        WITH DELEGACIONES AS (
            SELECT
            SECT.OID_SECTOR,
            DELE.NEC_GMT_MINUTOS,
            DELE.FYH_VERANO_INICIO,
            DELE.FYH_VERANO_FIN,
            DELE.NEC_VERANO_AJUSTE
            FROM
            GEPR_TSECTOR SECT
            INNER JOIN GEPR_TPLANTA PLAN ON SECT.OID_PLANTA = PLAN.OID_PLANTA
            INNER JOIN GEPR_TDELEGACION DELE ON PLAN.OID_DELEGACION = DELE.OID_DELEGACION
        )
        SELECT
            MOVI.OID_MOVIMIENTO,
            DOCU.COD_COMPROBANTE,
            CLIENTEAJ.DES_AJENO DES_CLIENTE_OPE,
            SUBCLIAJ.DES_AJENO DES_SUBCLIENTE_OPE,
            PTOAJ.DES_AJENO DES_PTO_SERVICIO_OPE,
            CANAJ.COD_AJENO COD_CANAL,
            SUBCAJ.COD_AJENO COD_SUBCANAL,
            TRUNC(TO_TIMESTAMP_TZ(TO_CHAR(DOCU.FYH_GESTION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM')) FEC_MOVIMIENTO,
            TO_TIMESTAMP_TZ(TO_CHAR(DOCU.FYH_GESTION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM') HOR_MOVIMIENTO,
            TO_TIMESTAMP_TZ(TO_CHAR(NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION) + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) >= DELEG.FYH_VERANO_INICIO AND (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) >= DELEG.FYH_VERANO_INICIO AND (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) >= DELEG.FYH_VERANO_INICIO AND (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM') FYH_CONTABLE,
            CASE WHEN DOCU.FYH_NOTIFICACION IS NOT NULL THEN
            TO_TIMESTAMP_TZ(TO_CHAR(DOCU.FYH_NOTIFICACION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_NOTIFICACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_NOTIFICACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_NOTIFICACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_NOTIFICACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_NOTIFICACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_NOTIFICACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM')
            ELSE DOCU.FYH_NOTIFICACION END FYH_NOTIFICACION, 
            CASE WHEN DOCU.FYH_ACREDITACION IS NOT NULL THEN
            TO_TIMESTAMP_TZ(TO_CHAR(DOCU.FYH_ACREDITACION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM')
            ELSE DOCU.FYH_ACREDITACION END FYH_ACREDITACION,
            PLANIFI.COD_PLANIFICACION COD_PLANIFICACION,
            PLANIFI.DES_PLANIFICACION DES_PLANIFICACION,
            BANCOAJ.COD_AJENO COD_PLANIF_BANCO_OPE,
            BANCO.COD_CLIENTE COD_PLANIF_BANCO_MDM,
            BANCO.DES_CLIENTE DES_PLANIF_BANCO,
            CASE WHEN PERI.FYH_INICIO IS NOT NULL THEN
            TO_TIMESTAMP_TZ(TO_CHAR(PERI.FYH_INICIO + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (PERI.FYH_INICIO) >= DELEG.FYH_VERANO_INICIO AND (PERI.FYH_INICIO) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (PERI.FYH_INICIO) >= DELEG.FYH_VERANO_INICIO AND (PERI.FYH_INICIO) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' ||
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (PERI.FYH_INICIO) >= DELEG.FYH_VERANO_INICIO AND (PERI.FYH_INICIO) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM') 
            ELSE PERI.FYH_INICIO END FYH_PLANIF_PERIODO_INI,
            CASE WHEN PERI.FYH_FIN IS NOT NULL THEN
            TO_TIMESTAMP_TZ(TO_CHAR(PERI.FYH_FIN + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (PERI.FYH_FIN) >= DELEG.FYH_VERANO_INICIO AND (PERI.FYH_FIN) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (PERI.FYH_FIN) >= DELEG.FYH_VERANO_INICIO AND (PERI.FYH_FIN) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' ||
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (PERI.FYH_FIN) >= DELEG.FYH_VERANO_INICIO AND (PERI.FYH_FIN) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM') 
            ELSE PERI.FYH_FIN END FYH_PLANIF_PERIODO_FIN,
            TO_TIMESTAMP_TZ(TO_CHAR(SYS_EXTRACT_UTC(DOCU.GMT_CREACION) + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (SYS_EXTRACT_UTC(DOCU.GMT_CREACION)) >= DELEG.FYH_VERANO_INICIO AND (SYS_EXTRACT_UTC(DOCU.GMT_CREACION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (SYS_EXTRACT_UTC(DOCU.GMT_CREACION)) >= DELEG.FYH_VERANO_INICIO AND (SYS_EXTRACT_UTC(DOCU.GMT_CREACION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' ||
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (SYS_EXTRACT_UTC(DOCU.GMT_CREACION)) >= DELEG.FYH_VERANO_INICIO AND (SYS_EXTRACT_UTC(DOCU.GMT_CREACION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM') GMT_CREACION                  
        FROM
            SAPR_TMOVIMIENTO MOVI
            INNER JOIN SAPR_TDOCUMENTO DOCU ON MOVI.OID_DOCUMENTO = DOCU.OID_DOCUMENTO AND MOVI.FEC_MOVIMIENTO = TRUNC(DOCU.FYH_GESTION)
            INNER JOIN SAPR_VCUENTA VISTA_CUENTA ON VISTA_CUENTA.OID_CUENTA = DOCU.OID_CUENTA_SALDO_ORIGEN
            INNER JOIN DELEGACIONES DELEG ON DOCU.OID_SECTOR_ORIGEN = DELEG.OID_SECTOR
            LEFT JOIN SAPR_TPERIODOXDOCUMENTO PERXDOCU ON PERXDOCU.OID_DOCUMENTO = DOCU.OID_DOCUMENTO
            LEFT JOIN SAPR_TPERIODO PERI ON PERI.OID_PERIODO = PERXDOCU.OID_PERIODO
            LEFT JOIN SAPR_TPLANIFICACION PLANIFI ON PLANIFI.OID_PLANIFICACION = PERI.OID_PLANIFICACION
            LEFT JOIN GEPR_TCLIENTE BANCO ON BANCO.OID_CLIENTE = PLANIFI.OID_CLIENTE
            LEFT JOIN GEPR_TCODIGO_AJENO BANCOAJ ON BANCOAJ.OID_TABLA_GENESIS = BANCO.OID_CLIENTE AND BANCOAJ.COD_IDENTIFICADOR = 'MAE' AND BANCOAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TCLIENTE'
            LEFT JOIN GEPR_TCODIGO_AJENO CLIENTEAJ ON CLIENTEAJ.OID_TABLA_GENESIS = VISTA_CUENTA.OID_CLIENTE AND CLIENTEAJ.COD_IDENTIFICADOR = 'MAE' AND CLIENTEAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TCLIENTE'
            LEFT JOIN GEPR_TCODIGO_AJENO SUBCLIAJ ON SUBCLIAJ.OID_TABLA_GENESIS = VISTA_CUENTA.OID_SUBCLIENTE AND SUBCLIAJ.COD_IDENTIFICADOR = 'MAE' AND SUBCLIAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TSUBCLIENTE'
            LEFT JOIN GEPR_TCODIGO_AJENO PTOAJ ON PTOAJ.OID_TABLA_GENESIS = VISTA_CUENTA.OID_PTO_SERVICIO AND PTOAJ.COD_IDENTIFICADOR = 'MAE' AND PTOAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TPUNTO_SERVICIO'
            LEFT JOIN GEPR_TCODIGO_AJENO CANAJ ON CANAJ.OID_TABLA_GENESIS = VISTA_CUENTA.OID_CANAL AND CANAJ.COD_IDENTIFICADOR = 'MAE' AND CANAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TCANAL'
            LEFT JOIN GEPR_TCODIGO_AJENO SUBCAJ ON SUBCAJ.OID_TABLA_GENESIS = VISTA_CUENTA.OID_SUBCANAL AND SUBCAJ.COD_IDENTIFICADOR = 'MAE' AND SUBCAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TSUBCANAL'

        WHERE
            MOVI.FEC_MOVIMIENTO = R_FECHA.FEC_MOVIMIENTO
        )
        LOOP
            V_TOTAL_MOVIMIENTOS := V_TOTAL_MOVIMIENTOS + 1;
            UPDATE SAPR_TMOVIMIENTO MOVI 
				SET MOVI.HOR_MOVIMIENTO                 = R_MOVIMIENTO.HOR_MOVIMIENTO, 
					MOVI.FYH_CONTABLE                   = R_MOVIMIENTO.FYH_CONTABLE, 
					MOVI.FYH_ACREDITACION               = R_MOVIMIENTO.FYH_ACREDITACION, 
					MOVI.FYH_NOTIFICACION               = R_MOVIMIENTO.FYH_NOTIFICACION,
					MOVI.FEC_MOVIMIENTO                 = R_MOVIMIENTO.FEC_MOVIMIENTO,
                    MOVI.COD_PLANIFICACION              = R_MOVIMIENTO.COD_PLANIFICACION, 
                    MOVI.DES_PLANIFICACION              = R_MOVIMIENTO.DES_PLANIFICACION, 
                    MOVI.COD_PLANIFICACION_BANCO_OPE    = R_MOVIMIENTO.COD_PLANIF_BANCO_OPE, 
                    MOVI.COD_PLANIFICACION_BANCO_MDM    = R_MOVIMIENTO.COD_PLANIF_BANCO_MDM, 
                    MOVI.DES_PLANIFICACION_BANCO        = R_MOVIMIENTO.DES_PLANIF_BANCO,
                    MOVI.FYH_PLANIFICACION_PERIODO_INI  = R_MOVIMIENTO.FYH_PLANIF_PERIODO_INI,
                    MOVI.FYH_PLANIFICACION_PERIODO_FIN  = R_MOVIMIENTO.FYH_PLANIF_PERIODO_FIN,
                    MOVI.COD_COMPROBANTE                = R_MOVIMIENTO.COD_COMPROBANTE,
                    MOVI.DES_CLIENTE_OPE                = R_MOVIMIENTO.DES_CLIENTE_OPE,
                    MOVI.DES_SUBCLIENTE_OPE             = R_MOVIMIENTO.DES_SUBCLIENTE_OPE,
                    MOVI.DES_PTO_SERVICIO_OPE           = R_MOVIMIENTO.DES_PTO_SERVICIO_OPE,
                    MOVI.COD_CANAL                      = R_MOVIMIENTO.COD_CANAL,
                    MOVI.COD_SUBCANAL                   = R_MOVIMIENTO.COD_SUBCANAL,
                    MOVI.GMT_MODIFICACION               = SYSTIMESTAMP,
                    MOVI.DES_USUARIO_MODIFICACION       = 'SCRIPT_ACTUALIZACION_MOVIMIENTOS',
                    MOVI.GMT_CREACION                   = R_MOVIMIENTO.GMT_CREACION
            WHERE MOVI.OID_MOVIMIENTO = R_MOVIMIENTO.OID_MOVIMIENTO;
			
			--ACTUALIZAR FEC_MOVIMIENTO EN SAPR_TMOVIMIENTO_DETALLE
			UPDATE SAPR_TMOVIMIENTO_DETALLE MOVI_DET
			   SET MOVI_DET.FEC_MOVIMIENTO = R_MOVIMIENTO.FEC_MOVIMIENTO
			 WHERE MOVI_DET.OID_MOVIMIENTO = R_MOVIMIENTO.OID_MOVIMIENTO;
			 
			--ACTUALIZAR FEC_MOVIMIENTO EN SAPR_TMOVIMIENTO_CAMPO_EXTRA
			UPDATE SAPR_TMOVIMIENTO_CAMPO_EXTRA MOVI_EXT
			   SET MOVI_EXT.FEC_MOVIMIENTO = R_MOVIMIENTO.FEC_MOVIMIENTO
			 WHERE MOVI_EXT.OID_MOVIMIENTO = R_MOVIMIENTO.OID_MOVIMIENTO;
			 
        END LOOP; 
        
        UPDATE SAPR_TTEMP_UPDATE_FECHAS_MOV SET NUM_TOTAL_MOVIMIENTOS = V_TOTAL_MOVIMIENTOS, GMT_MODIFICACION = SYSTIMESTAMP WHERE FEC_MOVIMIENTO = R_FECHA.FEC_MOVIMIENTO;
        COMMIT;
    END LOOP;
	
END;
/
ALTER TABLE SAPR_TMOVIMIENTO DISABLE ROW MOVEMENT;
ALTER TABLE SAPR_TMOVIMIENTO_DETALLE DISABLE ROW MOVEMENT;
ALTER TABLE SAPR_TMOVIMIENTO_CAMPO_EXTRA DISABLE ROW MOVEMENT;
/