/*PGP-2358*/

ALTER TABLE SAPR_TMOVIMIENTO ENABLE ROW MOVEMENT;
ALTER TABLE SAPR_TMOVIMIENTO_DETALLE ENABLE ROW MOVEMENT;
ALTER TABLE SAPR_TMOVIMIENTO_CAMPO_EXTRA ENABLE ROW MOVEMENT;

DECLARE
    V_TOTAL_MOVIMIENTOS NUMBER := 0;
    CURSOR cur$c_Fechas IS
        SELECT TEMP.FEC_MOVIMIENTO FROM SAPR_TTEMP_UPDATE_FECHAS_MOV TEMP WHERE TEMP.NUM_TOTAL_MOVIMIENTOS = '0'
        ORDER BY 1 ASC;

BEGIN
    INSERT INTO SAPR_TTEMP_UPDATE_FECHAS_MOV (FEC_MOVIMIENTO, NUM_TOTAL_MOVIMIENTOS, GMT_MODIFICACION)
    SELECT DISTINCT MOVI.FEC_MOVIMIENTO, 0, SYSTIMESTAMP FROM SAPR_TMOVIMIENTO MOVI WHERE NOT EXISTS (SELECT TEMP.FEC_MOVIMIENTO FROM SAPR_TTEMP_UPDATE_FECHAS_MOV TEMP WHERE MOVI.FEC_MOVIMIENTO = TEMP.FEC_MOVIMIENTO) ORDER BY 1 ASC;
    COMMIT;
	
    FOR R_FECHA IN cur$c_Fechas
    LOOP
        V_TOTAL_MOVIMIENTOS := 0;
        FOR R_MOVIMIENTO IN (
        WITH DELEGACIONES AS (
            SELECT
            SECT.OID_SECTOR,
            DELE.NEC_GMT_MINUTOS,
            DELE.FYH_VERANO_INICIO,
            DELE.FYH_VERANO_FIN,
            DELE.NEC_VERANO_AJUSTE
            FROM
            GEPR_TSECTOR SECT
            INNER JOIN GEPR_TPLANTA PLAN ON SECT.OID_PLANTA = PLAN.OID_PLANTA
            INNER JOIN GEPR_TDELEGACION DELE ON PLAN.OID_DELEGACION = DELE.OID_DELEGACION
        )
        SELECT
            MOVI.OID_MOVIMIENTO,
            TRUNC(TO_TIMESTAMP_TZ(TO_CHAR(DOCU.FYH_GESTION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM')) FEC_MOVIMIENTO,
            TO_TIMESTAMP_TZ(TO_CHAR(DOCU.FYH_GESTION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_GESTION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_GESTION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM') HOR_MOVIMIENTO,
            TO_TIMESTAMP_TZ(TO_CHAR(NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION) + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) >= DELEG.FYH_VERANO_INICIO AND (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) >= DELEG.FYH_VERANO_INICIO AND (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) >= DELEG.FYH_VERANO_INICIO AND (NVL(DOCU.FEC_CONTABLE, DOCU.FYH_GESTION)) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM') FYH_CONTABLE,
            CASE WHEN DOCU.FYH_NOTIFICACION IS NOT NULL THEN
            TO_TIMESTAMP_TZ(TO_CHAR(DOCU.FYH_NOTIFICACION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_NOTIFICACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_NOTIFICACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_NOTIFICACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_NOTIFICACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_NOTIFICACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_NOTIFICACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM')
            ELSE DOCU.FYH_NOTIFICACION END FYH_NOTIFICACION, 
            CASE WHEN DOCU.FYH_ACREDITACION IS NOT NULL THEN
            TO_TIMESTAMP_TZ(TO_CHAR(DOCU.FYH_ACREDITACION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
            TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
            TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (DOCU.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (DOCU.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM')
            ELSE DOCU.FYH_ACREDITACION END FYH_ACREDITACION                     
        FROM
            SAPR_TMOVIMIENTO MOVI
            INNER JOIN SAPR_TDOCUMENTO DOCU ON MOVI.OID_DOCUMENTO = DOCU.OID_DOCUMENTO 
            INNER JOIN DELEGACIONES DELEG ON DOCU.OID_SECTOR_ORIGEN = DELEG.OID_SECTOR
        WHERE
            MOVI.FEC_MOVIMIENTO = R_FECHA.FEC_MOVIMIENTO
        )
        LOOP
            V_TOTAL_MOVIMIENTOS := V_TOTAL_MOVIMIENTOS + 1;
            UPDATE SAPR_TMOVIMIENTO MOVI 
				SET MOVI.HOR_MOVIMIENTO = R_MOVIMIENTO.HOR_MOVIMIENTO, 
					MOVI.FYH_CONTABLE = R_MOVIMIENTO.FYH_CONTABLE, 
					MOVI.FYH_ACREDITACION = R_MOVIMIENTO.FYH_ACREDITACION, 
					MOVI.FYH_NOTIFICACION = R_MOVIMIENTO.FYH_NOTIFICACION,
					MOVI.FEC_MOVIMIENTO = R_MOVIMIENTO.FEC_MOVIMIENTO
            WHERE MOVI.OID_MOVIMIENTO = R_MOVIMIENTO.OID_MOVIMIENTO;
			
			--ACTUALIZAR FEC_MOVIMIENTO EN SAPR_TMOVIMIENTO_DETALLE
			UPDATE SAPR_TMOVIMIENTO_DETALLE MOVI_DET
			   SET MOVI_DET.FEC_MOVIMIENTO = R_MOVIMIENTO.FEC_MOVIMIENTO
			 WHERE MOVI_DET.OID_MOVIMIENTO = R_MOVIMIENTO.OID_MOVIMIENTO;
			 
			--ACTUALIZAR FEC_MOVIMIENTO EN SAPR_TMOVIMIENTO_CAMPO_EXTRA
			UPDATE SAPR_TMOVIMIENTO_CAMPO_EXTRA MOVI_EXT
			   SET MOVI_EXT.FEC_MOVIMIENTO = R_MOVIMIENTO.FEC_MOVIMIENTO
			 WHERE MOVI_EXT.OID_MOVIMIENTO = R_MOVIMIENTO.OID_MOVIMIENTO;
			 
        END LOOP; 
        
        UPDATE SAPR_TTEMP_UPDATE_FECHAS_MOV SET NUM_TOTAL_MOVIMIENTOS = V_TOTAL_MOVIMIENTOS, GMT_MODIFICACION = SYSTIMESTAMP WHERE FEC_MOVIMIENTO = R_FECHA.FEC_MOVIMIENTO;
        COMMIT;
    END LOOP;
	
END;
/
ALTER TABLE SAPR_TMOVIMIENTO DISABLE ROW MOVEMENT;
ALTER TABLE SAPR_TMOVIMIENTO_DETALLE DISABLE ROW MOVEMENT;
ALTER TABLE SAPR_TMOVIMIENTO_CAMPO_EXTRA DISABLE ROW MOVEMENT;
/