DECLARE

    GENESIS_OWNER       varchar2(50);
    PERMISOS_OWNER      varchar2(50);

BEGIN

    GENESIS_OWNER := 'XXXX';
    PERMISOS_OWNER := 'YYYY';

	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TAPLICACION TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TAPLICACION_VERSION TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TCONVERSION_LEGADO	TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TDELE_TIPO_ROLE_USR TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TDELEGACION TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TDELEGACION_TIPO_SECTOR TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TDELEGACION_VERSION TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TGRUPO_USUARIO TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TGRUPO_VERSION TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TNEGOCIO TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TPAIS TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TPERMISO TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TPLANTA TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TPLANTA_TIPO_SECTOR TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TROLE TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TROLEXDELEGACIONXSECTOR TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TROLEXPERMISO TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TSECTOR TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TSERVIDOR_DELEGACION TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TTIPO_SECTOR TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TTOKEN_ACCESO TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TUSUARIO TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.ADPR_TUSUARIO_VERSION TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.CPPR_TLOG TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.CPPR_TLOG_ERROR TO ' || GENESIS_OWNER;
	execute immediate 'GRANT SELECT ON ' || PERMISOS_OWNER || '.CPPR_TSESION TO ' || GENESIS_OWNER;


EXCEPTION
  WHEN OTHERS THEN
    raise_application_error(-20001,
                            'Arquivo: SCRIPT_SYNONYMS_PERMISOS.sql Script: GRANTS SYNONYMS PERMISOS' ||
                            sqlerrm);
    RAISE;
END;
/