DECLARE
  VAR$COD_DELEGACION VARCHAR2(30) := 'XXX';
BEGIN
  UPDATE GEPR_TDELEGACION SET BOL_DEFAULT = 1 WHERE COD_DELEGACION = VAR$COD_DELEGACION;
  COMMIT;

EXCEPTION
  WHEN OTHERS THEN 
    ROLLBACK;
    raise_application_error( -20001, 'Arquivo: Genesis.sql Script: SCRIPT_DELEGACION_DEFAULT - ' || sqlerrm);
    RAISE;
END;  
/