INSERT INTO IAPR_TPARAMETROS_REPORTES
(OID_PARAMETRO,
OID_CONFIGURACION,
COD_PARAMETRO,
COD_NOMBRE_PARAMETRO,
DES_PARAMETRO, 
ES_TODOS)
VALUES
([]OID_PARAMETRO,
[]OID_CONFIGURACION,
[]COD_PARAMETRO,
[]COD_NOMBRE_PARAMETRO,
[]DES_PARAMETRO,
[]ES_TODOS)