SELECT 
	MP.COD_TIPO_MEDIO_PAGO, 
	NULL AS DES_TIPO_MEDIO_PAGO, 
	DIV.COD_ISO_DIVISA, 
	DIV.DES_DIVISA, 
	MP.COD_MEDIO_PAGO, 
	MP.DES_MEDIO_PAGO, 
	MPPRC.NUM_TOLERANCIA_PARCIAL_MIN, 
	MPPRC.NUM_TOLERANCIA_PARCIAL_MAX, 
	MPPRC.NUM_TOLERANCIA_BULTO_MIN, 
	MPPRC.NUM_TOLERANCIA_BULTO_MAX, 
	MPPRC.NUM_TOLERANCIA_REMESA_MIN, 
	MPPRC.NUM_TOLERANCIA_REMESA_MAX, 
	MP.OID_MEDIO_PAGO, 
	MP.OBS_MEDIO_PAGO, 
	MP.BOL_MERCANCIA,
	MP.BOL_VIGENTE 
FROM 
	GEPR_TMEDIO_PAGO_POR_PROCESO MPPRC 
	INNER JOIN GEPR_TMEDIO_PAGO MP ON MPPRC.OID_MEDIO_PAGO = MP.OID_MEDIO_PAGO 
	INNER JOIN GEPR_TDIVISA DIV ON MP.OID_DIVISA = DIV.OID_DIVISA 
WHERE 
	MPPRC.OID_PROCESO = []OID_PROCESO 

