SELECT 
	DIV.COD_ISO_DIVISA, 
	DIV.DES_DIVISA, 
	DIV.BOL_VIGENTE, 
	DEN.COD_DENOMINACION, 
	DEN.DES_DENOMINACION, 
	DEN.BOL_BILLETE, 
	DEN.NUM_VALOR, 
	DEN.NUM_PESO, 
	DEN.BOL_VIGENTE, 
	DIVPRC.NUM_TOLERANCIA_PARCIAL_MIN, 
	DIVPRC.NUM_TOLERANCIA_PARCIAL_MAX, 
	DIVPRC.NUM_TOLERANCIA_BULTO_MIN, 
	DIVPRC.NUM_TOLERANCIA_BULTO_MAX, 
	DIVPRC.NUM_TOLERANCIA_REMESA_MIN, 
	DIVPRC.NUM_TOLERANCIA_REMESA_MAX 
FROM 
	GEPR_TDIVISA_POR_PROCESO DIVPRC 
	INNER JOIN GEPR_TDIVISA DIV ON DIVPRC.OID_DIVISA = DIV.OID_DIVISA 
	INNER JOIN GEPR_TDENOMINACION DEN ON DIV.OID_DIVISA = DEN.OID_DIVISA 
WHERE 
	DIVPRC.OID_PROCESO = []OID_PROCESO 
ORDER BY 
	DIV.COD_ISO_DIVISA