SELECT 	
	MP.COD_MEDIO_PAGO, 
	TMP.OID_TERMINO, 
	TMP.COD_TERMINO, 
	TMP.DES_TERMINO, 
	TMP.OBS_TERMINO, 
	TMP.DES_VALOR_INICIAL, 
	TMP.NEC_LONGITUD, 
	FORM.COD_FORMATO, 
	FORM.DES_FORMATO, 
	MASC.COD_MASCARA, 
	MASC.DES_MASCARA, 
	MASC.DES_EXP_REGULAR,
	AVAL.COD_ALGORITMO_VALIDACION, 
	AVAL.DES_ALGORITMO_VALIDACION, 
	TMP.BOL_MOSTRAR_CODIGO, 
	TMPP.BOL_ES_OBLIGATORIO,
	TMP.NEC_ORDEN, 
	TMP.BOL_VIGENTE 
FROM 
	GEPR_TPROCESO_SUBCANAL PSUB 
	INNER JOIN GEPR_TTERMINO_MED_PAGO_POR_PRO TMPP ON TMPP.OID_PROCESO_SUBCANAL = PSUB.OID_PROCESO_SUBCANAL 
	INNER JOIN GEPR_TTERMINO_MEDIO_PAGO TMP ON TMP.OID_TERMINO = TMPP.OID_TERMINO 
	INNER JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = TMP.OID_MEDIO_PAGO 
	LEFT OUTER JOIN GEPR_TFORMATO FORM ON FORM.OID_FORMATO = TMP.OID_FORMATO 
	LEFT OUTER JOIN GEPR_TMASCARA MASC ON MASC.OID_MASCARA = TMP.OID_MASCARA 
	LEFT OUTER JOIN GEPR_TALGORITMO_VALIDACION AVAL ON AVAL.OID_ALGORITMO_VALIDACION = TMP.OID_ALGORITMO_VALIDACION 
WHERE 
	PSUB.OID_PROCESO_POR_PSERVICIO = []OID_PROCESO_POR_PSERVICIO 
	AND PSUB.OID_SUBCANAL = []OID_SUBCANAL