MERGE INTO SAPR_TSALDO_MEDIO_PAGO Q1
USING ( SELECT A.OID_TRANSACCION_MEDIO_PAGO
               ,A.OID_CUENTA_SALDO
               ,A.OID_MEDIO_PAGO
               ,A.OID_DIVISA
               ,A.COD_TIPO_MEDIO_PAGO
               ,A.COD_NIVEL_DETALLE
               ,A.BOL_DISPONIBLE
               ,A.NEL_CANTIDAD
               ,A.NUM_IMPORTE   
			   ,A.OID_UNIDAD_MEDIDA
          FROM SAPR_TTRANSACCION_MEDIO_PAGO A
          WHERE A.OID_TRANSACCION_MEDIO_PAGO = []OID_TRANSACCION_MEDIO_PAGO
      ) Q2
   ON ( Q1.OID_CUENTA_SALDO = Q2.OID_CUENTA_SALDO
        AND Q1.COD_NIVEL_DETALLE = Q2.COD_NIVEL_DETALLE
        AND Q1.BOL_DISPONIBLE = Q2.BOL_DISPONIBLE
        AND Q1.OID_DIVISA = Q2.OID_DIVISA
		AND Q1.COD_TIPO_MEDIO_PAGO = Q2.COD_TIPO_MEDIO_PAGO
		AND NVL(Q1.OID_MEDIO_PAGO,'-') = NVL(Q2.OID_MEDIO_PAGO,'-')
		AND NVL(Q1.OID_UNIDAD_MEDIDA,'-') = NVL(Q2.OID_UNIDAD_MEDIDA,'-')
        AND ROWNUM <= 1)
WHEN MATCHED THEN
  update 
     set q1.num_importe  = nvl(q1.num_importe,0) + nvl(q2.num_importe,0)
        ,q1.nel_cantidad = nvl(q1.nel_cantidad,0) + nvl(q2.nel_cantidad,0)
        ,q1.GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###
        ,q1.DES_USUARIO_MODIFICACION = []DES_USUARIO
        ,q1.OID_ULTIMA_TRANSACCION = q2.oid_transaccion_medio_pago
WHEN NOT MATCHED THEN
  INSERT (Q1.OID_SALDO_MEDIO_PAGO, 
          Q1.OID_CUENTA_SALDO, 
          Q1.OID_MEDIO_PAGO, 
          Q1.OID_DIVISA,
          Q1.OID_ULTIMA_TRANSACCION,
          Q1.COD_TIPO_MEDIO_PAGO,
          Q1.COD_NIVEL_DETALLE,
		  Q1.OID_UNIDAD_MEDIDA,
          Q1.BOL_DISPONIBLE,
          Q1.NUM_IMPORTE, 
          Q1.NEL_CANTIDAD,
          Q1.GMT_CREACION, 
          Q1.DES_USUARIO_CREACION, 
          Q1.GMT_MODIFICACION, 
          Q1.DES_USUARIO_MODIFICACION)
                    
VALUES (SYS_GUID(), 
      Q2.OID_CUENTA_SALDO, 
      Q2.OID_MEDIO_PAGO, 
      Q2.OID_DIVISA,
      []OID_TRANSACCION_MEDIO_PAGO,
      Q2.COD_TIPO_MEDIO_PAGO,
      Q2.COD_NIVEL_DETALLE,
	  Q2.OID_UNIDAD_MEDIDA,
      Q2.BOL_DISPONIBLE, 
      Q2.NUM_IMPORTE, 
      Q2.NEL_CANTIDAD,
      FN_GMT_ZERO_###VERSION###, 
      []DES_USUARIO, 
      FN_GMT_ZERO_###VERSION###, 
      []DES_USUARIO)