SELECT CU.OID_CUENTA,  
       MP.COD_MEDIO_PAGO, 
       TMP.COD_NIVEL_DETALLE, 
		   TMP.BOL_DISPONIBLE,
		   TMP.OID_DIVISA,
       SUM(TMP.NUM_IMPORTE) NUM_IMPORTE,
       SUM(TMP.NEL_CANTIDAD) NEL_CANTIDAD,
	   TMP.OID_DIVISA,
	   TMP.COD_TIPO_MEDIO_PAGO,
	   TMP.OID_UNIDAD_MEDIDA
FROM SAPR_TDOCUMENTO D
INNER JOIN SAPR_TTRANSACCION_MEDIO_PAGO TMP ON TMP.OID_DOCUMENTO = D.OID_DOCUMENTO
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = TMP.OID_CUENTA_SALDO
INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = CU.OID_SECTOR
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DL ON DL.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = TMP.OID_MEDIO_PAGO
INNER JOIN SAPR_TTIPO_DOCUMENTO TP ON D.OID_TIPO_DOCUMENTO = TP.OID_TIPO_DOCUMENTO
WHERE D.FYH_PLAN_CERTIFICACION <= []FYH_PLAN_CERTIFICACION 
	  AND D.BOL_CERTIFICADO = []BOL_CERTIFICADO AND CL.COD_CLIENTE = []COD_CLIENTE
	  AND NOT EXISTS (SELECT CER.OID_CERTIFICADO FROM SAPR_TCERTIFICADO CER WHERE CER.OID_CERTIFICADO = TMP.OID_CERTIFICADO AND CER.COD_ESTADO = 'DE')
	  AND TP.BOL_CERTIFICACION = 1 
{0}
GROUP BY CU.OID_CUENTA,  
         MP.COD_MEDIO_PAGO, 
         TMP.COD_NIVEL_DETALLE, 
         TMP.BOL_DISPONIBLE,
		 TMP.OID_DIVISA,
		 TMP.COD_TIPO_MEDIO_PAGO,
		 TMP.OID_UNIDAD_MEDIDA