DELETE SAPR_TVALOR_TERM_MP_ELEMENTO
WHERE OID_CONTADO_MEDIO_PAGO 
IN(SELECT OID_CONTADO_MEDIO_PAGO FROM SAPR_TCONTADO_MEDIO_PAGO 
WHERE OID_PARCIAL =[]OID_PARCIAL)
OR OID_DECLARADO_MEDIO_PAGO 
IN(SELECT OID_DECLARADO_MEDIO_PAGO FROM SAPR_TDECLARADO_MEDIO_PAGO 
WHERE OID_PARCIAL =[]OID_PARCIAL)