SELECT
		Q.OID_CONTADO_MEDIO_PAGO
        ,Q.OID_DECLARADO_MEDIO_PAGO
		,Q.DES_VALOR
		,Q.OID_TERMINO_MEDIO_PAGO
		,Q.NEC_INDICE_GRUPO
FROM
  (SELECT C.OID_CONTADO_MEDIO_PAGO
        ,C.OID_DECLARADO_MEDIO_PAGO
		,C.DES_VALOR
		,C.OID_TERMINO_MEDIO_PAGO
		,C.NEC_INDICE_GRUPO
    FROM SAPR_TVALOR_TERM_MP_ELEMENTO C
   WHERE 1 = 1 {0}

UNION

  SELECT D.OID_CONTADO_MEDIO_PAGO
        ,D.OID_DECLARADO_MEDIO_PAGO
        ,D.DES_VALOR
		,D.OID_TERMINO_MEDIO_PAGO
		,D.NEC_INDICE_GRUPO
    FROM SAPR_TVALOR_TERM_MP_ELEMENTO D
   WHERE 1 = 1 {1} ) Q
ORDER BY Q.NEC_INDICE_GRUPO