INSERT INTO SAPR_TCONFIGRPXTIPOCLI
(OID_CONFIGRPXTIPOCLI
,OID_CONFIG_REPORTE
,OID_TIPO_CLIENTE
,GMT_CREACION
,DES_USUARIO_CREACION)
VALUES
([]OID_CONFIGRPXTIPOCLI
,[]OID_CONFIG_REPORTE
,[]OID_TIPO_CLIENTE
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_CREACION)
 