UPDATE SAPR_TCONFIG_REPORTE 
SET COD_CONFIG_REPORTE = []COD_CONFIG_REPORTE, 
	DES_CONFIG_REPORTE = []DES_CONFIG_REPORTE, 
	DES_DIRECCION = []DES_DIRECCION, 
	GMT_CREACION = FN_GMT_ZERO_###VERSION###, 
	NEL_TIPO_REPORTE = []NEL_TIPO_REPORTE,
	COD_MASCARA_NOMBRE = []COD_MASCARA_NOMBRE,
	COD_RENDERIZADOR = []COD_RENDERIZADOR, 
	DES_EXTENSION = []DES_EXTENSION, 
	DES_SEPARADOR = []DES_SEPARADOR,
	DES_USUARIO_CREACION = []DES_USUARIO_CREACION
WHERE OID_CONFIG_REPORTE = []OID_CONFIG_REPORTE
