SELECT 
      CF.OID_CONFIG_REPORTE, 
      CF.COD_CONFIG_REPORTE, 
      CF.DES_CONFIG_REPORTE, 
      CF.DES_DIRECCION,
      CF.DES_USUARIO_CREACION,
      CF.NEL_TIPO_REPORTE,
      CF.COD_MASCARA_NOMBRE,
      CF.COD_RENDERIZADOR,
      CF.DES_EXTENSION,
      CF.DES_SEPARADOR,
	  CTRP.OID_TIPO_REPORTEXPARAMETRO,
      CTRP.COD_PARAMETRO,
      CTRP.DES_PARAMETRO
FROM SAPR_TCONFIG_REPORTE CF
LEFT JOIN SAPR_TCONFIGRPXPARAMETRO CRP ON CRP.OID_CONFIG_REPORTE = CF.OID_CONFIG_REPORTE
LEFT JOIN SAPR_TTIPO_REPORTEXPARAMETRO CTRP ON CTRP.OID_TIPO_REPORTEXPARAMETRO = CRP.OID_TIPO_REPORTEXPARAMETRO
WHERE 1=1
