UPDATE GEPR_TTIPO_PROCESADO
SET DES_TIPO_PROCESADO = []DES_TIPO_PROCESADO, OBS_TIPO_PROCESADO = []OBS_TIPO_PROCESADO, BOL_ADMITE_IAC = []BOL_ADMITE_IAC, BOL_CONTAR_CIEGO = []BOL_CONTAR_CIEGO, BOL_VIGENTE = []BOL_VIGENTE, COD_USUARIO = []COD_USUARIO, FYH_ACTUALIZACION = []FYH_ACTUALIZACION 
WHERE COD_TIPO_PROCESADO = []COD_TIPO_PROCESADO