INSERT INTO GEPR_TTIPO_PROCESADO (OID_TIPO_PROCESADO, 
COD_TIPO_PROCESADO, 
DES_TIPO_PROCESADO, 
OBS_TIPO_PROCESADO,
BOL_VIGENTE, 
COD_USUARIO, 
FYH_ACTUALIZACION) 
VALUES 
([]OID_TIPO_PROCESADO, 
[]COD_TIPO_PROCESADO, 
[]DES_TIPO_PROCESADO, 
[]OBS_TIPO_PROCESADO, 
[]BOL_VIGENTE, 
[]COD_USUARIO, 
[]FYH_ACTUALIZACION)