INSERT INTO	
	GEPR_TCARAC_POR_TIPO_PROCESADO CPTP 
	(
		OID_CARACT_TIPO_PROCESADO, 
		OID_TIPO_PROCESADO, 
		OID_CARACTERISTICA, 
		COD_USUARIO, 
		FYH_ACTUALIZACION
	) 
VALUES
	(
		[]OID_CARACT_TIPO_PROCESADO, 
		(SELECT TP.OID_TIPO_PROCESADO FROM GEPR_TTIPO_PROCESADO TP WHERE TP.COD_TIPO_PROCESADO = []COD_TIPO_PROCESADO),
		(SELECT C.OID_CARACTERISTICA FROM GEPR_TCARACTERISTICA C WHERE C.COD_CARACTERISTICA = []COD_CARACTERISTICA), 
		[]COD_USUARIO, 
		[]FYH_ACTUALIZACION
	)
