SELECT
    TP.COD_TIPO_PROCESADO, 
    TP.DES_TIPO_PROCESADO,     
    SUM(CASE WHEN C.COD_CARACTERISTICA_CONTEO = []COD_CARACTERISTICA_CONTEO THEN 1 ELSE 0 END) ADMITE_IAC
FROM
    GEPR_TTIPO_PROCESADO TP
    LEFT JOIN GEPR_TCARAC_POR_TIPO_PROCESADO CTP ON TP.OID_TIPO_PROCESADO = CTP.OID_TIPO_PROCESADO
    LEFT JOIN GEPR_TCARACTERISTICA C ON CTP.OID_CARACTERISTICA = C.OID_CARACTERISTICA
WHERE
      TP.BOL_VIGENTE = 1
GROUP BY
  TP.COD_TIPO_PROCESADO, 
  TP.DES_TIPO_PROCESADO