SELECT 
	TPROC.COD_TIPO_PROCESADO, 
	TPROC.DES_TIPO_PROCESADO, 
	TPROC.BOL_CONTAR_CIEGO, 
	TPROC.BOL_ADMITE_IAC, 
	TPROC.BOL_VIGENTE 
FROM 
	GEPR_TPROCESO PROC 
	INNER JOIN GEPR_TTIPO_PROCESADO TPROC ON TPROC.OID_TIPO_PROCESADO = PROC.OID_TIPO_PROCESADO 
WHERE 
	PROC.OID_PROCESO = []OID_PROCESO