SELECT TPROC.OID_TIPO_PROCESADO
FROM GEPR_TTIPO_PROCESADO TPROC 
INNER JOIN GEPR_TPROCESO PRC ON TPROC.OID_TIPO_PROCESADO = PRC.OID_TIPO_PROCESADO
WHERE TPROC.COD_TIPO_PROCESADO = []COD_TIPO_PROCESADO
AND PRC.BOL_VIGENTE = 1