SELECT COD_CARACT_FORMULARIO,CFF.OID_FORMULARIO
FROM SAPR_TCARACT_FORMULARIO CF 
INNER JOIN SAPR_TCARACTFORMXFORMULARIO CFF ON CFF.OID_CARACT_FORMULARIO = CF.OID_CARACT_FORMULARIO
INNER JOIN SAPR_TGRUPO_DOCUMENTO GP ON GP.OID_FORMULARIO = CFF.OID_FORMULARIO
WHERE GP.COD_COMPROBANTE  =[]COD_COMPROBANTE