SELECT OID_GRUPO_DOCUMENTO,
	   OID_GRUPO_DOCUMENTO_PADRE,
       OID_FORMULARIO,
       OID_SECTOR_ORIGEN,
       OID_SECTOR_DESTINO,
       COD_ESTADO,
       COD_MIGRACION,
       GMT_CREACION,
       DES_USUARIO_CREACION,
       GMT_MODIFICACION,
	   COD_COMPROBANTE,
       DES_USUARIO_MODIFICACION
  FROM SAPR_TGRUPO_DOCUMENTO
  WHERE OID_GRUPO_DOCUMENTO = []pOID_GRUPO_DOCUMENTO