create or replace trigger TRG_SAPR_TDOCUMENTO
after update of BOL_NOTIFICADO, FYH_NOTIFICACION, BOL_ACREDITADO, FYH_ACREDITACION on SAPR_TDOCUMENTO for each row
DECLARE
    FYH_NOTIFICACION_GMT TIMESTAMP(6) WITH TIME ZONE;
    FYH_ACREDITACION_GMT TIMESTAMP(6) WITH TIME ZONE;
begin     
        
    IF :new.BOL_NOTIFICADO = 1 THEN 
    BEGIN
        SELECT TO_TIMESTAMP_TZ(TO_CHAR(:new.FYH_NOTIFICACION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (:new.FYH_NOTIFICACION ) >= DELEG.FYH_VERANO_INICIO AND (:new.FYH_NOTIFICACION ) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
        TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (:new.FYH_NOTIFICACION ) >= DELEG.FYH_VERANO_INICIO AND (:new.FYH_NOTIFICACION ) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
        TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (:new.FYH_NOTIFICACION ) >= DELEG.FYH_VERANO_INICIO AND (:new.FYH_NOTIFICACION ) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM')
        INTO FYH_NOTIFICACION_GMT
        FROM SAPR_VCUENTA VISTA_CUENTA 
        INNER JOIN GEPR_TDELEGACION DELEG ON DELEG.OID_DELEGACION = VISTA_CUENTA.OID_DELEGACION
        WHERE
        VISTA_CUENTA.OID_CUENTA = :old.OID_CUENTA_SALDO_ORIGEN;
        
        UPDATE SAPR_TMOVIMIENTO SET BOL_NOTIFICADO = :new.BOL_NOTIFICADO, FYH_NOTIFICACION = FYH_NOTIFICACION_GMT, 
        GMT_MODIFICACION = SYSTIMESTAMP, DES_USUARIO_MODIFICACION = 'TRG_SAPR_TDOCUMENTO'
        WHERE OID_DOCUMENTO = :old.OID_DOCUMENTO;
    END;
    END IF;
    
    IF :new.BOL_ACREDITADO = 1 THEN 
    BEGIN
        SELECT TO_TIMESTAMP_TZ(TO_CHAR(:new.FYH_ACREDITACION + ((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (:new.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (:new.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END) / 1440), 'DD/MM/YYYY HH24:MI:SS ') ||  
        TRIM(TO_CHAR(ROUND((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (:new.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (:new.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END)/ 60), '09')) || ':' || 
        TRIM(TO_CHAR(MOD((NVL(DELEG.NEC_GMT_MINUTOS, 0) + CASE WHEN (:new.FYH_ACREDITACION) >= DELEG.FYH_VERANO_INICIO AND (:new.FYH_ACREDITACION) <= DELEG.FYH_VERANO_FIN THEN NVL(DELEG.NEC_VERANO_AJUSTE, 0) ELSE 0 END), 60), '09')), 'DD/MM/YYYY HH24:MI:SS TZH:TZM')
        INTO FYH_ACREDITACION_GMT
        FROM SAPR_VCUENTA VISTA_CUENTA 
        INNER JOIN GEPR_TDELEGACION DELEG ON DELEG.OID_DELEGACION = VISTA_CUENTA.OID_DELEGACION
        WHERE
        VISTA_CUENTA.OID_CUENTA = :old.OID_CUENTA_SALDO_ORIGEN;
        
        UPDATE SAPR_TMOVIMIENTO SET BOL_ACREDITADO = :new.BOL_ACREDITADO, FYH_ACREDITACION = FYH_ACREDITACION_GMT, 
        GMT_MODIFICACION = SYSTIMESTAMP, DES_USUARIO_MODIFICACION = 'TRG_SAPR_TDOCUMENTO'
        WHERE OID_DOCUMENTO = :old.OID_DOCUMENTO;
    END;
    END IF;
end;