create or replace TRIGGER TRG_SAPR_TDATO_BANCARIO_AFTER
    AFTER UPDATE ON SAPR_TDATO_BANCARIO FOR EACH ROW
BEGIN
    INSERT INTO SAPR_THIST_DATO_BANCARIO (
    OID_HIST_DATO_BANCARIO, OID_DATO_BANCARIO, OID_BANCO, OID_CLIENTE, OID_SUBCLIENTE, OID_PTO_SERVICIO,
        OID_DIVISA, COD_TIPO_CUENTA_BANCARIA, COD_CUENTA_BANCARIA, COD_DOCUMENTO, DES_TITULARIDAD, DES_OBSERVACIONES,
        BOL_DEFECTO, BOL_ACTIVO, COD_AGENCIA, DES_CAMPO_ADICIONAL_1, DES_CAMPO_ADICIONAL_2, DES_CAMPO_ADICIONAL_3,
        DES_CAMPO_ADICIONAL_4, DES_CAMPO_ADICIONAL_5, DES_CAMPO_ADICIONAL_6, DES_CAMPO_ADICIONAL_7, DES_CAMPO_ADICIONAL_8, 
        GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), :OLD.OID_DATO_BANCARIO, :OLD.OID_BANCO, :OLD.OID_CLIENTE, :OLD.OID_SUBCLIENTE, :OLD.OID_PTO_SERVICIO, 
        :OLD.OID_DIVISA, :OLD.COD_TIPO_CUENTA_BANCARIA, :OLD.COD_CUENTA_BANCARIA, :OLD.COD_DOCUMENTO, :OLD.DES_TITULARIDAD, :OLD.DES_OBSERVACIONES,
        :OLD.BOL_DEFECTO, :OLD.BOL_ACTIVO, :OLD.COD_AGENCIA, :OLD.DES_CAMPO_ADICIONAL_1, :OLD.DES_CAMPO_ADICIONAL_2, :OLD.DES_CAMPO_ADICIONAL_3,
        :OLD.DES_CAMPO_ADICIONAL_4, :OLD.DES_CAMPO_ADICIONAL_5, :OLD.DES_CAMPO_ADICIONAL_6, :OLD.DES_CAMPO_ADICIONAL_7, :OLD.DES_CAMPO_ADICIONAL_8,
        SYSTIMESTAMP, :OLD.DES_USUARIO_CREACION, SYSTIMESTAMP, :OLD.DES_USUARIO_MODIFICACION);
END;