SELECT T.OID_TIPO_SECTOR,
       T.COD_TIPO_SECTOR,
       T.DES_TIPO_SECTOR,
       T.COD_MIGRACION,
       T.BOL_ACTIVO,
       T.GMT_CREACION,
       T.DES_USUARIO_CREACION,
       T.GMT_MODIFICACION,
       T.DES_USUARIO_MODIFICACION
  FROM GEPR_TTIPO_SECTOR T
  INNER JOIN GEPR_TTIPO_SECTORXPLANTA TP ON (TP.OID_TIPO_SECTOR = T.OID_TIPO_SECTOR)
  INNER JOIN GEPR_TPLANTA P ON (TP.OID_PLANTA = P.OID_PLANTA)
  INNER JOIN GEPR_TDELEGACION D ON (D.OID_DELEGACION = P.OID_DELEGACION)
  WHERE D.COD_DELEGACION = []pCOD_DELEGACION
  AND P.COD_PLANTA = []pCOD_PLANTA
