SELECT DISTINCT 
      TS.OID_TIPO_SECTOR,
      TS.COD_TIPO_SECTOR,
      TS.DES_TIPO_SECTOR,
      TS.COD_MIGRACION,
      TS.BOL_ACTIVO,
      TS.GMT_CREACION,
      TS.DES_USUARIO_CREACION,
      TS.GMT_MODIFICACION,
      TS.DES_USUARIO_MODIFICACION
FROM GEPR_TTIPO_SECTOR TS
INNER JOIN GEPR_TTIPO_SECTORXFORMULARIO TSF
ON TS.OID_TIPO_SECTOR = TSF.OID_TIPO_SECTOR
INNER JOIN SAPR_TFORMULARIO F
ON F.OID_FORMULARIO = TSF.OID_FORMULARIO
WHERE F.OID_FORMULARIO = []OID_FORMULARIO