SELECT TS.BOL_ACTIVO,
       TS.COD_MIGRACION,
       TS.COD_TIPO_SECTOR,
       TS.DES_TIPO_SECTOR,
       TS.DES_USUARIO_CREACION,
       TS.DES_USUARIO_MODIFICACION,
       TS.GMT_CREACION,
       TS.GMT_MODIFICACION,
       TS.OID_TIPO_SECTOR
FROM GEPR_TTIPO_SECTOR TS
WHERE TS.OID_TIPO_SECTOR = (SELECT OID_TIPO_SECTOR FROM GEPR_TSECTOR S WHERE S.OID_SECTOR = []OID_SECTOR)