SELECT
      TS.OID_TIPO_SECTOR,
      TS.COD_TIPO_SECTOR,
      TS.DES_TIPO_SECTOR,
      TS.COD_MIGRACION,
      TS.BOL_ACTIVO,
      TS.GMT_CREACION,
      TS.DES_USUARIO_CREACION,
      TS.GMT_MODIFICACION,
      TS.DES_USUARIO_MODIFICACION
FROM GEPR_TTIPO_SECTOR TS
WHERE TS.BOL_ACTIVO = 1