UPDATE GEPR_TPROCESO_POR_PSERVICIO
SET FYH_ACTUALIZACION = 
	CASE 
	WHEN OID_CLIENTE_FACTURACION IS NULL AND LENGTH([]COD_CLIENTE) > 0 THEN
		[]FYH_ACTUALIZACION 
	WHEN OID_CLIENTE_FACTURACION IS NOT NULL AND OID_CLIENTE_FACTURACION <> (SELECT OID_CLIENTE FROM GEPR_TCLIENTE WHERE COD_CLIENTE = []COD_CLIENTE AND ROWNUM = 1) THEN 
		[]FYH_ACTUALIZACION 
	WHEN OID_IAC IS NULL AND LENGTH([]COD_IAC) > 0 THEN
		[]FYH_ACTUALIZACION 
	WHEN OID_IAC IS NOT NULL AND OID_IAC <> (SELECT OID_IAC FROM GEPR_TINFORM_ADICIONAL_CLIENTE WHERE COD_IAC = []COD_IAC AND ROWNUM = 1) THEN
		[]FYH_ACTUALIZACION 
	WHEN BOL_VIGENTE = 0 THEN
		[]FYH_ACTUALIZACION 
	ELSE 
		FYH_ACTUALIZACION 
	END,
	OID_CLIENTE_FACTURACION = (SELECT OID_CLIENTE FROM GEPR_TCLIENTE WHERE COD_CLIENTE = []COD_CLIENTE AND ROWNUM = 1),
	OID_IAC = (SELECT OID_IAC FROM GEPR_TINFORM_ADICIONAL_CLIENTE WHERE COD_IAC = []COD_IAC AND ROWNUM = 1),
	BOL_VIGENTE = 1	
WHERE OID_PROCESO_POR_PSERVICIO = []OID_PROCESO_POR_PSERVICIO