SELECT OID_PROCESO_POR_PSERVICIO
FROM GEPR_TPROCESO_POR_PSERVICIO PROPSERV
INNER JOIN GEPR_TCLIENTE CLI ON PROPSERV.OID_CLIENTE = CLI.OID_CLIENTE
LEFT JOIN GEPR_TSUBCLIENTE SUBCLI ON SUBCLI.OID_SUBCLIENTE = PROPSERV.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PTOSERV ON PTOSERV.OID_PTO_SERVICIO = PROPSERV.OID_PTO_SERVICIO
WHERE OID_PROCESO = []OID_PROCESO 
AND CLI.COD_CLIENTE = []COD_CLIENTE
AND PROPSERV.BOL_VIGENTE = 1
