SELECT
  OID_CONFIGURACION,
  COD_CONFIGURACION,
  DES_CONFIGURACION,
  COD_CLIENTE,
  COD_SUBCLIENTE,
  COD_PTO_SERVICIO,
  COD_CANAL,
  COD_SUBCANAL,
  COD_DELEGACION,
  NEC_FORMATO_ARCHIVO,
  NEC_TIPO_ARCHIVO,
  DES_OBSERVACION,
  BIN_CONFIGURACION_CP,
  COD_USUARIO,
  FYH_ACTUALIZACION,
  BOL_VIGENTE
FROM
  GEPR_TCONFIGURACION_CP
  WHERE OID_CONFIGURACION = []OID_CONFIGURACION
  AND COD_CONFIGURACION = []COD_CONFIGURACION
