SELECT PF.IdFormulario,
       PF.Descripcion,
       PF.IdMotivo,
       PF.SoloEnGrupo,
       PF.ConValores,
       PF.ConBultos,
       PF.ConLector,
       PF.BasadoEnReporte,
       PF.IdReporte,
       PF.BasadoEnSaldos,
       PF.SeImprime,
       PF.Interplantas,
       PF.DistinguirPorNivel,
       PF.Matrices,
       PF.SoloIndividual,
       PF.EsActaProceso,
       PF.SoloSaldoDisponible,
       PF.Color,
       PF.Sustituible,
       PF.BasadoEnExtracto,
       PF.TotalCero,
       PF.BOL_VALIDAR_NUM_EXT_EXISTENTE,
       C.IdCampo,
       C.Nombre,
       C.Clase,
       C.Coleccion,
       C.Etiqueta,
       C.Tipo,
       C.Orden
  FROM PD_Formulario PF
  INNER JOIN PD_FormularioCampo FC ON FC.Idformulario = PF.Idformulario
  INNER JOIN PD_Campo C ON FC.IdCampo = C.IdCampo