UPDATE GEPR_TCARAC_POR_TIPO_PROCESADO
SET
BOL_VIGENTE = []BOL_VIGENTE,
COD_USUARIO = []COD_USUARIO,
FYH_ACTUALIZACION = []FYH_ACTUALIZACION
WHERE
OID_CARACT_TIPO_PROCESADO = []OID_CARACT_TIPO_PROCESADO