INSERT INTO GEPR_TCARACTERISTICA 
	(OID_CARACTERISTICA, COD_CARACTERISTICA, DES_CARACTERISTICA, OBS_CARACTERISTICA, COD_CARACTERISTICA_CONTEO, BOL_VIGENTE, COD_USUARIO, FYH_ACTUALIZACION)
VALUES
	([]OID_CARACTERISTICA, []COD_CARACTERISTICA, []DES_CARACTERISTICA, []OBS_CARACTERISTICA, []COD_CARACTERISTICA_CONTEO, []BOL_VIGENTE, []COD_USUARIO, []FYH_ACTUALIZACION)
