SELECT CARAC.COD_CARACTERISTICA, CARACTP.BOL_VIGENTE
FROM GEPR_TCARACTERISTICA CARAC
INNER JOIN GEPR_TCARAC_POR_TIPO_PROCESADO CARACTP ON CARACTP.OID_CARACTERISTICA = CARAC.OID_CARACTERISTICA
INNER JOIN GEPR_TTIPO_PROCESADO TP ON TP.OID_TIPO_PROCESADO = CARACTP.OID_TIPO_PROCESADO
WHERE TP.COD_TIPO_PROCESADO = []COD_TIPO_PROCESADO