SELECT 
	C.COD_CARACTERISTICA, 
	C.DES_CARACTERISTICA, 
	C.COD_CARACTERISTICA_CONTEO 
FROM 
	GEPR_TCARACTERISTICA C
	INNER JOIN GEPR_TCARAC_POR_TIPO_PROCESADO CTP ON CTP.OID_CARACTERISTICA = C.OID_CARACTERISTICA
WHERE
	CTP.OID_TIPO_PROCESADO = []OID_TIPO_PROCESADO