SELECT
	COUNT(0) AS QUANTIDADE
FROM
	GEPR_TCARACTERISTICA C
	INNER JOIN GEPR_TCARAC_POR_TIPO_PROCESADO CPTP ON
		C.OID_CARACTERISTICA = CPTP.OID_CARACTERISTICA
WHERE
	C.COD_CARACTERISTICA = []COD_CARACTERISTICA
	