UPDATE GEPR_TSUBCLIENTE
   SET COD_SUBCLIENTE           = []COD_SUBCLIENTE,
       OID_CLIENTE              = []OID_CLIENTE,
       DES_SUBCLIENTE           = []DES_SUBCLIENTE,
       BOL_VIGENTE				= []BOL_VIGENTE,
       FYH_ACTUALIZACION		= []FYH_ACTUALIZACION,
       OID_TIPO_SUBCLIENTE      = []OID_TIPO_SUBCLIENTE,
       BOL_TOTALIZADOR_SALDO	= []BOL_TOTALIZADOR_SALDO,
	   COD_USUARIO				= []COD_USUARIO
 WHERE OID_SUBCLIENTE           = []OID_SUBCLIENTE