UPDATE GEPR_TSUBCLIENTE 
SET BOL_ENVIADO_SALDOS = []BOL_ENVIADO_SALDOS 
WHERE
     COD_SUBCLIENTE = []COD_SUBCLIENTE AND 
     OID_CLIENTE = (SELECT OID_CLIENTE
                    FROM GEPR_TCLIENTE
                    WHERE COD_CLIENTE = []COD_CLIENTE)