INSERT INTO GEPR_TSUBCLIENTE (OID_SUBCLIENTE, OID_CLIENTE, COD_SUBCLIENTE, DES_SUBCLIENTE, BOL_VIGENTE, COD_USUARIO, FYH_ACTUALIZACION) 
VALUES 
([]OID_SUBCLIENTE, []OID_CLIENTE, []COD_SUBCLIENTE, []DES_SUBCLIENTE, []BOL_VIGENTE, []COD_USUARIO, []FYH_ACTUALIZACION)