UPDATE GEPR_TSUBCLIENTE
SET BOL_VIGENTE = 0, COD_USUARIO = []COD_USUARIO, FYH_ACTUALIZACION = []FYH_ACTUALIZACION
WHERE OID_CLIENTE IN (SELECT CLI.OID_CLIENTE 
FROM GEPR_TCLIENTE CLI INNER JOIN GEPR_TSUBCLIENTE SUBC ON CLI.OID_CLIENTE = SUBC.OID_CLIENTE
WHERE CLI.COD_CLIENTE = []COD_CLIENTE)