SELECT CLI.COD_CLIENTE, CLI.DES_CLIENTE, 
SUBC.COD_SUBCLIENTE,
SUBC.DES_SUBCLIENTE,
SUBC.OID_SUBCLIENTE,
SUBC.BOL_TOTALIZADOR_SALDO,
CA.COD_AJENO,
CA.DES_AJENO
FROM GEPR_TCLIENTE CLI INNER JOIN GEPR_TSUBCLIENTE SUBC ON CLI.OID_CLIENTE = SUBC.OID_CLIENTE
LEFT JOIN GEPR_TCODIGO_AJENO CA
ON CA.OID_TABLA_GENESIS = SUBC.Oid_Subcliente AND  CA.COD_TIPO_TABLA_GENESIS = 'GEPR_TSUBCLIENTE' AND CA.BOL_DEFECTO = 1 AND CA.BOL_ACTIVO = 1
WHERE 1=1 
 {0}
ORDER BY CLI.COD_CLIENTE, SUBC.COD_SUBCLIENTE