SELECT S.OID_SUBCLIENTE,
	   S.OID_CLIENTE,
       S.COD_SUBCLIENTE,
       S.DES_SUBCLIENTE,
       S.BOL_VIGENTE,
       S.COD_USUARIO,
       S.FYH_ACTUALIZACION,
       S.BOL_ENVIADO_SALDOS,
       S.OID_TIPO_SUBCLIENTE,
       S.COD_MIGRACION,
       S.BOL_TOTALIZADOR_SALDO,
       T.COD_TIPO_SUBCLIENTE,
       T.DES_TIPO_SUBCLIENTE,
	   C.COD_CLIENTE,
	   C.DES_CLIENTE
FROM GEPR_TSUBCLIENTE S
  INNER JOIN GEPR_TCLIENTE C
	ON S.OID_CLIENTE = C.OID_CLIENTE
   LEFT JOIN GEPR_TTIPO_SUBCLIENTE T
    ON S.OID_TIPO_SUBCLIENTE = T.OID_TIPO_SUBCLIENTE
 WHERE 1 = 1