WITH PAIS AS(
    SELECT
          P.OID_PAIS,
          P.COD_PAIS,
          P.DES_PAIS,
          P.BOL_ACTIVO,
          P.GMT_CREACION,
          P.DES_USUARIO_CREACION,
          P.GMT_MODIFICACION,
          P.DES_USUARIO_MODIFICACION,
          1 ORDEN
    FROM GEPR_TPAIS P
    WHERE P.COD_PAIS = []COD_PAIS
    UNION
    SELECT
      P.OID_PAIS,
      P.COD_PAIS,
      P.DES_PAIS,
      P.BOL_ACTIVO,
      P.GMT_CREACION,
      P.DES_USUARIO_CREACION,
      P.GMT_MODIFICACION,
      P.DES_USUARIO_MODIFICACION,
      2 ORDEN
    FROM GEPR_TPAIS P
    WHERE ROWNUM = 1
)
SELECT
      OID_PAIS,
      COD_PAIS,
      DES_PAIS,
      BOL_ACTIVO,
      GMT_CREACION,
      DES_USUARIO_CREACION,
      GMT_MODIFICACION,
      DES_USUARIO_MODIFICACION,
      ORDEN
      FROM PAIS 
      WHERE ROWNUM = 1 
      ORDER BY ORDEN