SELECT
      P.OID_PAIS,
      P.COD_PAIS,
      P.DES_PAIS,
      P.BOL_ACTIVO,
      P.GMT_CREACION,
      P.DES_USUARIO_CREACION,
      P.GMT_MODIFICACION,
      P.DES_USUARIO_MODIFICACION
FROM GEPR_TPAIS P
WHERE P.COD_PAIS = []COD_PAIS