SELECT
      P.OID_PAIS,
      P.COD_PAIS,
      P.DES_PAIS,
      P.BOL_ACTIVO,
      P.GMT_CREACION,
      P.DES_USUARIO_CREACION,
      P.GMT_MODIFICACION,
      P.DES_USUARIO_MODIFICACION
FROM GEPR_TPAIS P 
INNER JOIN GEPR_TDELEGACION D ON P.COD_PAIS = D.COD_PAIS
INNER JOIN GEPR_TCODIGO_AJENO CAPA ON CAPA.OID_TABLA_GENESIS = P.OID_PAIS AND CAPA.COD_TIPO_TABLA_GENESIS = 'GEPR_TPAIS'
INNER JOIN GEPR_TCODIGO_AJENO CADE ON CADE.OID_TABLA_GENESIS = D.OID_DELEGACION AND CADE.COD_TIPO_TABLA_GENESIS = 'GEPR_TDELEGACION'
WHERE CADE.COD_AJENO = []COD_DELEGACION