SELECT
      P.OID_PAIS,
      P.COD_PAIS,
      P.DES_PAIS,
      P.BOL_ACTIVO,
      P.GMT_CREACION,
      P.DES_USUARIO_CREACION,
      P.GMT_MODIFICACION,
      P.DES_USUARIO_MODIFICACION
FROM GEPR_TPAIS P INNER JOIN GEPR_TDELEGACION D
ON P.COD_PAIS = D.COD_PAIS
WHERE D.COD_DELEGACION = []COD_DELEGACION