		SELECT TBU.OID_TIPO_BULTO
          ,TBU.COD_TIPO_BULTO
          ,TBU.DES_TIPO_BULTO
		  ,TBU.BOL_CAJETIN
          ,TBD.COD_DELEGACION
          ,TBD.NEC_PRIORIDAD
		  ,TBU.COD_FORMATO
		FROM GEPR_TTIPO_BULTO TBU
    INNER JOIN GEPR_TTIPO_BULTO_DISP TBD ON TBU.OID_TIPO_BULTO = TBD.OID_TIPO_BULTO
	{0}
	ORDER BY TBU.DES_TIPO_BULTO