SELECT TIP.COD_TIPO_BULTO
,TIP.NUM_IMPORTE_MAXIMO_SEGURO
,TIP.BOL_APTO_PICOS
,TIP.BOL_APTO_MEZCLA
,DIV.COD_ISO_DIVISA
,DEN.COD_DENOMINACION
,DEN.NUM_VALOR_FACIAL
,DEN.BOL_BILLETE
,IMP.NEL_MAXIMO_UNIDADES
,NVL(IMP.NEC_AGRUPACION,0) AS NEC_AGRUPACION
,DEN.DES_DENOMINACION
,DEN.OID_DENOMINACION
FROM GEPR_TTIPO_BULTO_DISP DIS 
INNER JOIN GEPR_TTIPO_BULTO TIP ON DIS.OID_TIPO_BULTO = TIP.OID_TIPO_BULTO 
INNER JOIN GEPR_TIMPORTE_ESTAND_BULTO IMP ON TIP.OID_TIPO_BULTO = IMP.OID_TIPO_BULTO
INNER JOIN GEPR_TDENOMINACION DEN ON IMP.OID_DENOMINACION = DEN.OID_DENOMINACION
INNER JOIN GEPR_TDIVISA DIV ON DEN.OID_DIVISA = DIV.OID_DIVISA
WHERE DIS.COD_DELEGACION = :COD_DELEGACION
AND DIV.COD_ISO_DIVISA || '|' || DEN.COD_DENOMINACION IN ({0})
ORDER BY DIV.COD_ISO_DIVISA, DEN.BOL_BILLETE DESC, DEN.NUM_VALOR_FACIAL