SELECT TBU.OID_TIPO_BULTO
	  ,TBU.COD_TIPO_BULTO
	  ,TBU.DES_TIPO_BULTO
	  ,TBU.NUM_IMPORTE_MAXIMO_SEGURO
	  ,TBU.BOL_APTO_PICOS
	  ,TBU.BOL_APTO_MEZCLA
	  ,TBU.COD_USUARIO
	  ,TBU.FYH_ACTUALIZACION
	  ,TBU.BOL_CAJETIN
	  ,TBU.BOL_MEDIO_PAGO
	  ,TBU.COD_FORMATO
FROM GEPR_TTIPO_BULTO TBU