SELECT
OID_TRANSACCION_EFECTIVO
,OID_DOCUMENTO
,OID_CUENTA
,OID_CUENTA_SALDO
,OID_DIVISA
,OID_DENOMINACION
,OID_CERTIFICADO
,COD_NIVEL_DETALLE
,COD_TIPO_EFECTIVO_TOTAL
,BOL_DISPONIBLE
,NUM_IMPORTE
,NEL_CANTIDAD
,COD_ESTADO_DOCUMENTO
,COD_TIPO_MOVIMIENTO
,OBS_TRANSACCION
,COD_MIGRACION
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION
,COD_TIPO_SITIO
,OID_UNIDAD_MEDIDA
,OID_CALIDAD
,BOL_CONTRA_MOVIMIENTO
,FYH_PLAN_CERTIFICACION
FROM SAPR_TTRANSACCION_EFECTIVO
WHERE BOL_CONTRA_MOVIMIENTO = 0 -- somente transações que não foram anuladas
AND OID_DOCUMENTO			=[]OID_DOCUMENTO
AND COD_ESTADO_DOCUMENTO	=[]COD_ESTADO_DOCUMENTO
ORDER BY GMT_CREACION