INSERT INTO SAPR_TTRANSACCION_EFECTIVO 
(OID_TRANSACCION_EFECTIVO
,OID_DOCUMENTO
,OID_CUENTA
,OID_CUENTA_SALDO
,OID_DIVISA
,OID_DENOMINACION
,OID_CERTIFICADO
,OID_UNIDAD_MEDIDA
,COD_NIVEL_DETALLE
,COD_TIPO_EFECTIVO_TOTAL
,OID_CALIDAD
,BOL_DISPONIBLE
,NUM_IMPORTE
,NEL_CANTIDAD
,COD_ESTADO_DOCUMENTO
,COD_TIPO_SITIO
,COD_TIPO_MOVIMIENTO
,OBS_TRANSACCION
,COD_MIGRACION
,FYH_PLAN_CERTIFICACION
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,BOL_CONTRA_MOVIMIENTO
,DES_USUARIO_MODIFICACION)
SELECT []OID_TRANSACCION_EFECTIVO
,[]OID_DOCUMENTO
,OID_CUENTA
,OID_CUENTA_SALDO
,OID_DIVISA
,OID_DENOMINACION
,NULL OID_CERTIFICADO
,OID_UNIDAD_MEDIDA
,COD_NIVEL_DETALLE
,COD_TIPO_EFECTIVO_TOTAL
,OID_CALIDAD
,BOL_DISPONIBLE
,NUM_IMPORTE * (-1) -- Inverte o valor
,NEL_CANTIDAD * (-1) -- Inverte o valor
,[]COD_ESTADO_DOCUMENTO
,[]COD_TIPO_SITIO
,COD_TIPO_MOVIMIENTO
,OBS_TRANSACCION
,COD_MIGRACION
,[]FYH_PLAN_CERTIFICACION
,FN_GMT_ZERO_###VERSION###
,[]USUARIO
,FN_GMT_ZERO_###VERSION###
,1 -- Anulado
,[]USUARIO
FROM SAPR_TTRANSACCION_EFECTIVO
WHERE OID_TRANSACCION_EFECTIVO  =[]OID_TRANSACCION_EFECTIVO_ATUAL