    SELECT 1
      FROM SAPR_TDOCUMENTO D
INNER JOIN SAPR_TTRANSACCION_EFECTIVO TE ON TE.OID_DOCUMENTO = D.OID_DOCUMENTO
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = TE.OID_CUENTA_SALDO
INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = CU.OID_SECTOR
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DL ON DL.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
INNER JOIN SAPR_TTIPO_DOCUMENTO TP ON D.OID_TIPO_DOCUMENTO = TP.OID_TIPO_DOCUMENTO
     WHERE ROWNUM = 1 
	   AND D.FYH_PLAN_CERTIFICACION <= []FYH_PLAN_CERTIFICACION 
	   AND TE.FYH_PLAN_CERTIFICACION <= []FYH_PLAN_CERTIFICACION 
	   AND D.BOL_CERTIFICADO = []BOL_CERTIFICADO 
	   AND CL.COD_CLIENTE = []COD_CLIENTE
       AND TP.BOL_CERTIFICACION = 1 
	   AND NOT EXISTS (SELECT CER.OID_CERTIFICADO FROM SAPR_TCERTIFICADO CER WHERE CER.OID_CERTIFICADO = TE.OID_CERTIFICADO AND CER.COD_ESTADO = 'DE')
