WITH documentos AS (
      SELECT 
        DOCU.OID_DOCUMENTO,       
        CLI_O.OID_CLIENTE AS OID_CLIENTE_ORIGEN,
        CLI_O.COD_CLIENTE AS COD_CLIENTE_ORIGEN,
        CLI_O.DES_CLIENTE AS DES_CLIENTE_ORIGEN,
        SBCLI_O.OID_SUBCLIENTE AS OID_SUBCLIENTE_ORIGEN,
        SBCLI_O.COD_SUBCLIENTE AS COD_SUBCLIENTE_ORIGEN,
        SBCLI_O.DES_SUBCLIENTE AS DES_SUBCLIENTE_ORIGEN,
        PT_O.OID_PTO_SERVICIO AS OID_PUNTO_SERVICIO_ORIGEN,
        PT_O.COD_PTO_SERVICIO AS COD_PUNTO_SERVICIO_ORIGEN,
        PT_O.DES_PTO_SERVICIO AS DES_PUNTO_SERVICIO_ORIGEN,
        CN_O.OID_CANAL AS OID_CANAL_ORIGEN,
        CN_O.COD_CANAL AS COD_CANAL_ORIGEN,
        CN_O.DES_CANAL AS DES_CANAL_ORIGEN,
        SC_O.OID_SUBCANAL AS OID_SUBCANAL_ORIGEN,
        SC_O.COD_SUBCANAL AS COD_SUBCANAL_ORIGEN,
        SC_O.DES_SUBCANAL AS DES_SUBCANAL_ORIGEN,
        CLI_D.OID_CLIENTE AS OID_CLIENTE_DESTINO,
        CLI_D.COD_CLIENTE AS COD_CLIENTE_DESTINO,
        CLI_D.DES_CLIENTE AS DES_CLIENTE_DESTINO,
        SBCLI_D.OID_SUBCLIENTE AS OID_SUBCLIENTE_DESTINO,
        SBCLI_D.COD_SUBCLIENTE AS COD_SUBCLIENTE_DESTINO,
        SBCLI_D.DES_SUBCLIENTE AS DES_SUBCLIENTE_DESTINO,
        PT_D.OID_PTO_SERVICIO AS OID_PUNTO_SERVICIO_DESTINO,
        PT_D.COD_PTO_SERVICIO AS COD_PUNTO_SERVICIO_DESTINO,
        PT_D.DES_PTO_SERVICIO AS DES_PUNTO_SERVICIO_DESTINO,
        CN_D.OID_CANAL AS OID_CANAL_DESTINO,
        CN_D.COD_CANAL AS COD_CANAL_DESTINO,
        CN_D.DES_CANAL AS DES_CANAL_DESTINO,
        SC_D.OID_SUBCANAL AS OID_SUBCANAL_DESTINO,
        SC_D.COD_SUBCANAL AS COD_SUBCANAL_DESTINO,
        SC_D.DES_SUBCANAL AS DES_SUBCANAL_DESTINO,   
        DOCU.COD_COMPROBANTE,
        DOCU.COD_EXTERNO COD_EXTERNO,
        to_char(DOCU.FYH_GESTION, 'YYYY-MM-DD HH24:MI:SS') || '+00:00'  AS FYH_GESTION,
        to_char(DOCU.gmt_creacion, 'YYYY-MM-DD HH24:MI:SS TZR') FECHA_RESOLUSION,
        DOCU.BOL_CERTIFICADO,
        FORM.OID_FORMULARIO,
        FORM.COD_FORMULARIO,
        FORM.DES_FORMULARIO,
        DOCU.OID_CUENTA_ORIGEN,
        DOCU.OID_CUENTA_DESTINO,
        DOCU.BOL_NOTIFICADO,        
        DOCU.BOL_ACREDITADO,
		{10}
        DEL_O.OID_DELEGACION AS OID_DELEGACION_ORIGEN,
        DEL_O.COD_DELEGACION AS COD_DELEGACION_ORIGEN,
        DEL_O.DES_DELEGACION AS DES_DELEGACION_ORIGEN,
        PL_O.OID_PLANTA AS OID_PLANTA_ORIGEN,
        PL_O.COD_PLANTA AS COD_PLANTA_ORIGEN,
        PL_O.DES_PLANTA AS DES_PLANTA_ORIGEN,
        SEC_O.OID_SECTOR AS OID_SECTOR_ORI,
        SEC_O.COD_SECTOR AS COD_SECTOR_ORI,
        SEC_O.DES_SECTOR AS DES_SECTOR_ORI,
        DEL_D.OID_DELEGACION AS OID_DELEGACION_DESTINO,
        DEL_D.COD_DELEGACION AS COD_DELEGACION_DESTINO,
        DEL_D.DES_DELEGACION AS DES_DELEGACION_DESTINO,
        PL_D.OID_PLANTA AS OID_PLANTA_DESTINO,
        PL_D.COD_PLANTA AS COD_PLANTA_DESTINO,
        PL_D.DES_PLANTA AS DES_PLANTA_DESTINO,
        SEC_D.OID_SECTOR AS OID_SECTOR_DESTINO,
        SEC_D.COD_SECTOR AS COD_SECTOR_DESTINO,
        SEC_D.DES_SECTOR AS DES_SECTOR_DESTINO
        
      FROM SAPR_TDOCUMENTO DOCU
        INNER JOIN SAPR_TFORMULARIO FORM ON DOCU.OID_FORMULARIO = FORM.OID_FORMULARIO       
               
        INNER JOIN SAPR_TCUENTA CUEN_O ON CUEN_O.OID_CUENTA = DOCU.OID_CUENTA_ORIGEN
        INNER JOIN GEPR_TCLIENTE CLI_O ON CLI_O.OID_CLIENTE = CUEN_O.OID_CLIENTE
        INNER JOIN GEPR_TSUBCANAL SC_O ON SC_O.OID_SUBCANAL = CUEN_O.OID_SUBCANAL
        INNER JOIN GEPR_TCANAL CN_O ON CN_O.OID_CANAL = SC_O.OID_CANAL
        LEFT OUTER JOIN GEPR_TSUBCLIENTE SBCLI_O ON SBCLI_O.OID_SUBCLIENTE = CUEN_O.OID_SUBCLIENTE
        LEFT OUTER JOIN GEPR_TPUNTO_SERVICIO PT_O ON PT_O.OID_PTO_SERVICIO = CUEN_O.OID_PTO_SERVICIO

        INNER JOIN SAPR_TCUENTA CUEN_D ON CUEN_D.OID_CUENTA = DOCU.OID_CUENTA_DESTINO
        INNER JOIN GEPR_TCLIENTE CLI_D ON CLI_D.OID_CLIENTE = CUEN_D.OID_CLIENTE
        INNER JOIN GEPR_TSUBCANAL SC_D ON SC_D.OID_SUBCANAL = CUEN_D.OID_SUBCANAL
        INNER JOIN GEPR_TCANAL CN_D ON CN_D.OID_CANAL = SC_D.OID_CANAL
        LEFT OUTER JOIN GEPR_TSUBCLIENTE SBCLI_D ON SBCLI_D.OID_SUBCLIENTE = CUEN_D.OID_SUBCLIENTE
        LEFT OUTER JOIN GEPR_TPUNTO_SERVICIO PT_D ON PT_D.OID_PTO_SERVICIO = CUEN_D.OID_PTO_SERVICIO
      
        INNER JOIN GEPR_TSECTOR SEC_O ON SEC_O.OID_SECTOR = DOCU.OID_SECTOR_ORIGEN  
        INNER JOIN GEPR_TPLANTA PL_O ON PL_O.OID_PLANTA = SEC_O.OID_PLANTA  
        INNER JOIN GEPR_TDELEGACION DEL_O ON DEL_O.OID_DELEGACION = PL_O.OID_DELEGACION  
        INNER JOIN GEPR_TSECTOR SEC_D ON SEC_D.OID_SECTOR = DOCU.OID_SECTOR_DESTINO  
        INNER JOIN GEPR_TPLANTA PL_D ON PL_D.OID_PLANTA = SEC_D.OID_PLANTA  
        INNER JOIN GEPR_TDELEGACION DEL_D ON DEL_D.OID_DELEGACION = PL_D.OID_DELEGACION

		{7}
        
        WHERE DOCU.COD_ESTADO = 'AC'
         {0}

         ),
		   {13}
trans As (
             SELECT 
                       
              TRANS.OID_DOCUMENTO OID_DOCUMENTO_TRANS,     
              TRANS.OID_DIVISA,
              SUM(TRANS.NUM_IMPORTE) NUM_IMPORTE,
              SUM(TRANS.NEL_CANTIDAD) NEL_CANTIDAD,
              TRANS.BOL_DISPONIBLE,
              TRANS.BOL_CERTIFICADO
              {1}
             FROM SAPR_TTRANSACCION_EFECTIVO TRANS
              INNER JOIN documentos DOCU ON DOCU.OID_DOCUMENTO = TRANS.OID_DOCUMENTO
			  {2}
			  WHERE 1=1 
			  {9}
			  GROUP BY  TRANS.OID_DOCUMENTO, TRANS.OID_DIVISA,
			  TRANS.BOL_DISPONIBLE, TRANS.BOL_CERTIFICADO
			  {16}
			  --[MEDIOPAGO]
             UNION ALL
             SELECT
                TRANS.OID_DOCUMENTO OID_DOCUMENTO_TRANS,
                TRANS.OID_DIVISA,
                SUM(TRANS.NUM_IMPORTE) NUM_IMPORTE,
               SUM(TRANS.NEL_CANTIDAD) NEL_CANTIDAD,
                TRANS.BOL_DISPONIBLE,
                TRANS.BOL_CERTIFICADO    
				{3}      
              FROM SAPR_TTRANSACCION_MEDIO_PAGO TRANS
              INNER JOIN documentos DOCU ON DOCU.OID_DOCUMENTO = TRANS.OID_DOCUMENTO
			  {4}
			  WHERE 1=1
			  {9}
			  GROUP BY  TRANS.OID_DOCUMENTO, TRANS.OID_DIVISA,
			  TRANS.BOL_DISPONIBLE, TRANS.BOL_CERTIFICADO
			  {17}
			  --[MEDIOPAGO]
             )
SELECT 

   DOCU.OID_DOCUMENTO IDENTIFICADOR,
   DOCU.COD_EXTERNO,
   DOCU.COD_COMPROBANTE,
   DOCU.FYH_GESTION,
   DOCU.FECHA_RESOLUSION,
   DOCU.OID_FORMULARIO,
   DOCU.COD_FORMULARIO,
   DOCU.DES_FORMULARIO,
   TRANS.BOL_CERTIFICADO,
   TRANS.BOL_DISPONIBLE,
   
   DOCU.OID_CLIENTE_ORIGEN,
   DOCU.COD_CLIENTE_ORIGEN,
   DOCU.DES_CLIENTE_ORIGEN,
   DOCU.OID_SUBCLIENTE_ORIGEN,
        DOCU.COD_SUBCLIENTE_ORIGEN,
        DOCU.DES_SUBCLIENTE_ORIGEN,
    DOCU.OID_PUNTO_SERVICIO_ORIGEN,
        DOCU.COD_PUNTO_SERVICIO_ORIGEN,
        DOCU.DES_PUNTO_SERVICIO_ORIGEN,
    DOCU.OID_DELEGACION_ORIGEN,
    DOCU.COD_DELEGACION_ORIGEN,
    DOCU.DES_DELEGACION_ORIGEN,
    DOCU.OID_PLANTA_ORIGEN,
    DOCU.COD_PLANTA_ORIGEN,
    DOCU.DES_PLANTA_ORIGEN,
    DOCU.OID_SECTOR_ORI,
        DOCU.COD_SECTOR_ORI,
        DOCU.DES_SECTOR_ORI,
    DOCU.OID_CANAL_ORIGEN,
        DOCU.COD_CANAL_ORIGEN,
        DOCU.DES_CANAL_ORIGEN,    
    DOCU.OID_SUBCANAL_ORIGEN,
        DOCU.COD_SUBCANAL_ORIGEN,
        DOCU.DES_SUBCANAL_ORIGEN,
        
    DOCU.OID_CLIENTE_DESTINO,
        DOCU.COD_CLIENTE_DESTINO,
        DOCU.DES_CLIENTE_DESTINO,
    DOCU.OID_SUBCLIENTE_DESTINO,
        DOCU.COD_SUBCLIENTE_DESTINO,
        DOCU.DES_SUBCLIENTE_DESTINO,
    DOCU.OID_PUNTO_SERVICIO_DESTINO,
        DOCU.COD_PUNTO_SERVICIO_DESTINO,
        DOCU.DES_PUNTO_SERVICIO_DESTINO,
    DOCU.OID_DELEGACION_DESTINO,
    DOCU.COD_DELEGACION_DESTINO,
    DOCU.DES_DELEGACION_DESTINO,
    DOCU.OID_PLANTA_DESTINO,
    DOCU.COD_PLANTA_DESTINO,
    DOCU.DES_PLANTA_DESTINO,
    DOCU.OID_SECTOR_DESTINO,
        DOCU.COD_SECTOR_DESTINO,
        DOCU.DES_SECTOR_DESTINO,
    DOCU.OID_CANAL_DESTINO,
        DOCU.COD_CANAL_DESTINO,
        DOCU.DES_CANAL_DESTINO,    
    DOCU.OID_SUBCANAL_DESTINO,
        DOCU.COD_SUBCANAL_DESTINO,
        DOCU.DES_SUBCANAL_DESTINO,

        {11}
	        {12}
	{5}
FROM documentos DOCU
{14}
  LEFT JOIN trans ON trans.OID_DOCUMENTO_TRANS = DOCU.OID_DOCUMENTO
   {18}
  LEFT JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = trans.OID_DIVISA
WHERE 1=1 {8}
GROUP BY
    DOCU.OID_DOCUMENTO,
    DOCU.COD_EXTERNO,
    DOCU.COD_COMPROBANTE,
    DOCU.FYH_GESTION,
    DOCU.FECHA_RESOLUSION,
    DOCU.OID_FORMULARIO,
    DOCU.COD_FORMULARIO,
    DOCU.DES_FORMULARIO,
    TRANS.BOL_CERTIFICADO,
    TRANS.BOL_DISPONIBLE,
    DOCU.OID_CLIENTE_ORIGEN,
    DOCU.COD_CLIENTE_ORIGEN,
    DOCU.DES_CLIENTE_ORIGEN,
    DOCU.OID_SUBCLIENTE_ORIGEN,
    DOCU.COD_SUBCLIENTE_ORIGEN,
    DOCU.DES_SUBCLIENTE_ORIGEN,
    DOCU.OID_PUNTO_SERVICIO_ORIGEN,
    DOCU.COD_PUNTO_SERVICIO_ORIGEN,
    DOCU.DES_PUNTO_SERVICIO_ORIGEN,
    DOCU.OID_DELEGACION_ORIGEN,
    DOCU.COD_DELEGACION_ORIGEN,
    DOCU.DES_DELEGACION_ORIGEN,
    DOCU.OID_PLANTA_ORIGEN,
    DOCU.COD_PLANTA_ORIGEN,
    DOCU.DES_PLANTA_ORIGEN,
    DOCU.OID_SECTOR_ORI,
    DOCU.COD_SECTOR_ORI,
    DOCU.DES_SECTOR_ORI,
    DOCU.OID_CANAL_ORIGEN,
    DOCU.COD_CANAL_ORIGEN,
    DOCU.DES_CANAL_ORIGEN,    
    DOCU.OID_SUBCANAL_ORIGEN,
    DOCU.COD_SUBCANAL_ORIGEN,
    DOCU.DES_SUBCANAL_ORIGEN,
    DOCU.OID_CLIENTE_DESTINO,
    DOCU.COD_CLIENTE_DESTINO,
    DOCU.DES_CLIENTE_DESTINO,
    DOCU.OID_SUBCLIENTE_DESTINO,
    DOCU.COD_SUBCLIENTE_DESTINO,
    DOCU.DES_SUBCLIENTE_DESTINO,
    DOCU.OID_PUNTO_SERVICIO_DESTINO,
    DOCU.COD_PUNTO_SERVICIO_DESTINO,
    DOCU.DES_PUNTO_SERVICIO_DESTINO,
    DOCU.OID_DELEGACION_DESTINO,
    DOCU.COD_DELEGACION_DESTINO,
    DOCU.DES_DELEGACION_DESTINO,
    DOCU.OID_PLANTA_DESTINO,
    DOCU.COD_PLANTA_DESTINO,
    DOCU.DES_PLANTA_DESTINO,
    DOCU.OID_SECTOR_DESTINO,
    DOCU.COD_SECTOR_DESTINO,
    DOCU.DES_SECTOR_DESTINO,
    DOCU.OID_CANAL_DESTINO,
    DOCU.COD_CANAL_DESTINO,
    DOCU.DES_CANAL_DESTINO,    
    DOCU.OID_SUBCANAL_DESTINO,
    DOCU.COD_SUBCANAL_DESTINO,
    DOCU.DES_SUBCANAL_DESTINO,
    DIV.OID_DIVISA,
    DIV.COD_ISO_DIVISA,
	DOCU.BOL_NOTIFICADO,
    DIV.DES_DIVISA
	{6}
	{15}
    