UPDATE SAPR_TTRANSACCION_EFECTIVO
SET
OID_CERTIFICADO = []OID_CERTIFICADO_NUEVO,
GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###,
DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE
OID_CERTIFICADO = []OID_CERTIFICADO