SELECT DIV.COD_ISO_DIVISA,
       D.COD_DENOMINACION,
       TE.COD_NIVEL_DETALLE,
       TE.COD_TIPO_EFECTIVO_TOTAL,
       TE.BOL_DISPONIBLE,
       TE.NUM_IMPORTE,
       TE.NEL_CANTIDAD,
       TE.COD_ESTADO_DOCUMENTO,
       TE.COD_TIPO_MOVIMIENTO,
	   TE.OID_TRANSACCION_EFECTIVO,
	   TE.OID_DIVISA,
	   TE.OID_CALIDAD,
	   TE.OID_UNIDAD_MEDIDA,
	   TE.FYH_PLAN_CERTIFICACION
FROM SAPR_TTRANSACCION_EFECTIVO TE
LEFT JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = TE.OID_DENOMINACION
LEFT JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = D.OID_DIVISA
WHERE TE.OID_TRANSACCION_EFECTIVO = []OID_TRANSACCION_EFECTIVO

