INSERT INTO SAPR_TABONO_SNAPSHOT_MEDIOPAGO S
(S.OID_ABONO_SNAPSHOT_MEDIOPAGO,S.OID_ABONO_SNAPSHOT,S.OID_CUENTA_SALDO,S.OID_DIVISA,S.OID_MEDIO_PAGO,
S.COD_TIPO_MEDIO_PAGO,S.OID_UNIDAD_MEDIDA,S.COD_NIVEL_DETALLE,S.NUM_IMPORTE,
S.NEL_CANTIDAD,S.GMT_CREACION,S.DES_USUARIO_CREACION,S.GMT_MODIFICACION,S.DES_USUARIO_MODIFICACION)
VALUES
([]OID_ABONO_SNAPSHOT_MEDIOPAGO,[]OID_ABONO_SNAPSHOT,[]OID_CUENTA_SALDO,[]OID_DIVISA,[]OID_MEDIO_PAGO,
[]COD_TIPO_MEDIO_PAGO,[]OID_UNIDAD_MEDIDA,[]COD_NIVEL_DETALLE,[]NUM_IMPORTE,
[]NEL_CANTIDAD,FN_GMT_ZERO_###VERSION###,[]DES_USUARIO_CREACION,FN_GMT_ZERO_###VERSION###,[]DES_USUARIO_MODIFICACION)