INSERT INTO SAPR_TCERTIFICADOXSECTOR
(OID_CERTIFICADOXSECTOR,
OID_CERTIFICADO,
OID_SECTOR,
GMT_CREACION,
DES_USUARIO_CREACION,
GMT_MODIFICACION,
DES_USUARIO_MODIFICACION)
SELECT DISTINCT SYS_GUID() OID_CERTIFICADOXSECTOR,
                []OID_CERTIFICADO OID_CERTIFICADO,
                OID_SECTOR,
                FN_GMT_ZERO_###VERSION### GMT_CREACION,
                []DES_USUARIO_CREACION DES_USUARIO_CREACION,
                FN_GMT_ZERO_###VERSION###,
                []DES_USUARIO_MODIFICACION DES_USUARIO_MODIFICACION
FROM GEPR_TSECTOR