SELECT GEPR_TDELEGACION.COD_DELEGACION,
       GEPR_TDELEGACION.DES_DELEGACION,
       GEPR_TPUESTO.COD_PUESTO,
       GEPR_TPUESTO.COD_HOST_PUESTO,
       GEPR_TPUESTO.BOL_VIGENTE,
       GEPR_TAPLICACION.COD_APLICACION,
       GEPR_TAPLICACION.DES_APLICACION,
       GEPR_TAPLICACION.COD_PERMISO
FROM GEPR_TPUESTO INNER JOIN GEPR_TAPLICACION 
  ON GEPR_TPUESTO.OID_APLICACION = gepr_taplicacion.OID_APLICACION
INNER JOIN GEPR_TDELEGACION
  ON GEPR_TPUESTO.OID_DELEGACION = GEPR_TDELEGACION.OID_DELEGACION
where GEPR_TPUESTO.COD_HOST_PUESTO = []COD_HOST_PUESTO 
  AND GEPR_TAPLICACION.COD_APLICACION = []COD_APLICACION
  AND GEPR_TPUESTO.COD_PUESTO = UPPER([]COD_PUESTO)