INSERT INTO GEPR_TPUESTO 
	(COD_PUESTO
	,OID_PUESTO
	,OID_DELEGACION
	,OID_APLICACION
	,COD_HOST_PUESTO
	,BOL_VIGENTE
	,COD_USUARIO
	,FYH_ACTUALIZACION)
VALUES 
	([]COD_PUESTO
	,[]OID_PUESTO
	,[]OID_DELEGACION
	,[]OID_APLICACION
	,[]COD_HOST_PUESTO
	,[]BOL_VIGENTE
	,[]COD_USUARIO 
	,[]FYH_ACTUALIZACION)