SELECT COD_HOST_PUESTO FROM GEPR_TPUESTO 
INNER JOIN GEPR_TAPLICACION ON 
	GEPR_TAPLICACION.OID_APLICACION = GEPR_TPUESTO.OID_APLICACION
WHERE COD_HOST_PUESTO != []COD_HOST_PUESTO
AND COD_PUESTO = UPPER([]COD_PUESTO)
AND COD_APLICACION = []COD_APLICACION