SELECT 1
FROM GEPR_TPUESTO P
INNER JOIN GEPR_TAPLICACION A ON A.OID_APLICACION = P.OID_APLICACION
WHERE P.COD_PUESTO = UPPER([]COD_PUESTO) AND UPPER(P.COD_HOST_PUESTO) = []COD_HOST_PUESTO AND A.COD_APLICACION = []COD_APLICACION