SELECT  
	AGR.OID_AGRUPACION, 
	AGR.COD_AGRUPACION, 
	AGR.DES_AGRUPACION, 
	AGR.OBS_AGRUPACION, 
	AGRPRC.NUM_TOLERANCIA_PARCIAL_MIN, 
	AGRPRC.NUM_TOLERANCIA_PARCIAL_MAX, 
	AGRPRC.NUM_TOLERANCIA_BULTO_MIN, 
	AGRPRC.NUM_TOLERANCIA_BULTO_MAX, 
	AGRPRC.NUM_TOLERANCIA_REMESA_MIN, 
	AGRPRC.NUM_TOLERANCIA_REMESA_MAX, 
	AGR.BOL_VIGENTE 
FROM 
	GEPR_TAGRUPACION_POR_PROCESO AGRPRC 
	INNER JOIN GEPR_TAGRUPACION AGR ON AGRPRC.OID_AGRUPACION = AGR.OID_AGRUPACION 
WHERE 
	AGRPRC.OID_PROCESO = []OID_PROCESO