SELECT
        OID_INVENTARIO
        ,COD_INVENTARIO
        ,GMT_CREACION
        ,DES_USUARIO_CREACION
FROM RPGE_Yinventario
WHERE OID_SECTOR =[]OID_SECTOR
AND GMT_CREACION BETWEEN []DATA_INICIAL AND []DATA_FINAL
