SELECT COD_CARACT_FORMULARIO
FROM SAPR_TCARACT_FORMULARIO CF 
INNER JOIN SAPR_TCARACTFORMXFORMULARIO CFF ON CFF.OID_CARACT_FORMULARIO = CF.OID_CARACT_FORMULARIO
WHERE OID_FORMULARIO =[]OID_FORMULARIO AND COD_TIPO_CARACTERISTICA = 'F'