INSERT INTO SAPR_TCARACTFORMXFORMULARIO
(OID_CARACTFORMXFORMULARIO
,OID_FORMULARIO
,OID_CARACT_FORMULARIO
,COD_MIGRACION
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION)
VALUES
([]OID_CARACTFORMXFORMULARIO
,[]OID_FORMULARIO
,[]OID_CARACT_FORMULARIO
,[]COD_MIGRACION
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_CREACION
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_MODIFICACION)