UPDATE GEPR_TCLIENTE
   SET COD_CLIENTE           = []COD_CLIENTE,
       DES_CLIENTE           = []DES_CLIENTE,
       BOL_VIGENTE           = []BOL_VIGENTE,
       FYH_ACTUALIZACION     = []FYH_ACTUALIZACION,
       OID_TIPO_CLIENTE      = []OID_TIPO_CLIENTE,
       BOL_TOTALIZADOR_SALDO = []BOL_TOTALIZADOR_SALDO,
	   COD_USUARIO           = []COD_USUARIO,
	   BOL_ABONA_POR_TOTAL	 = []BOL_ABONA_POR_TOTAL,
	   BOL_BANCO_CAPITAL	 = []BOL_BANCO_CAPITAL,
	   BOL_BANCO_COMISION	 = []BOL_BANCO_COMISION,
	   NUM_PORCENT_COMISION	 = []NUM_PORCENT_COMISION,
	   COD_BANCARIO			 = []COD_BANCARIO,
	   BOL_SALDO_HISTORICO			= []BOL_SALDO_HISTORICO,
	   COD_FECHA_SALDO_HISTORICO	= []COD_FECHA_SALDO_HISTORICO
 WHERE OID_CLIENTE           = []OID_CLIENTE