INSERT INTO GEPR_TCLIENTE (OID_CLIENTE, COD_CLIENTE, DES_CLIENTE, BOL_VIGENTE, COD_USUARIO, FYH_ACTUALIZACION) 
VALUES 
([]OID_CLIENTE, []COD_CLIENTE, []DES_CLIENTE, []BOL_VIGENTE, []COD_USUARIO, []FYH_ACTUALIZACION)