SELECT
    COUNT(0) as QUANTIDADE
FROM SAPR_TCONFIG_NIVEL_SALDO CNS
INNER JOIN SAPR_TCONFIG_NIVEL_MOVIMIENTO CNM ON CNM.OID_CONFIG_NIVEL_SALDO = CNS.OID_CONFIG_NIVEL_SALDO
WHERE
    CNS.OID_CLIENTE = []OID_CLIENTE AND CNS.OID_SUBCLIENTE IS NULL AND CNS.OID_PTO_SERVICIO IS NULL AND CNM.BOL_ACTIVO = 1   
    AND (CNM.OID_CLIENTE <> []OID_CLIENTE
        OR (CNM.OID_CLIENTE = []OID_CLIENTE AND CNM.OID_SUBCLIENTE IS NOT NULL))