SELECT 
	C.OID_CLIENTE,
	C.COD_CLIENTE,
	C.DES_CLIENTE,
	C.OID_TIPO_CLIENTE,
	TC.COD_TIPO_CLIENTE,
	TC.DES_TIPO_CLIENTE,
	C.BOL_TOTALIZADOR_SALDO
  FROM GEPR_TCLIENTE C
  INNER JOIN GEPR_TCODIGO_AJENO CA ON CA.OID_TABLA_GENESIS = C.OID_CLIENTE
  LEFT JOIN GEPR_TTIPO_CLIENTE TC
    ON C.OID_TIPO_CLIENTE = TC.OID_TIPO_CLIENTE
WHERE 
CA.COD_TIPO_TABLA_GENESIS = 'GEPR_TCLIENTE'
