SELECT C.OID_CLIENTE,
       C.COD_CLIENTE,
       C.DES_CLIENTE,
       C.BOL_VIGENTE,
       C.COD_USUARIO,
       C.FYH_ACTUALIZACION,
       C.BOL_ENVIADO_SALDOS,
       C.OID_TIPO_CLIENTE,
       C.COD_MIGRACION,
       C.BOL_TOTALIZADOR_SALDO,
	   C.BOL_ABONA_POR_TOTAL,
       C.BOL_BANCO_CAPITAL, 
       C.BOL_BANCO_COMISION, 
       C.NUM_PORCENT_COMISION, 
       C.COD_BANCARIO,
       T.COD_TIPO_CLIENTE,
       T.DES_TIPO_CLIENTE,
       C.BOL_SALDO_HISTORICO,
       C.COD_FECHA_SALDO_HISTORICO
  FROM GEPR_TCLIENTE C
 LEFT JOIN GEPR_TTIPO_CLIENTE T
    ON C.OID_TIPO_CLIENTE = T.OID_TIPO_CLIENTE
WHERE 1 = 1