SELECT SALDO_ANTERIOR.OID_DIVISA,
       DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       DIV.COD_COLOR,
       SALDO_ANTERIOR.OID_DENOMINACION,
       DENO.COD_DENOMINACION,
       DENO.DES_DENOMINACION,
       DENO.BOL_BILLETE,
       DENO.NUM_VALOR,
       SALDO_ANTERIOR.COD_NIVEL_DETALLE,
       SALDO_ANTERIOR.OID_UNIDAD_MEDIDA,
       UN.COD_UNIDAD_MEDIDA,
       UN.DES_UNIDAD_MEDIDA,
       UN.COD_TIPO_UNIDAD_MEDIDA,
       UN.BOL_DEFECTO,
       UN.NUM_VALOR_UNIDAD,
       SALDO_ANTERIOR.OID_CALIDAD,
       CA.COD_CALIDAD,
       CA.DES_CALIDAD,
       CA.COD_TIPO_CALIDAD,
       CASE
         WHEN SALDO_ANTERIOR.COD_TIPO_EFECTIVO_TOTAL = 'T' THEN
          'A'
         ELSE
          SALDO_ANTERIOR.COD_TIPO_EFECTIVO_TOTAL
       END AS COD_TIPO_EFECTIVO_TOTAL,
       SUM(SALDO_ANTERIOR.NEL_CANTIDAD) CANTIDAD_ANTERIOR,
       SUM(SALDO_ANTERIOR.NUM_IMPORTE) SALDO_ANTERIOR,
       SUM(SALDO_ACTUAL.NEL_CANTIDAD) CANTIDAD_ACTUAL,
       SUM(SALDO_ACTUAL.NUM_IMPORTE) SALDO_ACTUAL,
       CASE
         WHEN SUM(SALDO_ANTERIOR.NUM_IMPORTE) <>
              SUM(SALDO_ACTUAL.NUM_IMPORTE) THEN
          1
         ELSE
          0
       END BOL_DIFERENCIA
  FROM SAPR_TEFECTIVO_ANTERIORXDOC SALDO_ANTERIOR
 INNER JOIN SAPR_TSALDO_EFECTIVO SALDO_ACTUAL
    ON NVL(SALDO_ACTUAL.OID_DIVISA, '-') =
       NVL(SALDO_ANTERIOR.OID_DIVISA, '-')
   AND NVL(SALDO_ACTUAL.OID_DENOMINACION, '-') =
       NVL(SALDO_ANTERIOR.OID_DENOMINACION, '-')
   AND NVL(SALDO_ACTUAL.OID_UNIDAD_MEDIDA, '-') =
       NVL(SALDO_ANTERIOR.OID_UNIDAD_MEDIDA, '-')
   AND NVL(SALDO_ACTUAL.OID_CALIDAD, '-') =
       NVL(SALDO_ANTERIOR.OID_CALIDAD, '-')
   AND NVL(SALDO_ACTUAL.COD_NIVEL_DETALLE, '-') =
       NVL(SALDO_ANTERIOR.COD_NIVEL_DETALLE, '-')
   AND CASE
         WHEN NVL(SALDO_ACTUAL.COD_TIPO_EFECTIVO_TOTAL, '-') = 'T' THEN
          'A'
         ELSE
          NVL(SALDO_ACTUAL.COD_TIPO_EFECTIVO_TOTAL, '-')
       END = CASE
         WHEN NVL(SALDO_ANTERIOR.COD_TIPO_EFECTIVO_TOTAL, '-') = 'T' THEN
          'A'
         ELSE
          NVL(SALDO_ANTERIOR.COD_TIPO_EFECTIVO_TOTAL, '-')
       END
 INNER JOIN GEPR_TDIVISA DIV
    ON DIV.OID_DIVISA = SALDO_ANTERIOR.OID_DIVISA
  LEFT JOIN GEPR_TDENOMINACION DENO
    ON DENO.OID_DENOMINACION = SALDO_ANTERIOR.OID_DENOMINACION
  LEFT JOIN GEPR_TUNIDAD_MEDIDA UN
    ON UN.OID_UNIDAD_MEDIDA = SALDO_ANTERIOR.OID_UNIDAD_MEDIDA
  LEFT JOIN GEPR_TCALIDAD CA
    ON CA.OID_CALIDAD = SALDO_ANTERIOR.OID_CALIDAD
 WHERE SALDO_ACTUAL.OID_CUENTA_SALDO =[]OID_CUENTA_SALDO
   AND SALDO_ANTERIOR.OID_DOCUMENTO =[]OID_DOCUMENTO
   AND SALDO_ACTUAL.BOL_DISPONIBLE = 1
 GROUP BY SALDO_ANTERIOR.OID_DIVISA,
          DIV.COD_ISO_DIVISA,
          DIV.DES_DIVISA,
          DIV.COD_COLOR,
          SALDO_ANTERIOR.OID_DENOMINACION,
          DENO.COD_DENOMINACION,
          DENO.DES_DENOMINACION,
          DENO.BOL_BILLETE,
          DENO.NUM_VALOR,
          SALDO_ANTERIOR.COD_NIVEL_DETALLE,
          SALDO_ANTERIOR.OID_UNIDAD_MEDIDA,
          UN.COD_UNIDAD_MEDIDA,
          UN.DES_UNIDAD_MEDIDA,
          UN.COD_TIPO_UNIDAD_MEDIDA,
          UN.BOL_DEFECTO,
          UN.NUM_VALOR_UNIDAD,
          SALDO_ANTERIOR.OID_CALIDAD,
          CA.COD_CALIDAD,
          CA.DES_CALIDAD,
          CA.COD_TIPO_CALIDAD,
          SALDO_ANTERIOR.COD_TIPO_EFECTIVO_TOTAL
