SELECT SALDO_ANTERIOR.OID_DIVISA,  
       DIV.COD_ISO_DIVISA,  
       DIV.DES_DIVISA,  
       DIV.COD_COLOR,  
       SALDO_ANTERIOR.OID_MEDIO_PAGO,  
       MP.OID_MEDIO_PAGO,  
       MP.DES_MEDIO_PAGO,  
       MP.COD_MEDIO_PAGO,  
       SALDO_ANTERIOR.COD_NIVEL_DETALLE,  
       SALDO_ANTERIOR.COD_TIPO_MEDIO_PAGO,  
       SALDO_ANTERIOR.NEL_CANTIDAD CANTIDAD_ANTERIOR,  
       SALDO_ANTERIOR.NUM_IMPORTE SALDO_ANTERIOR,  
       SALDO_ACTUAL.NEL_CANTIDAD CANTIDAD_ACTUAL,  
       SALDO_ACTUAL.NUM_IMPORTE SALDO_ACTUAL,  
        CASE  
         WHEN SALDO_ANTERIOR.NUM_IMPORTE <> SALDO_ACTUAL.NUM_IMPORTE THEN  
			1
         ELSE  
			0
       END BOL_DIFERENCIA  
  FROM SAPR_TMEDIO_PAGO_ANTERIORXDOC SALDO_ANTERIOR  
 INNER JOIN SAPR_TSALDO_MEDIO_PAGO SALDO_ACTUAL
     ON NVL(SALDO_ACTUAL.OID_DIVISA, '-') = NVL(SALDO_ANTERIOR.OID_DIVISA, '-')
   AND NVL(SALDO_ACTUAL.OID_MEDIO_PAGO, '-')  =     NVL(SALDO_ANTERIOR.OID_MEDIO_PAGO, '-')  
   AND NVL(SALDO_ACTUAL.COD_NIVEL_DETALLE, '-') =     NVL(SALDO_ANTERIOR.COD_NIVEL_DETALLE, '-')  
   AND NVL(SALDO_ACTUAL.COD_TIPO_MEDIO_PAGO, '-') =  
       NVL(SALDO_ANTERIOR.COD_TIPO_MEDIO_PAGO, '-')  
   INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = SALDO_ANTERIOR.OID_DIVISA  
   LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = SALDO_ANTERIOR.OID_MEDIO_PAGO  
 WHERE SALDO_ACTUAL.OID_CUENTA_SALDO = []OID_CUENTA_SALDO  
   AND SALDO_ANTERIOR.OID_DOCUMENTO = []OID_DOCUMENTO
   AND SALDO_ACTUAL.BOL_DISPONIBLE = 1