SELECT 
  CUEN.COD_CLIENTE, CUEN.DES_CLIENTE,  DIV.DES_DIVISA, 
  'Efectivo' ||
  CASE SAEF.BOL_DISPONIBLE 
    WHEN 0 THEN ' No disponible'
    ELSE ' Disponible'
  END TIPO_VALOR, 
  SUM(SAEF.NUM_IMPORTE_SALDO) SALDO   

FROM SAPR_VSALDO_NO_CERT_EFECTIVO SAEF
  INNER JOIN SAPR_VCUENTA CUEN ON SAEF.OID_CUENTA_SALDO = CUEN.OID_CUENTA
  INNER JOIN GEPR_TDIVISA DIV  ON SAEF.OID_DIVISA = DIV.OID_DIVISA

WHERE 1 = 1

  {0}   
         
GROUP BY CUEN.COD_CLIENTE, CUEN.DES_CLIENTE, DIV.DES_DIVISA, 'EFECTIVO', SAEF.BOL_DISPONIBLE

UNION

SELECT CUEN.COD_CLIENTE, CUEN.DES_CLIENTE, DIV.DES_DIVISA,
  'Medio Pago' ||
  CASE SAEF.BOL_DISPONIBLE
    WHEN 0 THEN ' No disponible'
    ELSE ' Disponible'
  END  TIPO_VALOR,
  SUM(SAEF.NUM_IMPORTE_SALDO) SALDO

FROM SAPR_VSALDO_NO_CERT_MEDIO_PAGO SAEF
  INNER JOIN SAPR_VCUENTA CUEN ON SAEF.OID_CUENTA_SALDO = CUEN.OID_CUENTA
  INNER JOIN GEPR_TDIVISA DIV  ON SAEF.OID_DIVISA = DIV.OID_DIVISA
  
WHERE 1 = 1

  {0}    
       
GROUP BY CUEN.COD_CLIENTE, CUEN.DES_CLIENTE, DIV.DES_DIVISA, 'MEDIO PAGO', SAEF.BOL_DISPONIBLE
