SELECT DES_SECTOR,
       COD_ISO_DIVISA,
       DES_DIVISA,
       COD_COLOR,
       SUM((CASE BOL_DISPONIBLE WHEN 1 THEN NUM_IMPORTE END))NUM_IMPORTE_DISP,
       SUM((CASE BOL_DISPONIBLE WHEN 0 THEN NUM_IMPORTE END))NUM_IMPORTE_NODISP,    
       SUM(NUM_IMPORTE) NUM_IMPORTE
	   {4}    
FROM (
SELECT 
     DIV.COD_ISO_DIVISA,
     COALESCE(DIV.DES_DIVISA, ' ') as DES_DIVISA,
     DIV.COD_COLOR,
     SE.NUM_IMPORTE NUM_IMPORTE,
     SE.BOL_DISPONIBLE,
     SEC.DES_SECTOR
	 {3}
FROM SAPR_TSALDO_EFECTIVO SE
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = SE.OID_CUENTA_SALDO
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = SE.OID_DIVISA
{5} JOIN (
            SELECT {2}
              FROM GEPR_TSECTOR SECT
              START WITH 1 = 1 {0}
              CONNECT BY NOCYCLE PRIOR SECT.OID_SECTOR = SECT.OID_SECTOR_PADRE
            ) SEC ON SEC.OID_SECTOR = CU.OID_SECTOR
{6} JOIN GEPR_TSUBCANAL SUBCN ON SUBCN.OID_SUBCANAL = CU.OID_SUBCANAL
{6} JOIN GEPR_TCANAL CN ON CN.OID_CANAL = SUBCN.OID_CANAL
WHERE 0 = 0 {1}

UNION ALL

SELECT 
     DIV.COD_ISO_DIVISA,
     DECODE(SM.COD_TIPO_MEDIO_PAGO,
        'codtipoa',
        'Tickets',
        'codtipob',
        'Cheque',
        'codtipoc',
        'Tarjetas',
        'codtipo',
        'Otros Valores') || ' ' || DIV.DES_DIVISA,
     DIV.COD_COLOR,  
     SM.NUM_IMPORTE NUM_IMPORTE,
     SM.BOL_DISPONIBLE,
     SEC.DES_SECTOR
	 {3}
FROM SAPR_TSALDO_MEDIO_PAGO SM
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = SM.OID_CUENTA_SALDO
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = SM.OID_DIVISA
{5} JOIN (
            SELECT {2}
              FROM GEPR_TSECTOR SECT
              START WITH 1 = 1 {0}
              CONNECT BY NOCYCLE PRIOR SECT.OID_SECTOR = SECT.OID_SECTOR_PADRE
            ) SEC ON SEC.OID_SECTOR = CU.OID_SECTOR
{6} JOIN GEPR_TSUBCANAL SUBCN ON SUBCN.OID_SUBCANAL = CU.OID_SUBCANAL
{6} JOIN GEPR_TCANAL CN ON CN.OID_CANAL = SUBCN.OID_CANAL
WHERE 0 = 0 {1}
)
GROUP BY DES_SECTOR, COD_ISO_DIVISA, DES_DIVISA,COD_COLOR{4}
ORDER BY DES_SECTOR, DES_DIVISA