SELECT 
DIV.OID_DIVISA
,DIV.COD_ISO_DIVISA
,DIV.DES_DIVISA
,SMP.COD_NIVEL_DETALLE
,SMP.COD_TIPO_MEDIO_PAGO
,MP.OID_MEDIO_PAGO
,MP.COD_MEDIO_PAGO
,MP.DES_MEDIO_PAGO
,MP.OID_DIVISA
,SUM(SMP.NEL_CANTIDAD)AS NEL_CANTIDAD
,SUM(SMP.NUM_IMPORTE) AS NUM_IMPORTE
FROM SAPR_TSALDO_MEDIO_PAGO SMP
INNER JOIN SAPR_TCUENTA C  ON C.OID_CUENTA = SMP.OID_CUENTA_SALDO
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = SMP.OID_DIVISA
LEFT OUTER JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = SMP.OID_MEDIO_PAGO
     AND MP.OID_DIVISA = SMP.OID_DIVISA
WHERE SMP.BOL_DISPONIBLE = 1
	AND	C.OID_CLIENTE =[]OID_CLIENTE
	AND C.OID_SECTOR = []OID_SECTOR
	AND C.OID_SUBCANAL = []OID_SUBCANAL
{0}
GROUP BY
DIV.OID_DIVISA
,DIV.COD_ISO_DIVISA
,DIV.DES_DIVISA
,SMP.COD_NIVEL_DETALLE
,SMP.COD_TIPO_MEDIO_PAGO
,MP.OID_MEDIO_PAGO
,MP.COD_MEDIO_PAGO
,MP.DES_MEDIO_PAGO
,MP.OID_DIVISA
HAVING (SUM(SMP.NEL_CANTIDAD) <> 0 OR SUM(SMP.NUM_IMPORTE) <> 0)
ORDER BY DIV.DES_DIVISA,SMP.COD_NIVEL_DETALLE, SUM(SMP.NUM_IMPORTE) DESC
