SELECT
	   OID_SECTOR,
	   COD_SECTOR,
       DES_SECTOR,
	   OID_CLIENTE,
       COD_CLIENTE,
       DES_CLIENTE,
	   OID_SUBCLIENTE,
       COD_SUBCLIENTE,
       DES_SUBCLIENTE,
	   OID_PTO_SERVICIO,
       COD_PTO_SERVICIO,
       DES_PTO_SERVICIO,
	   OID_CANAL,
       COD_CANAL,
       DES_CANAL,
	   OID_SUBCANAL,
       COD_SUBCANAL,
       DES_SUBCANAL,
	   OID_DIVISA,
       COD_ISO_DIVISA,
       DES_DIVISA,
       COD_COLOR,
       OID_CUENTA,
       BOL_DISPONIBLE,    
       SUM(CASE WHEN TIPO = 'EFECTIVO' THEN NUM_IMPORTE ELSE 0 END) NUM_IMPORTE_EFECTIVO,
       SUM(CASE WHEN TIPO = 'MEDIOPAGO' THEN NUM_IMPORTE ELSE 0 END) NUM_IMPORTE_MP,
       SUM(NEL_CANTIDAD) NEL_CANTIDAD,
	   SUM(CASE WHEN OID_DENOMINACION IS NOT NULL THEN NUM_IMPORTE ELSE 0 END) NUM_IMPORTE_EFECTIVO_DET,
       SUM(CASE WHEN OID_MEDIO_PAGO IS NOT NULL THEN NUM_IMPORTE ELSE 0 END) NUM_IMPORTE_MP_DET
     {1}
FROM (
SELECT
       'EFECTIVO' AS TIPO,
	   SEC.OID_SECTOR,
       SEC.COD_SECTOR,
       SEC.DES_SECTOR,
	   CL.OID_CLIENTE,
       CL.COD_CLIENTE,
       CL.DES_CLIENTE,
	   SUBCL.OID_SUBCLIENTE,
       SUBCL.COD_SUBCLIENTE,
       SUBCL.DES_SUBCLIENTE,
	   PTO.OID_PTO_SERVICIO,
       PTO.COD_PTO_SERVICIO,
       PTO.DES_PTO_SERVICIO,
	   CN.OID_CANAL,
       CN.COD_CANAL,
       CN.DES_CANAL,
	   SUBCN.OID_SUBCANAL,
       SUBCN.COD_SUBCANAL,
       SUBCN.DES_SUBCANAL,
	   DIV.OID_DIVISA,
       DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       DIV.COD_COLOR,
       SALDO.NUM_IMPORTE,
       SALDO.BOL_DISPONIBLE,
       CU.OID_CUENTA,
	   SALDO.NEL_CANTIDAD,
	   SALDO.OID_DENOMINACION,
	   NULL AS OID_MEDIO_PAGO
	   {2}
FROM SAPR_TSALDO_EFECTIVO SALDO
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = SALDO.OID_CUENTA_SALDO
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = SALDO.OID_DIVISA
 JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
LEFT JOIN GEPR_TSUBCLIENTE SUBCL ON SUBCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
 INNER 
 JOIN GEPR_TSUBCANAL SUBCN ON SUBCN.OID_SUBCANAL = CU.OID_SUBCANAL
 INNER 
 JOIN GEPR_TCANAL CN ON CN.OID_CANAL = SUBCN.OID_CANAL
 {4}
WHERE 0 = 0 AND SALDO.NUM_IMPORTE <> 0   
 {0}
      
UNION ALL

SELECT 
       'MEDIOPAGO' AS TIPO,
	   SEC.OID_SECTOR,
       SEC.COD_SECTOR,
	   SEC.DES_SECTOR,
	   CL.OID_CLIENTE,
       CL.COD_CLIENTE,
       CL.DES_CLIENTE,
	   SUBCL.OID_SUBCLIENTE,
       SUBCL.COD_SUBCLIENTE,
       SUBCL.DES_SUBCLIENTE,
	   PTO.OID_PTO_SERVICIO,
       PTO.COD_PTO_SERVICIO,
       PTO.DES_PTO_SERVICIO,
	   CN.OID_CANAL,
       CN.COD_CANAL,
       CN.DES_CANAL,
	   SUBCN.OID_SUBCANAL,
       SUBCN.COD_SUBCANAL,
       SUBCN.DES_SUBCANAL,
	   DIV.OID_DIVISA,
       DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       DIV.COD_COLOR,
       SALDO.NUM_IMPORTE NUM_IMPORTE,
       SALDO.BOL_DISPONIBLE,
       CU.OID_CUENTA,
	   SALDO.NEL_CANTIDAD,
	   SALDO.OID_MEDIO_PAGO,
	   NULL AS OID_DENOMINACION
	   {3}
FROM SAPR_TSALDO_MEDIO_PAGO SALDO
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = SALDO.OID_CUENTA_SALDO
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = SALDO.OID_DIVISA
 JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
LEFT JOIN GEPR_TSUBCLIENTE SUBCL ON SUBCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
 INNER 
 JOIN GEPR_TSUBCANAL SUBCN ON SUBCN.OID_SUBCANAL = CU.OID_SUBCANAL
 INNER 
 JOIN GEPR_TCANAL CN ON CN.OID_CANAL = SUBCN.OID_CANAL
 {5}
WHERE 0 = 0
 {0}
)
