SELECT
        CUEN.COD_DELEGACION,
        CUEN.COD_SECTOR,
        CUEN.DES_SECTOR,
        'EFECTIVO' TIPO_VALOR,
        DIVI.COD_ISO_DIVISA,
        SUM(SAMP.NUM_IMPORTE_SALDO) AS SALDO
FROM
        SAPR_VSALDO_NO_CERT_MEDIO_PAGO SAMP
        INNER JOIN SAPR_VCUENTA CUEN ON SAMP.OID_CUENTA_SALDO = CUEN.OID_CUENTA
        INNER JOIN GEPR_TDIVISA DIVI ON SAMP.OID_DIVISA = DIVI.OID_DIVISA
WHERE
        SAMP.BOL_DISPONIBLE = []BOL_DISPONIBLE
        {0}
GROUP BY
        CUEN.COD_DELEGACION,
        CUEN.COD_SECTOR,
        CUEN.DES_SECTOR,
        'EFECTIVO',
        DIVI.COD_ISO_DIVISA
HAVING 
        SUM(SAMP.NUM_IMPORTE_SALDO) <> 0    