SELECT DIV.OID_DIVISA,
       DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       SE.COD_NIVEL_DETALLE,       
       CASE WHEN SE.COD_TIPO_EFECTIVO_TOTAL ='T' THEN 'A' ELSE SE.COD_TIPO_EFECTIVO_TOTAL END AS COD_TIPO_EFECTIVO_TOTAL,
       DENO.OID_DENOMINACION,
       DENO.COD_DENOMINACION,
       DENO.DES_DENOMINACION,
       DENO.NUM_VALOR,
       DENO.BOL_BILLETE,
       U.OID_UNIDAD_MEDIDA,
       U.COD_UNIDAD_MEDIDA,
       U.DES_UNIDAD_MEDIDA,
       U.COD_TIPO_UNIDAD_MEDIDA,
       U.BOL_DEFECTO,
       U.NUM_VALOR_UNIDAD,
       CAL.OID_CALIDAD,
       CAL.COD_CALIDAD,
       CAL.DES_CALIDAD,
       CAL.COD_TIPO_CALIDAD,
       SUM(SE.NEL_CANTIDAD)AS NEL_CANTIDAD,
       SUM(SE.NUM_IMPORTE) AS NUM_IMPORTE
  FROM SAPR_TSALDO_EFECTIVO SE
 INNER JOIN SAPR_TCUENTA C
    ON C.OID_CUENTA = SE.OID_CUENTA_SALDO
 INNER JOIN GEPR_TDIVISA DIV
    ON DIV.OID_DIVISA = SE.OID_DIVISA
 LEFT JOIN GEPR_TDENOMINACION DENO
    ON DENO.OID_DENOMINACION = SE.OID_DENOMINACION
 LEFT JOIN GEPR_TUNIDAD_MEDIDA U
      ON U.OID_UNIDAD_MEDIDA = SE.OID_UNIDAD_MEDIDA    
 LEFT JOIN GEPR_TCALIDAD CAL
      ON CAL.OID_CALIDAD = SE.OID_CALIDAD      
WHERE SE.BOL_DISPONIBLE =1
	AND	C.OID_CLIENTE =[]OID_CLIENTE
	AND C.OID_SECTOR = []OID_SECTOR
	AND C.OID_SUBCANAL = []OID_SUBCANAL
	{0}
GROUP BY
       DIV.OID_DIVISA,
       DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       SE.COD_NIVEL_DETALLE,       
       CASE WHEN SE.COD_TIPO_EFECTIVO_TOTAL ='T' THEN 'A' ELSE SE.COD_TIPO_EFECTIVO_TOTAL END,
       DENO.OID_DENOMINACION,
       DENO.COD_DENOMINACION,
       DENO.DES_DENOMINACION,
       DENO.NUM_VALOR,
       DENO.BOL_BILLETE,
       U.OID_UNIDAD_MEDIDA,
       U.COD_UNIDAD_MEDIDA,
       U.DES_UNIDAD_MEDIDA,
       U.COD_TIPO_UNIDAD_MEDIDA,
       U.BOL_DEFECTO,
       U.NUM_VALOR_UNIDAD,
       CAL.OID_CALIDAD,
       CAL.COD_CALIDAD,
       CAL.DES_CALIDAD,
       CAL.COD_TIPO_CALIDAD
HAVING (SUM(SE.NEL_CANTIDAD) <> 0 OR SUM(SE.NUM_IMPORTE) <> 0)
ORDER BY DIV.DES_DIVISA,SE.COD_NIVEL_DETALLE, SUM(SE.NUM_IMPORTE) DESC       
