SELECT
        CUEN.COD_DELEGACION,
        CUEN.COD_SECTOR,
        CUEN.DES_SECTOR,
        'EFECTIVO' TIPO_VALOR,
        DIVI.COD_ISO_DIVISA,
        SUM(SAEF.NUM_IMPORTE_SALDO) AS SALDO
FROM
        SAPR_VSALDO_NO_CERT_EFECTIVO SAEF
        INNER JOIN SAPR_VCUENTA CUEN ON SAEF.OID_CUENTA_SALDO = CUEN.OID_CUENTA
        INNER JOIN GEPR_TDIVISA DIVI ON SAEF.OID_DIVISA = DIVI.OID_DIVISA
        LEFT OUTER JOIN GEPR_TDENOMINACION DENO ON SAEF.OID_DENOMINACION = DENO.OID_DENOMINACION
WHERE
        SAEF.BOL_DISPONIBLE = []BOL_DISPONIBLE
        {0}
GROUP BY
        CUEN.COD_DELEGACION,
        CUEN.COD_SECTOR,
        CUEN.DES_SECTOR,
        'EFECTIVO',
        DIVI.COD_ISO_DIVISA
/*HAVING 
        SUM(SAEF.NUM_IMPORTE_SALDO) <> 0    */