SELECT DIV.OID_DIVISA,
       DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       SEA.COD_NIVEL_DETALLE,       
       SEA.COD_TIPO_EFECTIVO_TOTAL,
       DENO.OID_DENOMINACION,
       DENO.COD_DENOMINACION,
       DENO.DES_DENOMINACION,
       DENO.NUM_VALOR,
       DENO.BOL_BILLETE,
       U.OID_UNIDAD_MEDIDA,
       U.COD_UNIDAD_MEDIDA,
       U.DES_UNIDAD_MEDIDA,
       U.COD_TIPO_UNIDAD_MEDIDA,
       U.BOL_DEFECTO,
       U.NUM_VALOR_UNIDAD,
       CAL.OID_CALIDAD,
       CAL.COD_CALIDAD,
       CAL.DES_CALIDAD,
       CAL.COD_TIPO_CALIDAD,
       SUM(SEA.NEL_CANTIDAD)AS NEL_CANTIDAD,
       SUM(SEA.NUM_IMPORTE) AS NUM_IMPORTE
  FROM SAPR_TEFECTIVO_ANTERIORXDOC SEA
 INNER JOIN SAPR_TDOCUMENTO DOC 
	ON DOC.OID_DOCUMENTO = SEA.OID_DOCUMENTO
 INNER JOIN GEPR_TDIVISA DIV
    ON DIV.OID_DIVISA = SEA.OID_DIVISA
 LEFT JOIN GEPR_TDENOMINACION DENO
    ON DENO.OID_DENOMINACION = SEA.OID_DENOMINACION
 LEFT JOIN GEPR_TUNIDAD_MEDIDA U
      ON U.OID_UNIDAD_MEDIDA = SEA.OID_UNIDAD_MEDIDA    
 LEFT JOIN GEPR_TCALIDAD CAL
      ON CAL.OID_CALIDAD = SEA.OID_CALIDAD  
WHERE SEA.OID_DOCUMENTO = []OID_DOCUMENTO
GROUP BY
       DIV.OID_DIVISA,
       DIV.COD_ISO_DIVISA,
       DIV.DES_DIVISA,
       SEA.COD_NIVEL_DETALLE,       
       SEA.COD_TIPO_EFECTIVO_TOTAL,
       DENO.OID_DENOMINACION,
       DENO.COD_DENOMINACION,
       DENO.DES_DENOMINACION,
       DENO.NUM_VALOR,
       DENO.BOL_BILLETE,
       U.OID_UNIDAD_MEDIDA,
       U.COD_UNIDAD_MEDIDA,
       U.DES_UNIDAD_MEDIDA,
       U.COD_TIPO_UNIDAD_MEDIDA,
       U.BOL_DEFECTO,
       U.NUM_VALOR_UNIDAD,
       CAL.OID_CALIDAD,
       CAL.COD_CALIDAD,
       CAL.DES_CALIDAD,
       CAL.COD_TIPO_CALIDAD
HAVING (SUM(SEA.NEL_CANTIDAD) <> 0 OR SUM(SEA.NUM_IMPORTE) <> 0)
ORDER BY DIV.DES_DIVISA,SEA.COD_NIVEL_DETALLE, SUM(SEA.NUM_IMPORTE) DESC       
