'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ProxyLegadoMae
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://prosegur.com/switch/crearPeriodosAcreditacion/crearPeriodosAcreditacionImp"& _ 
        "l/FicherosFechaValor/ServiciosInvocacion/SI__BR__FV__Creacion__Periodos/Principa"& _ 
        "l", ConfigurationName:="ProxyLegadoMae.PortType")>  _
    Public Interface PortType
        
        'CODEGEN: Generating message contract since the operation crearPeriodosAcreditacion is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="/switchClientes/crearPeriodosAcreditacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function crearPeriodosAcreditacion(ByVal request As ProxyLegadoMae.crearPeriodosAcreditacionRequest) As ProxyLegadoMae.crearPeriodosAcreditacionResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://prosegur.com/switch/crearPeriodosAcreditacion")>  _
    Partial Public Class crearPeriodosAcreditacion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private peticionField As crearPeriodosAcreditacionType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property peticion() As crearPeriodosAcreditacionType
            Get
                Return Me.peticionField
            End Get
            Set
                Me.peticionField = value
                Me.RaisePropertyChanged("peticion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://prosegur.com/switch/crearPeriodosAcreditacion")>  _
    Partial Public Class crearPeriodosAcreditacionType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoDelegacionField As String
        
        Private codigoPlantaField As String
        
        Private codigoSectorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CodigoDelegacion() As String
            Get
                Return Me.codigoDelegacionField
            End Get
            Set
                Me.codigoDelegacionField = value
                Me.RaisePropertyChanged("CodigoDelegacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CodigoPlanta() As String
            Get
                Return Me.codigoPlantaField
            End Get
            Set
                Me.codigoPlantaField = value
                Me.RaisePropertyChanged("CodigoPlanta")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property CodigoSector() As String
            Get
                Return Me.codigoSectorField
            End Get
            Set
                Me.codigoSectorField = value
                Me.RaisePropertyChanged("CodigoSector")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://prosegur.com/switch/crearPeriodosAcreditacion")>  _
    Partial Public Class crearPeriodosAcreditacionResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoErrorField As String
        
        Private mensajeErrorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CodigoError() As String
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
                Me.RaisePropertyChanged("CodigoError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                Me.mensajeErrorField = value
                Me.RaisePropertyChanged("MensajeError")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class crearPeriodosAcreditacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://prosegur.com/switch/crearPeriodosAcreditacion", Order:=0)>  _
        Public crearPeriodosAcreditacion As ProxyLegadoMae.crearPeriodosAcreditacion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal crearPeriodosAcreditacion As ProxyLegadoMae.crearPeriodosAcreditacion)
            MyBase.New
            Me.crearPeriodosAcreditacion = crearPeriodosAcreditacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class crearPeriodosAcreditacionResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://prosegur.com/switch/crearPeriodosAcreditacion", Order:=0)>  _
        Public crearPeriodosAcreditacionResponse As ProxyLegadoMae.crearPeriodosAcreditacionResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal crearPeriodosAcreditacionResponse As ProxyLegadoMae.crearPeriodosAcreditacionResponse)
            MyBase.New
            Me.crearPeriodosAcreditacionResponse = crearPeriodosAcreditacionResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PortTypeChannel
        Inherits ProxyLegadoMae.PortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ProxyLegadoMae.PortType)
        Implements ProxyLegadoMae.PortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ProxyLegadoMae_PortType_crearPeriodosAcreditacion(ByVal request As ProxyLegadoMae.crearPeriodosAcreditacionRequest) As ProxyLegadoMae.crearPeriodosAcreditacionResponse1 Implements ProxyLegadoMae.PortType.crearPeriodosAcreditacion
            Return MyBase.Channel.crearPeriodosAcreditacion(request)
        End Function
        
        Public Function crearPeriodosAcreditacion(ByVal crearPeriodosAcreditacion1 As ProxyLegadoMae.crearPeriodosAcreditacion) As ProxyLegadoMae.crearPeriodosAcreditacionResponse
            Dim inValue As ProxyLegadoMae.crearPeriodosAcreditacionRequest = New ProxyLegadoMae.crearPeriodosAcreditacionRequest()
            inValue.crearPeriodosAcreditacion = crearPeriodosAcreditacion1
            Dim retVal As ProxyLegadoMae.crearPeriodosAcreditacionResponse1 = CType(Me,ProxyLegadoMae.PortType).crearPeriodosAcreditacion(inValue)
            Return retVal.crearPeriodosAcreditacionResponse
        End Function
    End Class
End Namespace
