SELECT P.COD_PARAMETRO, PV.DES_VALOR_PARAMETRO, P.BOL_OBLIGATORIO
FROM GEPR_TPARAMETRO P
INNER JOIN GEPR_TPARAMETRO_VALOR PV ON PV.OID_PARAMETRO = P.OID_PARAMETRO
INNER JOIN GEPR_TAPLICACION AP ON AP.OID_APLICACION = P.OID_APLICACION
WHERE {0} 
     AND PV.COD_IDENTIFICADOR_NIVEL = (SELECT D.COD_PAIS FROM GEPR_TDELEGACION D WHERE D.COD_DELEGACION = []COD_DELEGACION)
     AND AP.COD_APLICACION = []COD_APLICACION
UNION
SELECT P.COD_PARAMETRO, PV.DES_VALOR_PARAMETRO, P.BOL_OBLIGATORIO
FROM GEPR_TPARAMETRO P
INNER JOIN GEPR_TPARAMETRO_VALOR PV ON PV.OID_PARAMETRO = P.OID_PARAMETRO
INNER JOIN GEPR_TAPLICACION AP ON AP.OID_APLICACION = P.OID_APLICACION
WHERE {0}
AND AP.COD_APLICACION = []COD_APLICACION
