SELECT
       1 AS NIVEL
	  ,'' AS COD_PUESTO
	  ,'' AS COD_HOST_PUESTO
	  ,PV.COD_IDENTIFICADOR_NIVEL AS COD_PAIS
	  ,[]COD_DELEGACION AS COD_DELEGACION
	  ,AP.COD_APLICACION AS COD_APLICACION
      ,P.COD_PARAMETRO
	  ,P.NEC_TIPO_COMPONENTE
      ,PV.DES_VALOR_PARAMETRO
      ,P.BOL_OBLIGATORIO

      FROM GEPR_TPARAMETRO P
INNER JOIN GEPR_TPARAMETRO_VALOR PV ON PV.OID_PARAMETRO = P.OID_PARAMETRO
INNER JOIN GEPR_TAPLICACION AP ON AP.OID_APLICACION = P.OID_APLICACION
     WHERE 1 = 1
       AND PV.COD_IDENTIFICADOR_NIVEL = {0}
	   {1}

UNION

SELECT
       2 AS NIVEL
	  ,'' AS COD_PUESTO
	  ,'' AS COD_HOST_PUESTO
      ,D.COD_PAIS AS COD_PAIS
	  ,[]COD_DELEGACION AS COD_DELEGACION
	  ,AP.COD_APLICACION AS COD_APLICACION
      ,P.COD_PARAMETRO
	  ,P.NEC_TIPO_COMPONENTE
      ,PV.DES_VALOR_PARAMETRO
      ,P.BOL_OBLIGATORIO

      FROM GEPR_TPARAMETRO P
INNER JOIN GEPR_TPARAMETRO_VALOR PV ON PV.OID_PARAMETRO = P.OID_PARAMETRO
INNER JOIN GEPR_TAPLICACION AP ON AP.OID_APLICACION = P.OID_APLICACION
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = PV.COD_IDENTIFICADOR_NIVEL
     WHERE 1 = 1
       AND D.COD_DELEGACION = []COD_DELEGACION
	   {2}