SELECT
       3 AS NIVEL
	  ,[]COD_PUESTO AS COD_PUESTO
	  ,[]COD_HOST_PUESTO AS COD_HOST_PUESTO
	  ,DEL.COD_PAIS AS COD_PAIS
	  ,[]COD_DELEGACION AS COD_DELEGACION
	  ,AP.COD_APLICACION AS COD_APLICACION
      ,P.COD_PARAMETRO
	  ,P.NEC_TIPO_COMPONENTE
      ,PV.DES_VALOR_PARAMETRO
      ,P.BOL_OBLIGATORIO

      FROM GEPR_TPARAMETRO P
INNER JOIN GEPR_TPARAMETRO_VALOR PV ON PV.OID_PARAMETRO = P.OID_PARAMETRO
INNER JOIN GEPR_TAPLICACION AP ON AP.OID_APLICACION = P.OID_APLICACION
INNER JOIN GEPR_TPUESTO PUE ON PUE.OID_APLICACION = AP.OID_APLICACION AND PUE.BOL_VIGENTE = 1
	AND PUE.OID_PUESTO = PV.COD_IDENTIFICADOR_NIVEL
INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = PUE.OID_DELEGACION
     WHERE 1 = 1
	   AND PUE.COD_PUESTO = []COD_PUESTO
       AND PUE.COD_HOST_PUESTO = []COD_HOST_PUESTO
	   {0}