INSERT INTO GEPR_TVALOR_TERMINO_MEDIO_PAGO
  (OID_VALOR,
   OID_TERMINO,
   COD_VALOR,
   DES_VALOR,
   BOL_VIGENTE,
   COD_USUARIO, 
   FYH_ACTUALIZACION)
VALUES
  ([]OID_VALOR,
   []OID_TERMINO,
   []COD_VALOR,
   []DES_VALOR,
   []BOL_VIGENTE,
   []COD_USUARIO,
   []FYH_ACTUALIZACION)