UPDATE 
	GEPR_TVALOR_TERMINO_MEDIO_PAGO
SET    
    BOL_VIGENTE = []BOL_VIGENTE,
    COD_USUARIO = []COD_USUARIO,
    FYH_ACTUALIZACION = []FYH_ACTUALIZACION
    
WHERE 
	COD_VALOR=[]COD_VALOR
AND OID_TERMINO=[]OID_TERMINO

	
	