UPDATE 
	GEPR_TVALOR_TERMINO_MEDIO_PAGO
SET    
    BOL_VIGENTE = []BOL_VIGENTE,
    COD_USUARIO = []COD_USUARIO,
    FYH_ACTUALIZACION = []FYH_ACTUALIZACION
    
WHERE OID_TERMINO IN (SELECT OID_TERMINO FROM GEPR_TTERMINO_MEDIO_PAGO WHERE OID_MEDIO_PAGO = []OID_MEDIO_PAGO)