SELECT
           VTM.COD_VALOR,
           VTM.DES_VALOR,
           VTM.BOL_VIGENTE           
FROM 
           GEPR_TVALOR_TERMINO_MEDIO_PAGO VTM
INNER JOIN GEPR_TTERMINO_MEDIO_PAGO TMP ON
		   VTM.OID_TERMINO=TMP.OID_TERMINO           
WHERE 
		   TMP.OID_TERMINO=[]OID_TERMINO