UPDATE GEPR_TINFORM_ADICIONAL_CLIENTE
SET 
	DES_IAC = []DES_IAC, 
	OBS_IAC = []OBS_IAC, 
	BOL_VIGENTE = []BOL_VIGENTE, 
	COD_USUARIO = []COD_USUARIO, 
	FYH_ACTUALIZACION = []FYH_ACTUALIZACION 
WHERE COD_IAC = []COD_IAC