SELECT 
	IAC.COD_IAC, 
	IAC.DES_IAC, 
	IAC.OBS_IAC, 
	IAC.BOL_VIGENTE,
	IAC.BOL_COPIA_DECLARADOS, 
	IAC.BOL_INVISIBLE,
	IAC.BOL_ESPECIFICO_DE_SALDOS,
	TER.COD_TERMINO, 
	TER.DES_TERMINO, 
	TER.OBS_TERMINO, 
	FORMATO.COD_FORMATO, 
	FORMATO.DES_FORMATO, 
	TER.NEC_LONGITUD, 
	MASC.COD_MASCARA, 
	MASC.DES_MASCARA, 
	MASC.DES_EXP_REGULAR,
	ALG.COD_ALGORITMO_VALIDACION, 
	ALG.DES_ALGORITMO_VALIDACION, 
	TER.BOL_MOSTRAR_CODIGO, 
	TER.BOL_VALORES_POSIBLES, 
	TER.BOL_VIGENTE, 
	TERIAC.BOL_BUSQUEDA_PARCIAL, 
	TERIAC.BOL_CAMPO_CLAVE, 
	TERIAC.BOL_ES_OBLIGATORIO,
	TERIAC.BOL_TERMINO_COPIA,
	TERIAC.NEC_ORDEN, 
	TERIAC.BOL_ES_PROTEGIDO,
	IAC.BOL_INVISIBLE,
	TERIAC.BOL_ES_INVISIBLEREPORTE,
	TERIAC.BOL_ES_IDMECANIZADO
FROM 
	GEPR_TINFORM_ADICIONAL_CLIENTE IAC 
	LEFT JOIN GEPR_TTERMINO_POR_IAC TERIAC ON (IAC.OID_IAC = TERIAC.OID_IAC) 
	LEFT JOIN GEPR_TTERMINO TER ON (TERIAC.OID_TERMINO = TER.OID_TERMINO) 
	LEFT JOIN GEPR_TFORMATO FORMATO ON (FORMATO.OID_FORMATO = TER.OID_FORMATO) 
	LEFT JOIN GEPR_TMASCARA MASC ON (MASC.OID_MASCARA = TER.OID_MASCARA) 
	LEFT JOIN GEPR_TALGORITMO_VALIDACION ALG ON (ALG.OID_ALGORITMO_VALIDACION = TER.OID_ALGORITMO_VALIDACION)
