SELECT DISTINCT IAC.COD_IAC,
                IAC.DES_IAC,
                IAC.OBS_IAC,
                IAC.BOL_VIGENTE,
                IAC.BOL_ESPECIFICO_DE_SALDOS
  FROM GEPR_TINFORM_ADICIONAL_CLIENTE IAC
  LEFT JOIN GEPR_TTERMINO_POR_IAC TERIAC ON (IAC.OID_IAC = TERIAC.OID_IAC)
  LEFT JOIN GEPR_TTERMINO TER ON (TER.OID_TERMINO = TERIAC.OID_TERMINO)