SELECT  INFAD.COD_IAC,
        INFAD.DES_IAC,
        INFAD.BOL_COPIA_DECLARADOS,
		INFAD.BOL_INVISIBLE,
		INFAD.BOL_ESPECIFICO_DE_SALDOS,
        TPIAC.BOL_BUSQUEDA_PARCIAL,
        TPIAC.BOL_CAMPO_CLAVE, 
        TPIAC.BOL_ES_OBLIGATORIO,
        TPIAC.BOL_ES_PROTEGIDO,
        TPIAC.BOL_TERMINO_COPIA, 
        TPIAC.NEC_ORDEN,
		TPIAC.BOL_ES_INVISIBLEREPORTE,
		TPIAC.BOL_ES_IDMECANIZADO,
        TER.COD_TERMINO,
        TER.DES_TERMINO,
        TER.OBS_TERMINO,
        TER.NEC_LONGITUD,
        TER.BOL_MOSTRAR_CODIGO,
		TER.BOL_ACEPTAR_DIGITACION,
        FMT.COD_FORMATO,
        FMT.DES_FORMATO,
        MASC.COD_MASCARA,
        MASC.DES_MASCARA,
        MASC.DES_EXP_REGULAR, 
        ALG.COD_ALGORITMO_VALIDACION,
        ALG.DES_ALGORITMO_VALIDACION,
        TER.OID_TERMINO
FROM    GEPR_TINFORM_ADICIONAL_CLIENTE INFAD
        INNER JOIN GEPR_TTERMINO_POR_IAC TPIAC ON INFAD.OID_IAC = TPIAC.OID_IAC
        INNER JOIN GEPR_TTERMINO TER ON TPIAC.OID_TERMINO = TER.OID_TERMINO
        LEFT OUTER JOIN GEPR_TMASCARA MASC ON TER.OID_MASCARA = MASC.OID_MASCARA
        LEFT OUTER JOIN GEPR_TFORMATO FMT ON TER.OID_FORMATO = FMT.OID_FORMATO
        LEFT OUTER JOIN GEPR_TALGORITMO_VALIDACION ALG ON TER.OID_ALGORITMO_VALIDACION = ALG.OID_ALGORITMO_VALIDACION
WHERE   INFAD.BOL_VIGENTE = 1 AND
        INFAD.OID_IAC = []OID_IAC 
ORDER BY NEC_ORDEN