SELECT M.OID_MAQUINA,
       M.OID_TIPO_MAQUINA,
       M.COD_IDENTIFICACION,
       M.BOL_ACTIVO,
       M.GMT_CREACION,
       M.DES_USUARIO_CREACION,
       M.GMT_MODIFICACION,
       M.DES_USUARIO_MODIFICACION,
       M.BOL_CONSIDERA_RECUENTOS,
       M.OID_SECTOR,
       
       F.OID_FABRICANTE,
       F.COD_FABRICANTE,
       F.DES_FABRICANTE,
       
       M.OID_MODELO,
       MD.COD_MODELO,
       MD.DES_MODELO,
       
       CLI.OID_CLIENTE,
       CLI.COD_CLIENTE,
       CLI.DES_CLIENTE,
       
       SCLI.OID_SUBCLIENTE,
       SCLI.COD_SUBCLIENTE,
       SCLI.DES_SUBCLIENTE,
       
       PTO.OID_PTO_SERVICIO,
       PTO.COD_PTO_SERVICIO,
       PTO.DES_PTO_SERVICIO,
       S.DES_SECTOR,
       TT.COD_TIPO_MAQUINA
  FROM SAPR_TMAQUINA M
 INNER JOIN SAPR_TTIPO_MAQUINA TT
    ON TT.OID_TIPO_MAQUINA = M.OID_TIPO_MAQUINA
   AND TT.COD_TIPO_MAQUINA = 'MAE'
 INNER JOIN GEPR_TSECTOR S
    ON M.OID_SECTOR = S.OID_SECTOR
 INNER JOIN SAPR_TMODELO MD
    ON M.OID_MODELO = MD.OID_MODELO
 INNER JOIN SAPR_TFABRICANTE F
    ON MD.OID_FABRICANTE = F.OID_FABRICANTE
 INNER JOIN GEPR_TPUNTO_SERVICIO PTO
    ON PTO.OID_MAQUINA = M.OID_MAQUINA
 INNER JOIN GEPR_TSUBCLIENTE SCLI
    ON SCLI.OID_SUBCLIENTE = PTO.OID_SUBCLIENTE
 INNER JOIN GEPR_TCLIENTE CLI
    ON CLI.OID_CLIENTE = SCLI.OID_CLIENTE

 
