SELECT
       M.OID_MAQUINA,
       M.OID_TIPO_MAQUINA,
       M.COD_IDENTIFICACION,
       M.BOL_ACTIVO,
       M.GMT_CREACION,
       M.DES_USUARIO_CREACION,
       M.GMT_MODIFICACION,
       M.DES_USUARIO_MODIFICACION,
       M.BOL_CONSIDERA_RECUENTOS,
       M.OID_SECTOR,
       S.DES_SECTOR,

	   PL.OID_DELEGACION,
	   S.OID_PLANTA,

	   F.OID_FABRICANTE,
	   F.COD_FABRICANTE,
       F.DES_FABRICANTE,

       M.OID_MODELO,
	   MD.COD_MODELO,
       MD.DES_MODELO,

       PXM.FYH_VIGENCIA_INICIO,
       PXM.FYH_VIGENCIA_FIN,
       
       PLAN.DES_PLANIFICACION,
	   CLI.OID_CLIENTE,
	   CLI.COD_CLIENTE,
       CLI.DES_CLIENTE,

	   SCLI.OID_SUBCLIENTE,
       SCLI.COD_SUBCLIENTE,
       SCLI.DES_SUBCLIENTE,

	   PTO.OID_PTO_SERVICIO,
       PTO.COD_PTO_SERVICIO,
       PTO.DES_PTO_SERVICIO
 FROM SAPR_TMAQUINA M
 INNER JOIN GEPR_TSECTOR S ON M.OID_SECTOR = S.OID_SECTOR
 INNER JOIN GEPR_TPLANTA PL ON S.OID_PLANTA = PL.OID_PLANTA
 LEFT JOIN SAPR_TPLANXMAQUINA PXM ON M.OID_MAQUINA = PXM.OID_MAQUINA AND PXM.BOL_ACTIVO = 1
 INNER JOIN SAPR_TMODELO MD ON M.OID_MODELO = MD.OID_MODELO
 INNER JOIN SAPR_TFABRICANTE F ON MD.OID_FABRICANTE = F.OID_FABRICANTE
 LEFT JOIN SAPR_TPLANIFICACION PLAN ON PXM.OID_PLANIFICACION = PLAN.OID_PLANIFICACION
 LEFT JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_MAQUINA = M.OID_MAQUINA
 LEFT JOIN GEPR_TSUBCLIENTE SCLI ON SCLI.OID_SUBCLIENTE = PTO.OID_SUBCLIENTE
 LEFT JOIN GEPR_TCLIENTE CLI ON CLI.OID_CLIENTE = SCLI.OID_CLIENTE
 WHERE 1=1 