SELECT 
    PCAN.OID_PLANIFICACION, 
    CAN.OID_CANAL, 
    CAN.COD_CANAL, 
    CAN.DES_CANAL,
    SUCA.OID_SUBCANAL, 
    SUCA.COD_SUBCANAL, 
    SUCA.DES_SUBCANAL
FROM SAPR_TPLANXCANAL PCAN
LEFT JOIN SAPR_TPLANXSUBCANAL PSUB ON PCAN.OID_PLANXCANAL = PSUB.OID_PLANXCANAL  and PSUB.BOL_ACTIVO = 1
LEFT JOIN GEPR_TCANAL CAN ON CAN.OID_CANAL =  PCAN.OID_CANAL
LEFT JOIN GEPR_TSUBCANAL SUCA ON PSUB.OID_SUBCANAL = SUCA.OID_SUBCANAL and PSUB.BOL_ACTIVO = 1
WHERE PCAN.BOL_ACTIVO = 1 AND (PSUB.BOL_ACTIVO is null or PSUB.BOL_ACTIVO = 1) 
AND PCAN.OID_MAQUINA is null AND PCAN.OID_PTO_SERVICIO is null 