SELECT
       M.OID_MAQUINA,	         
       M.OID_TIPO_MAQUINA,
       M.COD_IDENTIFICACION,
       M.BOL_ACTIVO,
       M.GMT_CREACION,
       M.DES_USUARIO_CREACION,
       M.GMT_MODIFICACION,
       M.DES_USUARIO_MODIFICACION,
       M.BOL_CONSIDERA_RECUENTOS,

	   M.OID_SECTOR,
       S.DES_SECTOR,

	   PL.OID_DELEGACION,
	   S.OID_PLANTA,

	   F.OID_FABRICANTE,
	   F.COD_FABRICANTE,
       F.DES_FABRICANTE,

	   M.OID_MODELO,
	   MD.COD_MODELO,
       MD.DES_MODELO
 FROM SAPR_TMAQUINA M
 INNER JOIN GEPR_TSECTOR S ON M.OID_SECTOR = S.OID_SECTOR
 INNER JOIN GEPR_TPLANTA PL ON S.OID_PLANTA = PL.OID_PLANTA
 INNER JOIN SAPR_TMODELO MD ON M.OID_MODELO = MD.OID_MODELO
 INNER JOIN SAPR_TFABRICANTE F ON MD.OID_FABRICANTE = F.OID_FABRICANTE
 INNER JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_MAQUINA = M.OID_MAQUINA
 WHERE PTO.OID_PTO_SERVICIO = []OID_PTO_SERVICIO