SELECT M.OID_MAQUINA, M.COD_IDENTIFICACION || ' - ' || S.DES_SECTOR  as DESCRIPCION, M.BOL_CONSIDERA_RECUENTOS, M.BOL_MULTICLIENTE
 FROM SAPR_TMAQUINA M
 INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = M.OID_SECTOR
 INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA 
 {0}
 WHERE 1 = 1
 {1}


