    SELECT M.COD_IDENTIFICACION
         , C.COD_CLIENTE
         , C.DES_CLIENTE
         , SC.COD_SUBCLIENTE
         , SC.DES_SUBCLIENTE
         , PS.COD_PTO_SERVICIO
         , PS.DES_PTO_SERVICIO
         , D.COD_DELEGACION
         , D.DES_DELEGACION
         , P.COD_PLANTA
         , P.DES_PLANTA
         , PLA.COD_PLANIFICACION
         , PLA.DES_PLANIFICACION
         , CB.COD_CLIENTE COD_BANCO
         , CB.DES_CLIENTE DES_BANCO
      FROM SAPR_TMAQUINA M
INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = M.OID_SECTOR 
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA 
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION 
 LEFT  JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_MAQUINA = M.OID_MAQUINA
 LEFT  JOIN GEPR_TSUBCLIENTE SC ON SC.OID_SUBCLIENTE = PS.OID_SUBCLIENTE 
 LEFT  JOIN GEPR_TCLIENTE C ON C.OID_CLIENTE = SC.OID_CLIENTE
 LEFT  JOIN SAPR_TPLANXMAQUINA PM ON PM.OID_MAQUINA = M.OID_MAQUINA AND PM.BOL_ACTIVO = 1
 LEFT  JOIN SAPR_TPLANIFICACION PLA ON PLA.OID_PLANIFICACION = PM.OID_PLANIFICACION AND PLA.BOL_ACTIVO = 1 
 LEFT  JOIN GEPR_TCLIENTE CB ON CB.OID_CLIENTE = PLA.OID_CLIENTE
