UPDATE SAPR_TMAQUINA 
SET 
OID_SECTOR					= []OID_SECTOR,
OID_MODELO					= []OID_MODELO,
OID_TIPO_MAQUINA			= []OID_TIPO_MAQUINA,
COD_IDENTIFICACION			= []COD_IDENTIFICACION,
BOL_ACTIVO					= []BOL_ACTIVO,
GMT_MODIFICACION			= []GMT_MODIFICACION,
DES_USUARIO_MODIFICACION	= []DES_USUARIO_MODIFICACION,
BOL_CONSIDERA_RECUENTOS     = []BOL_CONSIDERA_RECUENTOS,
BOL_MULTICLIENTE			= []BOL_MULTICLIENTE
WHERE OID_MAQUINA			= []OID_MAQUINA