WITH CODIGOS AS (
  SELECT
    MAQU.COD_IDENTIFICACION as CODIGO_MAE,
    COAJ_DELE.COD_AJENO as COD_AJENO_DELEG,
    COAJ_PUSE.COD_AJENO as COD_AJENO_PTO_SERVICIO,
    CASE WHEN MAQU.COD_IDENTIFICACION = COAJ_DELE.COD_AJENO || REPLACE(COAJ_PUSE.COD_AJENO, '-', '') THEN 'IGUAL' ELSE 'DISTINTO' END AS VALIDACION
  FROM
    SAPR_TMAQUINA MAQU
    INNER JOIN GEPR_TPUNTO_SERVICIO PUSE ON MAQU.OID_MAQUINA = PUSE.OID_MAQUINA
    INNER JOIN GEPR_TCODIGO_AJENO COAJ_PUSE ON PUSE.OID_PTO_SERVICIO = COAJ_PUSE.OID_TABLA_GENESIS
                                               AND COAJ_PUSE.COD_IDENTIFICADOR = 'MAE'
                                               AND COAJ_PUSE.COD_TIPO_TABLA_GENESIS = 'GEPR_TPUNTO_SERVICIO'
    INNER JOIN GEPR_TSECTOR SECT ON MAQU.OID_SECTOR = SECT.OID_SECTOR
    INNER JOIN GEPR_TPLANTA PLAN ON SECT.OID_PLANTA = PLAN.OID_PLANTA
    INNER JOIN GEPR_TCODIGO_AJENO COAJ_DELE ON PLAN.OID_DELEGACION = COAJ_DELE.OID_TABLA_GENESIS
                                               AND COAJ_DELE.COD_IDENTIFICADOR = 'MAE'
                                               AND COAJ_DELE.COD_TIPO_TABLA_GENESIS = 'GEPR_TDELEGACION'
)
SELECT
    CODI.CODIGO_MAE,
    COUNT(CODI.VALIDACION) as VALIDACION
FROM
  CODIGOS CODI
WHERE
    CODI.VALIDACION = 'IGUAL'
GROUP BY CODI.CODIGO_MAE