SELECT DE.OID_DOCUMENTO FROM SAPR_TDOCUMENTOXELEMENTO DE
WHERE DE.COD_ESTADO_DOCXELEMENTO = []COD_ESTADO_DOCXELEMENTO
  AND DE.OID_BULTO = (SELECT DED.OID_BULTO FROM SAPR_TDOCUMENTOXELEMENTO DED
                         WHERE DED.OID_DOCUMENTO = []OID_DOCUMENTO AND rownum = 1)
  AND rownum = 1
ORDER BY DE.GMT_CREACION DESC