UPDATE SAPR_TBULTO 
SET COD_ESTADO		= []COD_ESTADO
,GMT_MODIFICACION =FN_GMT_ZERO_###VERSION###
,DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE OID_BULTO = []OID_BULTO
AND COD_ESTADO <>[]COD_ESTADO -- Atualiza estado que ainda não foi atualizado.