SELECT 1 MODIFICADA
       ,REME.FYH_INICIO
       ,NULL OID_REMESA_PADRE
       ,REME.OID_REMESA
       ,NULL OID_REMESA_LEGADO
       ,NULL COD_DELEGACION
       ,NULL COD_ESTADO_REMESA
       ,REME.FYH_INICIO_ARMADO
       ,REME.FYH_FIN_ARMADO
       ,NULL OID_CLIENTE_FACTURACION
       ,NULL COD_CLIENTE_FACTURACION
       ,NULL DES_CLIENTE_FACTURACION
       ,NULL OID_CLIENTE_SALDO
       ,NULL COD_CLIENTE_SALDO
       ,NULL DES_CLIENTE_SALDO
       ,NULL OID_SUBCLIENTE_SALDO
       ,NULL COD_SUBCLIENTE_SALDO
       ,NULL DES_SUBCLIENTE_SALDO
       ,NULL OID_PTO_SERVICIO_SALDO
       ,NULL COD_PTO_SERVICIO_SALDO
       ,NULL DES_PTO_SERVICIO_SALDO
       ,NULL OID_CLIENTE_DESTINO
       ,NULL COD_CLIENTE_DESTINO
       ,NULL DES_CLIENTE_DESTINO
       ,NULL OID_SUBCLIENTE
       ,NULL COD_SUBCLIENTE
       ,NULL DES_SUBCLIENTE
       ,NULL OID_PUNTO_SERVICIO
       ,NULL COD_PUNTO_SERVICIO
       ,NULL DES_PUNTO_SERVICIO
       ,NULL COD_RUTA_REMESA
       ,0 NEL_PARADA
       ,NULL COD_EMPRESA_TRANSPORTE
       ,NULL COD_CANAL
       ,NULL COD_SUBCANAL
       ,NULL DES_REF_CLIENTE
       ,NULL COD_CAJA_CENTRALIZADA
       ,NULL COD_SECTOR
       ,NULL DES_DIRECCION_ENTREGA
       ,NULL DES_LOCALIDAD_ENTREGA
       ,REME.FYH_PROCESO
       ,REME.FEC_SERVICIO
       ,REME.FYH_SALIDA
       ,0 NEL_PEDIDO_LEGADO
       ,NULL NEL_CONTROL_LEGADO
       ,NULL DES_COMENTARIO
       ,0 BOL_ATM
       ,NULL DES_MODELO_CAJERO
       ,NULL DES_RED
       ,0 NEC_MOD_HAB_REC
       ,NULL COD_RECIBO_REMESA
       ,NULL COD_USUARIO
       ,REME.FYH_ACTUALIZACION FECHA_MODIFICACION_REMESA
       ,REME.BOL_TRABAJA_POR_BULTO
       ,NULL COD_USUARIO_BLOQUEO
       ,NULL COD_ATM
       ,NULL OID_OT
       ,NULL COD_SERVICIO
       ,NULL COD_SECUENCIA
       ,0 BOL_MEDIO_PAGO
       ,BULT.OID_BULTO
       ,NULL COD_PRECINTO_BULTO
       ,BULT.COD_ESTADO_BULTO
       ,0 BOL_CUADRADO
       ,NULL COD_USUARIO
       ,BULT.FYH_ACTUALIZACION FECHA_MODIFICACION_BULTO
       ,NULL OID_MORFOLOGIA_COMPONENTE
       ,0 BOL_PICOS
       ,0 BOL_PREPARADO
       ,NULL COD_USUARIO_BLOQUEO
       ,NULL OID_TIPO_BULTO
       ,NULL COD_FORMATO
       ,NULL COD_PUESTO
       ,NULL COD_TIPO_BULTO
       ,NULL DES_TIPO_BULTO
       ,0 BOL_CAJETIN
       ,NULL COD_BOLSA
       ,NULL DES_CONTACTO1
       ,NULL DES_CONTACTO2
       ,NULL DES_CONTACTO3
       ,NULL DES_CONTACTO4
       ,NULL OID_REMESA_REF
FROM GEPR_TBULTO BULT INNER JOIN GEPR_TREMESA REME ON REME.OID_REMESA = BULT.OID_REMESA
{0}