/* Validar se todos os bultos estão no mesmo setor. Devolve o codigo externo das remesas que possuem bultos em setor diferentes dos filtrados. */
WITH CANT_TOT_BULTOS_REMESA AS (SELECT BULT.OID_REMESA, REME.COD_EXTERNO, COUNT(1) QTD_BULTOS
                                FROM SAPR_TBULTO BULT INNER JOIN SAPR_TREMESA REME ON REME.OID_REMESA = BULT.OID_REMESA 
								{0}
                                GROUP BY BULT.OID_REMESA, REME.COD_EXTERNO), 
	CANT_TOT_BULTOS_REMESA_SECTOR AS (SELECT BULT.OID_REMESA, COUNT(1) QTD_BULTOS_SECTOR
									  FROM SAPR_TBULTO BULT INNER JOIN SAPR_TCUENTA CUEN ON BULT.OID_CUENTA = CUEN.OID_CUENTA
									  WHERE CUEN.OID_SECTOR = []OID_SECTOR
											AND BULT.COD_ESTADO = 'CE'
											{1}
									  GROUP BY BULT.OID_REMESA),
RESULTADO AS (SELECT A.COD_EXTERNO,
					 CASE WHEN NVL(A.QTD_BULTOS, 0) <> NVL(B.QTD_BULTOS_SECTOR, 0) THEN 0 ELSE 1 END VALOR
			  FROM CANT_TOT_BULTOS_REMESA A LEFT JOIN CANT_TOT_BULTOS_REMESA_SECTOR B ON B.OID_REMESA = A.OID_REMESA)
SELECT RESU.COD_EXTERNO
FROM RESULTADO RESU
WHERE VALOR = 0