SELECT COUNT(1) EXISTE
FROM (
SELECT COUNT(1) EXISTE
 FROM SAPR_TREMESA R
INNER JOIN SAPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA
INNER JOIN SAPR_TCUENTA C ON C.OID_CUENTA = R.OID_CUENTA
INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = C.OID_SECTOR
WHERE B.OID_EXTERNO = []OID_EXTERNO
AND S.OID_SECTOR_PADRE = (
                          SELECT SP.OID_SECTOR FROM GEPR_TSECTOR S
                          INNER JOIN GEPR_TPLANTA PLA ON PLA.OID_PLANTA = S.OID_PLANTA
                          INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = PLA.OID_DELEGACION
                          LEFT JOIN GEPR_TSECTOR SP ON S.OID_SECTOR_PADRE = SP.OID_SECTOR
                          WHERE DEL.COD_DELEGACION = []COD_DELEGACION AND PLA.COD_PLANTA = []COD_PLANTA 
						  AND S.COD_SECTOR = []COD_PUESTO)
UNION
SELECT COUNT(1) EXISTE
FROM SAPR_TREMESA R
INNER JOIN SAPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA
INNER JOIN SAPR_TCUENTA C ON C.OID_CUENTA = R.OID_CUENTA
INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = C.OID_SECTOR
WHERE B.OID_EXTERNO = []OID_EXTERNO
AND S.OID_SECTOR_PADRE IS NULL
AND S.OID_SECTOR = (
                    SELECT S.OID_SECTOR 
                    FROM GEPR_TSECTOR S
                    INNER JOIN GEPR_TPLANTA PLA ON PLA.OID_PLANTA = S.OID_PLANTA
                    INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = PLA.OID_DELEGACION
                    WHERE DEL.COD_DELEGACION = []COD_DELEGACION AND PLA.COD_PLANTA = []COD_PLANTA 
					AND S.COD_SECTOR = []COD_PUESTO AND S.OID_SECTOR_PADRE IS NULL))
WHERE EXISTE > 0
