INSERT INTO GEPR_TOBJETO 
					(OID_OBJETO,
					OID_REMESA,
					OID_MORFOLOGIA_COMPONENTE,
					TIPO_OBJETO,
					COD_IDENTIFICADOR,
					COD_USUARIO,
					FYH_ACTUALIZACION)
			VALUES ([]OID_OBJETO,
					[]OID_REMESA,
					[]OID_MORFOLOGIA_COMPONENTE,
					[]TIPO_OBJETO,
					[]COD_IDENTIFICADOR,
					[]COD_USUARIO,
					[]FYH_ACTUALIZACION)