WITH Q AS(
SELECT 
       OID_DOCUMENTO,
       OID_DIVISA,
       OID_DENOMINACION,
       NULL AS OID_MEDIO_PAGO,
       NULL AS COD_TIPO_MEDIO_PAGO,
       COD_NIVEL_DETALLE,
       NULL AS BOL_DISPONIBLE,
	     OID_UNIDAD_MEDIDA,	
	     OID_CALIDAD,	
       NUM_IMPORTE,
       NEL_CANTIDAD,
       CASE WHEN NUM_IMPORTE >0 THEN 1 ELSE 0 END AS BOL_POSITIVO
  FROM SAPR_TEFECTIVOXDOCUMENTO
 WHERE 1 = 1 {0} 
UNION ALL
SELECT
	   OID_DOCUMENTO,
       OID_DIVISA,
       NULL AS OID_DENOMINACION,
       OID_MEDIO_PAGO,
       COD_TIPO_MEDIO_PAGO,
       COD_NIVEL_DETALLE,
       NULL AS BOL_DISPONIBLE,
     NULL AS OID_UNIDAD_MEDIDA,  
     NULL AS OID_CALIDAD,  
     NUM_IMPORTE,
     NEL_CANTIDAD,
     CASE WHEN NUM_IMPORTE >0 THEN 1 ELSE 0 END AS BOL_POSITIVO
  FROM SAPR_TMEDIO_PAGOXDOCUMENTO
 WHERE 1 = 1  {0})
SELECT 
       OID_DOCUMENTO,
       OID_DIVISA,
       OID_DENOMINACION,
       NULL AS OID_MEDIO_PAGO,
       NULL AS COD_TIPO_MEDIO_PAGO,
       COD_NIVEL_DETALLE,
       NULL AS BOL_DISPONIBLE,
	     OID_UNIDAD_MEDIDA,	
	     OID_CALIDAD,	
       SUM(NUM_IMPORTE) AS IMPORTE,
       SUM(NEL_CANTIDAD) AS CANTIDAD,
       BOL_POSITIVO
FROM Q         
     GROUP BY OID_DOCUMENTO,
       OID_DIVISA,
       OID_DENOMINACION,
       --OID_MEDIO_PAGO,
       --COD_TIPO_MEDIO_PAGO,
       COD_NIVEL_DETALLE,
       BOL_DISPONIBLE,
	     OID_UNIDAD_MEDIDA,	
	     OID_CALIDAD,	
       BOL_POSITIVO
