SELECT 
 CA.OID_TABLA_GENESIS
,CA.COD_TIPO_TABLA_GENESIS
,CA.COD_IDENTIFICADOR
,CA.COD_AJENO
,CA.DES_AJENO
,CA.BOL_DEFECTO
,CA.BOL_ACTIVO
 FROM GEPR_TCODIGO_AJENO CA
WHERE CA.COD_TIPO_TABLA_GENESIS IN ('GEPR_TDIVISA', 'GEPR_TDENOMINACION', 'GEPR_TMEDIO_PAGO') AND CA.BOL_ACTIVO = 1
  AND CA.COD_IDENTIFICADOR = []COD_IDENTIFICADOR