SELECT  CU.OID_CUENTA,
    SMP.OID_DIVISA,
    NULL AS OID_DENOMINACION,
    SMP.OID_MEDIO_PAGO,
    SMP.COD_TIPO_MEDIO_PAGO,
    SMP.COD_NIVEL_DETALLE,
	SMP.BOL_DISPONIBLE,
	NULL AS OID_UNIDAD_MEDIDA,	
	NULL AS OID_CALIDAD,
    SUM(SMP.NUM_IMPORTE) AS IMPORTE,
    SUM(SMP.NEL_CANTIDAD) AS CANTIDAD
	{3}   
FROM SAPR_TSALDO_MEDIO_PAGO SMP
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = SMP.OID_CUENTA_SALDO
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
INNER JOIN GEPR_TSUBCANAL SBC ON SBC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN GEPR_TCANAL CAN ON CAN.OID_CANAL = SBC.OID_CANAL
{0}
INNER JOIN GEPR_TTIPO_SECTOR TSE ON TSE.OID_TIPO_SECTOR = SE.OID_TIPO_SECTOR
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SE.OID_PLANTA
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
LEFT  JOIN GEPR_TSUBCLIENTE SCL ON SCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT  JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
{1} {2}
GROUP BY CU.OID_CUENTA, SMP.OID_DIVISA, SMP.COD_TIPO_MEDIO_PAGO, SMP.OID_MEDIO_PAGO, SMP.COD_NIVEL_DETALLE, SMP.BOL_DISPONIBLE
{3}