SELECT m.OID_MASCARA,
       m.COD_MASCARA,
       m.DES_MASCARA,
       m.DES_EXP_REGULAR,
       m.BOL_APLICA_TERM_MEDIO_PAGO,
       m.BOL_APLICA_TERM_IAC,
       m.COD_USUARIO,
       m.FYH_ACTUALIZACION
  FROM GEPR_TMASCARA m
  WHERE m.OID_MASCARA = []OID_MASCARA
  ORDER BY m.DES_MASCARA