SELECT 
    den.OID_DENOMINACION,
	den.COD_DENOMINACION,
	den.DES_DENOMINACION,
	den.BOL_BILLETE,
	den.NUM_VALOR,
	den.NUM_PESO,
	den.BOL_VIGENTE,
	den.COD_USUARIO,
	den.FYH_ACTUALIZACION
FROM 
	GEPR_TDENOMINACION den
WHERE
	den.OID_DIVISA = []OID_DIVISA
ORDER BY den.BOL_BILLETE DESC, den.NUM_VALOR DESC