-- SAPR_TDECLARADO_EFECTIVO
SELECT
    'DECLARADO_EFECTIVO' AS TIPO
    ,R.OID_REMESA
    ,R.OID_BULTO
    ,R.OID_PARCIAL
    ,R.OID_DIVISA
    ,R.COD_NIVEL_DETALLE
    ,NULL AS OID_DEC_CONT_MEDIO_PAGO
    ,NULL AS COD_TIPO_MEDIO_PAGO
    ,SUM(R.NUM_IMPORTE) AS IMPORTE
    ,SUM(R.NEL_CANTIDAD) AS CANTIDAD
FROM SAPR_TDECLARADO_EFECTIVO R
    INNER JOIN SAPR_TREMESA R1 ON R.OID_REMESA = R1.OID_REMESA
    LEFT JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = R.OID_DENOMINACION
WHERE R.COD_NIVEL_DETALLE <> 'D' {0}
    AND ((R1.BOL_GESTION_BULTO = 1 AND R.OID_BULTO IS NOT NULL AND R.OID_PARCIAL IS NULL)
    OR (R1.BOL_GESTION_BULTO = 0 AND R.OID_BULTO IS NULL AND R.OID_PARCIAL IS NULL))
GROUP BY R.OID_REMESA, R.OID_BULTO, R.OID_PARCIAL, R.OID_DIVISA, R.COD_NIVEL_DETALLE

UNION

-- SAPR_TDECLARADO_MEDIO_PAGO
SELECT
    'DECLARADO_MEDIO_PAGO' AS TIPO
    ,R.OID_REMESA
    ,R.OID_BULTO
    ,R.OID_PARCIAL
    ,R.OID_DIVISA
    ,R.COD_NIVEL_DETALLE
    ,R.OID_DECLARADO_MEDIO_PAGO AS OID_DEC_CONT_MEDIO_PAGO
    ,R.COD_TIPO_MEDIO_PAGO
    ,SUM(R.NUM_IMPORTE) AS IMPORTE
    ,SUM(R.NEL_CANTIDAD) AS CANTIDAD
FROM SAPR_TDECLARADO_MEDIO_PAGO R
    INNER JOIN SAPR_TREMESA R1 ON R.OID_REMESA = R1.OID_REMESA
    LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = R.OID_MEDIO_PAGO
WHERE R.COD_NIVEL_DETALLE <> 'D' {0}
    AND ((R1.BOL_GESTION_BULTO = 1 AND R.OID_BULTO IS NOT NULL AND R.OID_PARCIAL IS NULL)
    OR (R1.BOL_GESTION_BULTO = 0 AND R.OID_BULTO IS NULL AND R.OID_PARCIAL IS NULL))
GROUP BY R.OID_REMESA, R.OID_BULTO, R.OID_PARCIAL, R.OID_DIVISA, R.COD_NIVEL_DETALLE, R.OID_DECLARADO_MEDIO_PAGO, R.COD_TIPO_MEDIO_PAGO