-- SAPR_TDECLARADO_EFECTIVO
SELECT
 'DECLARADO_EFECTIVO' AS TIPO
,DECEF.OID_REMESA
,DECEF.OID_BULTO
,DECEF.OID_PARCIAL
,DECEF.OID_DIVISA
,DECEF.COD_NIVEL_DETALLE
,NULL AS OID_DEC_CONT_MEDIO_PAGO
,NULL AS COD_TIPO_MEDIO_PAGO
,SUM(DECEF.NUM_IMPORTE) AS IMPORTE
,SUM(DECEF.NEL_CANTIDAD) AS CANTIDAD
     
      FROM SAPR_TDECLARADO_EFECTIVO DECEF
 LEFT JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = DECEF.OID_DENOMINACION
     WHERE DECEF.COD_NIVEL_DETALLE <> 'D' {0}
  GROUP BY DECEF.OID_REMESA, DECEF.OID_BULTO, DECEF.OID_PARCIAL, DECEF.OID_DIVISA, DECEF.COD_NIVEL_DETALLE
  
UNION

-- SAPR_TDECLARADO_MEDIO_PAGO
SELECT
 'DECLARADO_MEDIO_PAGO' AS TIPO
,DECMP.OID_REMESA
,DECMP.OID_BULTO
,DECMP.OID_PARCIAL
,DECMP.OID_DIVISA
,DECMP.COD_NIVEL_DETALLE
,DECMP.OID_DECLARADO_MEDIO_PAGO AS OID_DEC_CONT_MEDIO_PAGO
,DECMP.COD_TIPO_MEDIO_PAGO
,SUM(DECMP.NUM_IMPORTE) AS IMPORTE
,SUM(DECMP.NEL_CANTIDAD) AS CANTIDAD

      FROM SAPR_TDECLARADO_MEDIO_PAGO DECMP
 LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = DECMP.OID_MEDIO_PAGO
     WHERE DECMP.COD_NIVEL_DETALLE <> 'D' {0}
  GROUP BY DECMP.OID_REMESA, DECMP.OID_BULTO, DECMP.OID_PARCIAL, DECMP.OID_DIVISA,
           DECMP.COD_NIVEL_DETALLE, DECMP.OID_DECLARADO_MEDIO_PAGO, DECMP.COD_TIPO_MEDIO_PAGO