SELECT
 'DIFERENCIA_EFECTIVO' AS TIPO
,DIFEF.OID_REMESA
,DIFEF.OID_BULTO
,DIFEF.OID_PARCIAL
,DIFEF.OID_DIVISA
,DIFEF.COD_NIVEL_DETALLE
,NULL AS OID_DEC_CONT_MEDIO_PAGO
,NULL AS COD_TIPO_MEDIO_PAGO
,SUM(DIFEF.NUM_IMPORTE) AS IMPORTE
,SUM(DIFEF.NEL_CANTIDAD) AS CANTIDAD

      FROM SAPR_TDIFERENCIA_EFECTIVO DIFEF
      INNER JOIN SAPR_TREMESA R ON R.OID_REMESA = DIFEF.OID_REMESA
 LEFT JOIN GEPR_TDENOMINACION D ON D.OID_DENOMINACION = DIFEF.OID_DENOMINACION
     WHERE DIFEF.COD_NIVEL_DETALLE <> 'D' AND R.COD_ESTADO_ABONO = 'AD' {0}
  GROUP BY DIFEF.OID_REMESA, DIFEF.OID_BULTO, DIFEF.OID_PARCIAL, DIFEF.OID_DIVISA, DIFEF.COD_NIVEL_DETALLE
  
UNION

-- SAPR_TDIFERENCIA_MEDIO_PAGO
SELECT
 'DIFERENCIA_MEDIO_PAGO' AS TIPO
,DIFMP.OID_REMESA
,DIFMP.OID_BULTO
,DIFMP.OID_PARCIAL
,DIFMP.OID_DIVISA
,DIFMP.COD_NIVEL_DETALLE
,NULL AS OID_DEC_CONT_MEDIO_PAGO
,DIFMP.COD_TIPO_MEDIO_PAGO
,SUM(DIFMP.NUM_IMPORTE) AS IMPORTE
,SUM(DIFMP.NEL_CANTIDAD) AS CANTIDAD

      FROM SAPR_TDIFERENCIA_MEDIO_PAGO DIFMP
      INNER JOIN SAPR_TREMESA R ON R.OID_REMESA = DIFMP.OID_REMESA
 LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = DIFMP.OID_MEDIO_PAGO
     WHERE DIFMP.COD_NIVEL_DETALLE <> 'D' AND R.COD_ESTADO_ABONO = 'AD' {0}
  GROUP BY DIFMP.OID_REMESA, DIFMP.OID_BULTO, DIFMP.OID_PARCIAL, DIFMP.OID_DIVISA,
           DIFMP.COD_NIVEL_DETALLE, DIFMP.COD_TIPO_MEDIO_PAGO