SELECT SUM(DE.NUM_IMPORTE) AS IMPORTE,
	   DE.COD_NIVEL_DETALLE
FROM  SAPR_TDECLARADO_EFECTIVO DE
WHERE
DE.OID_DIVISA = []OID_DIVISA AND DE.COD_NIVEL_DETALLE = []COD_NIVEL_DETALLE AND DE.OID_DENOMINACION IS NULL {0}
GROUP BY DE.COD_NIVEL_DETALLE