SELECT SUM(DMP.NUM_IMPORTE) AS NUM_IMPORTE,
	   SUM(DMP.NEL_CANTIDAD) AS CANTIDAD,
	   DMP.OID_MEDIO_PAGO
FROM SAPR_TDIFERENCIA_MEDIO_PAGO DMP
WHERE DMP.OID_MEDIO_PAGO = []OID_MEDIO_PAGO {0}
GROUP BY DMP.OID_MEDIO_PAGO
