SELECT CT.COD_CERTIFICADO,CT.FYH_CERTIFICADO
  FROM SAPR_TCERTIFICADO CT
 INNER JOIN SAPR_TCERTIFICADOXDELEGACION CTD
    ON CTD.OID_CERTIFICADO = CT.OID_CERTIFICADO
 INNER JOIN SAPR_TCERTIFICADOXSECTOR CTS
    ON CTS.OID_CERTIFICADO = CT.OID_CERTIFICADO
 INNER JOIN SAPR_TCERTIFICADOXSUBCANAL CTSC
    ON CTSC.OID_CERTIFICADO = CT.OID_CERTIFICADO
 INNER JOIN SAPR_TCONFIG_NIVEL_SALDO NS
    ON NS.OID_CONFIG_NIVEL_SALDO = CT.OID_CONFIG_NIVEL_SALDO
 WHERE CT.COD_ESTADO IN ('PC', 'DE')
   AND CT.FYH_CERTIFICADO >= []FYH_CERTIFICADO
