UPDATE SAPR_TCERTIFICADO
SET
COD_ESTADO = []COD_ESTADO,
GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###,
DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION,
COD_CERTIFICADO = []COD_CERTIFICADO,
COD_EXTERNO = []COD_CERTIFICADO
WHERE
OID_CERTIFICADO = []OID_CERTIFICADO