SELECT DISTINCT CT.OID_CERTIFICADO,
                CT.COD_CERTIFICADO,
                CT.COD_ESTADO,
                CT.COD_EXTERNO,
                CT.FYH_CERTIFICADO,
                CL.COD_CLIENTE,
                S.COD_SECTOR,
                SC.COD_SUBCANAL,
                D.COD_DELEGACION
  FROM SAPR_TCERTIFICADO CT
 INNER JOIN SAPR_TCONFIG_NIVEL_SALDO CONS
    ON CT.OID_CONFIG_NIVEL_SALDO = CONS.OID_CONFIG_NIVEL_SALDO
 INNER JOIN GEPR_TCLIENTE CL
    ON CONS.OID_CLIENTE = CL.OID_CLIENTE
 INNER JOIN SAPR_TCERTIFICADOXSUBCANAL CESC
    ON CT.OID_CERTIFICADO = CESC.OID_CERTIFICADO
 INNER JOIN GEPR_TSUBCANAL SC
    ON SC.OID_SUBCANAL = CESC.OID_SUBCANAL
 INNER JOIN SAPR_TCERTIFICADOXDELEGACION DEL
    ON DEL.OID_CERTIFICADO = CT.OID_CERTIFICADO
 INNER JOIN GEPR_TDELEGACION D
    ON D.OID_DELEGACION = DEL.OID_DELEGACION
 INNER JOIN SAPR_TCERTIFICADOXSECTOR CTS
    ON CTS.OID_CERTIFICADO = CT.OID_CERTIFICADO
 INNER JOIN GEPR_TSECTOR S
    ON S.OID_SECTOR = CTS.OID_SECTOR
WHERE {0} 