SELECT CT.OID_CERTIFICADO
FROM SAPR_TCERTIFICADO CT
INNER JOIN SAPR_TCERTIFICADOXDELEGACION CTD ON CTD.OID_CERTIFICADO = CT.OID_CERTIFICADO
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = CTD.OID_DELEGACION
INNER JOIN SAPR_TCERTIFICADOXSECTOR CTS ON CTS.OID_CERTIFICADO = CT.OID_CERTIFICADO
INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = CTS.OID_SECTOR
INNER JOIN SAPR_TCERTIFICADOXSUBCANAL CTSC ON CTSC.OID_CERTIFICADO = CT.OID_CERTIFICADO
INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = CTSC.OID_SUBCANAL
INNER JOIN SAPR_TCONFIG_NIVEL_SALDO NS ON NS.OID_CONFIG_NIVEL_SALDO = CT.OID_CONFIG_NIVEL_SALDO
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = NS.OID_CLIENTE
WHERE CL.COD_CLIENTE = []COD_CLIENTE AND CT.COD_ESTADO = []COD_ESTADO