SELECT DISTINCT CLISALDO.OID_CLIENTE,
       NISA.OID_CONFIG_NIVEL_MOVIMIENTO AS OID_CONFIG_NIVEL_MOVIMIENTO,
       CLIMOV.OID_CLIENTE                AS OID_CLIENTE_MOVIMIENTO,
       CLIMOV.COD_CLIENTE                AS COD_CLIENTE_MOVIMIENTO,
       CLIMOV.DES_CLIENTE                AS DES_CLIENTE_MOVIMIENTO,
       SUBCLIMOV.OID_SUBCLIENTE             AS OID_SUBCLIENTE_MOVIMIENTO,
       SUBCLIMOV.COD_SUBCLIENTE             AS COD_SUBCLIENTE_MOVIMIENTO,
       SUBCLIMOV.DES_SUBCLIENTE             AS DES_SUBCLIENTE_MOVIMIENTO,
       PSMOV.OID_PTO_SERVICIO            AS OID_PTO_SERVICIO_MOVIMIENTO,
       PSMOV.COD_PTO_SERVICIO            AS COD_PTO_SERVICIO_MOVIMIENTO,
       PSMOV.DES_PTO_SERVICIO            AS DES_PTO_SERVICIO_MOVIMIENTO,
       SUBCANAL.OID_SUBCANAL              AS OID_SUBCANAL_MOVIMIENTO,
       SUBCANAL.COD_SUBCANAL              AS COD_SUBCANAL_MOVIMIENTO,
       SUBCANAL.DES_SUBCANAL              AS DES_SUBCANAL_MOVIMIENTO,
       CNMOV.FYH_VIGENCIA                AS FYH_VIGENCIA_MOVIMIENTO,
       CNMOV.BOL_ACTIVO                  AS BOL_ACTIVO_MOVIMIENTO,
       CNMOV.GMT_CREACION                AS GMT_CREACION_MOVIMIENTO,
       CNMOV.DES_USUARIO_CREACION        AS DES_USUARIO_CREAC_MOVIMIENTO,
       CNMOV.GMT_MODIFICACION            AS GMT_MODIFICACION_MOVIMIENTO,
       CNMOV.DES_USUARIO_MODIFICACION    AS DES_USUARIO_MOD_MOVIMIENTO
  FROM SAPR_TNIVEL_SALDO NISA 
  INNER JOIN SAPR_TCONFIG_NIVEL_MOVIMIENTO CNMOV ON CNMOV.OID_CONFIG_NIVEL_MOVIMIENTO = NISA.OID_CONFIG_NIVEL_MOVIMIENTO
  INNER JOIN SAPR_TCUENTA CONTASALDO ON CONTASALDO.OID_CUENTA = NISA.OID_CUENTA_SALDO
  INNER JOIN GEPR_TCLIENTE CLISALDO ON CLISALDO.OID_CLIENTE = CONTASALDO.OID_CLIENTE
  INNER JOIN SAPR_TCUENTA CONTAMOV ON CONTAMOV.OID_CUENTA = NISA.OID_CUENTA_MOVIMIENTO 
  INNER JOIN GEPR_TCLIENTE CLIMOV ON CLIMOV.OID_CLIENTE = CONTAMOV.OID_CLIENTE
  INNER JOIN GEPR_TSUBCANAL SUBCANAL ON SUBCANAL.OID_SUBCANAL = CONTASALDO.OID_SUBCANAL
  LEFT JOIN GEPR_TSUBCLIENTE SUBCLIMOV ON SUBCLIMOV.OID_SUBCLIENTE = CONTAMOV.OID_SUBCLIENTE
  LEFT JOIN GEPR_TPUNTO_SERVICIO PSMOV ON PSMOV.OID_PTO_SERVICIO = CONTAMOV.OID_PTO_SERVICIO
 WHERE CNMOV.BOL_ACTIVO = 1
 AND CLISALDO.COD_CLIENTE = []COD_CLIENTE 

