'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfiguracionFormularios
    
    '''<summary>
    '''upSector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upSector As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phSector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phSector As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''grvResultadoFormularios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvResultadoFormularios As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upBotones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upBotones As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phAcciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phAcciones As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Master
        Get
            Return CType(MyBase.Master,Prosegur.[Global].GesEfectivo.NuevoSaldos.Web.Master)
        End Get
    End Property
End Class
