UPDATE GEPR_TBULTO BUL
SET COD_PRECINTO_BULTO = []COD_PRECINTO_BULTO
,OID_TIPO_BULTO = []OID_TIPO_BULTO
,COD_USUARIO = []COD_USUARIO
,FYH_ACTUALIZACION = []FYH_ACTUALIZACION
WHERE BUL.OID_BULTO = []OID_BULTO