INSERT INTO GEPR_TEFECTIVO_BULTO (
OID_EFECTIVO_BULTO
,OID_BULTO
,OID_DENOMINACION
,OID_MODULO_BULTO
,NEL_CANTIDAD
,NEC_AGRUPACION
,COD_USUARIO
,FYH_ACTUALIZACION
) VALUES ( 
[]OID_EFECTIVO_BULTO
,[]OID_BULTO
,[]OID_DENOMINACION
,[]OID_MODULO_BULTO
,[]NEL_CANTIDAD
,[]NEC_AGRUPACION
,[]COD_USUARIO
,SYSDATE
)