SELECT EEB.OID_EFECTIVO_BULTO, BB.OID_BULTO, DE.COD_DENOMINACION, EEB.NEL_CANTIDAD FROM (
       SELECT AA.OID_BULTO FROM (
              SELECT COUNT(EB.OID_BULTO), EB.OID_BULTO
              FROM GEPR_TBULTO B INNER JOIN GEPR_TEFECTIVO_BULTO EB ON B.OID_BULTO = EB.OID_BULTO
              WHERE B.OID_REMESA = []OID_REMESA AND B.OID_BULTO <> []OID_BULTO AND EB.OID_MODULO_BULTO IS NULL
              GROUP BY EB.OID_BULTO
              ORDER BY EB.OID_BULTO) AA
       WHERE ROWNUM = 1) BB INNER JOIN GEPR_TEFECTIVO_BULTO EEB ON BB.OID_BULTO = EEB.OID_BULTO
                            INNER JOIN GEPR_TDENOMINACION DE ON EEB.OID_DENOMINACION = DE.OID_DENOMINACION