SELECT EB.OID_EFECTIVO_BULTO, DE.COD_DENOMINACION, EB.NEL_CANTIDAD
FROM GEPR_TEFECTIVO_BULTO EB INNER JOIN GEPR_TDENOMINACION DE ON EB.OID_DENOMINACION = DE.OID_DENOMINACION
WHERE EB.OID_BULTO = []OID_BULTO