SELECT DISTINCT BUL.OID_BULTO 
			    ,BUL.COD_PRECINTO_BULTO 
				,BUL.COD_BOLSA
				,BUL.COD_ESTADO_BULTO
				,BUL.BOL_CUADRADO 
				,BUL.COD_USUARIO
				,BUL.FYH_ACTUALIZACION
				,TIB.COD_TIPO_BULTO
				,BUL.BOL_PICOS
				,BUL.BOL_PREPARADO
				,BUL.COD_USUARIO_BLOQUEO
				,BUL.OID_TIPO_BULTO
				,PST.COD_PUESTO
FROM GEPR_TBULTO BUL
LEFT JOIN GEPR_TTIPO_BULTO TIB ON BUL.OID_TIPO_BULTO = TIB.OID_TIPO_BULTO 
LEFT JOIN GEPR_TLISTA_TRABAJO LT ON LT.OID_BULTO = BUL.OID_BULTO
LEFT JOIN GEPR_TPUESTO PST ON LT.OID_PUESTO = PST.OID_PUESTO
WHERE BUL.OID_REMESA = []OID_REMESA
