SELECT REM.OID_REMESA,
       REM.COD_ESTADO_REMESA,
       BULTO.COD_ESTADO_BULTO
FROM GEPR_TREMESA REM
 INNER JOIN GEPR_TBULTO BULTO ON REM.OID_REMESA = BULTO.OID_REMESA
WHERE BULTO.OID_BULTO = []OID_BULTO
