SELECT 1
FROM GEPR_TREMESA R
INNER JOIN GEPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA
WHERE B.BOL_PREPARADO = 0 AND R.OID_REMESA = []OID_REMESA
/*UNION
SELECT 1
FROM GEPR_TREMESA R
INNER JOIN GEPR_TOBJETO O ON O.OID_REMESA = R.OID_REMESA
WHERE O.COD_ESTADO_OBJETO = []COD_ESTADO_OBJETO AND R.OID_REMESA = []OID_REMESA*/