SELECT DIV.COD_ISO_DIVISA
      ,DEN.COD_DENOMINACION
      ,DEN.BOL_BILLETE
      ,DEN.NUM_VALOR_FACIAL
      ,EFE.NEL_CANTIDAD
      ,EFE.NEC_AGRUPACION
FROM GEPR_TEFECTIVO_BULTO EFE 
	INNER JOIN GEPR_TDENOMINACION DEN ON EFE.OID_DENOMINACION = DEN.OID_DENOMINACION
	INNER JOIN GEPR_TDIVISA DIV ON DEN.OID_DIVISA = DIV.OID_DIVISA
    INNER JOIN GEPR_TBULTO BUL ON EFE.OID_BULTO=BUL.OID_BULTO
WHERE BUL.OID_BULTO = :OID_BULTO