UPDATE GEPR_TBULTO 
	SET COD_ESTADO_BULTO = []COD_ESTADO_BULTO
	,COD_USUARIO = []COD_USUARIO
	,FYH_ACTUALIZACION = []FYH_ACTUALIZACION
	--,COD_USUARIO_BLOQUEO = []COD_USUARIO_BLOQUEO
WHERE OID_BULTO = []OID_BULTO 
	AND COD_ESTADO_BULTO <> []COD_ESTADO_BULTO
