INSERT INTO GEPR_TBULTO (
OID_BULTO
,OID_TIPO_BULTO
,OID_REMESA
,COD_PRECINTO_BULTO
,COD_ESTADO_BULTO
,BOL_PREPARADO
,BOL_CUADRADO
,COD_USUARIO
,COD_USUARIO_BLOQUEO
,FYH_ACTUALIZACION
) VALUES (
[]OID_BULTO
,[]OID_TIPO_BULTO
,[]OID_REMESA
,[]COD_PRECINTO_BULTO
,[]COD_ESTADO_BULTO
,[]BOL_PREPARADO
,0
,[]COD_USUARIO
,[]COD_USUARIO_BLOQUEO
,[]FYH_ACTUALIZACION
)