   /*Salidas_Bulto_RecuperarBultosNoArqueados*/
   SELECT BUL.OID_REMESA 
        ,BUL.OID_BULTO 
        ,BUL.COD_PRECINTO_BULTO
        ,BUL.COD_ESTADO_BULTO
        ,BUL.FYH_ACTUALIZACION
        ,REM.COD_CLIENTE_DESTINO
        ,REM.DES_CLIENTE_DESTINO
        ,REM.COD_SUBCLIENTE
        ,REM.DES_SUBCLIENTE
        ,REM.COD_PUNTO_SERVICIO
        ,REM.DES_PUNTO_SERVICIO
        ,COA.OID_CONTENEDOR_REABIERTO
		,REM.BOL_TRABAJA_POR_BULTO
    FROM GEPR_TREMESA REM
     INNER JOIN GEPR_TBULTO BUL ON REM.OID_REMESA = BUL.OID_REMESA 
     INNER JOIN GEPR_TLISTA_TRABAJO LT ON REM.OID_REMESA = LT.OID_REMESA
     INNER JOIN GEPR_TPUESTO PUE ON LT.OID_PUESTO = PUE.OID_PUESTO
     LEFT JOIN GEPR_TCONTENEDOR_REABIERTO COA ON ( BUL.OID_BULTO = COA.OID_BULTO AND COA.COD_ESTADO_CONTENEDOR = 'RA' )
   WHERE BUL.COD_ESTADO_BULTO IN ('PR', 'EN', 'SA') AND BUL.BOL_CUADRADO = 0 AND REM.BOL_TRABAJA_POR_BULTO = 0
   UNION
      SELECT BUL.OID_REMESA 
        ,BUL.OID_BULTO 
        ,BUL.COD_PRECINTO_BULTO
        ,BUL.COD_ESTADO_BULTO
        ,BUL.FYH_ACTUALIZACION
        ,REM.COD_CLIENTE_DESTINO
        ,REM.DES_CLIENTE_DESTINO
        ,REM.COD_SUBCLIENTE
        ,REM.DES_SUBCLIENTE
        ,REM.COD_PUNTO_SERVICIO
        ,REM.DES_PUNTO_SERVICIO
        ,COA.OID_CONTENEDOR_REABIERTO
		,REM.BOL_TRABAJA_POR_BULTO
    FROM GEPR_TREMESA REM
     INNER JOIN GEPR_TBULTO BUL ON REM.OID_REMESA = BUL.OID_REMESA 
     INNER JOIN GEPR_TLISTA_TRABAJO LT ON LT.OID_REMESA = REM.OID_REMESA AND LT.OID_BULTO = BUL.OID_BULTO
     INNER JOIN GEPR_TPUESTO PUE ON LT.OID_PUESTO = PUE.OID_PUESTO
     LEFT JOIN GEPR_TCONTENEDOR_REABIERTO COA ON ( BUL.OID_BULTO = COA.OID_BULTO AND COA.COD_ESTADO_CONTENEDOR = 'RA' )
   WHERE BUL.COD_ESTADO_BULTO IN ('PR', 'EN', 'SA') AND BUL.BOL_CUADRADO = 0 AND REM.BOL_TRABAJA_POR_BULTO = 1