UPDATE GEPR_TBULTO SET COD_PRECINTO_BULTO = []COD_PRECINTO_BULTO,
					   FYH_ACTUALIZACION = []FYH_ACTUALIZACION,
					   COD_USUARIO = []COD_USUARIO,
				       BOL_PREPARADO = 1 ,
				       COD_BOLSA = []COD_BOLSA
WHERE OID_BULTO = []OID_BULTO