SELECT 
      DIV.OID_DIVISA,
      DIV.COD_ISO_DIVISA,
      DEN.OID_DENOMINACION,
      DEN.COD_DENOMINACION,
      DEN.NUM_VALOR_FACIAL,
      SUM(EB.NEL_CANTIDAD) CANTIDAD
FROM GEPR_TREMESA R
INNER JOIN GEPR_TBULTO B
      ON R.OID_REMESA = B.OID_REMESA
INNER JOIN GEPR_TEFECTIVO_BULTO EB ON EB.OID_BULTO = B.OID_BULTO
INNER JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = EB.OID_DENOMINACION
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = DEN.OID_DIVISA
{0}
WHERE R.COD_DELEGACION = []COD_DELEGACION
      AND R.COD_ESTADO_REMESA <> 'PR'
      AND B.COD_ESTADO_BULTO = 'PR'
	  {1}
GROUP BY DIV.OID_DIVISA,
DIV.COD_ISO_DIVISA,
DEN.OID_DENOMINACION,
DEN.COD_DENOMINACION,
DEN.NUM_VALOR_FACIAL