SELECT COD_OPCION
FROM GEPR_TPARAMETRO_OPCION
WHERE COD_OPCION = []COD_OPCION
AND BOL_VIGENTE = 1
AND OID_PARAMETRO_OPCION = (SELECT 
	PO.OID_PARAMETRO_OPCION
FROM 
	GEPR_TPARAMETRO_OPCION PO
	INNER JOIN GEPR_TPARAMETRO P ON PO.OID_PARAMETRO = P.OID_PARAMETRO
WHERE 	
	P.COD_PARAMETRO = []COD_PARAMETRO
	AND PO.BOL_VIGENTE = 1
	AND PO.COD_OPCION = []COD_OPCION
	AND OID_APLICACION = []OID_APLICACION)