SELECT MP.COD_MEDIO_PAGO,
       MP.OID_MEDIO_PAGO,
       MP.COD_USUARIO,
       MP.DES_MEDIO_PAGO,
       MP.BOL_VIGENTE,
       MP.FYH_ACTUALIZACION,
       MP.OBS_MEDIO_PAGO,
       MP.COD_TIPO_MEDIO_PAGO
FROM GEPR_TMEDIO_PAGO MP
WHERE MP.OID_MEDIO_PAGO = []OID_MEDIO_PAGO



