SELECT
 'CONTADO_MEDIO_PAGO' AS TIPO
,CONMP.OID_REMESA
,CONMP.OID_BULTO
,CONMP.OID_PARCIAL
,CONMP.OID_MEDIO_PAGO
,MP.OID_DIVISA
,SUM(CONMP.NUM_IMPORTE) AS IMPORTE
,SUM(CONMP.NEL_CANTIDAD) AS CANTIDAD
,CONMP.COD_TIPO_CONTADO
,CONMP.OID_CONTADO_MEDIO_PAGO
,NULL AS OID_DECLARADO_MEDIO_PAGO

      FROM SAPR_TCONTADO_MEDIO_PAGO CONMP
INNER JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = CONMP.OID_MEDIO_PAGO
     WHERE CONMP.OID_MEDIO_PAGO IS NOT NULL {0}
  GROUP BY CONMP.OID_REMESA, CONMP.OID_BULTO, CONMP.OID_PARCIAL, CONMP.OID_MEDIO_PAGO, MP.OID_DIVISA,
           CONMP.COD_TIPO_CONTADO, CONMP.OID_CONTADO_MEDIO_PAGO

UNION

SELECT
 'DIFERENCIA_MEDIO_PAGO' AS TIPO
,DIFMP.OID_REMESA
,DIFMP.OID_BULTO
,DIFMP.OID_PARCIAL
,DIFMP.OID_MEDIO_PAGO
,MP.OID_DIVISA
,SUM(DIFMP.NUM_IMPORTE) AS IMPORTE
,SUM(DIFMP.NEL_CANTIDAD) AS CANTIDAD
,NULL AS COD_TIPO_CONTADO
,NULL AS OID_CONTADO_MEDIO_PAGO
,NULL AS OID_DECLARADO_MEDIO_PAGO

      FROM SAPR_TDIFERENCIA_MEDIO_PAGO DIFMP
INNER JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = DIFMP.OID_MEDIO_PAGO
     WHERE DIFMP.OID_MEDIO_PAGO IS NOT NULL {0}
  GROUP BY DIFMP.OID_REMESA, DIFMP.OID_BULTO, DIFMP.OID_PARCIAL, DIFMP.OID_MEDIO_PAGO, MP.OID_DIVISA,
           DIFMP.OID_UNIDAD_MEDIDA

UNION

SELECT
'DECLARADO_MEDIO_PAGO' AS TIPO
,DECMP.OID_REMESA
,DECMP.OID_BULTO
,DECMP.OID_PARCIAL
,DECMP.OID_MEDIO_PAGO
,MP.OID_DIVISA
,SUM(DECMP.NUM_IMPORTE) AS IMPORTE
,SUM(DECMP.NEL_CANTIDAD) AS CANTIDAD
,NULL AS COD_TIPO_CONTADO
,NULL AS OID_CONTADO_MEDIO_PAGO
,DECMP.OID_DECLARADO_MEDIO_PAGO
     
      FROM SAPR_TDECLARADO_MEDIO_PAGO DECMP
INNER JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = DECMP.OID_MEDIO_PAGO
     WHERE DECMP.OID_MEDIO_PAGO IS NOT NULL {0}
  GROUP BY DECMP.OID_REMESA, DECMP.OID_BULTO, DECMP.OID_PARCIAL, DECMP.OID_MEDIO_PAGO, MP.OID_DIVISA,
           DECMP.OID_UNIDAD_MEDIDA, DECMP.OID_DECLARADO_MEDIO_PAGO
