SELECT
'DECLARADO_MEDIO_PAGO' AS TIPO
,DECMP.OID_REMESA
,DECMP.OID_BULTO
,DECMP.OID_PARCIAL
,DECMP.OID_MEDIO_PAGO
,MP.OID_DIVISA
,SUM(DECMP.NUM_IMPORTE) AS IMPORTE
,SUM(DECMP.NEL_CANTIDAD) AS CANTIDAD
,DECMP.OID_DECLARADO_MEDIO_PAGO
     
      FROM SAPR_TDECLARADO_MEDIO_PAGO DECMP
INNER JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = DECMP.OID_MEDIO_PAGO
     WHERE DECMP.OID_MEDIO_PAGO IS NOT NULL {0}
  GROUP BY DECMP.OID_REMESA, DECMP.OID_BULTO, DECMP.OID_PARCIAL, DECMP.OID_MEDIO_PAGO, MP.OID_DIVISA, DECMP.OID_DECLARADO_MEDIO_PAGO
