INSERT INTO SAPR_TABONO_VALOR_DET_EFECTIVO
  (OID_ABONO_VALOR_DET_EFECTIVO, OID_ABONO_VALOR, OID_DENOMINACION, COD_NIVEL_DETALLE, COD_TIPO_EFECTIVO_TOTAL, NUM_IMPORTE, NEL_CANTIDAD, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
VALUES
  ([]OID_ABONO_VALOR_DET_EFECTIVO, []OID_ABONO_VALOR, []OID_DENOMINACION, []COD_NIVEL_DETALLE, []COD_TIPO_EFECTIVO_TOTAL, []NUM_IMPORTE, []NEL_CANTIDAD, FN_GMT_ZERO_###VERSION###, []DES_USUARIO_CREACION, FN_GMT_ZERO_###VERSION###, []DES_USUARIO_MODIFICACION)
