UPDATE GEPR_TPROCEDENCIA
SET 
	OID_TIPO_SUBCLIENTE = []OID_TIPO_SUBCLIENTE, 
	OID_TIPO_PUNTO_SERVICIO = []OID_TIPO_PUNTO_SERVICIO, 
	OID_TIPO_PROCEDENCIA = []OID_TIPO_PROCEDENCIA, 
	DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION, 
	GMT_MODIFICACION = []GMT_MODIFICACION,  
	BOL_ACTIVO = []BOL_ACTIVO
WHERE 
	OID_PROCEDENCIA = []OID_PROCEDENCIA
