INSERT INTO 
	GEPR_TPROCEDENCIA (OID_PROCEDENCIA, OID_TIPO_SUBCLIENTE, OID_TIPO_PUNTO_SERVICIO, OID_TIPO_PROCEDENCIA, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION, BOL_ACTIVO) 
VALUES 
	([]OID_PROCEDENCIA, []OID_TIPO_SUBCLIENTE, []OID_TIPO_PUNTO_SERVICIO, []OID_TIPO_PROCEDENCIA, []GMT_CREACION, []DES_USUARIO_CREACION, []GMT_MODIFICACION, []DES_USUARIO_MODIFICACION, 1)