SELECT 
	COUNT(1)
FROM 
	GEPR_TPROCEDENCIA TPRO
WHERE
	TPRO.OID_TIPO_SUBCLIENTE = []OID_TIPO_SUBCLIENTE AND
	TPRO.OID_TIPO_PUNTO_SERVICIO = []OID_TIPO_PUNTO_SERVICIO AND
	TPRO.OID_TIPO_PROCEDENCIA =  []OID_TIPO_PROCEDENCIA