SELECT PUE.OID_PUESTO,
	   PUE.COD_PUESTO,
	   D.COD_DELEGACION,
	   PUE.BOL_VIGENTE 
FROM GEPR_TPUESTO PUE
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = PUE.OID_DELEGACION
INNER JOIN GEPR_TAPLICACION AP ON AP.OID_APLICACION = PUE.OID_APLICACION
WHERE AP.COD_APLICACION = []COD_APLICACION