/*ConteoRegistroMovimientoValidarModificacion.sql*/
SELECT COUNT(1)
FROM GEPR_TREGISTRO_MOVIMIENTO RM
WHERE RM.OID_REMESA = []OID_REMESA AND 
      RM.COD_TIPO_MOVIMIENTO = 'C' AND
      RM.FYH_ACTUALIZACION = []FECHA_MAX