UPDATE GEPR_TPLANTA
   SET OID_DELEGACION = []OID_DELEGACION,
       DES_PLANTA = []DES_PLANTA,
       BOL_ACTIVO = []BOL_ACTIVO,
       GMT_MODIFICACION = SYSDATE,
       DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION,
	   COD_PLANTA = []COD_PLANTA
 WHERE OID_PLANTA = []OID_PLANTA