INSERT INTO GEPR_TPLANTA (OID_PLANTA, OID_DELEGACION, COD_PLANTA, DES_PLANTA, BOL_ACTIVO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
VALUES  ([]OID_PLANTA, []OID_DELEGACION, []COD_PLANTA, []DES_PLANTA, []BOL_ACTIVO, SYSDATE, []DES_USUARIO_CREACION, SYSDATE, []DES_USUARIO_MODIFICAION)
                