select GEPR_TPLANTA.COD_PLANTA  from GEPR_TPLANTA 
inner join GEPR_TDELEGACION 
  ON GEPR_TPLANTA.OID_DELEGACION = GEPR_TDELEGACION.OID_DELEGACION
WHERE GEPR_TDELEGACION.COD_DELEGACION = []COD_DELEGACION AND GEPR_TPLANTA.COD_PLANTA = []COD_PLANTA 