SELECT PL.OID_PLANTA, PL.OID_DELEGACION, PD.COD_DELEGACION, PD.DES_DELEGACION, 
PL.COD_PLANTA, PL.DES_PLANTA, PL.BOL_ACTIVO,
PL.GMT_CREACION, PL.DES_USUARIO_CREACION, PL.GMT_MODIFICACION, PL.DES_USUARIO_MODIFICACION
FROM GEPR_TPLANTA PL 
INNER JOIN GEPR_TDELEGACION PD ON PL.OID_DELEGACION = PD.OID_DELEGACION
WHERE PL.OID_PLANTA = []OID_PLANTA