SELECT 
	M.OID_MORFOLOGIA, 
	CM.FEC_INICIO, 
	M.COD_MORFOLOGIA, 
	M.DES_MORFOLOGIA, 
	M.BOL_VIGENTE, 
	M.NEC_MODALIDAD_RECOGIDA 
FROM 
	GEPR_TCAJEROXMORFOLOGIA CM 
	INNER JOIN GEPR_TMORFOLOGIA M ON M.OID_MORFOLOGIA = CM.OID_MORFOLOGIA 
	WHERE CM.OID_CAJERO = []OID_CAJERO