SELECT distinct MOR.COD_MORFOLOGIA,
       MOR.DES_MORFOLOGIA,
       MOR.BOL_VIGENTE,
       MOR.FYH_ACTUALIZACION,
       MXC.OID_MORFOLOGIA_COMPONENTE,
       MXC.COD_TIPO_CONTENEDOR,
	   MXC.DES_TIPO_CONTENEDOR,
       MXC.NEC_FUNCION_CONTENEDOR,
       MOR.NEC_MODALIDAD_RECOGIDA,
	   MXC.NEC_ORDEN,
       MXC.BOL_VIGENTE BOL_VIGENTE_COMP,
       MXC.COD_MORFOLOGIA_COMPONENTE,
       COB.OID_COMPONENTE_OBJETO,
       COB.OID_DIVISA,
	   COB.nec_orden_divisa,
       COB.nec_orden_tipo_med_pag,
       DIV.DES_DIVISA,
       DIV.COD_ISO_DIVISA,
       DEN.OID_DENOMINACION,
       DEN.COD_DENOMINACION,
	   DEN.DES_DENOMINACION,
       DEN.BOL_BILLETE,
       DEN.NUM_VALOR,
       MPG.OID_MEDIO_PAGO,
       MPG.COD_MEDIO_PAGO,
       MPG.DES_MEDIO_PAGO,
       MPG.COD_TIPO_MEDIO_PAGO,
       TMP.OID_TERMINO,
       TMP.COD_TERMINO,
       TMP.DES_TERMINO,
       TMP.BOL_VIGENTE,
       TXP.BOL_ES_OBLIGATORIO
  FROM GEPR_TMORFOLOGIA MOR
 LEFT JOIN GEPR_TMORFOLOGIA_COMPONENTE MXC ON MXC.OID_MORFOLOGIA = MOR.OID_MORFOLOGIA
 LEFT JOIN GEPR_TCOMPONENTE_OBJETO COB ON COB.OID_MORFOLOGIA_COMPONENTE = MXC.OID_MORFOLOGIA_COMPONENTE
 LEFT JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = COB.OID_DIVISA
 LEFT JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = COB.OID_DENOMINACION
 LEFT JOIN GEPR_TMEDIO_PAGO MPG ON MPG.OID_MEDIO_PAGO = COB.OID_MEDIO_PAGO
 LEFT JOIN GEPR_TTERMINO_MEDIO_PAGO TMP ON MPG.OID_MEDIO_PAGO = TMP.OID_MEDIO_PAGO
 LEFT JOIN GEPR_TCAJEROXMORFOLOGIA CXM ON MOR.OID_MORFOLOGIA = CXM.OID_MORFOLOGIA
 LEFT JOIN GEPR_TCAJERO CAJ ON CXM.OID_CAJERO = CAJ.OID_CAJERO
 LEFT JOIN GEPR_TPROCESO_POR_PSERVICIO PXP ON CAJ.OID_PTO_SERVICIO = PXP.OID_PTO_SERVICIO
 LEFT JOIN GEPR_TPROCESO_SUBCANAL PSC ON PXP.OID_PROCESO_POR_PSERVICIO = PSC.OID_PROCESO_POR_PSERVICIO
 LEFT JOIN GEPR_TTERMINO_MED_PAGO_POR_PRO TXP ON PSC.OID_PROCESO_SUBCANAL = TXP.OID_PROCESO_SUBCANAL
                                              AND TMP.OID_TERMINO = TXP.OID_TERMINO
 WHERE MOR.OID_MORFOLOGIA = []OID_MORFOLOGIA