SELECT MOR.OID_MORFOLOGIA,
       MOR.COD_MORFOLOGIA,
       MOR.DES_MORFOLOGIA,
       MOR.BOL_VIGENTE,
       MOR.COD_USUARIO,
       MOR.FYH_ACTUALIZACION,
       MXC.NEC_FUNCION_CONTENEDOR,
       MXC.BOL_VIGENTE,
       MXC.OID_MORFOLOGIA_COMPONENTE,
       MOR.NEC_MODALIDAD_RECOGIDA,
       MXC.COD_TIPO_CONTENEDOR,
       MXC.COD_MORFOLOGIA_COMPONENTE,
	   MXC.NEC_ORDEN
  FROM GEPR_TMORFOLOGIA MOR
 LEFT JOIN GEPR_TMORFOLOGIA_COMPONENTE MXC ON MXC.OID_MORFOLOGIA = MOR.OID_MORFOLOGIA
 WHERE
	MOR.BOL_VIGENTE = []BOL_VIGENTE
 {0}
 ORDER BY MOR.OID_MORFOLOGIA