SELECT DISTINCT 
	DIV.COD_ISO_DIVISA, 
	DEN.COD_DENOMINACION, 
	MED.COD_TIPO_MEDIO_PAGO 
FROM 
	GEPR_TCOMPONENTE_OBJETO CO 
	LEFT JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = CO.OID_DIVISA 
	LEFT JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = CO.OID_DENOMINACION 
	LEFT JOIN GEPR_TMEDIO_PAGO MED ON MED.OID_MEDIO_PAGO = CO.OID_MEDIO_PAGO 
	WHERE CO.OID_MORFOLOGIA_COMPONENTE = []OID_MORFOLOGIA_COMPONENTE