UPDATE
	SAPR_TCONFIG_NIVEL_MOVIMIENTO
SET	
	BOL_ACTIVO = []BOL_ACTIVO,
	GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###,
	DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE
	OID_CONFIG_NIVEL_MOVIMIENTO = []OID_CONFIG_NIVEL_MOVIMIENTO