SELECT OID_CUENTA
FROM SAPR_TCUENTA CU
INNER JOIN GEPR_TSECTOR SEC ON SEC.OID_SECTOR = CU.OID_SECTOR
INNER JOIN GEPR_TPLANTA PL ON PL.OID_PLANTA = SEC.OID_PLANTA
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
LEFT JOIN GEPR_TSUBCLIENTE SUBCL ON SUBCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
INNER JOIN GEPR_TSUBCANAL SUBCN ON SUBCN.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN GEPR_TCANAL CN ON CN.OID_CANAL = SUBCN.OID_CANAL
WHERE 0 = 0
      {0}
ORDER BY OID_CUENTA