
SELECT
	CNM.OID_CONFIG_NIVEL_MOVIMIENTO,
	CNS.OID_CONFIG_NIVEL_SALDO,
	CNS.OID_CLIENTE,
	CNS.OID_SUBCLIENTE,
	CNS.OID_PTO_SERVICIO
FROM
	SAPR_TCONFIG_NIVEL_MOVIMIENTO CNM
	INNER JOIN SAPR_TCONFIG_NIVEL_SALDO CNS ON CNM.OID_CONFIG_NIVEL_SALDO = CNS.OID_CONFIG_NIVEL_SALDO
WHERE
	CNM.BOL_ACTIVO = 1
	AND CNM.OID_CLIENTE = []OID_CLIENTE
	####FILTROS####