SELECT CL.COD_CLIENTE,
       CL.DES_CLIENTE,
	   SC.COD_SECTOR,
	   SC.DES_SECTOR,
	   SBC.COD_SUBCANAL,
	   SBC.DES_SUBCANAL,
	   SBCL.COD_SUBCLIENTE,
	   SBCL.DES_SUBCLIENTE,
	   PS.COD_PTO_SERVICIO,
	   PS.DES_PTO_SERVICIO,
	   CU.COD_TIPO_CUENTA,
	   CU.OID_CUENTA,
	   D.COD_DELEGACION,
	   D.DES_DELEGACION
FROM SAPR_TCUENTA CU 
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
INNER JOIN GEPR_TSECTOR SC ON SC.OID_SECTOR = CU.OID_SECTOR
INNER JOIN GEPR_TSUBCANAL SBC ON SBC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SC.OID_PLANTA
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
LEFT JOIN GEPR_TSUBCLIENTE SBCL ON SBCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
WHERE CU.OID_CUENTA = []OID_CUENTA