SELECT
	  OID_CONFIG_NIVEL_MOVIMIENTO,
	  OID_CONFIG_NIVEL_SALDO,
	  OID_CLIENTE,
	  OID_SUBCLIENTE,
	  OID_PTO_SERVICIO,
	  RN
FROM
(
SELECT
	CNM.OID_CONFIG_NIVEL_MOVIMIENTO,
	CNS.OID_CONFIG_NIVEL_SALDO,
	CNS.OID_CLIENTE,
	CNS.OID_SUBCLIENTE,
	CNS.OID_PTO_SERVICIO,
	rank() OVER (order by CNM.Fyh_Vigencia desc, CNM.OID_CONFIG_NIVEL_MOVIMIENTO desc) RN
FROM
	SAPR_TCONFIG_NIVEL_MOVIMIENTO CNM
	INNER JOIN SAPR_TCONFIG_NIVEL_SALDO CNS ON CNM.OID_CONFIG_NIVEL_SALDO = CNS.OID_CONFIG_NIVEL_SALDO
WHERE
	CNM.BOL_ACTIVO = 1
	AND CNM.OID_CLIENTE = []OID_CLIENTE
	####FILTROS####
ORDER BY
	CNM.FYH_VIGENCIA DESC
)
WHERE
	RN = []vROWNUM