/* Nueva query para obterner Cuentas CuentaObtenerCuenta_v2.sql */
SELECT
    CU.OID_CUENTA,
    CU.COD_TIPO_CUENTA,
	CU.DES_USUARIO_CREACION,
	CU.DES_USUARIO_MODIFICACION,
    CL.OID_CLIENTE, 
    CL.COD_CLIENTE,
    CL.DES_CLIENTE, 
    CL.BOL_ENVIADO_SALDOS AS CL_BOL_ENVIADO_SALDOS,
    CL.BOL_TOTALIZADOR_SALDO AS CL_BOL_TOTALIZADOR_SALDO,
    CL.BOL_VIGENTE AS CL_BOL_VIGENTE,
    SCL.OID_SUBCLIENTE,
    SCL.COD_SUBCLIENTE,
    SCL.DES_SUBCLIENTE,
    SCL.BOL_ENVIADO_SALDOS AS SCL_BOL_ENVIADO_SALDOS,
    SCL.BOL_TOTALIZADOR_SALDO AS SCL_BOL_TOTALIZADOR_SALDO,
    SCL.BOL_VIGENTE AS SCL_BOL_VIGENTE,
    PTO.OID_PTO_SERVICIO,
    PTO.COD_PTO_SERVICIO,
    PTO.DES_PTO_SERVICIO,
    PTO.BOL_ENVIADO_SALDOS AS PTO_BOL_ENVIADO_SALDOS,
    PTO.BOL_TOTALIZADOR_SALDO AS PTO_BOL_TOTALIZADOR_SALDO,
    PTO.BOL_VIGENTE AS PTO_BOL_VIGENTE,
    CAN.OID_CANAL,
    CAN.COD_CANAL,
    CAN.DES_CANAL, 
    CAN.BOL_VIGENTE AS CAN_BOL_VIGENTE,
    SBC.OID_SUBCANAL,
    SBC.COD_SUBCANAL,
    SBC.DES_SUBCANAL,
    SBC.BOL_VIGENTE AS SBC_BOL_VIGENTE, 
    SE.OID_SECTOR,
    SE.COD_SECTOR,
    SE.DES_SECTOR,
    SE.BOL_ACTIVO AS SE_BOL_ACTIVO,
    SE.BOL_CENTRO_PROCESO,
    SE.BOL_CONTEO,
    SE.BOL_TESORO,
    SE.BOL_PERMITE_DISPONER_VALOR,
    D.OID_DELEGACION,
    D.COD_PAIS,
    D.COD_DELEGACION,
    D.DES_DELEGACION,
    D.BOL_VIGENTE AS D_BOL_VIGENTE,
    D.OID_PAIS,
    D.NEC_GMT_MINUTOS,
    D.FYH_VERANO_INICIO,
    D.FYH_VERANO_FIN,
    D.NEC_VERANO_AJUSTE,
    D.DES_ZONA,
    P.OID_PLANTA,
    P.COD_PLANTA,
    P.DES_PLANTA,
    P.BOL_ACTIVO AS P_BOL_ACTIVO,
    TSE.BOL_ACTIVO AS TSE_BOL_ACTIVO,
    TSE.COD_TIPO_SECTOR,
    TSE.DES_TIPO_SECTOR,
    TSE.OID_TIPO_SECTOR
FROM SAPR_TCUENTA CU
INNER JOIN  GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
INNER JOIN GEPR_TSUBCANAL SBC ON SBC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN GEPR_TCANAL CAN ON CAN.OID_CANAL = SBC.OID_CANAL
INNER JOIN GEPR_TSECTOR SE ON SE.OID_SECTOR = CU.OID_SECTOR
INNER JOIN GEPR_TTIPO_SECTOR TSE ON TSE.OID_TIPO_SECTOR = SE.OID_TIPO_SECTOR
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SE.OID_PLANTA
INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
LEFT JOIN GEPR_TSUBCLIENTE SCL ON SCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
WHERE 1 = 1
 {0}