SELECT CUENTA.COD_CLIENTE,
       CUENTA.DES_CLIENTE,
       CUENTA.COD_SECTOR,
       CUENTA.DES_SECTOR,
       CUENTA.COD_SUBCANAL,
       CUENTA.DES_SUBCANAL,
       CUENTA.COD_SUBCLIENTE,
       CUENTA.DES_SUBCLIENTE,
       CUENTA.COD_PTO_SERVICIO,
       CUENTA.DES_PTO_SERVICIO,
       CUENTA.COD_TIPO_CUENTA,
	   CUENTA.OID_CUENTA,
       CUENTA.COD_DELEGACION,
       CUENTA.OID_TRANSACCION_EFECTIVO,
	   CUENTA.OID_DOCUMENTO,
	   CUENTA.OID_TRANSACCION_MEDIO_PAGO
FROM(SELECT CL.COD_CLIENTE,
			CL.DES_CLIENTE,
		    SC.COD_SECTOR,
		    SC.DES_SECTOR,
		    SBC.COD_SUBCANAL,
		    SBC.DES_SUBCANAL,
		    SBCL.COD_SUBCLIENTE,
		    SBCL.DES_SUBCLIENTE,
		    PS.COD_PTO_SERVICIO,
		    PS.DES_PTO_SERVICIO,
		    CU.COD_TIPO_CUENTA,
		    CU.OID_CUENTA,
		    D.COD_DELEGACION,
		    TE.OID_TRANSACCION_EFECTIVO,
			TE.OID_DOCUMENTO,
		    NULL OID_TRANSACCION_MEDIO_PAGO
	FROM SAPR_TTRANSACCION_EFECTIVO TE
  INNER JOIN SAPR_TDOCUMENTO DOC ON DOC.OID_DOCUMENTO = TE.OID_DOCUMENTO
	INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = TE.OID_CUENTA_SALDO
	INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
	INNER JOIN GEPR_TSECTOR SC ON SC.OID_SECTOR = CU.OID_SECTOR
	INNER JOIN GEPR_TSUBCANAL SBC ON SBC.OID_SUBCANAL = CU.OID_SUBCANAL
	INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SC.OID_PLANTA
	INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
	LEFT JOIN GEPR_TSUBCLIENTE SBCL ON SBCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
	LEFT JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
	WHERE DOC.FYH_PLAN_CERTIFICACION <= []FYH_PLAN_CERTIFICACION AND DOC.BOL_CERTIFICADO = []BOL_CERTIFICADO AND CL.COD_CLIENTE = []COD_CLIENTE {0}
	UNION 
	SELECT CL.COD_CLIENTE,
		   CL.DES_CLIENTE,
		   SC.COD_SECTOR,
		   SC.DES_SECTOR,
		   SBC.COD_SUBCANAL,
		   SBC.DES_SUBCANAL,
		   SBCL.COD_SUBCLIENTE,
		   SBCL.DES_SUBCLIENTE,
		   PS.COD_PTO_SERVICIO,
		   PS.DES_PTO_SERVICIO,
		   CU.COD_TIPO_CUENTA,
		   CU.OID_CUENTA,
		   D.COD_DELEGACION,
		   NULL OID_TRANSACCION_EFECTIVO,
		   TMP.OID_DOCUMENTO,
		   TMP.OID_TRANSACCION_MEDIO_PAGO
	FROM SAPR_TTRANSACCION_MEDIO_PAGO TMP
  INNER JOIN SAPR_TDOCUMENTO DOC ON DOC.OID_DOCUMENTO = TMP.OID_DOCUMENTO
	INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = TMP.OID_CUENTA_SALDO
	INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
	INNER JOIN GEPR_TSECTOR SC ON SC.OID_SECTOR = CU.OID_SECTOR
	INNER JOIN GEPR_TSUBCANAL SBC ON SBC.OID_SUBCANAL = CU.OID_SUBCANAL
	INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SC.OID_PLANTA
	INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
	LEFT JOIN GEPR_TSUBCLIENTE SBCL ON SBCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
	LEFT JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
	WHERE DOC.FYH_PLAN_CERTIFICACION <= []FYH_PLAN_CERTIFICACION AND DOC.BOL_CERTIFICADO = []BOL_CERTIFICADO AND CL.COD_CLIENTE = []COD_CLIENTE {0}) CUENTA
ORDER BY CUENTA.OID_CUENTA