SELECT CUENTA.COD_CLIENTE,
       CUENTA.DES_CLIENTE,
       CUENTA.COD_SECTOR,
       CUENTA.DES_SECTOR,
       CUENTA.COD_SUBCANAL,
       CUENTA.DES_SUBCANAL,
       CUENTA.COD_SUBCLIENTE,
       CUENTA.DES_SUBCLIENTE,
       CUENTA.COD_PTO_SERVICIO,
       CUENTA.DES_PTO_SERVICIO,
       CUENTA.COD_TIPO_CUENTA,
	   CUENTA.OID_CUENTA,
       CUENTA.COD_DELEGACION,
	   CUENTA.OID_TRANSACCION_EFECTIVO,
	   CUENTA.OID_DOCUMENTO,
	   CUENTA.OID_TRANSACCION_MEDIO_PAGO,
	   CUENTA.OID_CERT_SALDO_EFECTIVO,
	   CUENTA.OID_CERT_SALDO_MEDIO_PAGO
FROM(SELECT CL.COD_CLIENTE,
			CL.DES_CLIENTE,
		    SC.COD_SECTOR,
		    SC.DES_SECTOR,
		    SBC.COD_SUBCANAL,
		    SBC.DES_SUBCANAL,
		    SBCL.COD_SUBCLIENTE,
		    SBCL.DES_SUBCLIENTE,
		    PS.COD_PTO_SERVICIO,
		    PS.DES_PTO_SERVICIO,
		    CU.COD_TIPO_CUENTA,
		    CU.OID_CUENTA,
		    D.COD_DELEGACION,
		    TE.OID_TRANSACCION_EFECTIVO,
			TE.OID_DOCUMENTO,
		    NULL OID_TRANSACCION_MEDIO_PAGO,
			SE.OID_CERT_SALDO_EFECTIVO,
		    NULL OID_CERT_SALDO_MEDIO_PAGO
	FROM SAPR_TCERTIFICADO CE
	INNER JOIN SAPR_TTRANSACCION_EFECTIVO TE ON CE.OID_CERTIFICADO = TE.OID_CERTIFICADO
  INNER JOIN SAPR_TCERT_SALDO_EFECTIVO SE ON CE.OID_CERTIFICADO = SE.OID_CERTIFICADO
                                             AND TE.OID_CUENTA_SALDO = SE.OID_CUENTA_SALDO
                                             AND TE.OID_DIVISA = SE.OID_DIVISA
                                             AND NVL(TE.OID_DENOMINACION, '0') = NVL(SE.OID_DENOMINACION, '0')
                                             AND TE.COD_NIVEL_DETALLE = SE.COD_NIVEL_DETALLE
                                             AND NVL(TE.COD_TIPO_EFECTIVO_TOTAL, '0') = NVL(SE.COD_TIPO_EFECTIVO_TOTAL, '0')
                                             AND NVL(TE.OID_CALIDAD, '0') = NVL(SE.OID_CALIDAD, '0')
                                             AND TE.BOL_DISPONIBLE = SE.BOL_DISPONIBLE
  INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = TE.OID_CUENTA_SALDO
  INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
  INNER JOIN GEPR_TSECTOR SC ON SC.OID_SECTOR = CU.OID_SECTOR
  INNER JOIN GEPR_TSUBCANAL SBC ON SBC.OID_SUBCANAL = CU.OID_SUBCANAL
  INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SC.OID_PLANTA
  INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
  LEFT JOIN GEPR_TSUBCLIENTE SBCL ON SBCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
  LEFT JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
	WHERE
	TE.OID_CERTIFICADO = []OID_CERTIFICADO
	UNION 
	SELECT CL.COD_CLIENTE,
		   CL.DES_CLIENTE,
		   SC.COD_SECTOR,
		   SC.DES_SECTOR,
		   SBC.COD_SUBCANAL,
		   SBC.DES_SUBCANAL,
		   SBCL.COD_SUBCLIENTE,
		   SBCL.DES_SUBCLIENTE,
		   PS.COD_PTO_SERVICIO,
		   PS.DES_PTO_SERVICIO,
		   CU.COD_TIPO_CUENTA,
		   CU.OID_CUENTA,
		   D.COD_DELEGACION,
		   NULL OID_TRANSACCION_EFECTIVO,
		   TMP.OID_DOCUMENTO,
		   TMP.OID_TRANSACCION_MEDIO_PAGO,
		   NULL OID_CERT_SALDO_EFECTIVO,
		   SMP.OID_CERT_SALDO_MEDIO_PAGO
	FROM SAPR_TCERTIFICADO CE
	INNER JOIN SAPR_TTRANSACCION_MEDIO_PAGO TMP ON TMP.OID_CERTIFICADO = CE.OID_CERTIFICADO
  INNER JOIN SAPR_TCERT_SALDO_MEDIO_PAGO SMP ON SMP.OID_CERTIFICADO = CE.OID_CERTIFICADO
                                             AND TMP.OID_CUENTA_SALDO = SMP.OID_CUENTA_SALDO
                                             AND TMP.OID_DIVISA = SMP.OID_DIVISA
                                             AND NVL(TMP.OID_MEDIO_PAGO, '0') = NVL(SMP.OID_MEDIO_PAGO, '0')
                                             AND TMP.COD_TIPO_MEDIO_PAGO = SMP.COD_TIPO_MEDIO_PAGO
                                             AND TMP.COD_NIVEL_DETALLE = SMP.COD_NIVEL_DETALLE
                                             AND TMP.BOL_DISPONIBLE = SMP.BOL_DISPONIBLE
  INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = TMP.OID_CUENTA_SALDO
  INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
  INNER JOIN GEPR_TSECTOR SC ON SC.OID_SECTOR = CU.OID_SECTOR
  INNER JOIN GEPR_TSUBCANAL SBC ON SBC.OID_SUBCANAL = CU.OID_SUBCANAL
  INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SC.OID_PLANTA
  INNER JOIN GEPR_TDELEGACION D ON D.OID_DELEGACION = P.OID_DELEGACION
  LEFT JOIN GEPR_TSUBCLIENTE SBCL ON SBCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
  LEFT JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
	WHERE
	TMP.OID_CERTIFICADO = []OID_CERTIFICADO) CUENTA
ORDER BY CUENTA.OID_DOCUMENTO,CUENTA.OID_CUENTA