SELECT 
        COUNT(1) TOTAL
FROM
        GEPR_TDELEGACION D
        INNER JOIN GEPR_TPLANTA P ON P.OID_DELEGACION = D.OID_DELEGACION
        INNER JOIN GEPR_TSECTOR S ON S.OID_PLANTA = P.OID_PLANTA
WHERE
        D.OID_DELEGACION = []OID_DELEGACION AND D.BOL_VIGENTE = 1 
		AND P.OID_PLANTA = []OID_PLANTA AND P.BOL_ACTIVO = 1 
		AND S.OID_SECTOR = []OID_SECTOR AND S.BOL_ACTIVO = 1 
		