SELECT 
        COUNT(1) TOTAL
FROM
        GEPR_TCANAL C
        INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_CANAL = C.OID_CANAL
WHERE
        C.OID_CANAL = []OID_CANAL AND C.BOL_VIGENTE = 1 
		AND SC.OID_SUBCANAL = []OID_SUBCANAL AND SC.BOL_VIGENTE = 1 
