SELECT 
        COUNT(1) TOTAL
FROM
        GEPR_TCLIENTE CLIE
        LEFT OUTER JOIN GEPR_TSUBCLIENTE SUCL ON CLIE.OID_CLIENTE = SUCL.OID_CLIENTE
        LEFT OUTER JOIN GEPR_TPUNTO_SERVICIO PUSE ON SUCL.OID_SUBCLIENTE = PUSE.OID_SUBCLIENTE
WHERE
        CLIE.OID_CLIENTE = []OID_CLIENTE AND CLIE.BOL_VIGENTE = 1 