SELECT C.OID_CLIENTE IDENTIFICADOR, C.DES_CLIENTE DESCRIPCION,'CLI' TIPO, 1 NUM_VALOR,1 UNIDAD_MEDIDA FROM GEPR_TCLIENTE C
WHERE C.COD_CLIENTE = []COD_CLIENTE
UNION
SELECT CAN.OID_CANAL IDENTIFICADOR, CAN.DES_CANAL DESCRIPCION,'CAN' TIPO,1 NUM_VALOR,1 UNIDAD_MEDIDA FROM GEPR_TCANAL CAN
WHERE CAN.COD_CANAL = []COD_CANAL
UNION
SELECT SCN.OID_SUBCANAL IDENTIFICADOR, SCN.DES_SUBCANAL DESCRIPCION,'SCN' TIPO,1 NUM_VALOR,1 UNIDAD_MEDIDA FROM GEPR_TSUBCANAL SCN
WHERE SCN.COD_SUBCANAL = []COD_SUBCANAL
UNION
SELECT DIV.OID_DIVISA IDENTIFICADOR, DIV.DES_DIVISA DESCRIPCION,'DIV' TIPO,1 NUM_VALOR,1UNIDAD_MEDIDA FROM GEPR_TDIVISA DIV
WHERE DIV.COD_ISO_DIVISA = []COD_ISO_DIVISA
UNION
SELECT DEN.OID_DENOMINACION IDENTIFICADOR, DEN.DES_DENOMINACION DESCRIPCION,'DEN' TIPO,DEN.NUM_VALOR,1 UNIDAD_MEDIDA FROM GEPR_TDENOMINACION DEN
WHERE DEN.COD_DENOMINACION = []COD_DENOMINACION
UNION
SELECT TCON.OID_TIPO_CONTENEDOR IDENTIFICADOR, TCON.DES_TIPO_CONTENEDOR DESCRIPCION,'TCON' TIPO,1 NUM_VALOR,(TCON.NEC_CANTIDAD * u.num_valor_unidad) UNIDAD_MEDIDA
FROM SAPR_TTIPO_CONTENEDOR TCON
LEFT JOIN GEPR_TUNIDAD_MEDIDA U
     ON U.OID_UNIDAD_MEDIDA = TCON.OID_UNIDAD_MEDIDA
WHERE TCON.COD_TIPO_CONTENEDOR = []COD_TIPO_CONTENEDOR
UNION
SELECT DEL.OID_DELEGACION IDENTIFICADOR, DEL.DES_DELEGACION DESCRIPCION,'DEL' TIPO,1 NUM_VALOR,1UNIDAD_MEDIDA FROM GEPR_TDELEGACION DEL
WHERE DEL.COD_DELEGACION = []COD_DELEGACION
UNION
SELECT PLA.OID_PLANTA IDENTIFICADOR, PLA.DES_PLANTA DESCRIPCION,'PLA' TIPO,1 NUM_VALOR,1UNIDAD_MEDIDA FROM GEPR_TPLANTA PLA
WHERE PLA.COD_PLANTA = []COD_PLANTA
UNION
SELECT SEC.OID_SECTOR IDENTIFICADOR, SEC.DES_SECTOR DESCRIPCION,'SEC' TIPO,1 NUM_VALOR,1UNIDAD_MEDIDA FROM GEPR_TSECTOR SEC
INNER JOIN GEPR_TPLANTA PLA ON PLA.OID_PLANTA = SEC.OID_PLANTA
WHERE SEC.COD_SECTOR = []COD_SECTOR AND PLA.COD_PLANTA = []COD_PLANTA2

