SELECT  OID_CODIGO_AJENO, 
		COD_IDENTIFICADOR, 
		COD_AJENO, DES_AJENO, 
		BOL_ACTIVO, 
		BOL_DEFECTO,
		BOL_MIGRADO
FROM GEPR_TCODIGO_AJENO 
WHERE OID_TABLA_GENESIS = []OID_TABLA_GENESIS
ORDER BY COD_IDENTIFICADOR