SELECT 
CA.OID_TABLA_GENESIS
,CA.COD_TIPO_TABLA_GENESIS
,CA.OID_CODIGO_AJENO
,CA.COD_IDENTIFICADOR
,CA.COD_AJENO
,CA.DES_AJENO
,CA.BOL_DEFECTO
,CA.BOL_MIGRADO
,CA.BOL_ACTIVO
,CA.GMT_CREACION
,CA.DES_USUARIO_CREACION
,CA.GMT_MODIFICACION
,CA.DES_USUARIO_MODIFICACION
FROM GEPR_TCODIGO_AJENO CA
{0}
ORDER BY 
CA.COD_TIPO_TABLA_GENESIS,
CA.OID_TABLA_GENESIS,
CA.COD_IDENTIFICADOR