SELECT 
CA.OID_CODIGO_AJENO,
EN.{0} COD,
EN.{1} DESCR
FROM GEPR_TCODIGO_AJENO CA
INNER JOIN {2} EN ON EN.{3} = CA.OID_TABLA_GENESIS
WHERE CA.COD_TIPO_TABLA_GENESIS = []COD_TIPO_TABLA_GENESIS
AND CA.COD_AJENO = []COD_AJENO
AND CA.COD_IDENTIFICADOR = []COD_IDENTIFICADOR
