SELECT  VTER.COD_VALOR,
        VTER.DES_VALOR,
        VTER.BOL_VALOR_DEFECTO,
        '0' NIVEL --Recupera Valores associados a nenhum cliente - subcliente - ponto serviço
FROM    GEPR_TVALOR_TERMINO_IAC VTER
WHERE   VTER.OID_TERMINO = :OID_TERMINO 
  AND   VTER.BOL_VIGENTE = 1
  AND   VTER.OID_CLIENTE IS NULL
  AND   VTER.OID_SUBCLIENTE IS NULL
  AND   VTER.OID_PTO_SERVICIO IS NULL
UNION 
SELECT  VTER.COD_VALOR,
        VTER.DES_VALOR,
        VTER.BOL_VALOR_DEFECTO,
        '1' NIVEL --Recupera Valores associados só ao cliente
FROM    GEPR_TVALOR_TERMINO_IAC VTER
WHERE   VTER.OID_TERMINO = :OID_TERMINO 
  AND   VTER.BOL_VIGENTE = 1
  AND   VTER.OID_CLIENTE = (SELECT OID_CLIENTE FROM GEPR_TCLIENTE WHERE COD_CLIENTE = :COD_CLIENTE)
  AND   VTER.OID_SUBCLIENTE IS NULL
  AND   VTER.OID_PTO_SERVICIO IS NULL
UNION 
SELECT  VTER.COD_VALOR,
        VTER.DES_VALOR,
        VTER.BOL_VALOR_DEFECTO,
        '2' NIVEL --Recupera Valores associados ao cliente e subcliente
FROM    GEPR_TVALOR_TERMINO_IAC VTER
WHERE   VTER.OID_TERMINO = :OID_TERMINO 
  AND   VTER.BOL_VIGENTE = 1
  AND   VTER.OID_CLIENTE = (SELECT OID_CLIENTE FROM GEPR_TCLIENTE WHERE COD_CLIENTE = :COD_CLIENTE)
  AND   VTER.OID_SUBCLIENTE = (SELECT OID_SUBCLIENTE FROM GEPR_TSUBCLIENTE WHERE COD_SUBCLIENTE = :COD_SUBCLIENTE
              and GEPR_TSUBCLIENTE.OID_CLIENTE = (SELECT OID_CLIENTE FROM GEPR_TCLIENTE WHERE COD_CLIENTE = :COD_CLIENTE))
  AND   VTER.OID_PTO_SERVICIO IS NULL
UNION 
SELECT  VTER.COD_VALOR,
        VTER.DES_VALOR,
        VTER.BOL_VALOR_DEFECTO,
        '3' NIVEL --Recupera Valores associados ao cliente - subcliente - ponto serviço
FROM    GEPR_TVALOR_TERMINO_IAC VTER
WHERE   VTER.OID_TERMINO = :OID_TERMINO 
  AND   VTER.BOL_VIGENTE = 1
  AND   VTER.OID_CLIENTE = (SELECT OID_CLIENTE FROM GEPR_TCLIENTE WHERE COD_CLIENTE = :COD_CLIENTE)
  AND   VTER.OID_SUBCLIENTE =  (SELECT OID_SUBCLIENTE FROM GEPR_TSUBCLIENTE WHERE COD_SUBCLIENTE = :COD_SUBCLIENTE
              and GEPR_TSUBCLIENTE.OID_CLIENTE = (SELECT OID_CLIENTE FROM GEPR_TCLIENTE WHERE COD_CLIENTE = :COD_CLIENTE))
  AND   VTER.OID_PTO_SERVICIO =  (SELECT OID_PTO_SERVICIO FROM GEPR_TPUNTO_SERVICIO WHERE COD_PTO_SERVICIO = :COD_PTO_SERVICIO
              and GEPR_TPUNTO_SERVICIO.OID_SUBCLIENTE = (SELECT OID_SUBCLIENTE FROM GEPR_TSUBCLIENTE WHERE COD_SUBCLIENTE = :COD_SUBCLIENTE
              and GEPR_TSUBCLIENTE.OID_CLIENTE = (SELECT OID_CLIENTE FROM GEPR_TCLIENTE WHERE COD_CLIENTE = :COD_CLIENTE))) 
