SELECT  T.COD_TERMINO,
	VT.COD_VALOR,
	VT.DES_VALOR,
	VT.BOL_VIGENTE,
	VT.BOL_VALOR_DEFECTO        
FROM GEPR_TTERMINO T
INNER JOIN GEPR_TVALOR_TERMINO_IAC VT 
        ON T.OID_TERMINO = VT.OID_TERMINO
LEFT JOIN GEPR_TCLIENTE C 
       ON VT.OID_CLIENTE = C.OID_CLIENTE
LEFT JOIN GEPR_TSUBCLIENTE SC 
       ON VT.OID_SUBCLIENTE = SC.OID_SUBCLIENTE       
LEFT JOIN GEPR_TPUNTO_SERVICIO PS
       ON VT.OID_PTO_SERVICIO = PS.OID_PTO_SERVICIO       
WHERE ( ([]COD_CLIENTE IS NULL AND C.COD_CLIENTE IS NULL) OR (C.COD_CLIENTE = []COD_CLIENTE) )
  AND ( ([]COD_SUBCLIENTE IS NULL AND SC.COD_SUBCLIENTE IS NULL) OR (SC.COD_SUBCLIENTE = []COD_SUBCLIENTE) )
  AND ( ([]COD_PTO_SERVICIO IS NULL AND PS.COD_PTO_SERVICIO IS NULL) OR (PS.COD_PTO_SERVICIO = []COD_PTO_SERVICIO) )
  