INSERT INTO GEPR_TVALOR_TERMINOXREMESA
(OID_VALOR_TERMINOXREMESA
,OID_REMESA
,OID_TERMINO
,COD_TERMINO
,DES_VALOR
,COD_USUARIO
,FYH_ACTUALIZACION)
VALUES
([]OID_VALOR_TERMINOXREMESA
,[]OID_REMESA
,[]OID_TERMINO
,[]COD_TERMINO
,[]DES_VALOR
,[]COD_USUARIO
,[]FYH_ACTUALIZACION)

