SELECT OID_EFECTIVOXDOCUMENTO
,OID_DOCUMENTO
,OID_DIVISA
,OID_DENOMINACION
,OID_UNIDAD_MEDIDA
,COD_NIVEL_DETALLE
,COD_TIPO_EFECTIVO_TOTAL
,OID_CALIDAD
,NUM_IMPORTE
,NEL_CANTIDAD
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION
FROM SAPR_TEFECTIVOXDOCUMENTO
WHERE OID_DOCUMENTO =[]OID_DOCUMENTO
