     UPDATE SAPR_TPERIODO PR SET PR.FYH_FIN = SYSTIMESTAMP
     WHERE PR.OID_MAQUINA = []OID_MAQUINA AND PR.OID_PLANIFICACION = []OID_PLANIFICACION 
     AND PR.OID_ESTADO_PERIODO IN (SELECT OID_ESTADO_PERIODO 
        FROM SAPR_TESTADO_PERIODO 
        WHERE COD_ESTADO_PERIODO IN ('AB', 'BL', 'DB', 'EC'))
