  DELETE FROM SAPR_TPERIODO PR
    WHERE PR.OID_MAQUINA = []OID_MAQUINA AND PR.OID_PLANIFICACION = []OID_PLANIFICACION
    AND PR.FYH_INICIO > SYSTIMESTAMP
    AND
    PR.OID_ESTADO_PERIODO IN (SELECT OID_ESTADO_PERIODO 
        FROM SAPR_TESTADO_PERIODO 
        WHERE COD_ESTADO_PERIODO IN ('AB', 'BL', 'DB', 'EC'))