DELETE SAPR_TPERIODO WHERE
OID_MAQUINA = []OID_MAQUINA AND
OID_PLANIFICACION = []OID_PLANIFICACION AND
OID_TIPO_PERIODO = (SELECT OID_TIPO_PERIODO FROM SAPR_TTIPO_PERIODO WHERE COD_TIPO_PERIODO = 'AC') AND
OID_ESTADO_PERIODO IN (SELECT OID_ESTADO_PERIODO 
FROM SAPR_TESTADO_PERIODO 
WHERE COD_ESTADO_PERIODO IN {0})
{1}