 DELETE FROM SAPR_TPERIODOXDOCUMENTO PD
     WHERE PD.OID_PERIODO IN (Select PERI.OID_PERIODO from SAPR_TPERIODO PERI
     INNER JOIN SAPR_TESTADO_PERIODO ESTADO ON ESTADO.OID_ESTADO_PERIODO = PERI.OID_ESTADO_PERIODO
WHERE PERI.OID_MAQUINA = []OID_MAQUINA  AND PERI.OID_PLANIFICACION = []OID_PLANIFICACION AND PERI.FYH_INICIO > SYSTIMESTAMP  AND ESTADO.COD_ESTADO_PERIODO IN ('AB', 'BL', 'DB', 'EC'))