SELECT
 IAC.OID_REMESA AS OID_REMESA
,NULL AS OID_BULTO
,NULL AS OID_PARCIAL
,TIAC.OID_IAC
,IAC.OID_TERMINO
,IAC.DES_VALOR_IAC
      FROM SAPR_TVALOR_IACXREMESA IAC
INNER JOIN GEPR_TTERMINO_POR_IAC TIAC ON TIAC.OID_TERMINO = IAC.OID_TERMINO
     WHERE {0}

UNION

SELECT
 NULL AS OID_REMESA
,IAC.OID_BULTO AS OID_BULTO
,NULL AS OID_PARCIAL
,TIAC.OID_IAC
,IAC.OID_TERMINO
,IAC.DES_VALOR_IAC
      FROM SAPR_TVALOR_IACXBULTO IAC
INNER JOIN GEPR_TTERMINO_POR_IAC TIAC ON TIAC.OID_TERMINO = IAC.OID_TERMINO
     WHERE  {1}
     
UNION

SELECT
 NULL AS OID_REMESA
,NULL AS OID_BULTO
,IAC.OID_PARCIAL AS OID_PARCIAL
,TIAC.OID_IAC
,IAC.OID_TERMINO
,IAC.DES_VALOR_IAC
      FROM SAPR_TVALOR_IACXPARCIAL IAC
INNER JOIN GEPR_TTERMINO_POR_IAC TIAC ON TIAC.OID_TERMINO = IAC.OID_TERMINO
     WHERE  {2}
