SELECT 
	 TIAC.OID_VALOR
	,TIAC.COD_VALOR
	,TIAC.DES_VALOR
	,TIAC.COD_USUARIO
	,TIAC.BOL_VIGENTE
	,TIAC.FYH_ACTUALIZACION
	,TIAC.BOL_VALOR_DEFECTO
	,TIAC.OID_TERMINO
FROM GEPR_TVALOR_TERMINO_IAC TIAC
{0}