  UPDATE SAPR_TPARCIAL
	SET COD_PRECINTO		=[]COD_PRECINTO
	,COD_ESTADO				=[]COD_ESTADO
	,COD_USUARIO_RESPONSABLE=[]COD_USUARIO_RESPONSABLE
	,COD_PUESTO_RESPONSABLE	=[]COD_PUESTO_RESPONSABLE
	,NEC_SECUENCIA			=[]NEC_SECUENCIA
	,GMT_MODIFICACION		=FN_GMT_ZERO_###VERSION###
	,DES_USUARIO_MODIFICACION	=[]DES_USUARIO_MODIFICACION
	,OID_PARCIAL_PADRE		=[]OID_PARCIAL_PADRE
	,OID_PARCIAL_SUSTITUTA	=[]OID_PARCIAL_SUSTITUTA
WHERE OID_PARCIAL = []OID_PARCIAL