UPDATE SAPR_TPARCIAL
SET COD_ESTADO		=[]COD_ESTADO
,GMT_MODIFICACION			=FN_GMT_ZERO_###VERSION###
,DES_USUARIO_MODIFICACION	=[]DES_USUARIO_MODIFICACION
WHERE OID_PARCIAL	=[]OID_PARCIAL
AND COD_ESTADO <> []COD_ESTADO