UPDATE SAPR_TREMESA
   SET COD_ESTADO_ABONO = 'NA'
 WHERE OID_REMESA IN (SELECT DISTINCT AE.OID_REMESA FROM SAPR_TABONO_ELEMENTO AE 
INNER JOIN SAPR_TABONO_VALOR AV ON AV.OID_ABONO_VALOR = AE.OID_ABONO_VALOR
INNER JOIN SAPR_TABONO A ON A.OID_ABONO = AV.OID_ABONO
WHERE A.OID_ABONO = []OID_ABONO)