UPDATE SAPR_TABONO
   SET COD_TIPO_ABONO = []COD_TIPO_ABONO,
       COD_ESTADO = []COD_ESTADO,
       GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###,
       DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION,
       COD_TIPO_VALORES = []COD_TIPO_VALORES,
	   OID_BANCO = []OID_BANCO
	   {0}
 WHERE OID_ABONO = []OID_ABONO
