SELECT 
  'EF' AS TIPO_MP,
  AV.OID_ABONO_VALOR,
  DIV.OID_DIVISA,
  DIV.COD_ISO_DIVISA,
  DIV.DES_DIVISA,
  DEN.OID_DENOMINACION OID_DEN_MP,
  DEN.COD_DENOMINACION COD_DEN_MP,
  DEN.DES_DENOMINACION DES_DEN_MP,
  AVE.COD_NIVEL_DETALLE,
  '' COD_TIPO_MEDIO_PAGO,
  A.COD_TIPO_VALORES,
  SUM(AVE.NUM_IMPORTE) IMPORTE,
  SUM(AVE.NEL_CANTIDAD) CANTIDAD,
  AVE.COD_TIPO_EFECTIVO_TOTAL
FROM SAPR_TABONO A
INNER JOIN SAPR_TABONO_VALOR AV ON AV.OID_ABONO = A.OID_ABONO
INNER JOIN SAPR_TABONO_VALOR_DET_EFECTIVO AVE ON AVE.OID_ABONO_VALOR = AV.OID_ABONO_VALOR
LEFT JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = AVE.OID_DENOMINACION
LEFT JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = DEN.OID_DIVISA
WHERE AV.OID_ABONO = []OID_ABONO
GROUP BY AV.OID_ABONO_VALOR,DIV.OID_DIVISA,DIV.COD_ISO_DIVISA,
  DIV.DES_DIVISA,DEN.OID_DENOMINACION,DEN.COD_DENOMINACION,
  DEN.DES_DENOMINACION,AVE.COD_NIVEL_DETALLE,A.COD_TIPO_VALORES,AVE.COD_TIPO_EFECTIVO_TOTAL

UNION

SELECT 
  'MP' AS TIPO_MP,
  AV.OID_ABONO_VALOR,
  DIV.OID_DIVISA,
  DIV.COD_ISO_DIVISA,
  DIV.DES_DIVISA,
  MP.OID_MEDIO_PAGO OID_DEN_MP,
  MP.COD_MEDIO_PAGO COD_DEN_MP,
  MP.DES_MEDIO_PAGO DES_DEN_MP,
  AVM.COD_NIVEL_DETALLE,
  AVM.COD_TIPO_MEDIO_PAGO,
  A.COD_TIPO_VALORES,
  SUM(AVM.NUM_IMPORTE) IMPORTE,
  SUM(AVM.NEL_CANTIDAD) CANTIDAD,
  NULL AS COD_TIPO_EFECTIVO_TOTAL
FROM SAPR_TABONO A
INNER JOIN SAPR_TABONO_VALOR AV ON AV.OID_ABONO = A.OID_ABONO
INNER JOIN SAPR_TABONO_VALOR_DET_MEDPAGO AVM ON AVM.OID_ABONO_VALOR = AV.OID_ABONO_VALOR
LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = AVM.OID_MEDIO_PAGO
LEFT JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = MP.OID_DIVISA
WHERE AV.OID_ABONO = []OID_ABONO
GROUP BY AV.OID_ABONO_VALOR,DIV.OID_DIVISA,DIV.COD_ISO_DIVISA,
  DIV.DES_DIVISA,MP.OID_MEDIO_PAGO,MP.COD_MEDIO_PAGO,
  MP.DES_MEDIO_PAGO,AVM.COD_NIVEL_DETALLE,AVM.COD_TIPO_MEDIO_PAGO,A.COD_TIPO_VALORES