SELECT 
'EFECTIVO' TIPO_MEDIO_PAGO,
SAL.OID_CUENTA_SALDO,
SAL.OID_DIVISA,
SAL.OID_DENOMINACION OID_DEN_MP,
SAL.COD_NIVEL_DETALLE,
SAL.OID_CALIDAD,
SAL.OID_UNIDAD_MEDIDA,
SAL.COD_TIPO_EFECTIVO_TOTAL,
/*CLIENTE*/
C.OID_CLIENTE,
C.COD_CLIENTE,
C.DES_CLIENTE,
/*SUB_CLIENTE*/
C.OID_SUBCLIENTE,
C.COD_SUBCLIENTE,
C.DES_SUBCLIENTE,
/*PTO_SERVICIO*/
C.OID_PTO_SERVICIO,
C.COD_PTO_SERVICIO,
C.DES_PTO_SERVICIO,
/*SUB_CANAL*/
C.OID_SUBCANAL,
C.COD_SUBCANAL,
C.DES_SUBCANAL,
/*CANAL*/
C.OID_CANAL,
C.COD_CANAL,
C.DES_CANAL,
{2} AS CUANT_CUENTAS,
SUM(SAL.NUM_IMPORTE) IMPORTE,
SUM(SAL.NEL_CANTIDAD) CANTIDAD
FROM SAPR_TSALDO_EFECTIVO SAL
INNER JOIN SAPR_VCUENTA C ON C.OID_CUENTA = SAL.OID_CUENTA_SALDO
{0} 
WHERE SAL.BOL_DISPONIBLE = 1 AND SAL.NUM_IMPORTE <> 0 
{1}
{3}
GROUP BY SAL.OID_CUENTA_SALDO,SAL.OID_DIVISA,SAL.OID_DENOMINACION,SAL.COD_NIVEL_DETALLE,
SAL.OID_CALIDAD,SAL.OID_UNIDAD_MEDIDA,SAL.COD_TIPO_EFECTIVO_TOTAL,
C.OID_CLIENTE,C.COD_CLIENTE,C.DES_CLIENTE,C.OID_SUBCLIENTE,C.COD_SUBCLIENTE,C.DES_SUBCLIENTE,
C.OID_PTO_SERVICIO,C.COD_PTO_SERVICIO,C.DES_PTO_SERVICIO,C.OID_CANAL,C.COD_CANAL,C.DES_CANAL,C.OID_SUBCANAL,C.COD_SUBCANAL,C.DES_SUBCANAL