SELECT 
OID_MEDIO_PAGOXDOCUMENTO
,OID_DOCUMENTO
,OID_DIVISA
,OID_MEDIO_PAGO
,COD_TIPO_MEDIO_PAGO
,COD_NIVEL_DETALLE
,NUM_IMPORTE
,NEL_CANTIDAD
,COD_MIGRACION
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION
FROM SAPR_TMEDIO_PAGOXDOCUMENTO
WHERE OID_DOCUMENTO = []OID_DOCUMENTO
