SELECT CU.OID_CUENTA,
       CSMP.BOL_DISPONIBLE,
       CSMP.NUM_IMPORTE,
       CSMP.NUM_IMPORTE_ACUMULADO,
       CSMP.NEL_CANTIDAD,
	   CSMP.NEL_CANTIDAD_ACUMULADO,
	   CSMP.COD_NIVEL_DETALLE,
       CSMP.COD_TIPO_MEDIO_PAGO,
       MP.COD_MEDIO_PAGO,
       MP.DES_MEDIO_PAGO,
	   CSMP.OID_DIVISA,
	   CSMP.OID_CERTIFICADO_ANTERIOR,
	   CSMP.OID_UNIDAD_MEDIDA
FROM SAPR_TCUENTA CU 
INNER JOIN SAPR_TCERT_SALDO_MEDIO_PAGO CSMP ON CSMP.OID_CUENTA_SALDO = CU.OID_CUENTA
LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = CSMP.OID_MEDIO_PAGO
WHERE CSMP.OID_CERTIFICADO = []OID_CERTIFICADO
ORDER BY CU.OID_CUENTA