SELECT MP.COD_MEDIO_PAGO,
       SMP.BOL_DISPONIBLE,
       SMP.NUM_IMPORTE,
       SMP.NUM_IMPORTE_ACUMULADO,
       SMP.NEL_CANTIDAD,
	   SMP.NEL_CANTIDAD_ACUMULADO,
	   SMP.COD_NIVEL_DETALLE,
	   SMP.OID_CERT_SALDO_MEDIO_PAGO,
	   SMP.OID_DIVISA,
       SMP.OID_CERT_SALDO_MEDIO_PAGO,
	   SMP.OID_CERTIFICADO_ANTERIOR,
	   SMP.OID_UNIDAD_MEDIDA
FROM SAPR_TCERT_SALDO_MEDIO_PAGO SMP
LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = SMP.OID_MEDIO_PAGO
WHERE OID_CERT_SALDO_MEDIO_PAGO = []OID_CERT_SALDO_MEDIO_PAGO