UPDATE 
	GEPR_TDENOMINACION
SET   
    DES_DENOMINACION = []DES_DENOMINACION,
    BOL_BILLETE = []BOL_BILLETE,
    NUM_VALOR = []NUM_VALOR,
    NUM_PESO = []NUM_PESO,
    BOL_VIGENTE = []BOL_VIGENTE,
    COD_USUARIO = []COD_USUARIO,
    FYH_ACTUALIZACION = []FYH_ACTUALIZACION
WHERE 
	COD_DENOMINACION = []COD_DENOMINACION