UPDATE 
	GEPR_TDENOMINACION
SET    
    BOL_VIGENTE = []BOL_VIGENTE,
    COD_USUARIO = []COD_USUARIO,
    FYH_ACTUALIZACION = []FYH_ACTUALIZACION
WHERE 
	OID_DIVISA = (SELECT OID_DIVISA FROM GEPR_TDIVISA WHERE COD_ISO_DIVISA = []COD_ISO_DIVISA)