SELECT 
	OID_DENOMINACION,
	COD_DENOMINACION,
	DES_DENOMINACION,
	BOL_BILLETE,
	NUM_VALOR,
	NUM_PESO,
	BOL_VIGENTE,
	COD_USUARIO,
	FYH_ACTUALIZACION,
	COD_ACCESO
FROM 
	GEPR_TDENOMINACION
WHERE
	OID_DIVISA = []OID_DIVISA