SELECT T.COD_ISO_DIVISA,
       T.DES_DIVISA,
       T.OID_DIVISA,
       T.OID_DENOMINACION,
       T.COD_DENOMINACION,
       T.DES_DENOMINACION,
       T.NUM_IMPORTE,
       T.NEL_CANTIDAD,
       T.BOL_DISPONIBLE,
       T.COD_NIVEL_DETALLE,
       T.OID_SECTOR,
       T.COD_SECTOR,
       T.DES_SECTOR,
       T.COD_TIPO_MEDIO_PAGO,
       T.OID_MEDIO_PAGO,
       T.COD_MEDIO_PAGO,
       T.DES_MEDIO_PAGO
FROM (
SELECT D.COD_ISO_DIVISA,
       D.DES_DIVISA,
       D.OID_DIVISA,
       DEN.OID_DENOMINACION,
       DEN.COD_DENOMINACION,
       DEN.DES_DENOMINACION,
       SUM(SE.NUM_IMPORTE) NUM_IMPORTE,
       SUM(SE.NEL_CANTIDAD) NEL_CANTIDAD,
       SE.BOL_DISPONIBLE,
       SE.COD_NIVEL_DETALLE,
       S.OID_SECTOR,
       S.COD_SECTOR,
       S.DES_SECTOR,
       NULL COD_TIPO_MEDIO_PAGO,
       NULL OID_MEDIO_PAGO,
       NULL COD_MEDIO_PAGO,
       NULL DES_MEDIO_PAGO
FROM GEPR_TSECTOR S 
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN SAPR_TCUENTA CU ON CU.OID_SECTOR = S.OID_SECTOR
INNER JOIN SAPR_TSALDO_EFECTIVO SE ON SE.OID_CUENTA_SALDO = CU.OID_CUENTA
INNER JOIN GEPR_TDIVISA D ON D.OID_DIVISA = SE.OID_DIVISA
LEFT JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = SE.OID_DENOMINACION
WHERE DEL.COD_DELEGACION = []COD_DELEGACION AND P.COD_PLANTA = []COD_PLANTA
{0}
GROUP BY D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA,DEN.OID_DENOMINACION,DEN.COD_DENOMINACION,
         DEN.DES_DENOMINACION, SE.BOL_DISPONIBLE,  S.OID_SECTOR, S.COD_SECTOR, S.DES_SECTOR,SE.COD_NIVEL_DETALLE
UNION
SELECT D.COD_ISO_DIVISA,
       D.DES_DIVISA,
       D.OID_DIVISA,
       NULL OID_DENOMINACION,
       NULL COD_DENOMINACION,
       NULL DES_DENOMINACION,
       SUM(SE.NUM_IMPORTE) NUM_IMPORTE,
       SUM(SE.NEL_CANTIDAD) NEL_CANTIDAD,
       SE.BOL_DISPONIBLE,
       SE.COD_NIVEL_DETALLE,
       S.OID_SECTOR,
       S.COD_SECTOR,
       S.DES_SECTOR,
       SE.COD_TIPO_MEDIO_PAGO,
       SE.OID_MEDIO_PAGO,
       MP.COD_MEDIO_PAGO,
       MP.DES_MEDIO_PAGO
FROM GEPR_TSECTOR S 
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN SAPR_TCUENTA CU ON CU.OID_SECTOR = S.OID_SECTOR
INNER JOIN SAPR_TSALDO_MEDIO_PAGO SE ON SE.OID_CUENTA_SALDO = CU.OID_CUENTA
INNER JOIN GEPR_TDIVISA D ON D.OID_DIVISA = SE.OID_DIVISA
LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_DIVISA = D.OID_DIVISA AND MP.OID_MEDIO_PAGO = SE.OID_MEDIO_PAGO
WHERE DEL.COD_DELEGACION = []COD_DELEGACION AND P.COD_PLANTA = []COD_PLANTA
{0}
GROUP BY D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA,SE.COD_TIPO_MEDIO_PAGO,SE.OID_MEDIO_PAGO, MP.COD_MEDIO_PAGO, MP.DES_MEDIO_PAGO, SE.BOL_DISPONIBLE,  
         S.OID_SECTOR, S.COD_SECTOR, S.DES_SECTOR,SE.COD_NIVEL_DETALLE) T
ORDER BY  T.OID_SECTOR,T.COD_ISO_DIVISA