SELECT CU.OID_CUENTA,
       CU.OID_SUBCANAL, 
       DV.OID_DIVISA,
       DV.COD_ISO_DIVISA,
       DV.DES_DIVISA,
       TE.BOL_DISPONIBLE,
       SUM(TE.NUM_IMPORTE) NUM_IMPORTE,
       SUM(TE.NEL_CANTIDAD) NEL_CANTIDAD,
       TE.COD_NIVEL_DETALLE,
       TE.OID_CALIDAD,
	   TE.OID_UNIDAD_MEDIDA,
       TE.COD_TIPO_EFECTIVO_TOTAL,
       TE.COD_NIVEL_DETALLE,
       DN.COD_DENOMINACION,
       DN.DES_DENOMINACION,
	   DN.OID_DENOMINACION
FROM SAPR_TDOCUMENTO D
INNER JOIN SAPR_TTRANSACCION_EFECTIVO TE ON TE.OID_DOCUMENTO = D.OID_DOCUMENTO
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = TE.OID_CUENTA_SALDO
INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = CU.OID_SECTOR
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DL ON DL.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
INNER JOIN GEPR_TDIVISA DV ON DV.OID_DIVISA = TE.OID_DIVISA
INNER JOIN SAPR_TTIPO_DOCUMENTO TP ON D.OID_TIPO_DOCUMENTO = TP.OID_TIPO_DOCUMENTO
LEFT JOIN GEPR_TDENOMINACION DN ON DN.OID_DENOMINACION = TE.OID_DENOMINACION 
WHERE D.FYH_PLAN_CERTIFICACION <= []FYH_PLAN_CERTIFICACION 
	 AND D.BOL_CERTIFICADO = []BOL_CERTIFICADO AND CL.COD_CLIENTE = []COD_CLIENTE
	 AND NOT EXISTS (SELECT CER.OID_CERTIFICADO FROM SAPR_TCERTIFICADO CER WHERE CER.OID_CERTIFICADO = TE.OID_CERTIFICADO AND CER.COD_ESTADO = 'DE')
	 AND TP.BOL_CERTIFICACION = 1 
{0}
GROUP BY CU.OID_CUENTA, 
       CU.OID_SUBCANAL, 
       DV.OID_DIVISA,
       DV.COD_ISO_DIVISA,
       DV.DES_DIVISA,
       TE.BOL_DISPONIBLE,
       TE.COD_NIVEL_DETALLE,
       TE.OID_CALIDAD,
	   TE.OID_UNIDAD_MEDIDA,
       TE.COD_TIPO_EFECTIVO_TOTAL,
       TE.COD_NIVEL_DETALLE,
       DN.COD_DENOMINACION,
       DN.DES_DENOMINACION,
	   DN.OID_DENOMINACION