MERGE INTO SAPR_TSALDO_EFECTIVO Q1
USING ( SELECT A.OID_TRANSACCION_EFECTIVO
              ,A.OID_CUENTA_SALDO
              ,A.OID_DIVISA
              ,A.OID_DENOMINACION
              ,A.COD_NIVEL_DETALLE
              ,A.OID_CALIDAD
              ,A.COD_TIPO_EFECTIVO_TOTAL
              ,A.NUM_IMPORTE
              ,A.NEL_CANTIDAD
              ,A.BOL_DISPONIBLE
              ,A.OID_UNIDAD_MEDIDA
          FROM SAPR_TTRANSACCION_EFECTIVO A
          WHERE A.OID_TRANSACCION_EFECTIVO = []OID_TRANSACCION_EFECTIVO
      ) Q2
   ON ( Q1.OID_CUENTA_SALDO = Q2.OID_CUENTA_SALDO
        AND Q1.OID_DIVISA = Q2.OID_DIVISA
        AND NVL(Q1.OID_DENOMINACION,'-') = NVL(Q2.OID_DENOMINACION,'-')
        AND NVL(Q1.COD_NIVEL_DETALLE,'-') = NVL(Q2.COD_NIVEL_DETALLE,'-')
        AND Q1.BOL_DISPONIBLE = Q2.BOL_DISPONIBLE
        AND NVL(Q1.OID_CALIDAD,'-') = NVL(Q2.OID_CALIDAD,'-')
        AND NVL(Q1.COD_TIPO_EFECTIVO_TOTAL,'-') = NVL(Q2.COD_TIPO_EFECTIVO_TOTAL,'-')
        AND NVL(Q1.OID_UNIDAD_MEDIDA,'-') = NVL(Q2.OID_UNIDAD_MEDIDA,'-')
        AND ROWNUM <= 1)
WHEN MATCHED THEN
  UPDATE 
     SET Q1.NUM_IMPORTE  = NVL(Q1.NUM_IMPORTE,0) + NVL(Q2.NUM_IMPORTE,0)
        ,Q1.NEL_CANTIDAD = NVL(Q1.NEL_CANTIDAD,0) + NVL(Q2.NEL_CANTIDAD,0)
        ,Q1.GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###
        ,Q1.DES_USUARIO_MODIFICACION = []DES_USUARIO
        ,Q1.OID_ULTIMA_TRANSACCION = Q2.OID_TRANSACCION_EFECTIVO
WHEN NOT MATCHED THEN
  INSERT (Q1.OID_SALDO_EFECTIVO
          ,Q1.OID_CUENTA_SALDO
          ,Q1.OID_ULTIMA_TRANSACCION
          ,Q1.OID_DENOMINACION
          ,Q1.OID_DIVISA
          ,Q1.COD_NIVEL_DETALLE
          ,Q1.COD_TIPO_EFECTIVO_TOTAL
          ,Q1.OID_CALIDAD
          ,Q1.BOL_DISPONIBLE
          ,Q1.OID_UNIDAD_MEDIDA
          ,Q1.NUM_IMPORTE
          ,Q1.NEL_CANTIDAD
          ,Q1.GMT_CREACION 
          ,Q1.DES_USUARIO_CREACION 
          ,Q1.GMT_MODIFICACION 
          ,Q1.DES_USUARIO_MODIFICACION)
VALUES (SYS_GUID() 
          ,Q2.OID_CUENTA_SALDO 
          ,[]OID_TRANSACCION_EFECTIVO
          ,Q2.OID_DENOMINACION 
          ,Q2.OID_DIVISA
          ,Q2.COD_NIVEL_DETALLE
          ,Q2.COD_TIPO_EFECTIVO_TOTAL
          ,Q2.OID_CALIDAD 
          ,Q2.BOL_DISPONIBLE 
          ,Q2.OID_UNIDAD_MEDIDA
          ,Q2.NUM_IMPORTE 
          ,Q2.NEL_CANTIDAD
          ,FN_GMT_ZERO_###VERSION###
          ,[]DES_USUARIO 
          ,FN_GMT_ZERO_###VERSION###
          ,[]DES_USUARIO)