SELECT D.COD_ISO_DIVISA,
       D.DES_DIVISA,
       D.OID_DIVISA,
       MP.COD_TIPO_MEDIO_PAGO,
       MP.OID_MEDIO_PAGO,
       MP.COD_MEDIO_PAGO,
       MP.DES_MEDIO_PAGO,
       SUM(SMP.NUM_IMPORTE) NUM_IMPORTE,
       SUM(SMP.NEL_CANTIDAD) NEL_CANTIDAD,
       SMP.BOL_DISPONIBLE,
       SMP.COD_NIVEL_DETALLE,
       CU.OID_CUENTA
FROM GEPR_TSECTOR S
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN SAPR_TCUENTA CU ON CU.OID_SECTOR = S.OID_SECTOR
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN SAPR_TSALDO_MEDIO_PAGO SMP ON SMP.OID_CUENTA_SALDO = CU.OID_CUENTA
INNER JOIN GEPR_TDIVISA D ON D.OID_DIVISA = SMP.OID_DIVISA
LEFT JOIN GEPR_TMEDIO_PAGO MP ON MP.OID_MEDIO_PAGO = SMP.OID_MEDIO_PAGO
LEFT JOIN GEPR_TSUBCLIENTE SCL ON SCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
WHERE DEL.COD_DELEGACION = []COD_DELEGACION AND P.COD_PLANTA = []COD_PLANTA
{0}
GROUP BY D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA, 
MP.COD_TIPO_MEDIO_PAGO,MP.OID_MEDIO_PAGO,COD_MEDIO_PAGO,DES_MEDIO_PAGO,
OID_CUENTA, COD_NIVEL_DETALLE, BOL_DISPONIBLE
ORDER BY  OID_CUENTA,COD_ISO_DIVISA
