SELECT D.COD_ISO_DIVISA,
	   D.DES_DIVISA,
       D.OID_DIVISA,
	   DEN.OID_DENOMINACION,
	   DEN.COD_DENOMINACION,
	   DEN.DES_DENOMINACION,
       SUM(SE.NUM_IMPORTE) NUM_IMPORTE,
	   SUM(SE.NEL_CANTIDAD) NEL_CANTIDAD,
       SE.BOL_DISPONIBLE,
	   SE.COD_NIVEL_DETALLE,
       S.OID_SECTOR,
       S.COD_SECTOR,
       S.DES_SECTOR,
	   NULL COD_TIPO_MEDIO_PAGO,
       NULL OID_MEDIO_PAGO,
       NULL COD_MEDIO_PAGO,
       NULL DES_MEDIO_PAGO
FROM GEPR_TSECTOR S
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN SAPR_TCUENTA CU ON CU.OID_SECTOR = S.OID_SECTOR
INNER JOIN SAPR_TSALDO_EFECTIVO SE ON SE.OID_CUENTA_SALDO = CU.OID_CUENTA
INNER JOIN GEPR_TDIVISA D ON D.OID_DIVISA = SE.OID_DIVISA
LEFT JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = SE.OID_DENOMINACION
WHERE DEL.COD_DELEGACION = []COD_DELEGACION AND P.COD_PLANTA = []COD_PLANTA
{0}
GROUP BY D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA,DEN.OID_DENOMINACION,DEN.COD_DENOMINACION,
         DEN.DES_DENOMINACION, SE.BOL_DISPONIBLE,  S.OID_SECTOR, S.COD_SECTOR, S.DES_SECTOR,SE.COD_NIVEL_DETALLE
ORDER BY  S.OID_SECTOR,D.COD_ISO_DIVISA