SELECT D.COD_ISO_DIVISA,
	   D.DES_DIVISA,
       D.OID_DIVISA,
       DEN.OID_DENOMINACION,
       DEN.COD_DENOMINACION,
       DEN.DES_DENOMINACION,
       SUM(SE.NUM_IMPORTE) NUM_IMPORTE,
	   SUM(SE.NEL_CANTIDAD) NEL_CANTIDAD,
       SE.BOL_DISPONIBLE,
       SE.COD_NIVEL_DETALLE,
       CU.OID_CUENTA,
	   SE.OID_CALIDAD
FROM GEPR_TSECTOR S
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = P.OID_DELEGACION
INNER JOIN SAPR_TCUENTA CU ON CU.OID_SECTOR = S.OID_SECTOR
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN SAPR_TSALDO_EFECTIVO SE ON SE.OID_CUENTA_SALDO = CU.OID_CUENTA
INNER JOIN GEPR_TDIVISA D ON D.OID_DIVISA = SE.OID_DIVISA
LEFT JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = SE.OID_DENOMINACION
LEFT JOIN GEPR_TSUBCLIENTE SCL ON SCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PS ON PS.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
WHERE DEL.COD_DELEGACION = []COD_DELEGACION AND P.COD_PLANTA = []COD_PLANTA
{0}
GROUP BY D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA, DEN.OID_DENOMINACION,DEN.COD_DENOMINACION,DEN.DES_DENOMINACION, CU.OID_CUENTA, SE.COD_NIVEL_DETALLE, SE.BOL_DISPONIBLE,SE.OID_CALIDAD
ORDER BY  CU.OID_CUENTA,D.COD_ISO_DIVISA
