var app = angular.module("ConsLocApp");

app.constant('ConsLocConstants', {
    CONST_OBTENER_SALDOS_CLIENTES_DELEGACION: 'OBTENER_SALDOS_CLIENTE_DELEGACION',
    CONST_OBTENER_SECTORES_CLIENTES: 'OBTENER_SECTORES_CLIENTE',
    CONST_OBTENER_SALDOS_CLIENTE: 'OBTENER_SALDOS_CLIENTE',
    CONST_TESORERIA_INTEGRAL: 'TESORERIA_INTEGRAL',
    CONST_OBTENER_TRADUCCIONES: 'OBTENER_TRADUCCIONES',
    CONST_ACCIONHANDLER_PATH: '/ActionHandler',
    CONST_CONSLOC_SERVICE_PATH: 'api/LogApi/EjecutarAccion',
    CONST_INFORMATIONREQUESTED_PATH: '/InformationRequested/',
    CONST_ROOT_PATH: '/',
    CONST_OBTENER_BANCOS: 'OBTENER_BANCOS',
    CONST_OBTENER_ACREDITACIONES: 'OBTENER_ACREDITACIONES',
    CONST_OBTENER_DETALLESCLIENTES: 'OBTENER_DETALLESCLIENTES',
    CONST_OBTENER_ACREDITACIONES_MAE: 'OBTENER_ACREDICTIONES_MAE',
    CONST_OBTENER_BANCOS_FECHAVALOR: 'OBTENER_BANCOS_FECHAVALOR',
    CONST_OBTENER_TORTAMAESXCLIENTE: 'OBTENER_TORTAMAESXCLIENTE',
    CONST_OBTENER_BANCOS_CONFIG: 'OBTENER_BANCOS_CONFIG',
    CONST_OBTENER_PLANIFICACIONES: 'OBTENER_PLANIFICACIONES',
    CONST_OBTENER_DETALLE_MAES: 'OBTENER_DETACREDMAE',
    CONST_OBTENER_SALDOSDESCLI: 'OBTENER_SALDOSDESCLI',
    CONST_OBTENER_SALDOSDESDELEG: 'OBTENER_SALDOSDESDELEG',
    CONST_OBTENER_SALDOSDESP: 'OBTENER_SALDOSDESP',
    CONST_OBTENER_SALDOSACRED: 'OBTENER_SALDOSACRED',
    CONST_OBTENER_CLIPLANIFICACION: 'OBTENER_CLIPLANIFICACION',
    CONST_OBTENER_DETALLEDELEGACIONES: 'OBTENER_DETALLEDELEG',
    CONST_OBTENER_ACREDITACIONES_MAE_DELEG: 'OBTENER_ACREDITACIONES_MAE_DELEG'
});