SELECT
       G.COD_GRUPO GRUPO_CODIGO,
       G.DES_GRUPO GRUPO_DESCRIPCION,
       G.BOL_GRUPO_VIGENTE GRUPO_VIGENTE,
       DC.IDMOVIMENTACIONFONDO TRANSACION_OIDTRANSACION,
       DC.FECHA TRANSACION_FECHA,
       DC.NUMEXTERNO TRANSACION_NUMEXTERNO,
       P_O.IDPS PLANTA_CODIGO,
       P_O.DESCRIPCION PLANTA_DESCRIPCION,
       CP_O.IDPS SECTORORIGEN_CODIGO,
       CP_O.DESCRIPCION SECTORORIGEN_DESCRIPCION,
       CP_D.IDPS SECTORDESTINO_CODIGO,
       CP_D.DESCRIPCION SECTORDESTINO_DESCRIPCION,
       C_O.IDPS CLIENTE_CODIGO,
       C_O.DESCRIPCION CLIENTE_DESCRIPCION,
       CA_O.IDPS CANALORIGEN_CODIGO,
       CA_O.DESCRIPCION CANALORIGEN_DESCRIPCION,
       CA_D.IDPS CANALDESTINO_CODIGO,
       CA_D.DESCRIPCION CANALDESTINO_DESCRIPCION,
       M.ISOGENESIS MONEDA_CODIGO,
       M.DESCRIPCION MONEDA_DESCRIPCION,
       E.IDESPECIE ESPECIE_CODIGO,
       E.DESCRIPCION ESPECIE_DESCRIPCION,
       DD.CANTIDAD ESPECIE_CANTIDAD,
       DD.IMPORTE ESPECIE_IMPORTE,
       F.DESCRIPCION DOCUMENTO_NOMBREDOCUMENTO,
       SALDO_DISPONIBLE_###VERSION###(M.ACCION, EC.CODIGO) SALDO_DISPONIBLE
FROM
       PD_GRUPO G
       INNER JOIN PD_GRUPOFORMULARIO GF ON G.ID_GRUPO = GF.ID_GRUPO
       INNER JOIN PD_FORMULARIO F ON GF.ID_FOMULARIO = F.IDFORMULARIO
       INNER JOIN PD_MOTIVO M ON F.IDMOTIVO = M.IDMOTIVO
       INNER JOIN PD_DOCUMENTOCABECERA DC ON DC.IDFORMULARIO = F.IDFORMULARIO
       INNER JOIN PD_ESTADOCOMPROBANTE EC ON DC.IDESTADOCOMPROBANTE = EC.IDESTADOCOMPROBANTE
       INNER JOIN PD_CENTROPROCESO CP_O ON DC.IDCENTROPROCESOORIGEN = CP_O.IDCENTROPROCESO
       INNER JOIN PD_CENTROPROCESO CP_D ON DC.IDCENTROPROCESODESTINO = CP_D.IDCENTROPROCESO
       INNER JOIN PD_PLANTA P_O ON CP_O.IDPLANTA = P_O.IDPLANTA
       INNER JOIN PD_CLIENTE C_O ON DC.IDCLIENTEORIGEN = C_O.IDCLIENTE
       INNER JOIN PD_CLIENTE CA_O ON DC.IDBANCO = CA_O.IDCLIENTE
       INNER JOIN PD_CLIENTE CA_D ON DC.IDBANCODEPOSITO = CA_D.IDCLIENTE
       INNER JOIN PD_DOCUMENTODETALLE DD ON DC.IDDOCUMENTO = DD.IDDOCUMENTO
       INNER JOIN PD_ESPECIE E ON DD.IDESPECIE = E.IDESPECIE
       INNER JOIN PD_MONEDA M ON E.IDMONEDA = M.IDMONEDA
WHERE
	   1 = 1
	   ###FILTROS###
GROUP BY
       G.COD_GRUPO,
       G.DES_GRUPO,
       G.BOL_GRUPO_VIGENTE,
       DC.IDMOVIMENTACIONFONDO,
       DC.FECHA,
       DC.NUMEXTERNO,
       P_O.IDPS,
       P_O.DESCRIPCION,
       CP_O.IDPS,
       CP_O.DESCRIPCION,
       CP_D.IDPS,
       CP_D.DESCRIPCION,
       C_O.IDPS,
       C_O.DESCRIPCION,
       CA_O.IDPS,
       CA_O.DESCRIPCION,
       CA_D.IDPS,
       CA_D.DESCRIPCION,
       M.ISOGENESIS,
       M.DESCRIPCION,
       E.IDESPECIE,
       E.DESCRIPCION,
       DD.IMPORTE,
       DD.CANTIDAD,
       DD.IMPORTE,
       F.DESCRIPCION,
       SALDO_DISPONIBLE_###VERSION###(M.ACCION, EC.CODIGO)
ORDER BY
       G.COD_GRUPO,
       G.DES_GRUPO,
       G.BOL_GRUPO_VIGENTE,
       F.DESCRIPCION,
       DC.IDMOVIMENTACIONFONDO,
       DC.FECHA,
       DC.NUMEXTERNO,
       P_O.IDPS,
       CP_O.IDPS,
       CP_D.IDPS,
       C_O.IDPS,
       C_O.DESCRIPCION,
       CA_O.IDPS,
       CA_D.IDPS,
       M.ISOGENESIS,
       M.DESCRIPCION,
       E.IDESPECIE,
       E.DESCRIPCION,
       SALDO_DISPONIBLE_###VERSION###(M.ACCION, EC.CODIGO)