SELECT 
  IDDOCUMENTO, 
  IDFORMULARIO, 
  IDESTADOCOMPROBANTE, 
  IDPRIMORDIAL,
  TO_CHAR(FECHA, 'DD/MM/YYYY HH24:mm:ss') FECHA
FROM PD_DOCUMENTOCABECERA
WHERE NUMEXTERNO = :NUMEXTERNO
ORDER BY IDDOCUMENTO DESC, FECHA DESC
