UPDATE 
  (SELECT 
		DC.IDCLIENTEORIGEN, 
		DC.IDCLIENTEDESTINO,
		DC2.IDCLIENTEORIGEN IDCLIENTEORIGENFIN, 
		DC2.IDCLIENTEDESTINO IDCLIENTEDESTINOFIN
    FROM PD_DOCUMENTOCABECERA DC
    INNER JOIN PD_DOCUMENTOCABECERA DC2 ON DC2.IDORIGEN = DC.IDDOCUMENTO
    WHERE DC2.IDORIGEN = :IDORIGEN
    AND DC2.AGRUPADO = 1)
SET
IDCLIENTEORIGENFIN = IDCLIENTEORIGEN, 
IDCLIENTEDESTINOFIN = IDCLIENTEDESTINO