SELECT SUBC.OID_SUBCANAL, SUBC.COD_SUBCANAL, SUBC.DES_SUBCANAL
FROM SAPR_TCERTIFICADOXSUBCANAL CESC INNER JOIN GEPR_TSUBCANAL SUBC ON CESC.OID_SUBCANAL = SUBC.OID_SUBCANAL
WHERE CESC.OID_CERTIFICADO = []OID_CERTIFICADO
ORDER BY SUBC.COD_SUBCANAL