SELECT DELE.OID_DELEGACION, DELE.COD_DELEGACION, DELE.DES_DELEGACION, PLANT.OID_PLANTA, PLANT.COD_PLANTA, PLANT.DES_PLANTA
FROM SAPR_TCERTIFICADOXDELEGACION CEDE INNER JOIN GEPR_TDELEGACION DELE ON CEDE.OID_DELEGACION = DELE.OID_DELEGACION INNER JOIN GEPR_TPLANTA PLANT ON DELE.OID_DELEGACION = PLANT.OID_DELEGACION
WHERE CEDE.OID_CERTIFICADO = []OID_CERTIFICADO
ORDER BY DELE.COD_DELEGACION, PLANT.COD_PLANTA