SELECT OID_TIPO_DOCUMENTO,
       COD_TIPO_DOCUMENTO,
       DES_TIPO_DOCUMENTO,
       NEC_ORDEN,
       BOL_ACTIVO,
       BOL_CERTIFICACION,
       GMT_CREACION,
       DES_USUARIO_CREACION,
       GMT_MODIFICACION,
       DES_USUARIO_MODIFICACION
FROM SAPR_TTIPO_DOCUMENTO
WHERE COD_TIPO_DOCUMENTO = []COD_TIPO_DOCUMENTO