INSERT INTO SAPR_TTRANSACCION_MEDIO_PAGO 
(OID_TRANSACCION_MEDIO_PAGO
,OID_DOCUMENTO
,OID_CUENTA
,OID_CUENTA_SALDO
,OID_DIVISA
,OID_MEDIO_PAGO
,OID_CERTIFICADO
,COD_TIPO_MEDIO_PAGO
,COD_NIVEL_DETALLE
,BOL_DISPONIBLE
,NUM_IMPORTE
,NEL_CANTIDAD
,COD_ESTADO_DOCUMENTO
,COD_TIPO_SITIO
,COD_TIPO_MOVIMIENTO
,OBS_TRANSACCION
,COD_MIGRACION
,FYH_PLAN_CERTIFICACION
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,BOL_CONTRA_MOVIMIENTO
,DES_USUARIO_MODIFICACION)
SELECT 
[]OID_TRANSACCION_MEDIO_PAGO
,[]OID_DOCUMENTO
,OID_CUENTA
,OID_CUENTA_SALDO
,OID_DIVISA
,OID_MEDIO_PAGO
,NULL OID_CERTIFICADO
,COD_TIPO_MEDIO_PAGO
,COD_NIVEL_DETALLE
,BOL_DISPONIBLE
,NUM_IMPORTE * (-1) -- Inverte o valor
,NEL_CANTIDAD * (-1) -- Inverte o valor
,[]COD_ESTADO_DOCUMENTO
,[]COD_TIPO_SITIO
,COD_TIPO_MOVIMIENTO
,OBS_TRANSACCION
,COD_MIGRACION
,[]FYH_PLAN_CERTIFICACION
,FN_GMT_ZERO_###VERSION###
,[]USUARIO
,FN_GMT_ZERO_###VERSION###
,1 -- ANULADO
,[]USUARIO
FROM SAPR_TTRANSACCION_MEDIO_PAGO
WHERE OID_TRANSACCION_MEDIO_PAGO	=[]OID_TRANSACCION_MP_ATUAL
