SELECT 
	DES_USUARIO,
	DES_DELEGACION,
	DES_SECTOR,
	DES_PRODUCTO,
	DES_CLIENTE,
	DES_DIVISA,
	DES_DENOMINACION,
	CASE BOL_MECANIZADO 
		WHEN 1 THEN SUM(NEL_CANTIDAD_TOTAL_BILLETES + NEL_CANTIDAD_TOTAL_MONEDAS)
	END CANTIDAD_MECANIZADO,
	CASE BOL_MECANIZADO 
		WHEN 0 THEN SUM(NEL_CANTIDAD_TOTAL_BILLETES + NEL_CANTIDAD_TOTAL_MONEDAS)
	END CANTIDAD_MANUAL
FROM DAPR_TVALORES_PROCESADOS
	{0}
GROUP BY 
	FECHA_HORA,
	COD_DELEGACION,
	DES_DELEGACION,
	COD_SECTOR,
	DES_SECTOR,
	COD_CLIENTE,
	DES_CLIENTE,
	COD_PRODUCTO,
	DES_PRODUCTO,
	COD_USUARIO,
	DES_USUARIO,
	COD_ISO_DIVISA,
	DES_DIVISA,
	COD_DENOMINACION,
	DES_DENOMINACION,
	BOL_MECANIZADO
ORDER BY
	SUM(NEL_CANTIDAD_TOTAL_BILLETES + NEL_CANTIDAD_TOTAL_MONEDAS) DESC