SELECT 
  COD_CLIENTE,
  DES_CLIENTE,
  SUM(NEL_CANTIDAD_TOTAL_BILLETES + NEL_CANTIDAD_TOTAL_MONEDAS) AS TOTAL
FROM DAPR_TVALORES_PROCESADOS
{0}
GROUP BY
  COD_CLIENTE,
  DES_CLIENTE
ORDER BY
  SUM(NEL_CANTIDAD_TOTAL_BILLETES + NEL_CANTIDAD_TOTAL_MONEDAS) DESC
