MERGE INTO DAPR_TVALORES_PROCESADOS Q1
USING DUAL ON
(
	  Q1.FECHA_HORA = []FECHA_HORA
		 AND Q1.COD_DELEGACION = []COD_DELEGACION
		 AND Q1.COD_SECTOR = []COD_SECTOR
		 AND Q1.COD_CLIENTE = []COD_CLIENTE
		 AND Q1.COD_PRODUCTO = []COD_PRODUCTO
		 AND Q1.COD_USUARIO = []COD_USUARIO
		 AND Q1.COD_ISO_DIVISA = []COD_ISO_DIVISA
		 AND Q1.COD_DENOMINACION = []COD_DENOMINACION
		 AND Q1.BOL_MECANIZADO = []BOL_MECANIZADO
)
WHEN MATCHED THEN
    UPDATE SET 
		Q1.NUM_IMPORTE_TOTAL_BILLETES = Q1.NUM_IMPORTE_TOTAL_BILLETES + []NUM_IMPORTE_TOTAL_BILLETES
		,Q1.NUM_IMPORTE_TOTAL_MONEDAS = Q1.NUM_IMPORTE_TOTAL_MONEDAS + []NUM_IMPORTE_TOTAL_MONEDAS
		,Q1.NEL_CANTIDAD_TOTAL_BILLETES = Q1.NEL_CANTIDAD_TOTAL_BILLETES + []NEL_CANTIDAD_TOTAL_BILLETES
		,Q1.NEL_CANTIDAD_TOTAL_MONEDAS = Q1.NEL_CANTIDAD_TOTAL_MONEDAS + []NEL_CANTIDAD_TOTAL_MONEDAS
		,Q1.NEL_CANTIDAD_TOTAL_MINUTOS = Q1.NEL_CANTIDAD_TOTAL_MINUTOS + []NEL_CANTIDAD_TOTAL_MINUTOS
WHEN NOT MATCHED THEN
    INSERT (
		Q1.OID_VALORES_PROCESADOS,
		Q1.FECHA_HORA,
		Q1.COD_DELEGACION,
		Q1.DES_DELEGACION,
		Q1.COD_SECTOR,
		Q1.DES_SECTOR,
		Q1.COD_CLIENTE,
		Q1.DES_CLIENTE,
		Q1.COD_PRODUCTO,
		Q1.DES_PRODUCTO,
		Q1.COD_USUARIO,
		Q1.DES_USUARIO,
		Q1.COD_ISO_DIVISA,
		Q1.DES_DIVISA,
		Q1.COD_DENOMINACION,
		Q1.DES_DENOMINACION,
		Q1.BOL_MECANIZADO,
		Q1.NUM_IMPORTE_TOTAL_BILLETES,
		Q1.NUM_IMPORTE_TOTAL_MONEDAS,
		Q1.NEL_CANTIDAD_TOTAL_BILLETES,
		Q1.NEL_CANTIDAD_TOTAL_MONEDAS,
		Q1.NEL_CANTIDAD_TOTAL_MINUTOS
	)
    VALUES (
		[]OID_VALORES_PROCESADOS,
		[]FECHA_HORA,
		[]COD_DELEGACION,
		[]DES_DELEGACION,
		[]COD_SECTOR,
		[]DES_SECTOR,
		[]COD_CLIENTE,
		[]DES_CLIENTE,
		[]COD_PRODUCTO,
		[]DES_PRODUCTO,
		[]COD_USUARIO,
		[]DES_USUARIO,
		[]COD_ISO_DIVISA,
		[]DES_DIVISA,
		[]COD_DENOMINACION,
		[]DES_DENOMINACION,
		[]BOL_MECANIZADO,
		[]NUM_IMPORTE_TOTAL_BILLETES,
		[]NUM_IMPORTE_TOTAL_MONEDAS,
		[]NEL_CANTIDAD_TOTAL_BILLETES,
		[]NEL_CANTIDAD_TOTAL_MONEDAS,
		[]NEL_CANTIDAD_TOTAL_MINUTOS
	)
