SELECT
  VAL.DES_USUARIO,
  VAL.DES_DELEGACION,
  VAL.DES_SECTOR,
  VAL.DES_PRODUCTO,
  VAL.DES_CLIENTE,
  MIN.MINUTOS HORAS_TRABAJADAS,
  (SUM(VAL.NEL_CANTIDAD_TOTAL_BILLETES) + SUM(VAL.NEL_CANTIDAD_TOTAL_MONEDAS)) BILLETES_MONEDAS_PROCESADAS FROM DAPR_TVALORES_PROCESADOS VAL INNER JOIN (
  SELECT
    TRUNC(MIN2.FECHA_HORA) FECHA_HORA,
    MIN2.COD_DELEGACION,
    MIN2.COD_SECTOR,
    MIN2.COD_CLIENTE,
    MIN2.COD_PRODUCTO,
    MIN2.COD_USUARIO,
    MIN2.COD_PUESTO,
    MIN2.BOL_MECANIZADO,
    ROUND((SUM(MIN2.NEL_CANTIDAD_TOTAL_MINUTOS) / 60), 2) MINUTOS
  FROM DAPR_TMINUTOS_PROCESADOS MIN2
  {0}
  GROUP BY   
    TRUNC(MIN2.FECHA_HORA),
    MIN2.COD_DELEGACION,
    MIN2.COD_SECTOR,
    MIN2.COD_CLIENTE,
    MIN2.COD_PRODUCTO,
    MIN2.COD_USUARIO,
    MIN2.COD_PUESTO,
    MIN2.BOL_MECANIZADO
) MIN
  ON TRUNC(VAL.FECHA_HORA) = MIN.FECHA_HORA
  AND VAL.COD_DELEGACION = MIN.COD_DELEGACION
  AND VAL.COD_SECTOR = MIN.COD_SECTOR
  AND VAL.COD_CLIENTE = MIN.COD_CLIENTE
  AND VAL.COD_PRODUCTO = MIN.COD_PRODUCTO
  AND VAL.COD_USUARIO = MIN.COD_USUARIO
  AND VAL.COD_PUESTO = MIN.COD_PUESTO
  AND VAL.BOL_MECANIZADO = MIN.BOL_MECANIZADO
  {1}
GROUP BY   
  VAL.DES_USUARIO,
  VAL.DES_DELEGACION,
  VAL.DES_SECTOR,
  VAL.DES_PRODUCTO,
  VAL.DES_CLIENTE,
  MIN.MINUTOS