SELECT D.COD_ISO_DIVISA,
       D.DES_DIVISA,
       D.OID_DIVISA,
       DEN.OID_DENOMINACION,
       DEN.COD_DENOMINACION,
       DEN.DES_DENOMINACION,
	   DEN.BOL_BILLETE,
	   DEN.NUM_VALOR_FACIAL,
       SUM(EL.NEL_CANTIDAD) NEL_CANTIDAD,
       SUM(EL.NEL_IMPORTE_EFECTIVO) NEL_IMPORTE_EFECTIVO,
	   EL.OID_REMESA
FROM GEPR_TDIVISA D
INNER JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DIVISA = D.OID_DIVISA
INNER JOIN GEPR_TEFECTIVO_LEGADO EL ON EL.OID_DENOMINACION = DEN.OID_DENOMINACION
{0}
GROUP BY EL.OID_REMESA, D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA, DEN.OID_DENOMINACION,DEN.COD_DENOMINACION, DEN.DES_DENOMINACION, DEN.BOL_BILLETE, DEN.NUM_VALOR_FACIAL