SELECT D.COD_ISO_DIVISA,
       D.DES_DIVISA,
       D.OID_DIVISA,
       SUM(EB.NEL_CANTIDAD * DEN.NUM_VALOR_FACIAL) NEL_IMPORTE_EFECTIVO
FROM GEPR_TDIVISA D
INNER JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DIVISA = D.OID_DIVISA
INNER JOIN GEPR_TEFECTIVO_BULTO EB ON EB.OID_DENOMINACION = DEN.OID_DENOMINACION
WHERE {0}
GROUP BY D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA
