SELECT D.COD_ISO_DIVISA,
       D.DES_DIVISA,
       D.OID_DIVISA,
       SUM(EL.NEL_IMPORTE_EFECTIVO) NEL_IMPORTE_EFECTIVO,
	   EL.OID_REMESA
FROM GEPR_TDIVISA D
INNER JOIN GEPR_TEFECTIVO_LEGADO EL ON EL.OID_DIVISA = D.OID_DIVISA
{0}
GROUP BY EL.OID_REMESA,D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA