SELECT D.COD_ISO_DIVISA,
       D.DES_DIVISA,
       D.OID_DIVISA,
       SUM(EB.NEL_CANTIDAD * DEN.NUM_VALOR_FACIAL) NEL_IMPORTE_EFECTIVO,
	   EB.OID_BULTO
FROM GEPR_TDIVISA D
INNER JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DIVISA = D.OID_DIVISA
INNER JOIN GEPR_TEFECTIVO_BULTO EB ON EB.OID_DENOMINACION = DEN.OID_DENOMINACION
{0}
GROUP BY EB.OID_BULTO,D.COD_ISO_DIVISA, D.DES_DIVISA, D.OID_DIVISA
