INSERT INTO SAPR_TABONO_SALDO S
(S.OID_ABONO_SALDO,S.OID_ABONO_SNAPSHOT,S.OID_ABONO_VALOR,S.OID_DOCUMENTO,S.GMT_CREACION,
S.DES_USUARIO_CREACION,S.GMT_MODIFICACION,S.DES_USUARIO_MODIFICACION)
VALUES
([]OID_ABONO_SALDO,[]OID_ABONO_SNAPSHOT,[]OID_ABONO_VALOR,[]OID_DOCUMENTO,FN_GMT_ZERO_###VERSION###,
[]DES_USUARIO_CREACION,FN_GMT_ZERO_###VERSION###,[]DES_USUARIO_MODIFICACION)