SELECT  DISTINCT
-- SNAP SHOT
   AV.OID_ABONO_VALOR,
   AV.OID_BANCO,
   AV.OID_DIVISA,
   AV.COD_TIPO_CUENTA_BANCARIA,
   AV.COD_CUENTA_BANCARIA,
   AV.COD_DOCUMENTO,
   AV.DES_TITULARIDAD,
   AV.DES_OBSERVACIONES,
   AV.NUM_IMPORTE,
-- ABONO SALDO
   ASALD.OID_ABONO_SALDO,
   ASALD.OID_DOCUMENTO,
   ASALD.OID_ABONO_SNAPSHOT,
--CLIENTE_SNAP_SHOT
  CLI.OID_CLIENTE,
  CLI.COD_CLIENTE,
  CLI.DES_CLIENTE,
  --SUB_CLIENTE_SNAP_SHOT
  SUBCLI.OID_SUBCLIENTE,
  SUBCLI.COD_SUBCLIENTE,
  SUBCLI.DES_SUBCLIENTE,
  --PTO_SERVICIO_SNAP_SHOT
  PTO.OID_PTO_SERVICIO,
  PTO.COD_PTO_SERVICIO,
  PTO.DES_PTO_SERVICIO
FROM SAPR_TABONO_VALOR AV 
INNER JOIN SAPR_TABONO_SALDO ASALD ON ASALD.OID_ABONO_VALOR = AV.OID_ABONO_VALOR
INNER JOIN GEPR_TCLIENTE CLI ON CLI.OID_CLIENTE = AV.OID_CLIENTE
LEFT JOIN GEPR_TSUBCLIENTE SUBCLI ON SUBCLI.OID_SUBCLIENTE = AV.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_PTO_SERVICIO = AV.OID_PTO_SERVICIO            
WHERE AV.OID_ABONO = []OID_ABONO 