SELECT 
-- TERMINO SALDOS
   ST.OID_ABONO_SALDO,
   ST.OID_TERMINO,
   ST.DES_VALOR, 
-- TERMINO
   T.NEC_LONGITUD,
   T.BOL_VALORES_POSIBLES,
   T.BOL_ACEPTAR_DIGITACION
FROM
       SAPR_TABONO_SALDO_TERMINO ST
       INNER JOIN GEPR_TTERMINO T ON ST.OID_TERMINO = T.OID_TERMINO
WHERE
       ST.OID_ABONO_SALDO IN ({0})