SELECT
  DATB.OID_DATO_BANCARIO,
  DATB.OID_BANCO,
  BAN.COD_CLIENTE COD_BANCO,
  BAN.DES_CLIENTE DES_BANCO,
  DATB.OID_CLIENTE,
  DATB.OID_SUBCLIENTE,
  DATB.OID_PTO_SERVICIO,
  DATB.OID_DIVISA,
  DIV.DES_DIVISA,
  DIV.COD_ISO_DIVISA,
  DATB.COD_TIPO_CUENTA_BANCARIA,
  DATB.COD_CUENTA_BANCARIA,
  DATB.COD_DOCUMENTO,
  DATB.DES_TITULARIDAD,
  DATB.DES_OBSERVACIONES,
  DATB.BOL_DEFECTO
FROM SAPR_TDATO_BANCARIO DATB
  INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = DATB.OID_DIVISA
  INNER JOIN GEPR_TCLIENTE BAN ON BAN.OID_CLIENTE = DATB.OID_BANCO
WHERE DATB.BOL_ACTIVO = 1