SELECT D.OID_DOCUMENTO,
       D.OID_GRUPO_DOCUMENTO,
       TD.COD_TIPO_DOCUMENTO,
       TD.DES_TIPO_DOCUMENTO,
       D.FYH_PLAN_CERTIFICACION,
       D.COD_EXTERNO,
       D.COD_ESTADO,
	   D.OID_SECTOR_DESTINO
FROM SAPR_TDOCUMENTO D
INNER JOIN SAPR_TTIPO_DOCUMENTO TD ON TD.OID_TIPO_DOCUMENTO = D.OID_TIPO_DOCUMENTO
WHERE
D.OID_DOCUMENTO = []OID_DOCUMENTO
