UPDATE SAPR_TDOCUMENTO
SET FYH_PLAN_CERTIFICACION = []FYH_PLAN_CERTIFICACION
   ,DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
   ,GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###
WHERE OID_DOCUMENTO = []OID_DOCUMENTO