SELECT
  COUNT(1)
FROM
  SAPR_TDOCUMENTO DOCU
  INNER JOIN SAPR_TFORMULARIO FORM ON DOCU.OID_FORMULARIO = FORM.OID_FORMULARIO  
  INNER JOIN SAPR_TCARACTFORMXFORMULARIO CFF ON CFF.OID_FORMULARIO = FORM.OID_FORMULARIO
  INNER JOIN SAPR_TCARACT_FORMULARIO C ON C.OID_CARACT_FORMULARIO = CFF.OID_CARACT_FORMULARIO
  INNER JOIN SAPR_TTIPO_DOCUMENTO TDOC ON TDOC.OID_TIPO_DOCUMENTO = DOCU.OID_TIPO_DOCUMENTO  
WHERE
  DOCU.OID_DOCUMENTO = []OID_DOCUMENTO
  AND FORM.OID_FORMULARIO = []OID_FORMULARIO
  AND TDOC.COD_TIPO_DOCUMENTO = 'REGPROC'
  AND C.COD_CARACT_FORMULARIO IN ('CARACTERISTICA_PRINCIPAL_GESTION_REMESAS',
  'CARACTERISTICA_PRINCIPAL_GESTION_BULTOS',
  'ACCION_ALTAS')