UPDATE SAPR_TDOCUMENTO
SET OID_CUENTA_ORIGEN		=[]OID_CUENTA_ORIGEN
,OID_CUENTA_DESTINO		=[]OID_CUENTA_DESTINO
,OID_CUENTA_SALDO_ORIGEN	=[]OID_CUENTA_SALDO_ORIGEN
,OID_CUENTA_SALDO_DESTINO	=[]OID_CUENTA_SALDO_DESTINO
,OID_SECTOR_DESTINO			=[]OID_SECTOR_DESTINO
,FYH_PLAN_CERTIFICACION		=[]FYH_PLAN_CERTIFICACION
,FYH_GESTION				=[]FYH_GESTION
,BOL_CERTIFICADO			=[]BOL_CERTIFICADO
,COD_EXTERNO				=[]COD_EXTERNO
,COD_ESTADO					=[]COD_ESTADO
,GMT_MODIFICACION			=FN_GMT_ZERO_###VERSION###
,DES_USUARIO_MODIFICACION	=[]DES_USUARIO_MODIFICACION
,OID_DOCUMENTO_PADRE		=[]OID_DOCUMENTO_PADRE
,OID_DOCUMENTO_SUSTITUTO	=[]OID_DOCUMENTO_SUSTITUTO
WHERE OID_DOCUMENTO			=[]OID_DOCUMENTO