UPDATE SAPR_TDOCUMENTO
SET
BOL_NO_CERTIFICAR = []BOL_NO_CERTIFICAR,
GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###,
DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE
OID_DOCUMENTO = []OID_DOCUMENTO