SELECT DISTINCT
  D.OID_DOCUMENTO,
  D.OID_FORMULARIO,
  D.OID_CUENTA_ORIGEN,
  D.OID_CUENTA_DESTINO,
  D.OID_CUENTA_SALDO_ORIGEN,
  D.OID_CUENTA_SALDO_DESTINO,
  D.OID_DOCUMENTO_PADRE,
  D.OID_DOCUMENTO_SUSTITUTO,
  D.OID_TIPO_DOCUMENTO,
  D.OID_SECTOR_ORIGEN,
  D.OID_SECTOR_DESTINO,
  D.FYH_PLAN_CERTIFICACION,
  D.BOL_CERTIFICADO,
  D.COD_EXTERNO,
  D.COD_ESTADO,
  D.GMT_CREACION,
  D.DES_USUARIO_CREACION,
  D.GMT_MODIFICACION,
  D.COD_COMPROBANTE,
  D.DES_USUARIO_MODIFICACION,

   /*  CONTA BULTO    */
  
  CB.OID_CUENTA AS OID_CUENTA_BULTO,                         -- CONTA BULTO
  CB.GMT_CREACION AS GMT_CREACION_CUENTA_BULTO,              -- CONTA BULTO
  CB.GMT_MODIFICACION AS GMT_MOD_CUENTA_BULTO,               -- CONTA BULTO
  CB.DES_USUARIO_CREACION AS USU_CREACION_CUENTA_BULTO,      -- CONTA BULTO
  CB.DES_USUARIO_MODIFICACION AS USUARIO_MOD_CUENTA_BULTO,   -- CONTA BULTO
  CB.COD_TIPO_CUENTA AS COD_TIPO_CUENTA_BULTO,               -- CONTA BULTO
  
  CLB.COD_CLIENTE AS COD_CLIENTE_BULTO,                      -- CLIENTE BULTO
  CLB.DES_CLIENTE AS DES_CLIENTE_BULTO,                      -- CLIENTE BULTO
  CLB.BOL_ENVIADO_SALDOS AS CLIENTE_ENV_SALDOS_BULTO,        -- CLIENTE BULTO 
  CLB.BOL_TOTALIZADOR_SALDO AS CLIENTE_TOT_SALDOS_BULTO,     -- CLIENTE BULTO
  CLB.BOL_VIGENTE AS CLIENTE_ACTIVO_BULTO,                   -- CLIENTE BULTO
  CLB.OID_CLIENTE AS OID_CLIENTE_BULTO,                      -- CLIENTE BULTO  
  
  PTB.COD_PTO_SERVICIO AS COD_PTO_SERVICIO_BULTO,         -- PTO BULTO
  PTB.DES_PTO_SERVICIO AS DES_PTO_SERVICIO_BULTO,         -- PTO BULTO
  PTB.BOL_VIGENTE AS PTO_ACTIVO_BULTO,                    -- PTO BULTO
  PTB.BOL_ENVIADO_SALDOS AS PTO_ENV_SALDOS_BULTO,         -- PTO BULTO
  PTB.BOL_TOTALIZADOR_SALDO AS PTO_TOT_SALDOS_BULTO,      -- PTO BULTO
  PTB.OID_PTO_SERVICIO AS OID_PTO_SERVICIO_BULTO,         -- PTO BULTO
  
  SCLB.OID_SUBCLIENTE AS OID_SUBCLIENTE_BULTO,               -- SUBCLIENTE BULTO 
  SCLB.COD_SUBCLIENTE AS COD_SUBCLIENTE_BULTO,               -- SUBCLIENTE BULTO
  SCLB.DES_SUBCLIENTE AS DES_SUBCLIENTE_BULTO,               -- SUBCLIENTE BULTO
  SCLB.BOL_ENVIADO_SALDOS AS SUBCLIENTE_ENV_SALDOS_BULTO,    -- SUBCLIENTE BULTO
  SCLB.BOL_TOTALIZADOR_SALDO AS SUBCLIENTE_TOT_SALDOS_BULTO, -- SUBCLIENTE BULTO
  SCLB.BOL_VIGENTE AS SUBCLIENTE_ACTIVO_BULTO,               -- SUBCLIENTE BULTO

  CNB.OID_CANAL AS OID_CANAL_BULTO,                          -- CANAL BULTO
  CNB.COD_CANAL AS COD_CANAL_BULTO,                          -- CANAL BULTO
  CNB.COD_MIGRACION AS MIGRACION_CANAL_BULTO,                -- CANAL BULTO
  CNB.COD_USUARIO AS USUARIO_CANAL_BULTO,                    -- CANAL BULTO
  CNB.DES_CANAL AS DES_CANAL_BULTO,                          -- CANAL BULTO
  CNB.BOL_VIGENTE AS CANAL_ACTIVO_BULTO,                     -- CANAL BULTO
  CNB.FYH_ACTUALIZACION AS FYH_CANAL_BULTO,                  -- CANAL BULTO
  CNB.OBS_CANAL AS OBS_CANAL_BULTO,                          -- CANAL BULTO

  SCB.OID_SUBCANAL AS OID_SUBCANAL_BULTO,                    -- SUBCANAL BULTO
  SCB.COD_SUBCANAL AS COD_SUBCANAL_BULTO,                    -- SUBCANAL BULTO
  SCB.COD_MIGRACION AS MIGRACION_SUBCANAL_BULTO,             -- SUBCANAL BULTO
  SCB.COD_USUARIO AS USUARIO_SUBCANAL_BULTO,                 -- SUBCANAL BULTO
  SCB.DES_SUBCANAL AS DES_SUBCANAL_BULTO,                    -- SUBCANAL BULTO
  SCB.BOL_VIGENTE AS SUBCANAL_ACTIVO_BULTO,                  -- SUBCANAL BULTO
  SCB.FYH_ACTUALIZACION AS FYH_SUBCANAL_BULTO,               -- SUBCANAL BULTO
  SCB.OBS_SUBCANAL AS OBS_SUBCANAL_BULTO,                    -- SUBCANAL BULTO

  SB.OID_SECTOR AS OID_SECTOR_BULTO,                         -- SECTOR BULTO
  SB.COD_SECTOR AS COD_SECTOR_BULTO,                         -- SECTOR BULTO
  SB.COD_MIGRACION AS MIGRACION_SECTOR_BULTO,                -- SECTOR BULTO
  SB.DES_SECTOR AS DES_SECTOR_BULTO,                         -- SECTOR BULTO
  SB.BOL_ACTIVO AS SECTOR_ACTIVO_BULTO,                      -- SECTOR BULTO
  SB.BOL_CENTRO_PROCESO AS BOL_CENTRO_PROCESO_BULTO,         -- SECTOR BULTO
  SB.BOL_CONTEO AS BOL_CONTEO_BULTO,                         -- SECTOR BULTO
  SB.BOL_TESORO AS BOL_TESORO_BULTO,                         -- SECTOR BULTO
  SB.GMT_CREACION AS GMT_CREACION_SECTOR_BULTO,              -- SECTOR BULTO
  SB.GMT_MODIFICACION AS GMT_MOD_SECTOR_BULTO,               -- SECTOR BULTO
  SB.BOL_PERMITE_DISPONER_VALOR AS BOL_PERMITE_DISP_VAL_BULTO,-- SECTOR BULTO
  
  DELB.OID_DELEGACION AS OID_DELEGACION_BULTO,                -- DELEGACION BULTO
  DELB.COD_DELEGACION AS COD_DELEGACION_BULTO,                -- DELEGACION BULTO
  DELB.DES_DELEGACION AS DES_DELEGACION_BULTO,                -- DELEGACION BULTO
  DELB.BOL_VIGENTE AS DELEGACION_ACTIVA_BULTO,                -- DELEGACION BULTO
  
  PB.OID_PLANTA AS OID_PLANTA_BULTO,                    -- PLANTA BULTO
  PB.COD_PLANTA AS COD_PLANTA_BULTO,                    -- PLANTA BULTO
  PB.DES_PLANTA AS DES_PLANTA_BULTO,                    -- PLANTA BULTO
  PB.BOL_ACTIVO AS PLANTA_ACTIVA_BULTO,                 -- PLANTA BULTO

  /*  CONTA REMESA    */
  
  CR.OID_CUENTA AS OID_CUENTA_REMESA,                         -- CONTA REMESA
  CR.GMT_CREACION AS GMT_CREACION_CUENTA_REMESA,              -- CONTA REMESA
  CR.GMT_MODIFICACION AS GMT_MOD_CUENTA_REMESA,               -- CONTA REMESA
  CR.DES_USUARIO_CREACION AS USU_CREACION_CUENTA_REMESA,      -- CONTA REMESA
  CR.DES_USUARIO_MODIFICACION AS USUARIO_MOD_CUENTA_REMESA,   -- CONTA REMESA
  CR.COD_TIPO_CUENTA AS COD_TIPO_CUENTA_REMESA,               -- CONTA REMESA
  
  CLR.COD_CLIENTE AS COD_CLIENTE_REMESA,                      -- CLIENTE REMESA
  CLR.DES_CLIENTE AS DES_CLIENTE_REMESA,                      -- CLIENTE REMESA
  CLR.BOL_ENVIADO_SALDOS AS CLIENTE_ENV_SALDOS_REMESA,        -- CLIENTE REMESA 
  CLR.BOL_TOTALIZADOR_SALDO AS CLIENTE_TOT_SALDOS_REMESA,     -- CLIENTE REMESA
  CLR.BOL_VIGENTE AS CLIENTE_ACTIVO_REMESA,                   -- CLIENTE REMESA
  CLR.OID_CLIENTE AS OID_CLIENTE_REMESA,                      -- CLIENTE REMESA  
  
  PTR.COD_PTO_SERVICIO AS COD_PTO_SERVICIO_REMESA,         -- PTO REMESA
  PTR.DES_PTO_SERVICIO AS DES_PTO_SERVICIO_REMESA,         -- PTO REMESA
  PTR.BOL_VIGENTE AS PTO_ACTIVO_REMESA,                    -- PTO REMESA
  PTR.BOL_ENVIADO_SALDOS AS PTO_ENV_SALDOS_REMESA,         -- PTO REMESA
  PTR.BOL_TOTALIZADOR_SALDO AS PTO_TOT_SALDOS_REMESA,      -- PTO REMESA
  PTR.OID_PTO_SERVICIO AS OID_PTO_SERVICIO_REMESA,         -- PTO REMESA
  
  SCLR.OID_SUBCLIENTE AS OID_SUBCLIENTE_REMESA,               -- SUBCLIENTE REMESA 
  SCLR.COD_SUBCLIENTE AS COD_SUBCLIENTE_REMESA,               -- SUBCLIENTE REMESA
  SCLR.DES_SUBCLIENTE AS DES_SUBCLIENTE_REMESA,               -- SUBCLIENTE REMESA
  SCLR.BOL_ENVIADO_SALDOS AS SUBCLIENTE_ENV_SALDOS_REMESA,    -- SUBCLIENTE REMESA
  SCLR.BOL_TOTALIZADOR_SALDO AS SUBCLIENTE_TOT_SALDOS_REMESA, -- SUBCLIENTE REMESA
  SCLR.BOL_VIGENTE AS SUBCLIENTE_ACTIVO_REMESA,               -- SUBCLIENTE REMESA

  CNR.OID_CANAL AS OID_CANAL_REMESA,                          -- CANAL REMESA
  CNR.COD_CANAL AS COD_CANAL_REMESA,                          -- CANAL REMESA
  CNR.COD_MIGRACION AS MIGRACION_CANAL_REMESA,                -- CANAL REMESA
  CNR.COD_USUARIO AS USUARIO_CANAL_REMESA,                    -- CANAL REMESA
  CNR.DES_CANAL AS DES_CANAL_REMESA,                          -- CANAL REMESA
  CNR.BOL_VIGENTE AS CANAL_ACTIVO_REMESA,                     -- CANAL REMESA
  CNR.FYH_ACTUALIZACION AS FYH_CANAL_REMESA,                  -- CANAL REMESA
  CNR.OBS_CANAL AS OBS_CANAL_REMESA,                          -- CANAL REMESA

  SCR.OID_SUBCANAL AS OID_SUBCANAL_REMESA,                    -- SUBCANAL REMESA
  SCR.COD_SUBCANAL AS COD_SUBCANAL_REMESA,                    -- SUBCANAL REMESA
  SCR.COD_MIGRACION AS MIGRACION_SUBCANAL_REMESA,             -- SUBCANAL REMESA
  SCR.COD_USUARIO AS USUARIO_SUBCANAL_REMESA,                 -- SUBCANAL REMESA
  SCR.DES_SUBCANAL AS DES_SUBCANAL_REMESA,                    -- SUBCANAL REMESA
  SCR.BOL_VIGENTE AS SUBCANAL_ACTIVO_REMESA,                  -- SUBCANAL REMESA
  SCR.FYH_ACTUALIZACION AS FYH_SUBCANAL_REMESA,               -- SUBCANAL REMESA
  SCR.OBS_SUBCANAL AS OBS_SUBCANAL_REMESA,                    -- SUBCANAL REMESA

  SR.OID_SECTOR AS OID_SECTOR_REMESA,                         -- SECTOR REMESA
  SR.COD_SECTOR AS COD_SECTOR_REMESA,                         -- SECTOR REMESA
  SR.COD_MIGRACION AS MIGRACION_SECTOR_REMESA,                -- SECTOR REMESA
  SR.DES_SECTOR AS DES_SECTOR_REMESA,                         -- SECTOR REMESA
  SR.BOL_ACTIVO AS SECTOR_ACTIVO_REMESA,                      -- SECTOR REMESA
  SR.BOL_CENTRO_PROCESO AS BOL_CENTRO_PROCESO_REMESA,         -- SECTOR REMESA
  SR.BOL_CONTEO AS BOL_CONTEO_REMESA,                         -- SECTOR REMESA
  SR.BOL_TESORO AS BOL_TESORO_REMESA,                         -- SECTOR REMESA
  SR.GMT_CREACION AS GMT_CREACION_SECTOR_REMESA,              -- SECTOR REMESA
  SR.GMT_MODIFICACION AS GMT_MOD_SECTOR_REMESA,               -- SECTOR REMESA
  SR.BOL_PERMITE_DISPONER_VALOR AS BOL_PERMITE_DISP_VAL_REMESA,-- SECTOR REMESA
  
  DELR.OID_DELEGACION AS OID_DELEGACION_REMESA,                -- DELEGACION REMESA
  DELR.COD_DELEGACION AS COD_DELEGACION_REMESA,                -- DELEGACION REMESA
  DELR.DES_DELEGACION AS DES_DELEGACION_REMESA,                -- DELEGACION REMESA
  DELR.BOL_VIGENTE AS DELEGACION_ACTIVA_REMESA,                -- DELEGACION REMESA
  
  PR.OID_PLANTA AS OID_PLANTA_REMESA,                    -- PLANTA REMESA
  PR.COD_PLANTA AS COD_PLANTA_REMESA,                    -- PLANTA REMESA
  PR.DES_PLANTA AS DES_PLANTA_REMESA,                    -- PLANTA REMESA
  PR.BOL_ACTIVO AS PLANTA_ACTIVA_REMESA,                  -- PLANTA REMESA

  /*  CONTA ORIGEM    */
  
  D.OID_CUENTA_ORIGEN,                                 -- CONTA ORIGEM
  CO.GMT_CREACION AS GMT_CREACION_CUENTA,              -- CONTA ORIGEM
  CO.GMT_MODIFICACION AS GMT_MOD_CUENTA,               -- CONTA ORIGEM
  CO.DES_USUARIO_CREACION AS USUARIO_CREACION_CUENTA,  -- CONTA ORIGEM
  CO.DES_USUARIO_MODIFICACION AS USUARIO_MOD_CUENTA,   -- CONTA ORIGEM
  CO.COD_TIPO_CUENTA,                                  -- CONTA ORIGEM
  
  CLO.COD_CLIENTE,                                  -- CLIENTE ORIGEM
  CLO.DES_CLIENTE,                                  -- CLIENTE ORIGEM
  CLO.BOL_ENVIADO_SALDOS AS CLIENTE_ENV_SALDOS,     -- CLIENTE ORIGEM 
  CLO.BOL_TOTALIZADOR_SALDO AS CLIENTE_TOT_SALDOS,	-- CLIENTE ORIGEM
  CLO.BOL_VIGENTE AS CLIENTE_ACTIVO,                -- CLIENTE ORIGEM
  CLO.OID_CLIENTE,                                  -- CLIENTE ORIGEM  
  
  PTO.COD_PTO_SERVICIO,                             -- PTO ORIGEM
  PTO.DES_PTO_SERVICIO,                             -- PTO ORIGEM
  PTO.BOL_VIGENTE AS PTO_ACTIVO,                    -- PTO ORIGEM
  PTO.BOL_ENVIADO_SALDOS AS PTO_ENV_SALDOS,         -- PTO ORIGEM
  PTO.BOL_TOTALIZADOR_SALDO AS PTO_TOT_SALDOS,      -- PTO ORIGEM
  PTO.OID_PTO_SERVICIO,                             -- PTO ORIGEM
  
  SCLD.OID_SUBCLIENTE,								-- SUBCLIENTE ORIGEM 
  SCLO.COD_SUBCLIENTE,                                -- SUBCLIENTE ORIGEM
  SCLO.DES_SUBCLIENTE,                                -- SUBCLIENTE ORIGEM
  SCLO.BOL_ENVIADO_SALDOS AS SUBCLIENTE_ENV_SALDOS,   -- SUBCLIENTE ORIGEM
  SCLO.BOL_TOTALIZADOR_SALDO AS SUBCLIENTE_TOT_SALDOS, -- SUBCLIENTE ORIGEM
  SCLO.BOL_VIGENTE AS SUBCLIENTE_ACTIVO,               -- SUBCLIENTE ORIGEM

  CNO.OID_CANAL,                                       -- CANAL ORIGEM
  CNO.COD_CANAL,                                       -- CANAL ORIGEM
  CNO.COD_MIGRACION AS MIGRACION_CANAL,                -- CANAL ORIGEM
  CNO.COD_USUARIO AS USUARIO_CANAL,                    -- CANAL ORIGEM
  CNO.DES_CANAL,                                       -- CANAL ORIGEM
  CNO.BOL_VIGENTE AS CANAL_ACTIVO,                     -- CANAL ORIGEM
  CNO.FYH_ACTUALIZACION AS FYH_CANAL,                  -- CANAL ORIGEM
  CNO.OBS_CANAL,                                       -- CANAL ORIGEM

  SCO.OID_SUBCANAL,                                    -- SUBCANAL ORIGEM
  SCO.COD_SUBCANAL,                                    -- SUBCANAL ORIGEM
  SCO.COD_MIGRACION AS MIGRACION_SUBCANAL,             -- SUBCANAL ORIGEM
  SCO.COD_USUARIO AS USUARIO_SUBCANAL,                 -- SUBCANAL ORIGEM
  SCO.DES_SUBCANAL,                                    -- SUBCANAL ORIGEM
  SCO.BOL_VIGENTE AS SUBCANAL_ACTIVO,                  -- SUBCANAL ORIGEM
  SCO.FYH_ACTUALIZACION AS FYH_SUBCANAL,               -- SUBCANAL ORIGEM
  SCO.OBS_SUBCANAL,                                    -- SUBCANAL ORIGEM

  SO.OID_SECTOR,                                       -- SECTOR ORIGEM
  SO.COD_SECTOR,                                       -- SECTOR ORIGEM
  SO.COD_MIGRACION AS MIGRACION_SECTOR,                -- SECTOR ORIGEM
  SO.DES_SECTOR,                                       -- SECTOR ORIGEM
  SO.BOL_ACTIVO AS SECTOR_ACTIVO,                      -- SECTOR ORIGEM
  SO.BOL_CENTRO_PROCESO,                               -- SECTOR ORIGEM
  SO.BOL_CONTEO,                                       -- SECTOR ORIGEM
  SO.BOL_TESORO,                                       -- SECTOR ORIGEM
  SO.GMT_CREACION AS GMT_CREACION_SECTOR,              -- SECTOR ORIGEM
  SO.GMT_MODIFICACION AS GMT_MOD_SECTOR,               -- SECTOR ORIGEM
  SO.BOL_PERMITE_DISPONER_VALOR,                       -- SECTOR ORIGEM
  
  DEL.OID_DELEGACION,                                  -- DELEGACION ORIGEM
  DEL.COD_DELEGACION,                                  -- DELEGACION ORIGEM
  DEL.DES_DELEGACION,                                  -- DELEGACION ORIGEM
  DEL.BOL_VIGENTE AS DELEGACION_ACTIVA,                -- DELEGACION ORIGEM
  
  P.OID_PLANTA,                                        -- PLANTA ORIGEM
  P.COD_PLANTA,                                        -- PLANTA ORIGEM
  P.DES_PLANTA,                                        -- PLANTA ORIGEM
  P.BOL_ACTIVO AS PLANTA_ACTIVA,                       -- PLANTA ORIGEM
  
/*  CONTA DESTINO    */
  
  D.OID_CUENTA_DESTINO,                                        -- CONTA DESTINO
  CD.GMT_CREACION AS GMT_CREACION_CUENTA_DESTINO,              -- CONTA DESTINO
  CD.GMT_MODIFICACION AS GMT_MOD_CUENTA_DESTINO,               -- CONTA DESTINO
  CD.DES_USUARIO_CREACION AS USU_CREACION_CUENTA_DESTINO,      -- CONTA DESTINO
  CD.DES_USUARIO_MODIFICACION AS USUARIO_MOD_CUENTA_DESTINO,   -- CONTA DESTINO
  CD.COD_TIPO_CUENTA AS COD_TIPO_CUENTA_DESTINO,               -- CONTA DESTINO

  
  CLD.COD_CLIENTE AS COD_CLIENTE_DESTINO,                      -- CLIENTE DESTINO
  CLD.DES_CLIENTE AS DES_CLIENTE_DESTINO,                      -- CLIENTE DESTINO
  CLD.BOL_ENVIADO_SALDOS AS CLIENTE_ENV_SALDOS_DESTINO,        -- CLIENTE DESTINO 
  CLD.BOL_TOTALIZADOR_SALDO AS CLIENTE_TOT_SALDOS_DESTINO,     -- CLIENTE DESTINO
  CLD.BOL_VIGENTE AS CLIENTE_ACTIVO_DESTINO,                   -- CLIENTE DESTINO
  CLD.OID_CLIENTE AS OID_CLIENTE_DESTINO,                      -- CLIENTE DESTINO  
  
  PTD.COD_PTO_SERVICIO AS COD_PTO_SERVICIO_DESTINO,         -- PTO DESTINO
  PTD.DES_PTO_SERVICIO AS DES_PTO_SERVICIO_DESTINO,         -- PTO DESTINO
  PTD.BOL_VIGENTE AS PTO_ACTIVO_DESTINO,                    -- PTO DESTINO
  PTD.BOL_ENVIADO_SALDOS AS PTO_ENV_SALDOS_DESTINO,         -- PTO DESTINO
  PTD.BOL_TOTALIZADOR_SALDO AS PTO_TOT_SALDOS_DESTINO,      -- PTO DESTINO
  PTD.OID_PTO_SERVICIO AS OID_PTO_SERVICIO_DESTINO,         -- PTO DESTINO
 
  SCLD.OID_SUBCLIENTE AS OID_SUBCLIENTE_DESTINO,               -- SUBCLIENTE DESTINO 
  SCLD.COD_SUBCLIENTE AS COD_SUBCLIENTE_DESTINO,               -- SUBCLIENTE DESTINO
  SCLD.DES_SUBCLIENTE AS DES_SUBCLIENTE_DESTINO,               -- SUBCLIENTE DESTINO
  SCLD.BOL_ENVIADO_SALDOS AS SUBCLIENTE_ENV_SALDOS_DESTINO,    -- SUBCLIENTE DESTINO
  SCLD.BOL_TOTALIZADOR_SALDO AS SUBCLIENTE_TOT_SALDOS_DESTINO, -- SUBCLIENTE DESTINO
  SCLD.BOL_VIGENTE AS SUBCLIENTE_ACTIVO_DESTINO,               -- SUBCLIENTE DESTINO

  CND.OID_CANAL AS OID_CANAL_DESTINO,                          -- CANAL DESTINO
  CND.COD_CANAL AS COD_CANAL_DESTINO,                          -- CANAL DESTINO
  CND.COD_MIGRACION AS MIGRACION_CANAL_DESTINO,                -- CANAL DESTINO
  CND.COD_USUARIO AS USUARIO_CANAL_DESTINO,                    -- CANAL DESTINO
  CND.DES_CANAL AS DES_CANAL_DESTINO,                          -- CANAL DESTINO
  CND.BOL_VIGENTE AS CANAL_ACTIVO_DESTINO,                     -- CANAL DESTINO
  CND.FYH_ACTUALIZACION AS FYH_CANAL_DESTINO,                  -- CANAL DESTINO
  CND.OBS_CANAL AS OBS_CANAL_DESTINO,                          -- CANAL DESTINO

  SCD.OID_SUBCANAL AS OID_SUBCANAL_DESTINO,                    -- SUBCANAL DESTINO
  SCD.COD_SUBCANAL AS COD_SUBCANAL_DESTINO,                    -- SUBCANAL DESTINO
  SCD.COD_MIGRACION AS MIGRACION_SUBCANAL_DESTINO,             -- SUBCANAL DESTINO
  SCD.COD_USUARIO AS USUARIO_SUBCANAL_DESTINO,                 -- SUBCANAL DESTINO
  SCD.DES_SUBCANAL AS DES_SUBCANAL_DESTINO,                    -- SUBCANAL DESTINO
  SCD.BOL_VIGENTE AS SUBCANAL_ACTIVO_DESTINO,                  -- SUBCANAL DESTINO
  SCD.FYH_ACTUALIZACION AS FYH_SUBCANAL_DESTINO,               -- SUBCANAL DESTINO
  SCD.OBS_SUBCANAL AS OBS_SUBCANAL_DESTINO,                    -- SUBCANAL DESTINO

  SD.OID_SECTOR AS OID_SECTOR_DESTINO,                         -- SECTOR DESTINO
  SD.COD_SECTOR AS COD_SECTOR_DESTINO,                         -- SECTOR DESTINO
  SD.COD_MIGRACION AS MIGRACION_SECTOR_DESTINO,                -- SECTOR DESTINO
  SD.DES_SECTOR AS DES_SECTOR_DESTINO,                         -- SECTOR DESTINO
  SD.BOL_ACTIVO AS SECTOR_ACTIVO_DESTINO,                      -- SECTOR DESTINO
  SD.BOL_CENTRO_PROCESO AS BOL_CENTRO_PROCESO_DESTINO,         -- SECTOR DESTINO
  SD.BOL_CONTEO AS BOL_CONTEO_DESTINO,                         -- SECTOR DESTINO
  SD.BOL_TESORO AS BOL_TESORO_DESTINO,                         -- SECTOR DESTINO
  SD.GMT_CREACION AS GMT_CREACION_SECTOR_DESTINO,              -- SECTOR DESTINO
  SD.GMT_MODIFICACION AS GMT_MOD_SECTOR_DESTINO,               -- SECTOR DESTINO
  SD.BOL_PERMITE_DISPONER_VALOR AS BOL_PERMITE_DISP_VAL_DESTINO,-- SECTOR DESTINO
  
  DELD.OID_DELEGACION AS OID_DELEGACION_DESTINO,                -- DELEGACION DESTINO
  DELD.COD_DELEGACION AS COD_DELEGACION_DESTINO,                -- DELEGACION DESTINO
  DELD.DES_DELEGACION AS DES_DELEGACION_DESTINO,                -- DELEGACION DESTINO
  DELD.BOL_VIGENTE AS DELEGACION_ACTIVA_DESTINO,                -- DELEGACION DESTINO
  
  PD.OID_PLANTA AS OID_PLANTA_DESTINO,                    -- PLANTA DESTINO
  PD.COD_PLANTA AS COD_PLANTA_DESTINO,                    -- PLANTA DESTINO
  PD.DES_PLANTA AS DES_PLANTA_DESTINO,                    -- PLANTA DESTINO
  PD.BOL_ACTIVO AS PLANTA_ACTIVA_DESTINO,                 -- PLANTA DESTINO

    /*  REMESA */

  R.OID_REMESA,
  R.OID_EXTERNO OID_EXTERNO_REMESA,
  R.COD_ESTADO COD_ESTADO_REMESA,
  R.GMT_CREACION, 
  R.GMT_MODIFICACION,       
  R.COD_PUESTO_RESPONSABLE,
  R.DES_USUARIO_CREACION,
  R.DES_USUARIO_MODIFICACION,
  R.COD_USUARIO_RESPONSABLE,
  R.OID_IAC,
  R.COD_RUTA,
  R.NEL_PARADA,
  R.COD_RECIBO_SALIDA,
  R.OID_REMESA_ORIGEN,
  R.OID_CUENTA,
  R.COD_EXTERNO,
  R.FYH_TRANSPORTE,

  /*  BULTO */
  
  B.OID_BULTO,
  B.OID_EXTERNO OID_EXTERNO_BULTO,
  B.COD_PRECINTO,
  B.NEL_CANTIDAD_PARCIALES

FROM 
  SAPR_TDOCUMENTO D
  
  INNER JOIN SAPR_TVALOR_TERMINOXDOCUMENTO TD ON TD.OID_DOCUMENTO = D.OID_DOCUMENTO
  INNER JOIN GEPR_TTERMINO T ON T.OID_TERMINO = TD.OID_TERMINO 
                              AND T.COD_TERMINO = 'codigoServicio' 
                              AND TD.DES_VALOR = []COD_SERVICIO

  
  INNER JOIN SAPR_TDOCUMENTOXELEMENTO DE ON D.OID_DOCUMENTO = DE.OID_DOCUMENTO
  INNER JOIN SAPR_TREMESA R ON DE.OID_REMESA = R.OID_REMESA
  LEFT JOIN SAPR_TBULTO B ON R.OID_REMESA = B.OID_REMESA
  LEFT JOIN SAPR_TVALOR_TERMINOXDOCUMENTO TDL ON TDL.OID_DOCUMENTO = D.OID_DOCUMENTO
  INNER JOIN GEPR_TTERMINO TL ON TDL.OID_TERMINO = TL.OID_TERMINO 

  INNER JOIN SAPR_TCUENTA CB ON CB.OID_CUENTA = B.OID_CUENTA -- CONTA REMESA
  INNER JOIN GEPR_TCLIENTE CLB ON CLB.OID_CLIENTE = CB.OID_CLIENTE -- CLIENTE REMESA
  LEFT JOIN GEPR_TSUBCLIENTE SCLB ON SCLB.OID_SUBCLIENTE = CB.OID_SUBCLIENTE -- SUBCLIENTE REMESA
  INNER JOIN GEPR_TSUBCANAL SCB ON SCB.OID_SUBCANAL = CB.OID_SUBCANAL -- SUBCANAL REMESA
  INNER JOIN GEPR_TCANAL CNB ON CNB.OID_CANAL = SCB.OID_CANAL         -- CANAL REMESA
  INNER JOIN GEPR_TSECTOR SB ON SB.OID_SECTOR = CB.OID_SECTOR -- SETOR REMESA
  LEFT JOIN GEPR_TPUNTO_SERVICIO PTB ON PTB.OID_PTO_SERVICIO = CB.OID_PTO_SERVICIO -- PTO REMESA
  INNER JOIN GEPR_TPLANTA PB ON PB.OID_PLANTA = SB.OID_PLANTA -- PLANTA REMESA
  INNER JOIN GEPR_TDELEGACION DELB ON DELB.OID_DELEGACION = PB.OID_DELEGACION -- DELEGACION REMESA

  INNER JOIN SAPR_TCUENTA CR ON CR.OID_CUENTA = R.OID_CUENTA -- CONTA REMESA
  INNER JOIN GEPR_TCLIENTE CLR ON CLR.OID_CLIENTE = CR.OID_CLIENTE -- CLIENTE REMESA
  LEFT JOIN GEPR_TSUBCLIENTE SCLR ON SCLR.OID_SUBCLIENTE = CR.OID_SUBCLIENTE -- SUBCLIENTE REMESA
  INNER JOIN GEPR_TSUBCANAL SCR ON SCR.OID_SUBCANAL = CR.OID_SUBCANAL -- SUBCANAL REMESA
  INNER JOIN GEPR_TCANAL CNR ON CNR.OID_CANAL = SCR.OID_CANAL         -- CANAL REMESA
  INNER JOIN GEPR_TSECTOR SR ON SR.OID_SECTOR = CR.OID_SECTOR -- SETOR REMESA
  LEFT JOIN GEPR_TPUNTO_SERVICIO PTR ON PTR.OID_PTO_SERVICIO = CR.OID_PTO_SERVICIO -- PTO REMESA
  INNER JOIN GEPR_TPLANTA PR ON PR.OID_PLANTA = SR.OID_PLANTA -- PLANTA REMESA
  INNER JOIN GEPR_TDELEGACION DELR ON DELR.OID_DELEGACION = PR.OID_DELEGACION -- DELEGACION REMESA
  
  INNER JOIN SAPR_TCUENTA CO ON CO.OID_CUENTA = D.OID_CUENTA_ORIGEN -- CONTA ORIGEM
  INNER JOIN GEPR_TCLIENTE CLO ON CLO.OID_CLIENTE = CO.OID_CLIENTE -- CLIENTE ORIGEM
  LEFT JOIN GEPR_TSUBCLIENTE SCLO ON SCLO.OID_SUBCLIENTE = CO.OID_SUBCLIENTE -- SUBCLIENTE ORIGEM
  INNER JOIN GEPR_TSUBCANAL SCO ON SCO.OID_SUBCANAL = CO.OID_SUBCANAL -- SUBCANAL ORIGEM
  INNER JOIN GEPR_TCANAL CNO ON CNO.OID_CANAL = SCO.OID_CANAL         -- CANAL ORIGEM
  INNER JOIN GEPR_TSECTOR SO ON SO.OID_SECTOR = D.OID_SECTOR_ORIGEN -- SETOR ORIGEM
  LEFT JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_PTO_SERVICIO = CO.OID_PTO_SERVICIO -- PTO ORIGEM
  INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = SO.OID_PLANTA -- PLANTA ORIGEM
  INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = P.OID_DELEGACION -- DELEGACION ORIGEM

  INNER JOIN SAPR_TCUENTA CD ON CD.OID_CUENTA = D.OID_CUENTA_ORIGEN -- CONTA DESTINO
  INNER JOIN GEPR_TCLIENTE CLD ON CLD.OID_CLIENTE = CD.OID_CLIENTE -- CLIENTE DESTINO
  LEFT JOIN GEPR_TSUBCLIENTE SCLD ON SCLD.OID_SUBCLIENTE = CO.OID_SUBCLIENTE -- SUBCLIENTE DESTINO
  INNER JOIN GEPR_TSUBCANAL SCD ON SCD.OID_SUBCANAL = CD.OID_SUBCANAL -- SUBCANAL DESTINO
  INNER JOIN GEPR_TCANAL CND ON CND.OID_CANAL = SCD.OID_CANAL         -- CANAL DESTINO
  INNER JOIN GEPR_TSECTOR SD ON SD.OID_SECTOR = D.OID_SECTOR_ORIGEN -- SETOR DESTINO
  LEFT JOIN GEPR_TPUNTO_SERVICIO PTD ON PTD.OID_PTO_SERVICIO = CD.OID_PTO_SERVICIO -- PTO DESTINO
  INNER JOIN GEPR_TPLANTA PD ON PD.OID_PLANTA = SD.OID_PLANTA -- PLANTA DESTINO
  INNER JOIN GEPR_TDELEGACION DELD ON DELD.OID_DELEGACION = PD.OID_DELEGACION -- DELEGACION DESTINO
    
WHERE
  D.COD_ESTADO <> []COD_ESTADO AND	
  T.COD_TERMINO = []COD_TERMINO AND TD.DES_VALOR = []COD_SERVICIO AND 
  R.NEL_PARADA IS NULL AND R.COD_RUTA IS NULL AND 
  R.OID_REMESA NOT IN (SELECT R.OID_REMESA
                      FROM SAPR_TDOCUMENTO D  
                        INNER JOIN SAPR_TFORMULARIO F ON F.OID_FORMULARIO = D.OID_FORMULARIO
                        INNER JOIN SAPR_TDOCUMENTOXELEMENTO DE ON D.OID_DOCUMENTO = DE.OID_DOCUMENTO
                        INNER JOIN SAPR_TREMESA R ON DE.OID_REMESA = R.OID_REMESA
                      WHERE F.COD_FORMULARIO = []COD_FORMULARIO)
   AND CLR.COD_CLIENTE = []COD_CLIENTE
   AND (SCLR.COD_SUBCLIENTE = []COD_SUBCLIENTE OR SCLR.COD_SUBCLIENTE IS NULL )
   AND (PTR.COD_PTO_SERVICIO = []COD_PTO_SERVICIO OR PTR.COD_PTO_SERVICIO IS NULL) AND
  D.GMT_MODIFICACION = (SELECT MAX(D1.GMT_MODIFICACION) FROM SAPR_TDOCUMENTO D1 WHERE D1.COD_EXTERNO = D.COD_EXTERNO)  
   
ORDER BY
  D.GMT_MODIFICACION DESC, D.COD_EXTERNO  