/*DocumentosRecuperarPorRuta.sql*/
WITH DOCUMENTOS AS
      (SELECT
   D.OID_DOCUMENTO
  ,D.OID_FORMULARIO
  ,D.OID_CUENTA_ORIGEN
  ,D.OID_CUENTA_DESTINO
  ,D.OID_CUENTA_SALDO_ORIGEN
  ,D.OID_CUENTA_SALDO_DESTINO
  ,D.OID_DOCUMENTO_PADRE
  ,D.OID_DOCUMENTO_SUSTITUTO
  ,D.OID_TIPO_DOCUMENTO
  ,D.OID_SECTOR_ORIGEN
  ,D.OID_SECTOR_DESTINO
  ,D.OID_MOVIMENTACION_FONDO
  ,D.OID_GRUPO_DOCUMENTO
  ,D.DES_USUARIO_CREACION
  ,D.DES_USUARIO_MODIFICACION
  ,DE.OID_REMESA
  ,FN_GMT_DELEGACION_###VERSION###(P.OID_DELEGACION, D.FYH_PLAN_CERTIFICACION) AS FYH_PLAN_CERTIFICACION
  ,FN_GMT_DELEGACION_###VERSION###(P.OID_DELEGACION, D.FYH_GESTION) AS FYH_GESTION
  ,D.BOL_CERTIFICADO
  ,D.COD_EXTERNO
  ,D.COD_ESTADO
  ,D.COD_COMPROBANTE
  ,D.GMT_MODIFICACION
  ,DEL.OID_DELEGACION
  ,D.ROWVER
FROM 
  SAPR_TDOCUMENTO D
  INNER JOIN SAPR_TFORMULARIO F ON F.OID_FORMULARIO = D.OID_FORMULARIO
  INNER JOIN SAPR_TDOCUMENTOXELEMENTO DE ON D.OID_DOCUMENTO = DE.OID_DOCUMENTO
  INNER JOIN SAPR_TREMESA R ON DE.OID_REMESA = R.OID_REMESA
  INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = D.OID_SECTOR_DESTINO
  INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
  INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = P.OID_DELEGACION
   WHERE 1 = 1
     AND DE.COD_ESTADO_DOCXELEMENTO = []COD_ESTADO_DOCXELEMENTO
     AND R.BOL_ANULADO = 0
     AND D.COD_ESTADO <> []COD_ESTADO
     AND R.COD_RUTA = []COD_RUTA
     AND R.FYH_TRANSPORTE >= TO_DATE([]FYH_RUTA, 'dd/mm/yyyy') 
     AND R.FYH_TRANSPORTE < (TO_DATE([]FYH_RUTA, 'dd/mm/yyyy') + 1)
     AND DEL.COD_DELEGACION = []COD_DELEGACION),
   HISTORICO AS
      (SELECT DISTINCT D.OID_DOCUMENTO AS OID_DOCUMENTO_FILTRO,DOCE.OID_DOCUMENTO AS OID_DOC_HISTORICO, REME.COD_EXTERNO
       FROM DOCUMENTOS D INNER JOIN SAPR_TBULTO BULT ON BULT.OID_DOCUMENTO = D.OID_DOCUMENTO
                   INNER JOIN SAPR_TREMESA REME ON REME.OID_REMESA = BULT.OID_REMESA
                   INNER JOIN SAPR_TDOCUMENTOXELEMENTO DOCE ON DOCE.OID_REMESA = REME.OID_REMESA),
    SOL AS
      (SELECT H.OID_DOCUMENTO_FILTRO, OID_DOC_HISTORICO,H.COD_EXTERNO 
         FROM HISTORICO H INNER JOIN GEPR_TINTEGRACION I ON I.OID_TABLA_INTEGRACION = H.OID_DOC_HISTORICO
          AND I.COD_TABLA_INTEGRACION = 'SAPR_TDOCUMENTO'
          AND I.COD_ESTADO IN ('EV', 'OK')
          AND I.COD_MODULO_ORIGEN = 'GenesisRecepcionEnvio'
          AND I.COD_MODULO_DESTINO = 'SOL'
          AND I.COD_PROCESO = 'GRABARDOCUMENTO')
SELECT
   D.OID_DOCUMENTO
  ,D.OID_FORMULARIO
  ,D.OID_CUENTA_ORIGEN
  ,D.OID_CUENTA_DESTINO
  ,D.OID_CUENTA_SALDO_ORIGEN
  ,D.OID_CUENTA_SALDO_DESTINO
  ,D.OID_DOCUMENTO_PADRE
  ,D.OID_DOCUMENTO_SUSTITUTO
  ,D.OID_TIPO_DOCUMENTO
  ,D.OID_SECTOR_ORIGEN
  ,D.OID_SECTOR_DESTINO
  ,D.OID_MOVIMENTACION_FONDO
  ,D.OID_GRUPO_DOCUMENTO
  ,D.DES_USUARIO_CREACION
  ,D.DES_USUARIO_MODIFICACION
  ,D.OID_REMESA
  ,FN_GMT_DELEGACION_###VERSION###(D.OID_DELEGACION, D.FYH_PLAN_CERTIFICACION) AS FYH_PLAN_CERTIFICACION
  ,FN_GMT_DELEGACION_###VERSION###(D.OID_DELEGACION, D.FYH_GESTION) AS FYH_GESTION
  ,D.BOL_CERTIFICADO
  ,D.COD_EXTERNO
  ,D.COD_ESTADO
  ,D.COD_COMPROBANTE
  ,D.GMT_MODIFICACION
  ,NVL((SELECT MAX(1) FROM SOL WHERE SOL.COD_EXTERNO = D.COD_EXTERNO), 0) AS EXPORTADO_SOL
  ,D.ROWVER
FROM 
  DOCUMENTOS D
ORDER BY D.GMT_MODIFICACION DESC, D.COD_EXTERNO
