SELECT * FROM (
  SELECT 
  'INDIVIDUAL' TIPO,
  DOC.Oid_Documento IDENTIFICADOR,
  FORM.COD_COLOR,
  FORM.DES_FORMULARIO,
  SECO.DES_SECTOR,
  SECO.OID_SECTOR,
  SECD.DES_SECTOR DES_SECTOR_DES,
  SECD.OID_SECTOR OID_SECTOR_DES,
  DOC.GMT_CREACION,
  DOC.DES_USUARIO_CREACION,
  DOC.COD_EXTERNO,
  DOC.COD_COMPROBANTE
  ,DOC.GMT_MODIFICACION,
  DOC.DES_USUARIO_MODIFICACION,
  SC.DES_SUBCANAL
  
  FROM SAPR_TDOCUMENTO DOC
  INNER JOIN SAPR_TCUENTA CAO ON CAO.OID_CUENTA = CASE WHEN []DESTINORIGEN = 'O' THEN DOC.OID_CUENTA_ORIGEN ELSE DOC.OID_CUENTA_DESTINO END
  INNER JOIN SAPR_TCUENTA CAD ON CAD.OID_CUENTA = CASE WHEN []DESTINORIGEN = 'O' THEN DOC.OID_CUENTA_DESTINO ELSE DOC.OID_CUENTA_ORIGEN END
  INNER JOIN GEPR_TSUBCANAL SC ON CAO.OID_SUBCANAL = SC.Oid_Subcanal
  INNER JOIN SAPR_TFORMULARIO FORM ON DOC.OID_FORMULARIO = FORM.OID_FORMULARIO
  {4}
  INNER JOIN GEPR_TSECTOR SECD ON CAD.OID_SECTOR = SECD.OID_SECTOR
  {1}
  WHERE 1 = 1
  {0} {2}
   AND DOC.OID_GRUPO_DOCUMENTO IS NULL
   AND NOT (SECO.OID_SECTOR = SECD.OID_SECTOR AND []DESTINORIGEN = 'D')
   UNION

  SELECT 
  'GRUPO' TIPO,
  GRU.OID_GRUPO_DOCUMENTO IDENTIFICADOR,
  FORM.COD_COLOR,
  FORM.DES_FORMULARIO,
  SECO.DES_SECTOR,
  SECO.OID_SECTOR,
  SECD.DES_SECTOR DES_SECTOR_DES,
  SECD.OID_SECTOR OID_SECTOR_DES,
  GRU.GMT_CREACION,
  GRU.DES_USUARIO_CREACION,
  NULL,
  GRU.COD_COMPROBANTE,
  GRU.GMT_MODIFICACION,
  GRU.DES_USUARIO_MODIFICACION,
  NULL
 
  FROM SAPR_TGRUPO_DOCUMENTO GRU
  INNER JOIN SAPR_TFORMULARIO FORM ON GRU.OID_FORMULARIO = FORM.OID_FORMULARIO
  INNER JOIN SAPR_TDOCUMENTO DOC ON GRU.OID_GRUPO_DOCUMENTO = DOC.OID_GRUPO_DOCUMENTO
  {5}
  INNER JOIN GEPR_TSECTOR SECD ON CASE WHEN []DESTINORIGEN = 'O' THEN GRU.OID_SECTOR_DESTINO ELSE GRU.OID_SECTOR_ORIGEN END = SECD.OID_SECTOR
  {1}
  WHERE 
  NOT (SECO.OID_SECTOR = SECD.OID_SECTOR AND []DESTINORIGEN = 'D')
  {0} {3}  
GROUP BY
  'GRUPO',
  GRU.OID_GRUPO_DOCUMENTO,
  FORM.COD_COLOR,
  FORM.DES_FORMULARIO,
  SECO.DES_SECTOR,
  SECO.OID_SECTOR,
  SECD.DES_SECTOR,
  SECD.OID_SECTOR,
  GRU.GMT_CREACION,
  GRU.Des_Usuario_Creacion,
  NULL,
  GRU.COD_COMPROBANTE,
  GRU.Gmt_Modificacion,
  GRU.DES_USUARIO_MODIFICACION,
  NULL)
