SELECT
  DOCU.OID_DOCUMENTO IDENTIFICADOR,
  DOCU.COD_EXTERNO,
  DOCU.COD_COMPROBANTE,  
  FORM.OID_FORMULARIO,
  FORM.DES_FORMULARIO,
  CLI.DES_CLIENTE,
  SUBCLI.DES_SUBCLIENTE,
  SC.DES_SUBCANAL,
  SECO.DES_SECTOR,
  SECD.DES_SECTOR DES_SECTOR_DESTINO,
  DOCU.FYH_PLAN_CERTIFICACION,
  DOCU.BOL_NO_CERTIFICAR,

  DOCU.OID_CUENTA_SALDO_ORIGEN,
  CUOR.OID_CLIENTE,
  CUOR.OID_SUBCLIENTE,
  CUOR.OID_SECTOR,
  CUOR.OID_SUBCANAL,

  DOCU.OID_CUENTA_SALDO_DESTINO,
  CUDE.OID_CLIENTE OID_CLIENTE_DESTINO,
  CUDE.OID_SUBCLIENTE OID_SUBCLIENTE_DESTINO,
  CUDE.OID_SECTOR OID_SECTOR_DESTINO,
  CUDE.OID_SUBCANAL OID_SUBCANAL_DESTINO
FROM
  SAPR_TDOCUMENTO DOCU
  INNER JOIN SAPR_TFORMULARIO FORM ON DOCU.OID_FORMULARIO = FORM.OID_FORMULARIO  
  INNER JOIN SAPR_TTIPO_DOCUMENTO TDOC ON TDOC.OID_TIPO_DOCUMENTO = DOCU.OID_TIPO_DOCUMENTO
  INNER JOIN SAPR_TCUENTA CUOR ON CUOR.OID_CUENTA = DOCU.OID_CUENTA_SALDO_ORIGEN
  INNER JOIN GEPR_TCLIENTE CLI ON CLI.OID_CLIENTE = CUOR.OID_CLIENTE
  LEFT JOIN GEPR_TSUBCLIENTE SUBCLI ON SUBCLI.OID_SUBCLIENTE = CUOR.OID_SUBCLIENTE
  INNER JOIN GEPR_TSECTOR SECO ON SECO.OID_SECTOR = CUOR.OID_SECTOR
  INNER JOIN GEPR_TSUBCANAL SC ON SC.OID_SUBCANAL = CUOR.OID_SUBCANAL  
  INNER JOIN SAPR_TCUENTA CUDE ON CUDE.OID_CUENTA = DOCU.OID_CUENTA_SALDO_DESTINO
  INNER JOIN GEPR_TSECTOR SECD ON SECD.OID_SECTOR = CUDE.OID_SECTOR
WHERE
  DOCU.BOL_CERTIFICADO = 0 AND TDOC.BOL_CERTIFICACION = 1
  {0}