/* Consulta para recuperar documento para alocação
   Sempre buscará o documento tendo como referência o setor atual do MALOTE e eliminando as repetições do mesmo através da cláusula MAX	 */
WITH FILTRO_REMESA AS (SELECT MAX(BULT.OID_REMESA) AS OID_REMESA
                       FROM SAPR_TBULTO BULT INNER JOIN SAPR_TCUENTA CUEN ON BULT.OID_CUENTA = CUEN.OID_CUENTA
											 INNER JOIN SAPR_TREMESA REME ON REME.OID_REMESA = BULT.OID_REMESA
                       WHERE BULT.COD_ESTADO = 'CE' AND CUEN.OID_SECTOR = []OID_SECTOR {0})
SELECT
	 DOCU.OID_DOCUMENTO
	,DOCU.OID_FORMULARIO
	,DOCU.OID_CUENTA_ORIGEN
	,DOCU.OID_CUENTA_DESTINO
	,DOCU.OID_CUENTA_SALDO_ORIGEN
	,DOCU.OID_CUENTA_SALDO_DESTINO
	,DOCU.OID_DOCUMENTO_PADRE
	,DOCU.OID_DOCUMENTO_SUSTITUTO
	,DOCU.OID_TIPO_DOCUMENTO
	,DOCU.OID_SECTOR_ORIGEN
	,DOCU.OID_SECTOR_DESTINO
	,DOCU.OID_MOVIMENTACION_FONDO
	,DOCU.OID_GRUPO_DOCUMENTO
	,FN_GMT_DELEGACION_###VERSION###(PLA.OID_DELEGACION, DOCU.FYH_PLAN_CERTIFICACION) AS FYH_PLAN_CERTIFICACION
	,DOCU.FYH_PLAN_CERTIFICACION AS FYH_PLAN_CERTIFICACION_SINGMT
	,FN_GMT_DELEGACION_###VERSION###(PLA.OID_DELEGACION, DOCU.FYH_GESTION) AS FYH_GESTION
	,DOCU.BOL_CERTIFICADO
	,DOCU.COD_EXTERNO
	,DOCU.COD_ESTADO
	,DOCU.COD_COMPROBANTE
	,DOCU.COD_CERTIFICACION_CUENTAS
FROM FILTRO_REMESA F_REME
     INNER JOIN SAPR_TDOCUMENTOXELEMENTO DOCE ON DOCE.OID_REMESA = F_REME.OID_REMESA
     INNER JOIN SAPR_TDOCUMENTO DOCU ON DOCU.OID_DOCUMENTO = DOCE.OID_DOCUMENTO
     INNER JOIN GEPR_TSECTOR SECT ON SECT.OID_SECTOR = DOCU.OID_SECTOR_DESTINO
     INNER JOIN GEPR_TPLANTA PLA ON PLA.OID_PLANTA = SECT.OID_PLANTA
WHERE DOCE.COD_ESTADO_DOCXELEMENTO = 'C'