SELECT CERT.OID_CERTIFICADO, CERT.COD_ESTADO, CERT.FYH_CERTIFICADO
FROM SAPR_TDOCUMENTO DOCU 
	INNER JOIN SAPR_TTRANSACCION_EFECTIVO TREF ON DOCU.OID_DOCUMENTO = TREF.OID_DOCUMENTO
	LEFT OUTER JOIN SAPR_TCERTIFICADO CERT ON TREF.OID_CERTIFICADO = CERT.OID_CERTIFICADO
WHERE
	CERT.COD_ESTADO IN ('PS','PC')
	AND DOCU.OID_DOCUMENTO = []OID_DOCUMENTO
UNION
SELECT TRMP.OID_CERTIFICADO, CERT.COD_ESTADO, CERT.FYH_CERTIFICADO
FROM SAPR_TDOCUMENTO DOCU 
	INNER JOIN SAPR_TTRANSACCION_MEDIO_PAGO TRMP ON DOCU.OID_DOCUMENTO = TRMP.OID_DOCUMENTO
	LEFT OUTER JOIN SAPR_TCERTIFICADO CERT ON TRMP.OID_CERTIFICADO = CERT.OID_CERTIFICADO
WHERE
	CERT.COD_ESTADO IN ('PS','PC')
	AND DOCU.OID_DOCUMENTO = []OID_DOCUMENTO