SELECT 
       F.OID_FILTRO_FORMULARIO,
       F.DES_FILTRO_FORMULARIO,
       F.BOL_SOLO_DISPONIBLE,
       F.BOL_CON_VALOR,
       F.BOL_CON_BULTO,
       F.BOL_SOLO_REENVIO,
       F.BOL_SOLO_SUSTITUCION,
       F.BOL_CON_FECHA_ESPECIFICA,
       F.NEC_DIAS_BUSQUEDA_INICIO,
       F.NEC_DIAS_BUSQUEDA_FIN,
       F.COD_MIGRACION,
       F.BOL_ACTIVO,
       F.GMT_CREACION,
       F.DES_USUARIO_CREACION,
       F.GMT_MODIFICACION,
       F.DES_USUARIO_MODIFICACION
FROM SAPR_TFILTRO_FORMULARIO F
WHERE F.BOL_ACTIVO = 1