SELECT GEPR_TPARAMETRO.COD_PARAMETRO,
       GEPR_TPARAMETRO.DES_DESCRIPCION_CORTO,
       GEPR_TPARAMETRO.DES_DESCRIPCION_LARGA,
       GEPR_TPARAMETRO.NEC_ORDEN,
       GEPR_TPARAMETRO.BOL_OBLIGATORIO,
       GEPR_TPARAMETRO.NEC_TIPO_COMPONENTE,
	   GEPR_TPARAMETRO.NEC_TIPO_DATO,
       GEPR_TAPLICACION.COD_APLICACION,
       GEPR_TAPLICACION.DES_APLICACION,
       GEPR_TAPLICACION.COD_PERMISO,
       GEPR_TGRUPO_PARAMETRO.DES_DESCRIPCION_CORTO as GRUPO_DES_DESCRIPCION_CORTO,
       GEPR_TGRUPO_PARAMETRO.DES_DESCRIPCION_LARGA as GRUPO_DES_DESCRIPCION_LARGA,
       GEPR_TGRUPO_PARAMETRO.NEC_ORDEN as GRUPO_NEC_ORDEN,
       GEPR_TNIVEL_PARAMETRO.COD_NIVEL_PARAMETRO ,
	   GEPR_TNIVEL_PARAMETRO.DES_NIVEL_PARAMETRO
FROM GEPR_TPARAMETRO INNER JOIN GEPR_TAPLICACION ON 
  GEPR_TPARAMETRO.OID_APLICACION =  GEPR_TAPLICACION.OID_APLICACION
INNER JOIN GEPR_TNIVEL_PARAMETRO ON 
  GEPR_TPARAMETRO.OID_NIVEL_PARAMETRO = GEPR_TNIVEL_PARAMETRO.OID_NIVEL_PARAMETRO
INNER JOIN GEPR_TGRUPO_PARAMETRO ON 
  GEPR_TPARAMETRO.OID_GRUPO_PARAMETRO = GEPR_TGRUPO_PARAMETRO.OID_GRUPO_PARAMETRO
