SELECT
	   DEL.COD_DELEGACION
FROM
       GEPR_TPARAMETRO PAR
       INNER JOIN GEPR_TNIVEL_PARAMETRO NPA ON PAR.OID_NIVEL_PARAMETRO = NPA.OID_NIVEL_PARAMETRO AND NPA.COD_NIVEL_PARAMETRO = 3 -- POSTO
       INNER JOIN GEPR_TAPLICACION APL ON PAR.OID_APLICACION = APL.OID_APLICACION
       INNER JOIN GEPR_TPUESTO PUE ON APL.OID_APLICACION = PUE.OID_APLICACION AND PUE.BOL_VIGENTE = 1
       INNER JOIN GEPR_TDELEGACION DEL ON PUE.OID_DELEGACION = DEL.OID_DELEGACION
       LEFT OUTER JOIN GEPR_TPARAMETRO_VALOR PVA ON PAR.OID_PARAMETRO = PVA.OID_PARAMETRO AND PVA.COD_IDENTIFICADOR_NIVEL = PUE.OID_PUESTO -- POSTO
       LEFT OUTER JOIN GEPR_TPARAMETRO_OPCION POP ON PAR.OID_PARAMETRO = POP.OID_PARAMETRO AND POP.BOL_VIGENTE = 1 AND (POP.COD_DELEGACION = DEL.COD_DELEGACION OR POP.COD_DELEGACION IS NULL)
WHERE
       APL.COD_APLICACION = COD_APLICACION -- CÓDIGO APLICAÇÃO
       AND PUE.COD_PUESTO = UPPER(:COD_PUESTO) -- CÓDIGO POSTO
       AND UPPER(PUE.COD_HOST_PUESTO) = UPPER(:COD_HOST_PUESTO) -- HOST POSTO
	   AND ROWNUM <=1