SELECT GEPR_TPARAMETRO_OPCION.COD_OPCION,
       GEPR_TPARAMETRO_OPCION.DES_OPCION,
	   GEPR_TPARAMETRO_OPCION.BOL_VIGENTE,
	   GEPR_TPARAMETRO.COD_PARAMETRO,
       GEPR_TPARAMETRO.Des_Descripcion_Corto,
       GEPR_TPARAMETRO.Nec_Tipo_Dato,
       GEPR_TPARAMETRO.Nec_Tipo_Dato,
	   GEPR_TPARAMETRO_OPCION.COD_DELEGACION
FROM GEPR_TPARAMETRO INNER JOIN GEPR_TAPLICACION ON 
  GEPR_TPARAMETRO.OID_APLICACION =  GEPR_TAPLICACION.OID_APLICACION
INNER JOIN GEPR_TPARAMETRO_OPCION ON 
  GEPR_TPARAMETRO.OID_PARAMETRO = GEPR_TPARAMETRO_OPCION.OID_PARAMETRO
WHERE GEPR_TAPLICACION.COD_APLICACION = []COD_APLICACION AND 
      GEPR_TPARAMETRO.COD_PARAMETRO = []COD_PARAMETRO AND
	  GEPR_TPARAMETRO_OPCION.BOL_VIGENTE = 1
