SELECT P.OID_PARAMETRO, NP.COD_NIVEL_PARAMETRO
FROM GEPR_TPARAMETRO P
INNER JOIN GEPR_TNIVEL_PARAMETRO NP ON NP.OID_NIVEL_PARAMETRO = P.OID_NIVEL_PARAMETRO
WHERE UPPER(P.COD_PARAMETRO) = []COD_PARAMETRO AND P.OID_APLICACION = []OID_APLICACION