SELECT GEPR_TPARAMETRO.OID_PARAMETRO
FROM GEPR_TPARAMETRO INNER JOIN GEPR_TAPLICACION ON
  GEPR_TPARAMETRO.OID_APLICACION = GEPR_TAPLICACION.OID_APLICACION
WHERE GEPR_TAPLICACION.COD_APLICACION = []COD_APLICACION
      AND GEPR_TPARAMETRO.COD_PARAMETRO = []COD_PARAMETRO
