select 
 NSER.DES_NOMBRE_ARCHIVO,
 NSER.OID_NUMERO_SERIE,
 NSER.COD_USUARIO,
 NSER.FYH_ACTUALIZACION,
 NSER.COD_NUMERO_SERIE,
 REM.COD_DELEGACION,
 DEN.COD_DENOMINACION,
 DIV.COD_ISO_DIVISA,
 NSER.OID_REMESA,
 NSER.OID_BULTO
 
 FROM GEPR_TREMESA REM
 INNER JOIN GEPR_TNUMERO_SERIE NSER ON {0}
 INNER JOIN GEPR_TDENOMINACION DEN ON DEN.OID_DENOMINACION = NSER.Oid_Denominacion AND DEN.BOL_BILLETE = '1'
 INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = DEN.Oid_Divisa
 WHERE REM.OID_REMESA = []COD_PRECINTO
 order by NSER.Des_Nombre_Archivo,DIV.COD_ISO_DIVISA,NSER.OID_DENOMINACION
 
 
 