UPDATE GEPR_TPUNTO_SERVICIO 
SET	    OID_MAQUINA = []OID_MAQUINA,
       COD_USUARIO             = []COD_USUARIO,
       FYH_ACTUALIZACION       = []FYH_ACTUALIZACION 
WHERE OID_PTO_SERVICIO = []OID_PTO_SERVICIO