UPDATE GEPR_TPUNTO_SERVICIO
   SET OID_SUBCLIENTE          = []OID_SUBCLIENTE,
       COD_PTO_SERVICIO        = []COD_PTO_SERVICIO,
       DES_PTO_SERVICIO        = []DES_PTO_SERVICIO,
       BOL_VIGENTE             = []BOL_VIGENTE,
       COD_USUARIO             = []COD_USUARIO,
       FYH_ACTUALIZACION       = []FYH_ACTUALIZACION,
       OID_TIPO_PUNTO_SERVICIO = []OID_TIPO_PUNTO_SERVICIO,
       BOL_TOTALIZADOR_SALDO   = []BOL_TOTALIZADOR_SALDO
 WHERE OID_PTO_SERVICIO = []OID_PTO_SERVICIO