INSERT INTO GEPR_TPUNTO_SERVICIO (OID_PTO_SERVICIO, OID_SUBCLIENTE, COD_PTO_SERVICIO, DES_PTO_SERVICIO, BOL_VIGENTE, COD_USUARIO, FYH_ACTUALIZACION) 
VALUES 
([]OID_PTO_SERVICIO, []OID_SUBCLIENTE, []COD_PTO_SERVICIO, []DES_PTO_SERVICIO, []BOL_VIGENTE, []COD_USUARIO, []FYH_ACTUALIZACION)