SELECT
    COUNT(0) as QUANTIDADE
FROM SAPR_TCONFIG_NIVEL_SALDO CNS
INNER JOIN SAPR_TCONFIG_NIVEL_MOVIMIENTO CNM ON CNM.OID_CONFIG_NIVEL_SALDO = CNS.OID_CONFIG_NIVEL_SALDO
WHERE
    CNS.OID_PTO_SERVICIO = []OID_PTO_SERVICIO AND CNM.OID_PTO_SERVICIO <> []OID_PTO_SERVICIO AND CNM.BOL_ACTIVO = 1