SELECT 
  CLI.COD_CLIENTE, 
  CLI.DES_CLIENTE,
  SUBC.COD_SUBCLIENTE,
  SUBC.DES_SUBCLIENTE,
  PTSERV.COD_PTO_SERVICIO,
  CA.COD_AJENO, 
	CA.DES_AJENO,
  PTSERV.DES_PTO_SERVICIO
FROM 
  GEPR_TCLIENTE CLI 
  INNER JOIN GEPR_TSUBCLIENTE SUBC ON CLI.OID_CLIENTE = SUBC.OID_CLIENTE
  INNER JOIN GEPR_TPUNTO_SERVICIO PTSERV ON SUBC.OID_SUBCLIENTE = PTSERV.OID_SUBCLIENTE
  LEFT JOIN GEPR_TCODIGO_AJENO CA
  ON CA.OID_TABLA_GENESIS =  PTSERV.OID_PTO_SERVICIO AND  CA.COD_TIPO_TABLA_GENESIS = 'GEPR_TPUNTO_SERVICIO'
  AND CA.BOL_DEFECTO = 1 AND CA.BOL_ACTIVO = 1
WHERE 
  PTSERV.BOL_VIGENTE = 1 {0}  
ORDER BY
  CLI.COD_CLIENTE,
  SUBC.COD_SUBCLIENTE,
  PTSERV.COD_PTO_SERVICIO