SELECT P.OID_PTO_SERVICIO,
       P.OID_SUBCLIENTE,
       P.COD_PTO_SERVICIO,
       P.DES_PTO_SERVICIO,
       P.OID_TIPO_PUNTO_SERVICIO,
       P.BOL_TOTALIZADOR_SALDO,

       S.COD_SUBCLIENTE,
       S.OID_SUBCLIENTE,
       S.DES_SUBCLIENTE,

       C.OID_CLIENTE,
       C.COD_CLIENTE,
       C.DES_CLIENTE,
       
       T.COD_TIPO_PUNTO_SERVICIO,
       T.DES_TIPO_PUNTO_SERVICIO

  FROM GEPR_TPUNTO_SERVICIO P  
	INNER JOIN GEPR_TCODIGO_AJENO CA ON CA.OID_TABLA_GENESIS = P.OID_PTO_SERVICIO
	INNER JOIN GEPR_TSUBCLIENTE S    ON P.OID_SUBCLIENTE = S.OID_SUBCLIENTE
	INNER JOIN GEPR_TCLIENTE C    ON S.OID_CLIENTE = C.OID_CLIENTE
	LEFT JOIN GEPR_TTIPO_PUNTO_SERVICIO T ON P.OID_TIPO_PUNTO_SERVICIO = T.OID_TIPO_PUNTO_SERVICIO
 WHERE 
  CA.COD_TIPO_TABLA_GENESIS = 'GEPR_TPUNTO_SERVICIO'