SELECT P.OID_PTO_SERVICIO,
       P.OID_SUBCLIENTE,
       P.COD_PTO_SERVICIO,
       P.DES_PTO_SERVICIO,
       P.BOL_VIGENTE,
       P.COD_USUARIO,
       P.FYH_ACTUALIZACION,
       P.BOL_ENVIADO_SALDOS,
       P.OID_TIPO_PUNTO_SERVICIO,
       P.COD_MIGRACION,
       P.BOL_TOTALIZADOR_SALDO,

       S.COD_SUBCLIENTE,
       S.DES_SUBCLIENTE,

       C.OID_CLIENTE,
       C.COD_CLIENTE,
       C.DES_CLIENTE,
       
       T.DES_TIPO_PUNTO_SERVICIO,
	   T.COD_TIPO_PUNTO_SERVICIO

  FROM GEPR_TPUNTO_SERVICIO P
 INNER JOIN GEPR_TSUBCLIENTE S
    ON P.OID_SUBCLIENTE = S.OID_SUBCLIENTE
 INNER JOIN GEPR_TCLIENTE C
    ON S.OID_CLIENTE = C.OID_CLIENTE
 LEFT JOIN GEPR_TTIPO_PUNTO_SERVICIO T
    ON P.OID_TIPO_PUNTO_SERVICIO = T.OID_TIPO_PUNTO_SERVICIO
 WHERE 1 = 1
