SELECT	 
	TBILLETAJEXSUC.RECUENTO,
	TBILLETAJEXSUC.FECHA,
	TBILLETAJEXSUC.LETRA,
	TBILLETAJEXSUC.F22,
    TBILLETAJEXSUC.OID_REMESA_ORI,
	TBILLETAJEXSUC.COD_SUBCLIENTE,
	TBILLETAJEXSUC.ESTACION ,
	TBILLETAJEXSUC.DES_ESTACION,
	TBILLETAJEXSUC.MEDIO_PAGO,
	TBILLETAJEXSUC.DIVISA,
	TBILLETAJEXSUC.DES_DIVISA,
	TBILLETAJEXSUC.UNIDAD,
	TBILLETAJEXSUC.MUTIPLICADOR,
    TBILLETAJEXSUC.ES_BILLETE,
	SUM(TBILLETAJEXSUC.CANTIDAD) CANTIDAD,
	SUM(TBILLETAJEXSUC.VALOR) VALOR
FROM	
( 
	-- MEDIOS DE PAGO
	SELECT	
		TBULT.DES_BOOK_PROCESO		RECUENTO,
		TBULT.FEC_TRANSPORTE		FECHA,
		'A'							LETRA,
		TBULT.COD_TRANSPORTE		F22,
		TREGI.OID_REMESA_ORI        OID_REMESA_ORI,
		TBULT.COD_SUBCLIENTE        COD_SUBCLIENTE, 
		TBULT.COD_PUNTO_SERVICIO	ESTACION,
		TBULT.DES_PUNTO_SERVICIO	DES_ESTACION,
		TMEDI.DES_TIPO_MEDIO_PAGO	MEDIO_PAGO,
		TMEDI.COD_ISO_DIVISA		DIVISA,
        TDIVI.DES_DIVISA            DES_DIVISA,
		CASE WHEN 
			TMEDI.COD_TIPO_MEDIO_PAGO = 'codtipoa'
		THEN
			TMEDI.DES_MEDIO_PAGO
		ELSE
			TMEDI.DES_TIPO_MEDIO_PAGO
		END							UNIDAD,
		0							MUTIPLICADOR,
		0							ES_BILLETE,
		TMEDI.NUM_UNIDADES			CANTIDAD,
		TMEDI.NUM_IMPORTE			VALOR
	FROM
		GEPR_TBULTO  TBULT  
		INNER JOIN  GEPR_TREGISTRO_MOVIMIENTO TREGI ON TBULT.OID_BULTO = TREGI.OID_BULTO
		INNER JOIN  GEPR_TMEDIO_PAGO TMEDI ON TREGI.OID_REGISTRO_MOVIMIENTO = TMEDI.OID_REGISTRO_MOVIMIENTO
        INNER JOIN  GEPR_TDIVISA TDIVI  ON  TMEDI.COD_ISO_DIVISA=TDIVI.COD_ISO_DIVISA
	WHERE	 
		TBULT.COD_CLIENTE = []COD_CLIENTE
		AND TBULT.COD_DELEGACION = []COD_DELEGACION           
		AND (TRUNC(TBULT.FEC_TRANSPORTE) >= []FECHA_TRANSPORTE_DESDE OR []FECHA_TRANSPORTE_DESDE IS NULL)
		AND	(TRUNC(TBULT.FEC_TRANSPORTE) <= []FECHA_TRANSPORTE_HASTA OR []FECHA_TRANSPORTE_HASTA IS NULL)
		AND (TBULT.FEC_PROCESO >= []FECHA_DESDE OR []FECHA_DESDE IS NULL)
		AND	(TBULT.FEC_PROCESO <= []FECHA_HASTA OR []FECHA_HASTA IS NULL)
		AND (TBULT.FYH_FIN_CONTEO >= []FECHA_DESDE_FINCONTEO OR []FECHA_DESDE_FINCONTEO IS NULL)
		AND	(TBULT.FYH_FIN_CONTEO <= []FECHA_HASTA_FINCONTEO OR []FECHA_HASTA_FINCONTEO IS NULL)
		AND	(TBULT.DES_BOOK_PROCESO = []DES_BOOK_PROCESO OR []DES_BOOK_PROCESO IS NULL)
		AND	TREGI.COD_TIPO_MOVIMIENTO = []COD_TIPO_MOVIMENTO 
		AND TMEDI.NEC_SECUENCIA = 0        
	UNION ALL
	--  EFECTIVO
	SELECT	
		TBULT.DES_BOOK_PROCESO      RECUENTO,
		TBULT.FEC_TRANSPORTE        FECHA,
		'A'                         LETRA,
		TBULT.COD_TRANSPORTE        F22,
		TREGI.OID_REMESA_ORI        OID_REMESA_ORI,
		TBULT.COD_SUBCLIENTE        COD_SUBCLIENTE, 
		TBULT.COD_PUNTO_SERVICIO    ESTACION,
		TBULT.DES_PUNTO_SERVICIO    DES_ESTACION,
		'Efectivo'                  MEDIO_PAGO,
		TEFEC.COD_ISO_DIVISA        DIVISA,
        TDIVI.DES_DIVISA            DES_DIVISA,
		TDENO.DES_DENOMINACION      UNIDAD,
		TDENO.NUM_VALOR             CANTIDAD,
		TDENO.BOL_BILLETE           ES_BILLETE,
		(TEFEC.NEL_UNIDADES_MANUAL + TEFEC.NEL_UNIDADES_MAQUINA)MUTIPLICADOR,
		(TEFEC.NEL_UNIDADES_MANUAL + TEFEC.NEL_UNIDADES_MAQUINA) * TDENO.NUM_VALOR VALOR
	FROM
		GEPR_TBULTO  TBULT  
		INNER JOIN GEPR_TREGISTRO_MOVIMIENTO TREGI ON TBULT.OID_BULTO=TREGI.OID_BULTO
		INNER JOIN GEPR_TEFECTIVO  TEFEC ON	TREGI.OID_REGISTRO_MOVIMIENTO=TEFEC.OID_REGISTRO_MOVIMIENTO
		INNER JOIN  GEPR_TDENOMINACION  TDENO  ON TEFEC.COD_DENOMINACION=TDENO.COD_DENOMINACION  
		INNER JOIN GEPR_TDIVISA TDIVI ON TDENO.OID_DIVISA=TDIVI.OID_DIVISA
	WHERE	 
		TBULT.COD_CLIENTE = []COD_CLIENTE
		AND TBULT.COD_DELEGACION = []COD_DELEGACION
		AND (TRUNC(TBULT.FEC_TRANSPORTE) >= []FECHA_TRANSPORTE_DESDE OR []FECHA_TRANSPORTE_DESDE IS NULL)
		AND	(TRUNC(TBULT.FEC_TRANSPORTE) <= []FECHA_TRANSPORTE_HASTA OR []FECHA_TRANSPORTE_HASTA IS NULL)
		AND (TBULT.FEC_PROCESO >= []FECHA_DESDE OR []FECHA_DESDE IS NULL)
		AND	(TBULT.FEC_PROCESO <= []FECHA_HASTA OR []FECHA_HASTA IS NULL)
		AND (TBULT.FYH_FIN_CONTEO >= []FECHA_DESDE_FINCONTEO OR []FECHA_DESDE_FINCONTEO IS NULL)
		AND	(TBULT.FYH_FIN_CONTEO <= []FECHA_HASTA_FINCONTEO OR []FECHA_HASTA_FINCONTEO IS NULL)
		AND	(TBULT.DES_BOOK_PROCESO = []DES_BOOK_PROCESO OR []DES_BOOK_PROCESO IS NULL)
		AND TREGI.COD_TIPO_MOVIMIENTO = []COD_TIPO_MOVIMENTO 
	) TBILLETAJEXSUC
GROUP	BY 
	TBILLETAJEXSUC.RECUENTO,
	TBILLETAJEXSUC.FECHA,
	TBILLETAJEXSUC.LETRA,
	TBILLETAJEXSUC.F22,
    TBILLETAJEXSUC.OID_REMESA_ORI,
	TBILLETAJEXSUC.COD_SUBCLIENTE,
	TBILLETAJEXSUC.ESTACION,
	TBILLETAJEXSUC.DES_ESTACION,
	TBILLETAJEXSUC.DIVISA,
    TBILLETAJEXSUC.DES_DIVISA,
	TBILLETAJEXSUC.MEDIO_PAGO,    
	TBILLETAJEXSUC.UNIDAD,
	TBILLETAJEXSUC.MUTIPLICADOR,
    TBILLETAJEXSUC.ES_BILLETE
ORDER BY
	TBILLETAJEXSUC.F22