SELECT '00' TIPO_REGISTRO,
       BUL.DES_BOOK_PROCESO,
       BUL.FEC_TRANSPORTE,
       RE.FYH_FIN_CONTEO,
       'A' LETRA_RECIBO_TRANSPORTE,
       BUL.COD_TRANSPORTE,
       RE.COD_ESTADO,
       RE.OID_REMESA
FROM GEPR_TBULTO BUL
INNER JOIN GEPR_TREMESA RE
        ON BUL.OID_REMESA = RE.OID_REMESA
WHERE BUL.COD_CLIENTE = :COD_CLIENTE
  AND RE.FYH_FIN_CONTEO BETWEEN :FECHA_DESDE_FINCONTEO AND :FECHA_HASTA_FINCONTEO
  AND RE.COD_DELEGACION = :COD_DELEGACION
  AND RE.COD_ESTADO = 'PR' 
ORDER BY  RE.FYH_FIN_CONTEO, 
          BUL.FEC_TRANSPORTE,
          BUL.COD_TRANSPORTE