SELECT 
	OID_SESION,
	COD_USUARIO,
	COD_APLICACION,
	FYH_CREACION,
	FYH_ULTIMO_USO,
	NUM_CADUCIDAD,
	DATEDIFF(minute, GETDATE(), DATEADD(minute, NUM_CADUCIDAD, FYH_ULTIMO_USO)) AS CADUCIDAD
FROM
	GEPR_TSESION 
WHERE 
	OID_SESION = []OID_SESION