UPDATE 
	GEPR_TSESION 
SET 
	FYH_ULTIMO_USO = GETDATE() 
WHERE 
	OID_SESION = []OID_SESION AND 
	COD_USUARIO = []COD_USUARIO AND 
	COD_APLICACION = []COD_APLICACION AND
	DATEADD(minute, NUM_CADUCIDAD, FYH_ULTIMO_USO) > GETDATE()