SELECT COUNT(1) ATIVO, COD_PUESTO, OID_SESION
FROM
	GEPR_TSESION 
WHERE 
	COD_USUARIO = []COD_USUARIO AND 
	COD_APLICACION = []COD_APLICACION AND
	DATEADD(MINUTE, NUM_CADUCIDAD, FYH_ULTIMO_USO) > GETDATE()
GROUP BY COD_PUESTO, OID_SESION