SELECT COUNT(1) ATIVO, COD_PUESTO, OID_SESION
FROM
	GEPR_TSESION 
WHERE 
    COD_USUARIO = []COD_USUARIO AND
	COD_APLICACION = []COD_APLICACION AND
	(FYH_ULTIMO_USO + (NUM_CADUCIDAD/60/24)) > SYSDATE
GROUP BY COD_PUESTO, OID_SESION