UPDATE 
	GEPR_TSESION 
SET 
	FYH_ULTIMO_USO = SYSDATE 
WHERE 
	OID_SESION = []OID_SESION AND 
	COD_USUARIO = []COD_USUARIO AND 
	COD_APLICACION = []COD_APLICACION AND
	(FYH_ULTIMO_USO + (NUM_CADUCIDAD/60/24)) > SYSDATE