INSERT INTO GEPR_TSESION 
	(OID_SESION, 
	COD_USUARIO, 
	COD_APLICACION, 
	FYH_CREACION, 
	FYH_ULTIMO_USO, 
	NUM_CADUCIDAD,
	COD_PUESTO) 
VALUES 
	([]OID_SESION, 
	[]COD_USUARIO, 
	[]COD_APLICACION, 
	SYSDATE, 
	SYSDATE, 
	[]NUM_CADUCIDAD,
	[]COD_PUESTO)