SELECT 
	OID_SESION,
	COD_USUARIO,
	COD_APLICACION,
	FYH_CREACION,
	FYH_ULTIMO_USO,
	NUM_CADUCIDAD,
	CEIL((FYH_ULTIMO_USO + (NUM_CADUCIDAD/60/24))- SYSDATE) AS CADUCIDAD
FROM
	GEPR_TSESION 
WHERE 
	OID_SESION = []OID_SESION