SELECT        

      DIV.COD_ISO_DIVISA,

      DIV.DES_DIVISA,

	  DIVPRC.NEC_NUM_ORDEN,
	  
	  DIVPRC.NUM_TOLERANCIA_PARCIAL_MIN,

      DIVPRC.NUM_TOLERANCIA_PARCIAL_MAX,

      DIVPRC.NUM_TOLERANCIA_BULTO_MIN,

      DIVPRC.NUM_TOLERANCIA_BULTO_MAX,

      DIVPRC.NUM_TOLERANCIA_REMESA_MIN,

      DIVPRC.NUM_TOLERANCIA_REMESA_MAX

FROM  

      GEPR_TDIVISA_POR_PROCESO DIVPRC

      INNER JOIN GEPR_TDIVISA DIV ON DIVPRC.OID_DIVISA = DIV.OID_DIVISA

WHERE 

      DIVPRC.OID_PROCESO = []OID_PROCESO AND 

      DIV.BOL_VIGENTE = 1
