UPDATE SAPR_TREMESA REME
SET REME.COD_RUTA = []COD_RUTA, 
    REME.FYH_TRANSPORTE = []FYH_TRANSPORTE, 
    REME.GMT_MODIFICACION = []GMT_MODIFICACION,
    REME.DES_USUARIO_MODIFICACION = []USUARIO_MODIFICACION
WHERE REME.OID_REMESA = []OID_REMESA