UPDATE SAPR_TREMESA R 
SET R.COD_RUTA = []COD_RUTA, 
	R.NEL_PARADA = []NEL_PARADA, 
	R.FYH_TRANSPORTE = []FYH_TRANSPORTE,
	R.GMT_MODIFICACION = []GMT_MODIFICACION, 
	R.DES_USUARIO_MODIFICACION = []USUARIO_MODIFICACION , 
	R.OID_EXTERNO = []OID_EXTERNO 
WHERE R.OID_REMESA = []OID_REMESA