SELECT  DISTINCT
   
    -- Remesas
  R.OID_REMESA,
  R.OID_CUENTA AS R_OID_CUENTA,
  R.COD_EXTERNO AS R_COD_EXTERNO,  
  R.BOL_GESTION_BULTO,
 -- Bultos
  B.OID_BULTO,
  B.OID_CUENTA AS B_OID_CUENTA,  
  B.COD_PRECINTO AS B_COD_PRECINTO,  
  --CLIENTE
  CU.OID_CLIENTE,
  CU.COD_CLIENTE,
  CU.DES_CLIENTE,
  --SUB_CLIENTE
  CU.OID_SUBCLIENTE,
  CU.COD_SUBCLIENTE,
  CU.DES_SUBCLIENTE,
  --PTO_SERVICIO
  CU.OID_PTO_SERVICIO,
  CU.COD_PTO_SERVICIO,
  CU.DES_PTO_SERVICIO,
  (SELECT COUNT(1) FROM SAPR_TDATO_BANCARIO DATB WHERE 
   DATB.BOL_ACTIVO = 1 AND DATB.OID_CLIENTE = CU.OID_CLIENTE AND DATB.OID_SUBCLIENTE = CU.OID_SUBCLIENTE 
   AND DATB.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO) AS CUANT_CUENTAS
  {2}
FROM SAPR_TREMESA R
LEFT JOIN SAPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA AND B.COD_ESTADO NOT IN ('SU', 'AN', 'EE', 'EC')
INNER JOIN SAPR_VCUENTA CU ON CU.OID_CUENTA = B.OID_CUENTA
INNER JOIN SAPR_VCUENTA CUS ON CUS.OID_CUENTA = B.OID_CUENTA_SALDO
{0}
{1}
{3}