UPDATE SAPR_TREMESA 
   SET COD_ESTADO = []COD_ESTADO
      ,GMT_MODIFICACION = FN_GMT_ZERO_###VERSION###
      ,DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
 WHERE OID_REMESA = []OID_REMESA 
   AND COD_ESTADO <> []COD_ESTADO