SELECT
DOCE.OID_DOCUMENTO,
DOC.COD_ESTADO AS COD_ESTADO_DOCUMENTO,
F.DES_FORMULARIO,
DOCE.COD_ESTADO_DOCXELEMENTO,
DOC.OID_SECTOR_DESTINO,
SECO.DES_SECTOR,
CASE WHEN DOCE.COD_ESTADO_DOCXELEMENTO='C'
  THEN (SELECT COUNT(1)
FROM SAPR_TCARACTFORMXFORMULARIO CFF
INNER JOIN SAPR_TCARACT_FORMULARIO CF ON CF.OID_CARACT_FORMULARIO = CFF.OID_CARACT_FORMULARIO
WHERE CF.COD_CARACT_FORMULARIO ='ACCION_BAJAS'
AND  CFF.OID_FORMULARIO = DOC.OID_FORMULARIO)
ELSE 0
END ES_BAJA
FROM SAPR_TDOCUMENTOXELEMENTO DOCE 
INNER JOIN SAPR_TREMESA R ON R.OID_REMESA = DOCE.OID_REMESA 
INNER JOIN SAPR_TDOCUMENTO DOC ON DOC.OID_DOCUMENTO = DOCE.OID_DOCUMENTO
INNER JOIN SAPR_TFORMULARIO F ON F.OID_FORMULARIO = DOC.OID_FORMULARIO
INNER JOIN GEPR_TSECTOR SECO ON SECO.OID_SECTOR = DOC.OID_SECTOR_DESTINO
INNER JOIN GEPR_TPLANTA PLA ON PLA.OID_PLANTA = SECO.OID_PLANTA 
WHERE DOCE.COD_ESTADO_DOCXELEMENTO IN('C','T')
      AND R.COD_EXTERNO = []COD_EXTERNO 
      AND PLA.OID_DELEGACION = []OID_DELEGACION
	  {0}
  