SELECT COUNT(D.OID_DIFERENCIA_EFECTIVO) DIF FROM SAPR_TDIFERENCIA_EFECTIVO D
WHERE D.OID_REMESA = []OID_REMESA
UNION
SELECT COUNT(D.OID_DIFERENCIA_MEDIO_PAGO) DIF FROM SAPR_TDIFERENCIA_MEDIO_PAGO D
WHERE D.OID_REMESA = []OID_REMESA