SELECT DISTINCT
   
    -- Remesas
	R.ROWVER AS R_ROWVER,
	R.OID_REMESA,
	R.OID_CUENTA AS R_OID_CUENTA,
	R.OID_CUENTA_SALDO AS R_OID_CUENTA_SALDO,
    R.COD_ESTADO AS R_COD_ESTADO,
    R.GMT_CREACION AS R_GMT_CREACION, 
    R.GMT_MODIFICACION AS R_GMT_MODIFICACION,       
    R.COD_PUESTO_RESPONSABLE AS R_COD_PUESTO_RESPONSABLE,
    R.DES_USUARIO_CREACION AS R_DES_USUARIO_CREACION,
    R.DES_USUARIO_MODIFICACION AS R_DES_USUARIO_MODIFICACION,
    R.COD_USUARIO_RESPONSABLE AS R_COD_USUARIO_RESPONSABLE,
    R.OID_IAC AS R_OID_IAC,
    R.COD_RUTA AS R_COD_RUTA,
    R.COD_RECIBO_SALIDA AS R_COD_RECIBO_SALIDA,
    R.OID_REMESA_ORIGEN AS R_OID_REMESA_ORIGEN,
    R.COD_EXTERNO AS R_COD_EXTERNO,
    DER.OID_DOCUMENTO AS R_OID_DOCUMENTO,
    DER.COD_ESTADO_DOCXELEMENTO AS COD_ESTADO_DOCXELEMENTO_R,
    R.FYH_TRANSPORTE AS R_FYH_TRANSPORTE,
	R.NEL_PARADA AS R_NEL_PARADA,
	R.OID_EXTERNO AS R_OID_EXTERNO,
	R.COD_CAJERO AS R_COD_CAJERO,
	R.OID_REMESA_PADRE,
	R.FYH_CONTEO_INICIO R_FYH_CONTEO_INICIO,
	R.FYH_CONTEO_FIN R_FYH_CONTEO_FIN,
	R.BOL_GESTION_BULTO,
	R.BOL_NOENTREGUE,
	R.BOL_ANULADO,
	R.COD_NIVEL_DETALLE R_COD_NIVEL_DETALLE,

    -- Bultos
	B.ROWVER AS B_ROWVER,
    B.OID_BULTO,
	B.OID_CUENTA AS B_OID_CUENTA,
	B.OID_CUENTA_SALDO AS B_OID_CUENTA_SALDO,
	B.COD_PRECINTO AS B_COD_PRECINTO,
    B.COD_ESTADO AS B_COD_ESTADO,
    B.GMT_CREACION AS B_GMT_CREACION, 
    B.GMT_MODIFICACION AS B_GMT_MODIFICACION,
    B.COD_PUESTO_RESPONSABLE AS B_COD_PUESTO_RESPONSABLE,       
    B.DES_USUARIO_CREACION AS B_DES_USUARIO_CREACION,
    B.DES_USUARIO_MODIFICACION AS B_DES_USUARIO_MODIFICACION,
    B.COD_USUARIO_RESPONSABLE AS B_COD_USUARIO_RESPONSABLE,
    B.OID_IAC AS B_OID_IAC,
	B.OID_IAC_PARCIALES AS B_OID_IAC_PARCIALES,
    B.COD_BOLSA AS B_COD_BOLSA,
	B.OID_CUENTA AS B_OID_CUENTA,
	B.OID_EXTERNO AS B_OID_EXTERNO,
	DER.OID_DOCUMENTO AS B_OID_DOCUMENTO,
    DER.COD_ESTADO_DOCXELEMENTO AS COD_ESTADO_DOCXELEMENTO_B,
	B.FYH_PROCESO_LEGADO AS B_FYH_PROCESO_LEGADO,
	B.NEL_CANTIDAD_PARCIALES AS B_NEL_CANTIDAD_PARCIALES,
	B.BOL_CUADRADO AS BOL_CUADRADO,
	B.OID_BULTO_PADRE,
	B.FYH_CONTEO_INICIO B_FYH_CONTEO_INICIO,
	B.FYH_CONTEO_FIN B_FYH_CONTEO_FIN,
	B.COD_NIVEL_DETALLE B_COD_NIVEL_DETALLE,
	(SELECT LV1.COD_VALOR
		FROM SAPR_TLISTA_VALORXELEMENTO LVB1
		INNER JOIN GEPR_TLISTA_TIPO LT1 ON LT1.OID_LISTA_TIPO = LVB1.OID_LISTA_TIPO AND LT1.COD_TIPO = []COD_TIPOUBICACION
		INNER JOIN GEPR_TLISTA_VALOR LV1 ON LV1.OID_LISTA_VALOR = LVB1.OID_LISTA_VALOR
		WHERE LVB1.OID_BULTO = B.OID_BULTO AND rownum = 1 ) AS B_TipoUbicacion,

    -- Parciales
    P.OID_PARCIAL,
    P.COD_PRECINTO AS P_COD_PRECINTO,
    P.COD_ESTADO AS P_COD_ESTADO,
    P.COD_USUARIO_RESPONSABLE AS P_COD_USUARIO_RESPONSABLE,
    P.COD_PUESTO_RESPONSABLE AS P_COD_PUESTO_RESPONSABLE,
    P.NEC_SECUENCIA AS P_NEC_SECUENCIA,
    P.GMT_CREACION AS P_GMT_CREACION,
    P.DES_USUARIO_CREACION AS P_DES_USUARIO_CREACION,
    P.GMT_MODIFICACION AS P_GMT_MODIFICACION,
    P.DES_USUARIO_MODIFICACION AS P_DES_USUARIO_MODIFICACION,
    P.OID_IAC AS P_OID_IAC,
    P.FYH_CONTEO_INICIO AS P_FYH_CONTEO_INICIO,
    P.FYH_CONTEO_FIN AS P_FYH_CONTEO_FIN,
	P.OID_EXTERNO AS P_OID_EXTERNO

FROM SAPR_TREMESA R
     LEFT  JOIN SAPR_TBULTO B ON B.OID_REMESA = R.OID_REMESA
     LEFT  JOIN SAPR_TPARCIAL P ON P.OID_BULTO = B.OID_BULTO
     
     -- Documentos
	 INNER JOIN SAPR_TDOCUMENTOXELEMENTO DER ON DER.OID_REMESA = R.OID_REMESA
	 AND (DER.OID_BULTO = B.OID_BULTO)
	 INNER JOIN SAPR_TDOCUMENTO DOCR ON DER.OID_DOCUMENTO = DOCR.OID_DOCUMENTO

WHERE 1 = 1
	{0}
