SELECT DISTINCT
    
    -- Remesas
    R.OID_REMESA
	,R.OID_CUENTA AS R_OID_CUENTA
	,R.OID_CUENTA_SALDO AS R_OID_CUENTA_SALDO
    ,R.GMT_CREACION AS R_GMT_CREACION
    ,R.GMT_MODIFICACION AS R_GMT_MODIFICACION
    ,R.DES_USUARIO_CREACION AS R_DES_USUARIO_CREACION
    ,R.DES_USUARIO_MODIFICACION AS R_DES_USUARIO_MODIFICACION
    ,R.COD_EXTERNO AS R_COD_EXTERNO
    ,R.OID_DOCUMENTO AS R_OID_DOCUMENTO
	,R.BOL_GESTION_BULTO
	,R.ROWVER AS R_ROWVER

    -- Bultos
    ,B.OID_BULTO
	,B.OID_CUENTA AS B_OID_CUENTA
	,B.OID_CUENTA_SALDO AS B_OID_CUENTA_SALDO
    ,B.COD_PRECINTO AS B_COD_PRECINTO
    ,B.GMT_CREACION AS B_GMT_CREACION
    ,B.GMT_MODIFICACION AS B_GMT_MODIFICACION
    ,B.DES_USUARIO_CREACION AS B_DES_USUARIO_CREACION
    ,B.DES_USUARIO_MODIFICACION AS B_DES_USUARIO_MODIFICACION
    ,B.OID_DOCUMENTO AS B_OID_DOCUMENTO
    ,B.OID_CUENTA AS B_OID_CUENTA
    ,B.BOL_CUADRADO AS BOL_CUADRADO
	,B.ROWVER AS B_ROWVER
   
FROM SAPR_TBULTO B
INNER JOIN SAPR_TREMESA R ON R.OID_REMESA = B.OID_REMESA
INNER JOIN SAPR_TCUENTA CU ON CU.OID_CUENTA = B.OID_CUENTA
INNER JOIN GEPR_TCLIENTE CL ON CL.OID_CLIENTE = CU.OID_CLIENTE
INNER JOIN GEPR_TSUBCANAL SBC ON SBC.OID_SUBCANAL = CU.OID_SUBCANAL
INNER JOIN GEPR_TCANAL CAN ON CAN.OID_CANAL = SBC.OID_CANAL
INNER JOIN GEPR_TSECTOR SE ON SE.OID_SECTOR = CU.OID_SECTOR
INNER JOIN GEPR_TPLANTA PT ON PT.OID_PLANTA = SE.OID_PLANTA
INNER JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = PT.OID_DELEGACION
LEFT JOIN GEPR_TSUBCLIENTE SCL ON SCL.OID_SUBCLIENTE = CU.OID_SUBCLIENTE
LEFT JOIN GEPR_TPUNTO_SERVICIO PTO ON PTO.OID_PTO_SERVICIO = CU.OID_PTO_SERVICIO
WHERE R.COD_ESTADO = []COD_ESTADO_REMESA
AND B.COD_ESTADO = []COD_ESTADO_BULTO 
AND DEL.COD_DELEGACION = []COD_DELEGACION 
AND PT.COD_PLANTA = []COD_PLANTA
{0}
ORDER BY R.OID_REMESA