UPDATE SAPR_TREMESA R
   SET R.COD_RUTA = []COD_RUTA,
       R.FYH_TRANSPORTE = []FYH_SALIDA
  WHERE R.OID_REMESA IN (SELECT R.OID_REMESA
						 FROM SAPR_TREMESA R INNER JOIN SAPR_TBULTO B ON R.OID_REMESA = B.OID_REMESA
						 WHERE ((R.COD_ESTADO <> 'PR' AND B.COD_ESTADO <> 'SA') OR (R.COD_ESTADO = 'PE' AND B.COD_ESTADO <> 'SA')) {0}
						)