UPDATE SAPR_TREMESA R
   SET R.BOL_ANULADO = 1,
       R.DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION,
       R.GMT_MODIFICACION = []GMT_MODIFICACION
  WHERE R.OID_REMESA IN (SELECT R.OID_REMESA
						 FROM SAPR_TREMESA R INNER JOIN SAPR_TBULTO B ON R.OID_REMESA = B.OID_REMESA
						 WHERE ((R.COD_ESTADO <> 'PR' AND B.COD_ESTADO <> 'SA') OR (R.COD_ESTADO = 'PE' AND B.COD_ESTADO <> 'SA')) {0}
						)