INSERT INTO IAPR_TREPORTES_CONFIGURACION
(OID_REPORTE_CONFIGURACION,
 OID_CONFIGURACION,
 OID_CONFIGURACION_GENERAL)
VALUES
([]OID_REPORTE_CONFIGURACION,
 []OID_CONFIGURACION,
 []OID_CONFIGURACION_GENERAL)