INSERT INTO SAPR_TABONO_SNAPSHOT_EFECTIVO S
(S.OID_ABONO_SNAPSHOT_EFECTIVO,S.OID_ABONO_SNAPSHOT,S.OID_CUENTA_SALDO,S.OID_DIVISA,S.OID_UNIDAD_MEDIDA,
S.OID_CALIDAD,S.OID_DENOMINACION,S.COD_NIVEL_DETALLE,S.COD_TIPO_EFECTIVO_TOTAL,S.NUM_IMPORTE,
S.NEL_CANTIDAD,S.GMT_CREACION,S.DES_USUARIO_CREACION,S.GMT_MODIFICACION,S.DES_USUARIO_MODIFICACION)
VALUES
([]OID_ABONO_SNAPSHOT_EFECTIVO,[]OID_ABONO_SNAPSHOT,[]OID_CUENTA_SALDO,[]OID_DIVISA,[]OID_UNIDAD_MEDIDA,
[]OID_CALIDAD,[]OID_DENOMINACION,[]COD_NIVEL_DETALLE,[]COD_TIPO_EFECTIVO_TOTAL,[]NUM_IMPORTE,
[]NEL_CANTIDAD,FN_GMT_ZERO_###VERSION###,[]DES_USUARIO_CREACION,FN_GMT_ZERO_###VERSION###,[]DES_USUARIO_MODIFICACION)