UPDATE (
    SELECT TDOC.DES_VALOR,TDOC.DES_USUARIO_MODIFICACION,TDOC.GMT_MODIFICACION
    FROM SAPR_TVALOR_TERMINOxDOCUMENTO TDOC 
    INNER JOIN GEPR_TTERMINO T
    ON TDOC.OID_TERMINO = T.OID_TERMINO
    INNER JOIN SAPR_TDOCUMENTO DOC
    ON TDOC.OID_DOCUMENTO = DOC.OID_DOCUMENTO
    WHERE DOC.COD_EXTERNO = []COD_EXTERNO AND T.COD_TERMINO = []COD_TERMINO
    )
    SET DES_VALOR = []VALOR,
        DES_USUARIO_MODIFICACION = []USUARIO,
        GMT_MODIFICACION = SYSTIMESTAMP  AT TIME ZONE 'GMT'
