INSERT INTO GEPR_TCONFIGURACION_GRID
  (OID_CONFIGURACION_GRID, COD_USUARIO, COD_FUNCIONALIDAD, COD_CONTROL, DES_XML, FYH_CREACION, FYH_MODIFICACION)
VALUES
  ([]OID_CONFIGURACION_GRID, []COD_USUARIO, []COD_FUNCIONALIDAD, []COD_CONTROL, []DES_XML, []FYH_CREACION, []FYH_MODIFICACION)
