INSERT INTO GEPR_TDIVISA_POR_AGRUPACION
  (OID_DIVISA_AGRUPACION,
   OID_DIVISA,
   OID_AGRUPACION,
   COD_USUARIO,
   FYH_ACTUALIZACION)
VALUES
  ([]OID_DIVISA_AGRUPACION,
   []OID_DIVISA,
   []OID_AGRUPACION,
   []COD_USUARIO,
   []FYH_ACTUALIZACION)