SELECT
      DIV.COD_ISO_DIVISA,
      DIV.DES_DIVISA,
      DEN.COD_DENOMINACION,
      DEN.DES_DENOMINACION,
      DEN.BOL_BILLETE,
      DEN.NUM_VALOR,
      DEN.NUM_PESO
FROM  GEPR_TDIVISA_POR_AGRUPACION DIVAGR
      INNER JOIN GEPR_TDIVISA DIV ON DIVAGR.OID_DIVISA = DIV.OID_DIVISA
      INNER JOIN GEPR_TDENOMINACION DEN ON DIV.OID_DIVISA = DEN.OID_DIVISA
WHERE
      DIV.BOL_VIGENTE = 1 AND
      DEN.BOL_VIGENTE = 1 AND
      DIVAGR.OID_AGRUPACION = []OID_AGRUPACION
ORDER BY DIV.COD_ISO_DIVISA
