SELECT DIVAGRUP.OID_DIVISA_AGRUPACION
FROM GEPR_TDIVISA DIV
INNER JOIN GEPR_TDIVISA_POR_AGRUPACION DIVAGRUP ON DIVAGRUP.OID_DIVISA = DIV.OID_DIVISA
INNER JOIN GEPR_TAGRUPACION AGRUP ON AGRUP.OID_AGRUPACION = DIVAGRUP.OID_AGRUPACION
WHERE AGRUP.COD_AGRUPACION = []COD_AGRUPACION AND DIV.COD_ISO_DIVISA = []COD_ISO_DIVISA