 SELECT
   DOCU.OID_DOCUMENTO
  ,DOCU.OID_FORMULARIO
  ,DOCU.OID_CUENTA_ORIGEN
  ,DOCU.OID_CUENTA_DESTINO
  ,DOCU.OID_CUENTA_SALDO_ORIGEN
  ,DOCU.OID_CUENTA_SALDO_DESTINO
  ,DOCU.OID_DOCUMENTO_PADRE
  ,DOCU.OID_DOCUMENTO_SUSTITUTO
  ,DOCU.OID_TIPO_DOCUMENTO
  ,DOCU.OID_SECTOR_ORIGEN
  ,DOCU.OID_SECTOR_DESTINO
  ,DOCU.OID_MOVIMENTACION_FONDO
  ,DOCU.OID_GRUPO_DOCUMENTO
  ,FN_GMT_DELEGACION_###VERSION###(PLA.OID_DELEGACION, DOCU.FYH_PLAN_CERTIFICACION) AS FYH_PLAN_CERTIFICACION
  ,DOCU.FYH_PLAN_CERTIFICACION AS FYH_PLAN_CERTIFICACION_SINGMT
  ,FN_GMT_DELEGACION_###VERSION###(PLA.OID_DELEGACION, DOCU.FYH_GESTION) AS FYH_GESTION
  ,DOCU.BOL_CERTIFICADO
  ,DOCU.COD_EXTERNO
  ,DOCU.COD_ESTADO
  ,DOCU.COD_COMPROBANTE
  ,DOCU.COD_CERTIFICACION_CUENTAS
  ,REME.COD_ESTADO AS COD_ESTADO_REMESA
{0}
FROM 
  SAPR_TREMESA REME
  INNER JOIN SAPR_TDOCUMENTOXELEMENTO DOEL ON REME.OID_REMESA = DOEL.OID_REMESA AND DOEL.OID_BULTO IS NULL
  INNER JOIN SAPR_TDOCUMENTO DOCU ON DOEL.OID_DOCUMENTO = DOCU.OID_DOCUMENTO
  INNER JOIN GEPR_TSECTOR SECT ON SECT.OID_SECTOR = DOCU.OID_SECTOR_DESTINO
  INNER JOIN GEPR_TPLANTA PLA ON PLA.OID_PLANTA = SECT.OID_PLANTA
  INNER JOIN GEPR_TDELEGACION DELE ON DELE.OID_DELEGACION = PLA.OID_DELEGACION
  INNER JOIN SAPR_TBULTO BULT ON REME.OID_REMESA = BULT.OID_REMESA 
  {1}
WHERE 1 = 1 AND 
      DELE.COD_DELEGACION = []COD_DELEGACION AND
      SECT.OID_SECTOR = []OID_SECTOR AND 
      DOEL.COD_ESTADO_DOCXELEMENTO = []COD_ESTADO_DOCXELEMENTO {2}