SELECT 
 D.OID_DOCUMENTO
,D.OID_FORMULARIO
,D.OID_CUENTA_ORIGEN
,D.OID_CUENTA_DESTINO
,D.OID_CUENTA_SALDO_ORIGEN
,D.OID_CUENTA_SALDO_DESTINO
,D.OID_DOCUMENTO_PADRE
,D.OID_DOCUMENTO_SUSTITUTO
,D.OID_TIPO_DOCUMENTO
,D.OID_SECTOR_ORIGEN
,D.OID_SECTOR_DESTINO
,D.OID_MOVIMENTACION_FONDO
,D.OID_GRUPO_DOCUMENTO
,FN_GMT_DELEGACION_###VERSION###(P.OID_DELEGACION, D.FYH_PLAN_CERTIFICACION) AS FYH_PLAN_CERTIFICACION
,FN_GMT_DELEGACION_###VERSION###(P.OID_DELEGACION, D.FYH_GESTION) AS FYH_GESTION
,D.BOL_CERTIFICADO
,D.COD_EXTERNO
,D.COD_ESTADO
,D.COD_COMPROBANTE
,I2.NEL_INTENTO_ENVIO
,I2.OID_INTEGRACION
,R.OID_REMESA

      FROM SAPR_TDOCUMENTO D
INNER JOIN SAPR_TDOCUMENTOXELEMENTO DE ON D.OID_DOCUMENTO = DE.OID_DOCUMENTO
INNER JOIN SAPR_TREMESA R ON R.OID_DOCUMENTO = D.OID_DOCUMENTO
INNER JOIN GEPR_TSECTOR S ON S.OID_SECTOR = D.OID_SECTOR_DESTINO
INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA
 LEFT JOIN (SELECT I.NEL_INTENTO_ENVIO, I.OID_INTEGRACION, I.OID_TABLA_INTEGRACION
			  FROM GEPR_TINTEGRACION I  
			 WHERE I.COD_TABLA_INTEGRACION = 'SAPR_TDOCUMENTO' AND I.COD_ESTADO = 'KO' 
			   AND I.COD_MODULO_DESTINO = 'SOL' AND I.COD_PROCESO = 'GRABARDOCUMENTO' AND I.NEL_INTENTO_ENVIO <= []NEL_INTENTO_ENVIO
               AND I.GMT_CREACION = (SELECT MAX(GMT_CREACION) FROM GEPR_TINTEGRACION WHERE OID_TABLA_INTEGRACION = I.OID_TABLA_INTEGRACION)
           ) I2 ON I2.OID_TABLA_INTEGRACION = D.OID_DOCUMENTO
WHERE DE.COD_ESTADO_DOCXELEMENTO = []COD_ESTADO_DOCXELEMENTO {0}