SELECT COUNT(1) EXPORTADO_SOL FROM GEPR_TINTEGRACION I
INNER JOIN SAPR_TDOCUMENTO D ON D.OID_DOCUMENTO = I.OID_TABLA_INTEGRACION
WHERE D.COD_EXTERNO = []COD_EXTERNO
AND I.COD_MODULO_ORIGEN = 'GenesisRecepcionEnvio'
AND I.COD_MODULO_DESTINO = 'SOL'