    SELECT COUNT(1)
      FROM SAPR_TDOCUMENTO D
INNER JOIN SAPR_TFORMULARIO F ON F.OID_FORMULARIO = D.OID_FORMULARIO
INNER JOIN SAPR_TCARACTFORMXFORMULARIO CFF ON CFF.OID_FORMULARIO = F.OID_FORMULARIO
INNER JOIN SAPR_TCARACT_FORMULARIO CF ON CF.OID_CARACT_FORMULARIO = CFF.OID_CARACT_FORMULARIO
     WHERE D.COD_ESTADO = []COD_ESTADO
       AND CF.COD_CARACT_FORMULARIO = []COD_CARACT_FORMULARIO
       AND D.OID_SECTOR_ORIGEN = []OID_SECTOR_ORIGEN
       AND ROWNUM = 1
