INSERT INTO SAPR_TABONO_VALOR_DET_MEDPAGO
  (OID_ABONO_VALOR_DET_MEDPAGO, OID_ABONO_VALOR, OID_MEDIO_PAGO, COD_TIPO_MEDIO_PAGO, COD_NIVEL_DETALLE, NUM_IMPORTE, NEL_CANTIDAD, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
VALUES
  ([]OID_ABONO_VALOR_DET_MEDPAGO, []OID_ABONO_VALOR, []OID_MEDIO_PAGO, []COD_TIPO_MEDIO_PAGO, []COD_NIVEL_DETALLE, []NUM_IMPORTE, []NEL_CANTIDAD, FN_GMT_ZERO_###VERSION###, []DES_USUARIO_CREACION, FN_GMT_ZERO_###VERSION###, []DES_USUARIO_MODIFICACION)
