DELETE SAPR_TABONO_VALOR_DET_MEDPAGO AMP
WHERE AMP.OID_ABONO_VALOR IN (SELECT AV.OID_ABONO_VALOR
                              FROM SAPR_TABONO_VALOR AV 
                              WHERE AV.OID_ABONO = []OID_ABONO)