SELECT DIV.COD_ISO_DIVISA, DEN.COD_DENOMINACION, DEN.NUM_VALOR_FACIAL, IEM.NEL_UNIDADES 
FROM GEPR_TTIPO_MODULO TIP
INNER JOIN GEPR_TIMPORTE_ESTAND_MODULO IEM ON TIP.OID_TIPO_MODULO = IEM.OID_TIPO_MODULO
INNER JOIN GEPR_TDENOMINACION DEN ON IEM.OID_DENOMINACION = DEN.OID_DENOMINACION
INNER JOIN GEPR_TDIVISA DIV ON DEN.OID_DIVISA = DIV.OID_DIVISA
WHERE TIP.COD_TIPO_MODULO = []COD_TIPO_MODULO