SELECT DISTINCT
DIV.COD_ISO_DIVISA, DEN.BOL_BILLETE, DEN.NUM_VALOR_FACIAL, DEN.COD_DENOMINACION, 0 NEL_CANTIDAD,DIV.DES_DIVISA,DEN.DES_DENOMINACION
FROM GEPR_TDENOMINACION DEN
INNER JOIN GEPR_TDIVISA DIV ON DEN.OID_DIVISA = DIV.OID_DIVISA
WHERE DIV.COD_ISO_DIVISA || '|' || DEN.COD_DENOMINACION IN ({0})
ORDER BY DIV.COD_ISO_DIVISA ASC, DEN.BOL_BILLETE DESC, DEN.NUM_VALOR_FACIAL ASC