    select DEN.OID_DENOMINACION
          ,DEN.COD_DENOMINACION
          ,DEN.DES_DENOMINACION
          ,DEN.NUM_VALOR_FACIAL
          ,DEN.BOL_BILLETE
      from GEPR_TDENOMINACION DEN
inner join GEPR_TDIVISA DIV ON DEN.OID_DIVISA = DIV.OID_DIVISA
     where DIV.COD_ISO_DIVISA = []COD_ISO_DIVISA
  order by DEN.BOL_BILLETE DESC, DEN.NUM_VALOR_FACIAL DESC