INSERT INTO SAPR_TMONEDA_FALSA
(OID_MONEDA_FALSA
,OID_PARCIAL
,OID_DENOMINACION
,NEL_CANTIDAD_MANUAL
,GMT_CREACION
,DES_USUARIO_CREACION
,GMT_MODIFICACION
,DES_USUARIO_MODIFICACION)
VALUES
([]OID_MONEDA_FALSA
,[]OID_PARCIAL
,[]OID_DENOMINACION
,[]NEL_CANTIDAD_MANUAL
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_CREACION
,FN_GMT_ZERO_###VERSION###
,[]DES_USUARIO_MODIFICACION)
