SELECT 
        COUNT(DISTINCT N.OID_NOTIFICACION) CANTIDAD
FROM GEPR_TNOTIFICACION N
INNER JOIN GEPR_TTIPO_NOTIFICACION TN ON N.OID_TIPO_NOTIFICACION = TN.OID_TIPO_NOTIFICACION
INNER JOIN GEPR_TDESTINO_NOTIFICACION DN ON N.OID_NOTIFICACION = DN.OID_NOTIFICACION
LEFT JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = DN.OID_DELEGACION
LEFT JOIN GEPR_TPLANTA PLA ON PLA.OID_PLANTA = DN.OID_PLANTA
LEFT JOIN GEPR_TSECTOR SEC ON SEC.OID_SECTOR = DN.OID_SECTOR
LEFT JOIN ADPR_TUSUARIO USU ON USU.OID_USUARIO = DN.OID_USUARIO
WHERE TN.COD_APLICACION = []COD_APLICACION 
{0}
