SELECT 
        N.OID_NOTIFICACION,
        N.OBS_NOTIFICACION,
        N.OBS_PARAMETROS,
        N.BOL_ACTIVO,
        N.GMT_CREACION,
        N.DES_USUARIO_CREACION,
        N.GMT_MODIFICACION,
        N.DES_USUARIO_MODIFICACION,
        TN.OID_TIPO_NOTIFICACION,
        TN.COD_TIPO_NOTIFICACION,
        TN.DES_TIPO_NOTIFICACION,
        TN.COD_APLICACION,
		TN.BOL_EVENTO_RELACIONADO,
        DN.OID_DESTINO_NOTIFICACION,
        DN.OID_USUARIO,
        DN.OID_SECTOR,
        DN.OID_TIPO_SECTORXPLANTA,
        DN.OID_PLANTA,
        DN.OID_DELEGACION,
        DN.BOL_LEIDA,
        DN.GMT_CREACION AS GMT_CREACION_DESTINO,
        DN.DES_USUARIO_CREACION AS DES_USUARIO_CREACION_DESTINO,
        DN.GMT_MODIFICACION AS GMT_MODIFICACION_DESTINO,
        DN.DES_USUARIO_MODIFICACION AS DES_USUARIO_MOD_DESTINO
FROM GEPR_TNOTIFICACION N
INNER JOIN GEPR_TTIPO_NOTIFICACION TN ON N.OID_TIPO_NOTIFICACION = TN.OID_TIPO_NOTIFICACION
INNER JOIN GEPR_TDESTINO_NOTIFICACION DN ON N.OID_NOTIFICACION = DN.OID_NOTIFICACION
LEFT JOIN GEPR_TDELEGACION DEL ON DEL.OID_DELEGACION = DN.OID_DELEGACION
LEFT JOIN GEPR_TPLANTA PLA ON PLA.OID_PLANTA = DN.OID_PLANTA
LEFT JOIN GEPR_TSECTOR SEC ON SEC.OID_SECTOR = DN.OID_SECTOR
LEFT JOIN ADPR_TUSUARIO USU ON USU.OID_USUARIO = DN.OID_USUARIO
WHERE TN.COD_APLICACION = []COD_APLICACION 
{0}