UPDATE IAPR_TCONFIGURACION_REPORTES
SET
DES_RUTA = []DES_RUTA,
COD_USUARIO = []COD_USUARIO,
FYH_ACTUALIZACION = []FYH_ACTUALIZACION,
DES_CONFIGURACION = []DES_CONFIGURACION,
DES_NOMBRE_ARCHIVO = []DES_NOMBRE_ARCHIVO
WHERE
OID_CONFIGURACION = []OID_CONFIGURACION