INSERT INTO IAPR_TCONFIGURACION_REPORTES
(OID_CONFIGURACION,
DES_CONFIGURACION,
DES_RUTA,
COD_USUARIO,
FYH_ACTUALIZACION,
DES_NOMBRE_ARCHIVO)
VALUES
([]OID_CONFIGURACION,
[]DES_CONFIGURACION,
[]DES_RUTA,
[]COD_USUARIO,
[]FYH_ACTUALIZACION,
[]DES_NOMBRE_ARCHIVO)