UPDATE GEPR_TTIPO_PROCEDENCIA
   SET COD_TIPO_PROCEDENCIA = []COD_TIPO_PROCEDENCIA,
       DES_TIPO_PROCEDENCIA = []DES_TIPO_PROCEDENCIA,
       BOL_ACTIVO = []BOL_ACTIVO,
       GMT_CREACION = []GMT_CREACION,
       DES_USUARIO_CREACION = []DES_USUARIO_CREACION,
       GMT_MODIFICACION = []GMT_MODIFICACION,
       DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
 WHERE OID_TIPO_PROCEDENCIA = []OID_TIPO_PROCEDENCIA