SELECT DIV.COD_ISO_DIVISA,
       DIV.OID_DIVISA,
       DIV.DES_DIVISA,
       TMP.COD_TIPO_MEDIO_PAGO,
       SUM(TMP.NUM_IMPORTE_TIPO_MP_LEGADO)NUM_IMPORTE_TIPO_MP_LEGADO,
       TMP.OID_REMESA
FROM GEPR_TTIPO_MEDIO_PAGO_LEGADO TMP
INNER JOIN GEPR_TDIVISA DIV ON DIV.OID_DIVISA = TMP.OID_DIVISA
{0}
GROUP BY TMP.OID_REMESA, DIV.COD_ISO_DIVISA, DIV.OID_DIVISA, DIV.DES_DIVISA,TMP.COD_TIPO_MEDIO_PAGO