UPDATE
	GEPR_TGRUPO_CLIENTE
SET
	DES_GRUPO_CLIENTE = []DES_GRUPO_CLIENTE,
	BOL_VIGENTE = []BOL_VIGENTE,
	COD_USUARIO = []COD_USUARIO,
	FYH_ACTUALIZACION = []FYH_ACTUALIZACION,
	COD_TIPO_GRUPO_CLIENTE = []COD_TIPO_GRUPO_CLIENTE
WHERE
	COD_GRUPO_CLIENTE = []COD_GRUPO_CLIENTE