INSERT INTO GEPR_TGRUPO_CLIENTE_DETALLE
(
	OID_GRUPO_CLIENTE_DETALLE,
	OID_CLIENTE,
	OID_SUBCLIENTE,
	OID_PTO_SERVICIO,
	OID_GRUPO_CLIENTE,
	FYH_ACTUALIZACION
)
VALUES
(
	[]OID_GRUPO_CLIENTE_DETALLE,
	[]OID_CLIENTE,
	[]OID_SUBCLIENTE,
	[]OID_PTO_SERVICIO,
	[]OID_GRUPO_CLIENTE,
	[]FYH_ACTUALIZACION
)