SELECT
	GC.OID_GRUPO_CLIENTE,
	GC.COD_GRUPO_CLIENTE,
	GC.DES_GRUPO_CLIENTE,
	GC.BOL_VIGENTE,
	C.OID_CLIENTE,
	C.COD_CLIENTE,
	C.DES_CLIENTE,
	SC.OID_SUBCLIENTE,
	SC.COD_SUBCLIENTE,
	SC.DES_SUBCLIENTE,
	PS.OID_PTO_SERVICIO,
	PS.COD_PTO_SERVICIO,
	PS.DES_PTO_SERVICIO,
	GCD.OID_GRUPO_CLIENTE_DETALLE,
	GC.COD_TIPO_GRUPO_CLIENTE
FROM
	GEPR_TGRUPO_CLIENTE GC
	INNER JOIN GEPR_TGRUPO_CLIENTE_DETALLE GCD
		ON GC.OID_GRUPO_CLIENTE = GCD.OID_GRUPO_CLIENTE
	INNER JOIN GEPR_TCLIENTE C
		ON GCD.OID_CLIENTE = C.OID_CLIENTE
	LEFT JOIN GEPR_TSUBCLIENTE SC
		ON GCD.OID_SUBCLIENTE = SC.OID_SUBCLIENTE
	LEFT JOIN GEPR_TPUNTO_SERVICIO PS
		ON GCD.OID_PTO_SERVICIO = PS.OID_PTO_SERVICIO
WHERE {0}
ORDER BY	
	C.COD_CLIENTE,	
	SC.COD_SUBCLIENTE,	
	PS.COD_PTO_SERVICIO