insert into GEPR_TDELEGACIONXCONFIG_FACTUR (OID_DELEGACIONXCONFIG_FACTUR, OID_DELEGACION, OID_CLIENTE_CAPITAL, OID_SUBCLIENTE_TESORERIA, OID_PTO_SERVICIO_TESORERIA)
values ([]OID_DELEGACIONXCONFIG_FACTUR, []OID_DELEGACION, []OID_CLIENTE_CAPITAL, []OID_SUBCLIENTE_TESORERIA, []OID_PTO_SERVICIO_TESORERIA)
