INSERT INTO GEPR_TDELEGACION (OID_DELEGACION, OID_PAIS, COD_PAIS, COD_DELEGACION, DES_DELEGACION,
  NEC_GMT_MINUTOS, FYH_VERANO_INICIO, FYH_VERANO_FIN, NEC_VERANO_AJUSTE, DES_ZONA,
  BOL_VIGENTE, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
values
  ([]OID_DELEGACION, []OID_PAIS, []COD_PAIS, []COD_DELEGACION, []DES_DELEGACION,
  []NEC_GMT_MINUTOS, []FYH_VERANO_INICIO, []FYH_VERANO_FIN,
  []NEC_VERANO_AJUSTE, []DES_ZONA, []BOL_VIGENTE, []GMT_CREACION, []DES_USUARIO_CREACION,
  []GMT_MODIFICACION, []DES_USUARIO_MODIFICACION)