UPDATE GEPR_TDELEGACION
   SET OID_PAIS = []OID_PAIS,
	   COD_PAIS = []COD_PAIS,	
       DES_DELEGACION = []DES_DELEGACION,
       NEC_GMT_MINUTOS = []NEC_GMT_MINUTOS,
       FYH_VERANO_INICIO = []FYH_VERANO_INICIO,
       FYH_VERANO_FIN = []FYH_VERANO_FIN,
       NEC_VERANO_AJUSTE = []NEC_VERANO_AJUSTE,
       DES_ZONA = []DES_ZONA,
       BOL_VIGENTE = []BOL_VIGENTE,
       GMT_MODIFICACION = []GMT_MODIFICACION,
       DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION,
	   COD_DELEGACION = []COD_DELEGACION
 WHERE OID_DELEGACION = []OID_DELEGACION