UPDATE GEPR_TDELEGACION
   SET
       NEC_GMT_MINUTOS = []NEC_GMT_MINUTOS,
       FYH_VERANO_INICIO = []FYH_VERANO_INICIO,
       FYH_VERANO_FIN = []FYH_VERANO_FIN,
       NEC_VERANO_AJUSTE = []NEC_VERANO_AJUSTE,
       DES_ZONA = []DES_ZONA,      
       GMT_MODIFICACION = []GMT_MODIFICACION,
       DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
 WHERE BOL_VIGENTE = 1 AND  OID_PAIS = []OID_PAIS 