select 
     DL.OID_DELEGACION,
     DL.COD_DELEGACION,
     DL.DES_DELEGACION,
     DL.NEC_VERANO_AJUSTE,
     DL.NEC_GMT_MINUTOS,
     DL.FYH_VERANO_INICIO,
     DL.FYH_VERANO_FIN   
      from SAPR_TPLANIFICACION PLA
LEFT JOIN GEPR_TDELEGACION DL ON DL.OID_DELEGACION = PLA.OID_DELEGACION
WHERE OID_PLANIFICACION = []OID_PLANIFICACION