SELECT OID_CODIGO_AJENO, COD_IDENTIFICADOR, COD_AJENO, DES_AJENO, BOL_ACTIVO, BOL_DEFECTO FROM GEPR_TCODIGO_AJENO
 WHERE 
 OID_TABLA_GENESIS = []pOID_PLANTA 
 AND
 COD_TIPO_TABLA_GENESIS = 'GEPR_TPLANTA'