SELECT D.COD_DELEGACION, CAD.COD_AJENO
from GEPR_TDELEGACION D
LEFT JOIN GEPR_TCODIGO_AJENO CAD
ON CAD.OID_TABLA_GENESIS = D.OID_DELEGACION AND CAD.COD_IDENTIFICADOR = []COD_IDENTIFICADOR AND CAD.COD_TIPO_TABLA_GENESIS = 'GEPR_TDELEGACION'   
where D.OID_DELEGACION = []OID_DELEGACION