SELECT D.COD_DELEGACION
FROM GEPR_TDELEGACION D 
JOIN GEPR_TPUESTO P ON (D.OID_DELEGACION = P.OID_DELEGACION)
JOIN GEPR_TAPLICACION A ON (P.OID_APLICACION = A.OID_APLICACION)
WHERE UPPER(P.COD_HOST_PUESTO) = []COD_HOST_PUESTO AND ROWNUM = 1 