 SELECT OID_PLANTA, COD_PLANTA, DES_PLANTA, BOL_VIGENTE FROM GEPR_TPLANTA
INNER JOIN GEPR_TDELEGACION ON GEPR_TDELEGACION.OID_DELEGACION = GEPR_TPLANTA.OID_DELEGACION AND 
GEPR_TDELEGACION.COD_DELEGACION = GEPR_TPLANTA.COD_PLANTA
WHERE GEPR_TPLANTA.OID_DELEGACION = []pOID_DELEGACION