SELECT	D.OID_DELEGACION, DELEG.COD_DELEGACION, DELEG.DES_DELEGACION 
FROM	GEPR_TDELEGACIONXCONFIG_FACTUR D 
INNER JOIN GEPR_TDELEGACION DELEG ON DELEG.OID_DELEGACION = D.OID_DELEGACION
WHERE 
D.OID_CLIENTE_CAPITAL = []OID_CLIENTE_CAPITAL
AND D.OID_SUBCLIENTE_TESORERIA = []OID_SUBCLIENTE_TESORERIA
AND D.OID_PTO_SERVICIO_TESORERIA = []OID_PTO_SERVICIO_TESORERIA
AND D.OID_DELEGACION <> []OID_DELEGACION