SELECT
       PUSE.OID_PTO_SERVICIO,
       PUSE.COD_PTO_SERVICIO,
       PUSE.DES_PTO_SERVICIO,
       PUSE.BOL_VIGENTE,
       PUSE.COD_USUARIO,
       PUSE.FYH_ACTUALIZACION,
       PUSE.BOL_ENVIADO_SALDOS,
       PUSE.COD_MIGRACION,
       PUSE.BOL_TOTALIZADOR_SALDO,
       TIPS.OID_TIPO_PUNTO_SERVICIO TPPS_OID_TIPO_PUNTO_SERVICIO,
       TIPS.COD_TIPO_PUNTO_SERVICIO TPPS_COD_TIPO_PUNTO_SERVICIO,
       TIPS.DES_TIPO_PUNTO_SERVICIO TPPS_DES_TIPO_PUNTO_SERVICIO,
       TIPS.BOL_ACTIVO TPPS_BOL_ACTIVO,
       TIPS.GMT_CREACION TPPS_GMT_CREACION,
       TIPS.DES_USUARIO_CREACION TPPS_DES_USUARIO_CREACION,
       TIPS.GMT_MODIFICACION TPPS_GMT_MODIFICACION,
       TIPS.DES_USUARIO_MODIFICACION TPPS_DES_USUARIO_MODIFICACION
FROM
       GEPR_TPUNTO_SERVICIO PUSE
       LEFT OUTER JOIN GEPR_TTIPO_PUNTO_SERVICIO TIPS ON PUSE.OID_TIPO_PUNTO_SERVICIO = TIPS.OID_TIPO_PUNTO_SERVICIO
WHERE
       PUSE.COD_PTO_SERVICIO = []COD_PTO_SERVICIO