INSERT INTO GEPR_TTIPO_SECTOR
(OID_TIPO_SECTOR, COD_TIPO_SECTOR, DES_TIPO_SECTOR, BOL_ACTIVO, GMT_CREACION, 
DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
VALUES
([]OID_TIPO_SECTOR, []COD_TIPO_SECTOR, []DES_TIPO_SECTOR, []BOL_ACTIVO, 
[]GMT_CREACION, []DES_USUARIO_CREACION, []GMT_MODIFICACION, []DES_USUARIO_MODIFICACION)