INSERT INTO GEPR_TCARACTTIPOSECTORXTIPOSEC
(
    OID_CARACTTIPOSECTORXTIPOSEC,
    OID_TIPO_SECTOR,
    OID_CARACT_TIPOSECTOR,
    GMT_CREACION,
    DES_USUARIO_CREACION,
    GMT_MODIFICACION,
    DES_USUARIO_MODIFICACION
)
VALUES
(
    []OID_CARACTTIPOSECTORXTIPOSEC,
    (SELECT OID_TIPO_SECTOR FROM GEPR_TTIPO_SECTOR WHERE COD_TIPO_SECTOR = []COD_TIPO_SECTOR),
    (SELECT OID_CARACT_TIPOSECTOR FROM GEPR_TCARACT_TIPOSECTOR WHERE COD_CARACT_TIPOSECTOR = []COD_CARACT_TIPOSECTOR),
    []GMT_CREACION,
    []DES_USUARIO_CREACION,
    []GMT_MODIFICACION,
    []DES_USUARIO_MODIFICACION
)