INSERT INTO GEPR_TTIPO_SECTORXDELEGACION
  (OID_TIPO_SECTORXDELEGACION,
   OID_DELEGACION,
   OID_TIPO_SECTOR,
   GMT_CREACION,
   DES_USUARIO_CREACION,
   GMT_MODIFICACION,
   DES_USUARIO_MODIFICACION)
VALUES
  ([]OID_TIPO_SECTORXDELEGACION,
   []OID_DELEGACION,
   []OID_TIPO_SECTOR,
   []GMT_CREACION,
   []DES_USUARIO_CREACION,
   []GMT_MODIFICACION,
   []DES_USUARIO_MODIFICACION)