INSERT INTO GEPR_TTIPO_SECTORXPLANTA
  (OID_TIPO_SECTORXPLANTA, 
   OID_PLANTA,
   OID_TIPO_SECTOR,
   GMT_CREACION,
   DES_USUARIO_CREACION,
   GMT_MODIFICACION,
   DES_USUARIO_MODIFICACION)
VALUES
  ([]OID_TIPO_SECTORXPLANTA,
   []OID_PLANTA,
   []OID_TIPO_SECTOR,
   []GMT_CREACION,
   []DES_USUARIO_CREACION,
   []GMT_MODIFICACION,
   []DES_USUARIO_MODIFICACION)