INSERT INTO GEPR_TCARACTTIPOSECTORXTIPOSEC
(
	OID_CARACTTIPOSECTORXTIPOSEX, 
	OID_TIPO_SECTOR, 
	OID_CARACT_TIPOSECTOR, 
	GMT_CREACION, 
	DES_USUARIO_CREACION,
	GMT_MODIFICACION, 
	DES_USUARIO_MODIFICACION
)
VALUES
(
	[]OID_CARACTTIPOSECTORXTIPOSEX, 
	(SELECT TS.OID_TIPO_SECTOR FROM GEPR_TTIPO_SECTOR TS WHERE TS.COD_TIPO_SECTOR = []COD_TIPO_SECTOR),
	(SELECT TC.OID_CARACT_TIPOSECTOR FROM GEPR_TCARACT_TIPOSECTOR TC WHERE TC.COD_CARACT_TIPOSECTOR = []COD_CARACT_TIPOSECTOR), 
	[]GMT_CREACION, 
	[]DES_USUARIO_CREACION, 
	[]GMT_MODIFICACION, 
	[]DES_USUARIO_MODIFICACION
)