UPDATE GEPR_TTIPO_SECTOR
SET COD_TIPO_SECTOR = []COD_TIPO_SECTOR,
    DES_TIPO_SECTOR = []DES_TIPO_SECTOR,
    BOL_ACTIVO = []BOL_ACTIVO,
    GMT_MODIFICACION = []GMT_MODIFICACION,
    DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE OID_TIPO_SECTOR = []OID_TIPO_SECTOR