SELECT OID_CARACT_TIPOSECTOR, COD_CARACT_TIPOSECTOR, DES_CARACT_TIPOSECTOR, BOL_ACTIVO, GMT_CREACION,
DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION FROM GEPR_TCARACT_TIPOSECTOR
WHERE BOL_ACTIVO = 1