DECLARE
var$oid_tipo_periodo  VARCHAR2(36);
BEGIN

  
  SELECT OID_TIPO_PERIODO INTO var$oid_tipo_periodo FROM SAPR_TTIPO_PERIODO WHERE COD_TIPO_PERIODO = 'AC';
  UPDATE SAPR_TPERIODO SET OID_TIPO_PERIODO = var$oid_tipo_periodo WHERE OID_TIPO_PERIODO IS NULL;

COMMIT;
END;
/