DECLARE
  V_EXISTE NUMBER := 0;
  V_OID_IAC_INDIVIDUAL VARCHAR2(36) := '';
  V_OID_TIPO_DOCUMENTO VARCHAR2(36) := '';
  V_OID_TIPO_SECTOR VARCHAR2(36) := '';
  V_OID_FORMULARIO VARCHAR2(36) := '';
BEGIN
  -- Se obttiene información para la creación del Formulario
  -- IAC Documento Individual: IAC MAE GENERICO
  SELECT INAC.OID_IAC INTO V_OID_IAC_INDIVIDUAL FROM GEPR_TINFORM_ADICIONAL_CLIENTE INAC WHERE INAC.COD_IAC = 'IACMAE1';
  -- Tipo Movimiento: MOVIMIENTOS DE FONDOS
  SELECT TIDO.OID_TIPO_DOCUMENTO INTO V_OID_TIPO_DOCUMENTO FROM SAPR_TTIPO_DOCUMENTO TIDO WHERE TIDO.COD_TIPO_DOCUMENTO = 'MOVFONDOS';  
  -- Tipo Sector: MAE - Tesoro Contable
  SELECT TISE.OID_TIPO_SECTOR INTO V_OID_TIPO_SECTOR FROM GEPR_TTIPO_SECTOR TISE WHERE TISE.COD_TIPO_SECTOR = 'MAETC';

  --- MAERCJO - MAE - Recojo
  SELECT COUNT(1) INTO V_EXISTE FROM SAPR_TFORMULARIO FORM WHERE FORM.COD_FORMULARIO = 'MAERCJO';
  IF (V_EXISTE = 0) THEN
    SELECT SYS_GUID() INTO V_OID_FORMULARIO FROM DUAL;
    INSERT INTO SAPR_TFORMULARIO (OID_FORMULARIO, OID_ACCION_CONTABLE, OID_IAC_INDIVIDUAL, OID_TIPO_DOCUMENTO, COD_FORMULARIO, DES_FORMULARIO, COD_COLOR, BOL_ACTIVO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION, DES_COD_EXTERNO)
    SELECT V_OID_FORMULARIO, ACCO.OID_ACCION_CONTABLE, V_OID_IAC_INDIVIDUAL, V_OID_TIPO_DOCUMENTO, 'MAERCJO', 'MAE - Recojo', 'FFCCFF', '1', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA', 'RECOJO'
    FROM SAPR_TACCION_CONTABLE ACCO
    WHERE ACCO.COD_ACCION_CONTABLE = 'AC_000000000001' -- NO MUEVE VALORES
    ;
    
    INSERT INTO SAPR_TCARACTFORMXFORMULARIO (OID_CARACTFORMXFORMULARIO, OID_FORMULARIO, OID_CARACT_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    SELECT SYS_GUID(), V_OID_FORMULARIO, CAFO.OID_CARACT_FORMULARIO, SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA'
    FROM SAPR_TCARACT_FORMULARIO CAFO WHERE CAFO.COD_CARACT_FORMULARIO IN ('DOCUMENTO_INDIVIDUAL', 'CODIGO_EXTERNO_OBLIGATORIO', 'CARACTERISTICA_PRINCIPAL_CIERRES','CIERRE_TESORO','ENTRE_SECTORES_MISMA_PLANTA');     
    
    INSERT INTO SAPR_TCOPIA (OID_COPIA, OID_FORMULARIO, DES_DESTINO_COPIA, NEL_CANTIDAD_COPIA, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, 'ORIGINAL', '1', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');
    
    INSERT INTO GEPR_TTIPO_SECTORXFORMULARIO (OID_TIPO_SECTORXFORMULARIO, OID_FORMULARIO, OID_TIPO_SECTOR, COD_RELACION_CON_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, V_OID_TIPO_SECTOR, 'O', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');
    INSERT INTO GEPR_TTIPO_SECTORXFORMULARIO (OID_TIPO_SECTORXFORMULARIO, OID_FORMULARIO, OID_TIPO_SECTOR, COD_RELACION_CON_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, V_OID_TIPO_SECTOR, 'D', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');     
    
  END IF;

  --- MAEBOVE - MAE - Bóveda
  SELECT COUNT(1) INTO V_EXISTE FROM SAPR_TFORMULARIO FORM WHERE FORM.COD_FORMULARIO = 'MAEBOVE';
  IF (V_EXISTE = 0) THEN
    SELECT SYS_GUID() INTO V_OID_FORMULARIO FROM DUAL;
    INSERT INTO SAPR_TFORMULARIO (OID_FORMULARIO, OID_ACCION_CONTABLE, OID_IAC_INDIVIDUAL, OID_TIPO_DOCUMENTO, COD_FORMULARIO, DES_FORMULARIO, COD_COLOR, BOL_ACTIVO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION, DES_COD_EXTERNO)
    SELECT V_OID_FORMULARIO, ACCO.OID_ACCION_CONTABLE, V_OID_IAC_INDIVIDUAL, V_OID_TIPO_DOCUMENTO, 'MAEBOVE', 'MAE - Bóveda', 'FFCCFF', '1', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA', 'BOVEDA'
    FROM SAPR_TACCION_CONTABLE ACCO
    WHERE ACCO.COD_ACCION_CONTABLE = 'AC_000000000001' -- NO MUEVE VALORES
    ;
    
    INSERT INTO SAPR_TCARACTFORMXFORMULARIO (OID_CARACTFORMXFORMULARIO, OID_FORMULARIO, OID_CARACT_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    SELECT SYS_GUID(), V_OID_FORMULARIO, CAFO.OID_CARACT_FORMULARIO, SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA'
    FROM SAPR_TCARACT_FORMULARIO CAFO WHERE CAFO.COD_CARACT_FORMULARIO IN ('DOCUMENTO_INDIVIDUAL', 'CODIGO_EXTERNO_OBLIGATORIO', 'CARACTERISTICA_PRINCIPAL_CIERRES','CIERRE_TESORO','ENTRE_SECTORES_MISMA_PLANTA'); 
    
    INSERT INTO SAPR_TCOPIA (OID_COPIA, OID_FORMULARIO, DES_DESTINO_COPIA, NEL_CANTIDAD_COPIA, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, 'ORIGINAL', '1', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');
    
    INSERT INTO GEPR_TTIPO_SECTORXFORMULARIO (OID_TIPO_SECTORXFORMULARIO, OID_FORMULARIO, OID_TIPO_SECTOR, COD_RELACION_CON_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, V_OID_TIPO_SECTOR, 'O', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');
    INSERT INTO GEPR_TTIPO_SECTORXFORMULARIO (OID_TIPO_SECTORXFORMULARIO, OID_FORMULARIO, OID_TIPO_SECTOR, COD_RELACION_CON_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, V_OID_TIPO_SECTOR, 'D', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');     
    
  END IF;

   --- MAEBOR - MAE - BORRAR
  SELECT COUNT(1) INTO V_EXISTE FROM SAPR_TFORMULARIO FORM WHERE FORM.COD_FORMULARIO = 'MAEBOR';
  IF (V_EXISTE = 0) THEN
    SELECT SYS_GUID() INTO V_OID_FORMULARIO FROM DUAL;
    INSERT INTO SAPR_TFORMULARIO (OID_FORMULARIO, OID_ACCION_CONTABLE, OID_IAC_INDIVIDUAL, OID_TIPO_DOCUMENTO, COD_FORMULARIO, DES_FORMULARIO, COD_COLOR, BOL_ACTIVO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION, DES_COD_EXTERNO)
    SELECT V_OID_FORMULARIO, ACCO.OID_ACCION_CONTABLE, V_OID_IAC_INDIVIDUAL, V_OID_TIPO_DOCUMENTO, 'MAEBOR', 'MAE - Borrar', 'D6422A', '1', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA', 'DELETED'
    FROM SAPR_TACCION_CONTABLE ACCO
    WHERE ACCO.COD_ACCION_CONTABLE = 'AC_000000000001' -- NO MUEVE VALORES
    ;
    
    INSERT INTO SAPR_TCARACTFORMXFORMULARIO (OID_CARACTFORMXFORMULARIO, OID_FORMULARIO, OID_CARACT_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    SELECT SYS_GUID(), V_OID_FORMULARIO, CAFO.OID_CARACT_FORMULARIO, SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA'
    FROM SAPR_TCARACT_FORMULARIO CAFO WHERE CAFO.COD_CARACT_FORMULARIO IN ('DOCUMENTO_INDIVIDUAL', 'CODIGO_EXTERNO_OBLIGATORIO', 'CARACTERISTICA_PRINCIPAL_CIERRES','CIERRE_TESORO','ENTRE_SECTORES_MISMA_PLANTA');     
    
    INSERT INTO SAPR_TCOPIA (OID_COPIA, OID_FORMULARIO, DES_DESTINO_COPIA, NEL_CANTIDAD_COPIA, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, 'ORIGINAL', '1', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');
    
    INSERT INTO GEPR_TTIPO_SECTORXFORMULARIO (OID_TIPO_SECTORXFORMULARIO, OID_FORMULARIO, OID_TIPO_SECTOR, COD_RELACION_CON_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, V_OID_TIPO_SECTOR, 'O', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');
    INSERT INTO GEPR_TTIPO_SECTORXFORMULARIO (OID_TIPO_SECTORXFORMULARIO, OID_FORMULARIO, OID_TIPO_SECTOR, COD_RELACION_CON_FORMULARIO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
    VALUES (SYS_GUID(), V_OID_FORMULARIO, V_OID_TIPO_SECTOR, 'D', SYSTIMESTAMP, 'SCRIPT_CARGA', SYSTIMESTAMP, 'SCRIPT_CARGA');     
    
  END IF;

  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/