
DECLARE
   OWNER_OBJECTS VARCHAR2(30) := '';
   EXISTE NUMBER;
BEGIN
  SELECT sys_context( 'userenv', 'current_schema' ) INTO OWNER_OBJECTS FROM DUAL;

  /* COD_TIPO_PLANIFICACION */
  SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TMOVIMIENTO' AND COLUMN_NAME = 'COD_TIPO_PLANIFICACION';
  IF EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TMOVIMIENTO ADD COD_TIPO_PLANIFICACION VARCHAR2(20) NULL';
  END IF;

  /* DES_TIPO_PLANIFICACION */
  SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TMOVIMIENTO' AND COLUMN_NAME = 'DES_TIPO_PLANIFICACION';
  IF EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TMOVIMIENTO ADD DES_TIPO_PLANIFICACION VARCHAR2(100) NULL';
  END IF;

  /* COD_COMPROBANTE */
  SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TMOVIMIENTO' AND COLUMN_NAME = 'COD_COMPROBANTE';
  IF EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TMOVIMIENTO ADD COD_COMPROBANTE VARCHAR2(18) NULL';
  END IF;

  /* DES_CLIENTE_OPE */
  SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TMOVIMIENTO' AND COLUMN_NAME = 'DES_CLIENTE_OPE';
  IF EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TMOVIMIENTO ADD DES_CLIENTE_OPE VARCHAR2(100) NULL';
  END IF;

  /* DES_SUBCLIENTE_OPE */
  SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TMOVIMIENTO' AND COLUMN_NAME = 'DES_SUBCLIENTE_OPE';
  IF EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TMOVIMIENTO ADD DES_SUBCLIENTE_OPE VARCHAR2(100) NULL';
  END IF;

  /* DES_PTO_SERVICIO_OPE */
  SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TMOVIMIENTO' AND COLUMN_NAME = 'DES_PTO_SERVICIO_OPE';
  IF EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TMOVIMIENTO ADD DES_PTO_SERVICIO_OPE VARCHAR2(100) NULL';
  END IF;

  /* NEL_CANTIDAD */
  SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TMOVIMIENTO' AND COLUMN_NAME = 'NEL_CANTIDAD';
  IF EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TMOVIMIENTO ADD NEL_CANTIDAD NUMBER(20,0) DEFAULT 0 NULL';     
  END IF;

  /* COD_DEVICEID_BASE */
  SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TMOVIMIENTO' AND COLUMN_NAME = 'COD_DEVICEID_BASE';
  IF EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TMOVIMIENTO ADD COD_DEVICEID_BASE VARCHAR2(12) GENERATED ALWAYS AS (CASE WHEN LENGTH(COD_DEVICEID) >= 17 THEN SUBSTR(COD_DEVICEID, 6, 12) ELSE SUBSTR(COD_DEVICEID, 1, 12) END) VIRTUAL';     
  END IF;

  EXCEPTION
    WHEN OTHERS THEN raise_application_error( -20001, 'Arquivo: Genesis.sql Script: SAPR_TMOVIMIENTO - ' || sqlerrm);
    RAISE;
END;  
/
/*==============================================================*/
/* Indexes:                                                     */
/*==============================================================*/
DECLARE
  OWNER_OBJECTS VARCHAR2(30) := sys_context('userenv', 'current_schema');
  var$existe NUMBER;
BEGIN

  /* IX_SAPR_TMOVIMIENTO_03 */
  SELECT COUNT(1) INTO var$existe FROM ALL_INDEXES C WHERE UPPER(C.OWNER) = UPPER(OWNER_OBJECTS)  AND UPPER(C.TABLE_NAME) = 'SAPR_TMOVIMIENTO' AND C.INDEX_NAME = 'IX_SAPR_TMOVIMIENTO_03';
  IF var$existe = 0 THEN  
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SAPR_TMOVIMIENTO_03 ON SAPR_TMOVIMIENTO (COD_PAIS, COD_DEVICEID_BASE, FEC_MOVIMIENTO)  ONLINE';
  END IF;

  /* IX_SAPR_TMOVIMIENTO_04 */
  SELECT COUNT(1) INTO var$existe FROM ALL_INDEXES C WHERE UPPER(C.OWNER) = UPPER(OWNER_OBJECTS)  AND UPPER(C.TABLE_NAME) = 'SAPR_TMOVIMIENTO' AND C.INDEX_NAME = 'IX_SAPR_TMOVIMIENTO_04';
  IF var$existe = 0 THEN  
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SAPR_TMOVIMIENTO_04 ON SAPR_TMOVIMIENTO (COD_PAIS, COD_DEVICEID_BASE, FEC_MOVIMIENTO, SYS_EXTRACT_UTC(HOR_MOVIMIENTO), SYS_EXTRACT_UTC(FYH_ACREDITACION)) ONLINE';
  END IF;

  /* IX_SAPR_TMOVIMIENTO_05 */
  SELECT COUNT(1) INTO var$existe FROM ALL_INDEXES C WHERE UPPER(C.OWNER) = UPPER(OWNER_OBJECTS)  AND UPPER(C.TABLE_NAME) = 'SAPR_TMOVIMIENTO' AND C.INDEX_NAME = 'IX_SAPR_TMOVIMIENTO_05';
  IF var$existe = 0 THEN  
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SAPR_TMOVIMIENTO_05 ON SAPR_TMOVIMIENTO (COD_PAIS, FEC_MOVIMIENTO, COD_DEVICEID, COD_GRUPO_MOVIMIENTO) ONLINE';
  END IF;
  
EXCEPTION
  WHEN OTHERS THEN
    raise_application_error( -20001, 'Arquivo: Genesis.sql Script: SAPR_TMOVIMIENTO - Indexes ' || sqlerrm);
    RAISE;
END;
/