DECLARE
   OWNER_OBJECTS VARCHAR2(30) := '';
   EXISTE NUMBER;
BEGIN

  SELECT sys_context( 'userenv', 'current_schema' ) INTO OWNER_OBJECTS FROM DUAL;
  
  SELECT COUNT(1) INTO EXISTE FROM ALL_TABLES A WHERE UPPER(A.OWNER) = UPPER(OWNER_OBJECTS) AND UPPER(A.TABLE_NAME) = 'SAPR_TVALOR_TERMINOXDOCUMENTO';
  IF EXISTE = 1 THEN
    /* DES_VALOR */
    SELECT COUNT(1) INTO EXISTE FROM ALL_TAB_COLUMNS WHERE OWNER = OWNER_OBJECTS AND TABLE_NAME = 'SAPR_TVALOR_TERMINOXDOCUMENTO' AND COLUMN_NAME = 'DES_VALOR' AND DATA_LENGTH < 4000;        
    IF EXISTE = 1 THEN     
          EXECUTE IMMEDIATE 'ALTER TABLE SAPR_TVALOR_TERMINOXDOCUMENTO MODIFY DES_VALOR VARCHAR2(4000)';     
    END IF;     
  END IF;

  EXCEPTION
    WHEN OTHERS THEN raise_application_error( -20001, 'Arquivo: Genesis.sql Script: SAPR_TVALOR_TERMINOXDOCUMENTO - ' || sqlerrm);
    RAISE;
END;  
/