DECLARE
   OWNER_OBJECTS VARCHAR2(30) := '';
   EXISTE NUMBER;
BEGIN

   SELECT sys_context( 'userenv', 'current_schema' ) INTO OWNER_OBJECTS FROM DUAL;
    
   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'SAPR_TCUENTA';
   
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON SAPR_TCUENTA ]';
   END IF;   
       

   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TCLIENTE';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TCLIENTE ]';
   END IF;   
       

   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TSECTOR';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TSECTOR ]';
   END IF;
       

   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TPLANTA';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TPLANTA ]';
   END IF;
       

   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TDELEGACION';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TDELEGACION ]';
   END IF;
       
   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TSUBCANAL';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TSUBCANAL ]';
   END IF;
       
   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TCANAL';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TCANAL ]';
   END IF;
       
   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TSUBCLIENTE';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TSUBCLIENTE ]';
   END IF;
       
   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TPUNTO_SERVICIO';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TPUNTO_SERVICIO ]';
   END IF;
       
   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'SAPR_TMAQUINA';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON SAPR_TMAQUINA ]';
   END IF;
       
   SELECT COUNT(1) INTO EXISTE  FROM USER_MVIEW_LOGS WHERE MASTER = 'GEPR_TCODIGO_AJENO';
   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW LOG ON GEPR_TCODIGO_AJENO ]';
   END IF;
   


   SELECT COUNT(1) INTO EXISTE FROM ALL_MVIEWS WHERE MVIEW_NAME = 'SAPR_VMCUENTA';  


   IF EXISTE = 1 THEN
      EXECUTE IMMEDIATE q'[DROP MATERIALIZED VIEW SAPR_VMCUENTA ]';
   END IF;

   
  
EXCEPTION
   WHEN OTHERS THEN raise_application_error( -20001, 'Arquivo: Genesis.sql Script: SAPR_VMCUENTA - ' || sqlerrm);
   RAISE;
END;  
/