
BEGIN

INSERT INTO SAPR_TPLANXSUBCANAL (OID_PLANXSUBCANAL, OID_PLANXCANAL, OID_SUBCANAL, OID_MAQUINA, OID_PTO_SERVICIO, BOL_ACTIVO, GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION) 
WITH CANALES AS
  (SELECT PL.OID_PLANIFICACION,
          PL.COD_PLANIFICACION,
          PL.DES_PLANIFICACION,
          C.OID_CANAL,
          C.COD_CANAL,
          PC.OID_PLANXCANAL
   FROM SAPR_TPLANIFICACION PL
   INNER JOIN SAPR_TPLANXCANAL PC ON PL.OID_PLANIFICACION = PC.OID_PLANIFICACION AND PC.BOL_ACTIVO = 1
   INNER JOIN GEPR_TCANAL C ON C.OID_CANAL = PC.OID_CANAL  AND C.BOL_VIGENTE = 1
   LEFT JOIN SAPR_TPLANXSUBCANAL PSC ON PSC.OID_PLANXCANAL = PC.OID_PLANXCANAL AND PSC.BOL_ACTIVO = 1
   WHERE PSC.OID_PLANXSUBCANAL IS NULL )
SELECT  SYS_GUID() AS OID_PLANXSUBCANAL,
        CAN.OID_PLANXCANAL,
        SUBC.OID_SUBCANAL,
        NULL OID_MAQUINA,
        NULL OID_PTO_SERVICIO,
        1 AS BOL_ACTIVO,
        SYSTIMESTAMP AS GMT_CREACION,
        'SCRIPT_ACT_SAPR_TPLANXSUBCANAL' AS DES_USUARIO_CREACION,
        SYSTIMESTAMP GMT_MODIFICACION,
        'SCRIPT_ACT_SAPR_TPLANXSUBCANAL' AS DES_USUARIO_MODIFICACION
FROM CANALES CAN
INNER JOIN GEPR_TSUBCANAL SUBC ON CAN.OID_CANAL = SUBC.OID_CANAL
AND SUBC.BOL_VIGENTE = 1;

COMMIT;

END;
/
