create or replace TRIGGER TRG_GEPR_TCODIGO_AJENO_AFTER
AFTER UPDATE OR DELETE ON GEPR_TCODIGO_AJENO FOR EACH ROW
BEGIN    
    IF UPDATING AND :OLD.COD_IDENTIFICADOR <> :NEW.COD_IDENTIFICADOR THEN
        INSERT INTO SAPR_THISTORICO_CAMBIOS (OID_HISTORICO_CAMBIOS,
            OID_TABLA, COD_TABLA, COD_COLUMNA, DES_VALOR_ANTERIOR, DES_VALOR_ACTUAL,
            GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
        VALUES (SYS_GUID(), :OLD.OID_CODIGO_AJENO, 'GEPR_TCODIGO_AJENO', 'COD_IDENTIFICADOR', :OLD.COD_IDENTIFICADOR, :NEW.COD_IDENTIFICADOR, 
                SYSTIMESTAMP, :NEW.DES_USUARIO_MODIFICACION, SYSTIMESTAMP, :NEW.DES_USUARIO_MODIFICACION);
    END IF;
    
    IF UPDATING AND :OLD.COD_AJENO <> :NEW.COD_AJENO THEN
        INSERT INTO SAPR_THISTORICO_CAMBIOS (OID_HISTORICO_CAMBIOS,
            OID_TABLA, COD_TABLA, COD_COLUMNA, DES_VALOR_ANTERIOR, DES_VALOR_ACTUAL,
            GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
        VALUES (SYS_GUID(), :OLD.OID_CODIGO_AJENO, 'GEPR_TCODIGO_AJENO', 'COD_AJENO', :OLD.COD_AJENO, :NEW.COD_AJENO, 
                SYSTIMESTAMP, :NEW.DES_USUARIO_MODIFICACION, SYSTIMESTAMP, :NEW.DES_USUARIO_MODIFICACION);
    END IF;
    
    IF DELETING THEN
        INSERT INTO SAPR_THISTORICO_CAMBIOS (OID_HISTORICO_CAMBIOS,
            OID_TABLA, COD_TABLA, COD_COLUMNA, DES_VALOR_ANTERIOR, DES_VALOR_ACTUAL,
            GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
        VALUES (SYS_GUID(), :OLD.OID_CODIGO_AJENO, 'GEPR_TCODIGO_AJENO', 'COD_IDENTIFICADOR', :OLD.COD_IDENTIFICADOR, NULL, 
                SYSTIMESTAMP, :OLD.DES_USUARIO_MODIFICACION, SYSTIMESTAMP, :OLD.DES_USUARIO_MODIFICACION);
        INSERT INTO SAPR_THISTORICO_CAMBIOS (OID_HISTORICO_CAMBIOS,
            OID_TABLA, COD_TABLA, COD_COLUMNA, DES_VALOR_ANTERIOR, DES_VALOR_ACTUAL,
            GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
        VALUES (SYS_GUID(), :OLD.OID_CODIGO_AJENO, 'GEPR_TCODIGO_AJENO', 'COD_AJENO', :OLD.COD_AJENO, NULL, 
                SYSTIMESTAMP, :OLD.DES_USUARIO_MODIFICACION, SYSTIMESTAMP, :OLD.DES_USUARIO_MODIFICACION);
        INSERT INTO SAPR_THISTORICO_CAMBIOS (OID_HISTORICO_CAMBIOS,
            OID_TABLA, COD_TABLA, COD_COLUMNA, DES_VALOR_ANTERIOR, DES_VALOR_ACTUAL,
            GMT_CREACION, DES_USUARIO_CREACION, GMT_MODIFICACION, DES_USUARIO_MODIFICACION)
        VALUES (SYS_GUID(), :OLD.OID_CODIGO_AJENO, 'GEPR_TCODIGO_AJENO', 'BOL_ACTIVO', :OLD.BOL_ACTIVO, NULL, 
                SYSTIMESTAMP, :OLD.DES_USUARIO_MODIFICACION, SYSTIMESTAMP, :OLD.DES_USUARIO_MODIFICACION);
    END IF;
END TRG_GEPR_TCODIGO_AJENO_AFTER;