UPDATE GEPR_TINTEGRACION
SET
	COD_ESTADO = []COD_ESTADO, 
	NEL_INTENTO_ENVIO = []NEL_INTENTO_ENVIO + 1,
	GMT_MODIFICACION = FN_GMT_ZERO_###VERSION### ,
	DES_USUARIO_MODIFICACION = []DES_USUARIO_MODIFICACION
WHERE
	OID_INTEGRACION = []OID_INTEGRACION
