SELECT
	OID_INTEGRACION, 
	OID_TABLA_INTEGRACION, 
	COD_TABLA_INTEGRACION, 
	COD_ESTADO, 
	COD_MODULO_ORIGEN, 
	COD_MODULO_DESTINO, 
	COD_PROCESO, 
	NEL_INTENTO_ENVIO, 
	GMT_CREACION, 
	DES_USUARIO_CREACION, 
	GMT_MODIFICACION, 
	DES_USUARIO_MODIFICACION
FROM
	GEPR_TINTEGRACION
WHERE
	OID_TABLA_INTEGRACION = []OID_TABLA_INTEGRACION AND
	COD_PROCESO = []COD_PROCESO