INSERT INTO SAPR_TABONO_SALDO_TERMINO S
(S.OID_ABONO_SALDO_TERMINO,S.OID_ABONO_SALDO,S.OID_TERMINO,S.DES_VALOR,S.GMT_CREACION,
S.DES_USUARIO_CREACION,S.GMT_MODIFICACION,S.DES_USUARIO_MODIFICACION)
VALUES
([]OID_ABONO_SALDO_TERMINO,[]OID_ABONO_SALDO,[]OID_TERMINO,[]DES_VALOR,FN_GMT_ZERO_###VERSION###,
[]DES_USUARIO_CREACION,FN_GMT_ZERO_###VERSION###,[]DES_USUARIO_MODIFICACION)