DELETE SAPR_TABONO_SALDO_TERMINO AST
WHERE AST.OID_ABONO_SALDO IN (SELECT OID_ABONO_SALDO FROM SAPR_TABONO_SALDO ASAL
INNER JOIN SAPR_TABONO_VALOR ABV ON ASAL.OID_ABONO_VALOR = ABV.OID_ABONO_VALOR
WHERE ABV.OID_ABONO = []OID_ABONO)