SELECT
       TERM.OID_ABONO_SALDO_TERMINO,
       TERM.OID_ABONO_SALDO,
       TERM.OID_TERMINO,
       TERM.DES_VALOR
FROM
       SAPR_TABONO_SALDO_TERMINO TERM
WHERE 
       TERM.OID_ABONO_SALDO = :OID_ABONO_SALDO 