SELECT OID_FABRICANTE,
		COD_FABRICANTE, 
		DES_FABRICANTE, 
		DIRECCION, 
		BOL_ACTIVO,
		GMT_CREACION,
		DES_USUARIO_CREACION,
		GMT_CREACION, 
		GMT_MODIFICACION, 
		DES_USUARIO_MODIFICACION 
FROM SAPR_TFABRICANTE
