
SELECT
	
	 S.OID_SUBCANAL AS IDENTIFICADOR
	,S.OID_CANAL AS IDENTIFICADOR_PAI
	,S.COD_SUBCANAL	AS CODIGO
	,S.DES_SUBCANAL AS DESCRICAO
	,S.BOL_VIGENTE AS VIGENTE
	,S.OBS_SUBCANAL	
	,S.COD_USUARIO
	,S.FYH_ACTUALIZACION
	,S.BOL_POR_DEFECTO
	,S.COD_MIGRACION

FROM
	GEPR_TSUBCANAL S