  
WITH DATOS_ENTIDAD AS (
SELECT PTO.OID_PTO_SERVICIO AS OID_PTO_SERVICIO,
       PTO.OID_SUBCLIENTE AS OID_SUBCLIENTE,
       PTO.COD_PTO_SERVICIO AS COD_PTO_SERVICIO,
       PTO.DES_PTO_SERVICIO AS DES_PTO_SERVICIO,
       PTO.BOL_VIGENTE,
       PTO.COD_USUARIO,
       PTO.FYH_ACTUALIZACION,
       PTO.BOL_ENVIADO_SALDOS,
       PTO.OID_TIPO_PUNTO_SERVICIO,
       PTO.COD_MIGRACION,
       PTO.BOL_TOTALIZADOR_SALDO
  FROM GEPR_TPUNTO_SERVICIO PTO
 WHERE 1=1  {0} 
 
), DATOS_AJENO AS (
  SELECT
    COAJ.OID_TABLA_GENESIS OID_PTO_SERVICIO,
    PTO.OID_SUBCLIENTE AS OID_SUBCLIENTE,
    COAJ.COD_AJENO COD_PTO_SERVICIO,
    PTO.DES_PTO_SERVICIO AS DES_PTO_SERVICIO,
    PTO.BOL_VIGENTE,
    PTO.COD_USUARIO,
    PTO.FYH_ACTUALIZACION,
    PTO.BOL_ENVIADO_SALDOS,
    PTO.OID_TIPO_PUNTO_SERVICIO,
    PTO.COD_MIGRACION,
    PTO.BOL_TOTALIZADOR_SALDO
  FROM
    GEPR_TPUNTO_SERVICIO PTO
    INNER JOIN GEPR_TCODIGO_AJENO COAJ ON PTO.OID_PTO_SERVICIO = COAJ.OID_TABLA_GENESIS AND
                                          COAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TPUNTO_SERVICIO' AND
                                          COAJ.COD_IDENTIFICADOR = 'MAE'
  WHERE   1=1 {1}
  
  AND COAJ.OID_TABLA_GENESIS || COAJ.COD_AJENO NOT IN (SELECT OID_PTO_SERVICIO || COD_PTO_SERVICIO FROM DATOS_ENTIDAD)

),
PTO_SERVICIO AS (
SELECT
  OID_PTO_SERVICIO,
  OID_SUBCLIENTE,
  COD_PTO_SERVICIO,
  DES_PTO_SERVICIO,
  BOL_VIGENTE,
  COD_USUARIO,
  FYH_ACTUALIZACION,
  OID_TIPO_PUNTO_SERVICIO,
  BOL_ENVIADO_SALDOS,
  COD_MIGRACION,
  BOL_TOTALIZADOR_SALDO
FROM
  DATOS_ENTIDAD
WHERE
    BOL_VIGENTE = 1
UNION
SELECT
  OID_PTO_SERVICIO,
  OID_SUBCLIENTE,
  COD_PTO_SERVICIO || ' *'  COD_PTO_SERVICIO,
  DES_PTO_SERVICIO,
  BOL_VIGENTE,
  COD_USUARIO,
  FYH_ACTUALIZACION,
  OID_TIPO_PUNTO_SERVICIO,
  BOL_ENVIADO_SALDOS,
  COD_MIGRACION,
  BOL_TOTALIZADOR_SALDO
FROM
  DATOS_AJENO
WHERE
    BOL_VIGENTE = 1
    )
SELECT 
   P.OID_PTO_SERVICIO AS IDENTIFICADOR
  ,P.OID_SUBCLIENTE AS IDENTIFICADOR_PAI
  ,P.COD_PTO_SERVICIO AS CODIGO
  ,P.DES_PTO_SERVICIO AS DESCRICAO
  ,P.BOL_VIGENTE AS VIGENTE
  ,P.COD_USUARIO
  ,P.FYH_ACTUALIZACION
  ,P.BOL_ENVIADO_SALDOS
  ,P.OID_TIPO_PUNTO_SERVICIO
  ,P.COD_MIGRACION
  ,P.BOL_TOTALIZADOR_SALDO
FROM PTO_SERVICIO P
WHERE
1=1
  