
WITH DATOS_ENTIDAD AS (
SELECT CLIE.OID_CLIENTE AS OID_CLIENTE,
       CLIE.COD_CLIENTE AS COD,
       CLIE.DES_CLIENTE AS DESCRICAO,
       CLIE.BOL_VIGENTE AS VIGENTE,
       CLIE.COD_USUARIO,
       CLIE.FYH_ACTUALIZACION,
       CLIE.BOL_ENVIADO_SALDOS,
       CLIE.OID_TIPO_CLIENTE,
       CLIE.COD_MIGRACION,
       CLIE.BOL_TOTALIZADOR_SALDO
  FROM GEPR_TCLIENTE CLIE
  INNER JOIN GEPR_TTIPO_CLIENTE CLIT ON CLIT.OID_TIPO_CLIENTE = CLIE.OID_TIPO_CLIENTE
 WHERE 1=1 {0}
 
), DATOS_AJENO AS (
  SELECT
    COAJ.OID_TABLA_GENESIS OID_CLIENTE,
    COAJ.COD_AJENO COD,
    CLIE.DES_CLIENTE AS DESCRICAO,
    CLIE.BOL_VIGENTE AS VIGENTE,
    CLIE.COD_USUARIO,
    CLIE.FYH_ACTUALIZACION,
    CLIE.BOL_ENVIADO_SALDOS,
    CLIE.OID_TIPO_CLIENTE,
    CLIE.COD_MIGRACION,
    CLIE.BOL_TOTALIZADOR_SALDO
  FROM
    GEPR_TCLIENTE CLIE
    INNER JOIN GEPR_TTIPO_CLIENTE CLIT ON CLIT.OID_TIPO_CLIENTE = CLIE.OID_TIPO_CLIENTE
    INNER JOIN GEPR_TCODIGO_AJENO COAJ ON CLIE.OID_CLIENTE = COAJ.OID_TABLA_GENESIS AND
                                          COAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TCLIENTE' AND
                                          COAJ.COD_IDENTIFICADOR = 'MAE'
  WHERE   1=1 
    {1}
  AND COAJ.OID_TABLA_GENESIS || COAJ.COD_AJENO NOT IN (SELECT OID_CLIENTE || COD FROM DATOS_ENTIDAD)

),
CLIENTES AS (
SELECT
  DE.OID_CLIENTE,
  DE.COD AS COD_CLIENTE,
  DE.DESCRICAO AS DES_CLIENTE,
  DE.VIGENTE,
  DE.COD_USUARIO,
  DE.FYH_ACTUALIZACION,
  DE.BOL_ENVIADO_SALDOS,
  DE.OID_TIPO_CLIENTE,
  DE.COD_MIGRACION,
  DE.BOL_TOTALIZADOR_SALDO
FROM
  DATOS_ENTIDAD DE
WHERE
    DE.VIGENTE = 1
UNION
SELECT
  DA.OID_CLIENTE,
  DA.COD || ' *' AS COD_CLIENTE,
  DA.DESCRICAO AS DES_CLIENTE,
  DA.VIGENTE,
  DA.COD_USUARIO,
  DA.FYH_ACTUALIZACION,
  DA.BOL_ENVIADO_SALDOS,
  DA.OID_TIPO_CLIENTE,
  DA.COD_MIGRACION,
  DA.BOL_TOTALIZADOR_SALDO
FROM
  DATOS_AJENO DA
WHERE
    DA.VIGENTE=1
    )
SELECT 
  C.OID_CLIENTE AS IDENTIFICADOR,
  C.COD_CLIENTE AS CODIGO,
  C.DES_CLIENTE AS DESCRICAO,
  C.VIGENTE,
  C.COD_USUARIO,
  C.FYH_ACTUALIZACION,
  C.BOL_ENVIADO_SALDOS,
  C.OID_TIPO_CLIENTE,
  C.COD_MIGRACION,
  C.BOL_TOTALIZADOR_SALDO
FROM CLIENTES C
WHERE
1=1 