WITH DATOS_ENTIDAD AS (
SELECT SCLI.OID_SUBCLIENTE AS OID_SUBCLIENTE,
       SCLI.OID_CLIENTE AS OID_CLIENTE,
       SCLI.COD_SUBCLIENTE AS COD_SUBCLIENTE,
       SCLI.DES_SUBCLIENTE AS DES_SUBCLIENTE,
       SCLI.BOL_VIGENTE,
       SCLI.COD_USUARIO,
       SCLI.FYH_ACTUALIZACION,
       SCLI.BOL_ENVIADO_SALDOS,
       SCLI.OID_TIPO_SUBCLIENTE,
       SCLI.COD_MIGRACION,
       SCLI.BOL_TOTALIZADOR_SALDO
  FROM GEPR_TSUBCLIENTE SCLI
 WHERE 1=1  {0} 
 
), DATOS_AJENO AS (
  SELECT
    COAJ.OID_TABLA_GENESIS OID_SUBCLIENTE,
    SCLI.OID_CLIENTE AS OID_CLIENTE,
    COAJ.COD_AJENO COD_SUBCLIENTE,
    SCLI.DES_SUBCLIENTE AS DES_SUBCLIENTE,
    SCLI.BOL_VIGENTE,
    SCLI.COD_USUARIO,
    SCLI.FYH_ACTUALIZACION,
    SCLI.BOL_ENVIADO_SALDOS,
    SCLI.OID_TIPO_SUBCLIENTE,
    SCLI.COD_MIGRACION,
    SCLI.BOL_TOTALIZADOR_SALDO
  FROM
    GEPR_TSUBCLIENTE SCLI
    INNER JOIN GEPR_TCODIGO_AJENO COAJ ON SCLI.OID_SUBCLIENTE = COAJ.OID_TABLA_GENESIS AND
                                          COAJ.COD_TIPO_TABLA_GENESIS = 'GEPR_TSUBCLIENTE' AND
                                          COAJ.COD_IDENTIFICADOR = 'MAE'
  WHERE   1=1 {1}
  
  AND COAJ.OID_TABLA_GENESIS || COAJ.COD_AJENO NOT IN (SELECT OID_SUBCLIENTE || COD_SUBCLIENTE FROM DATOS_ENTIDAD)

),
SUBCLIENTES AS (
SELECT
  OID_SUBCLIENTE,
  OID_CLIENTE,
  COD_SUBCLIENTE,
  DES_SUBCLIENTE,
  BOL_VIGENTE,
  COD_USUARIO,
  FYH_ACTUALIZACION,
  OID_TIPO_SUBCLIENTE,
  BOL_ENVIADO_SALDOS,
  COD_MIGRACION,
  BOL_TOTALIZADOR_SALDO
FROM
  DATOS_ENTIDAD
WHERE
    BOL_VIGENTE = 1
UNION
SELECT
  OID_SUBCLIENTE,
  OID_CLIENTE,
  COD_SUBCLIENTE || ' *'  COD_SUBCLIENTE,
  DES_SUBCLIENTE,
  BOL_VIGENTE,
  COD_USUARIO,
  FYH_ACTUALIZACION,
  OID_TIPO_SUBCLIENTE,
  BOL_ENVIADO_SALDOS,
  COD_MIGRACION,
  BOL_TOTALIZADOR_SALDO
FROM
  DATOS_AJENO
WHERE
    BOL_VIGENTE = 1
    )
SELECT 
   OID_SUBCLIENTE AS IDENTIFICADOR
  ,OID_CLIENTE AS IDENTIFICADOR_PAI
  ,COD_SUBCLIENTE AS CODIGO
  ,DES_SUBCLIENTE AS DESCRICAO
  ,BOL_VIGENTE AS VIGENTE
  ,COD_USUARIO
  ,FYH_ACTUALIZACION
  ,BOL_ENVIADO_SALDOS
  ,OID_TIPO_SUBCLIENTE
  ,COD_MIGRACION
  ,BOL_TOTALIZADOR_SALDO
FROM SUBCLIENTES
WHERE 1 = 1 
  