WITH TERM AS (
    SELECT CAMPO_EXTRA.OID_TERMINO,
                campo_extra.cod_termino,
                campo_Extra.des_termino,
                campo_extra.bol_vigente
  FROM    GEPR_TTERMINO CAMPO_EXTRA
       INNER JOIN
          GEPR_TTERMINO_POR_IAC
       ON GEPR_TTERMINO_POR_IAC.OID_TERMINO=CAMPO_EXTRA.OID_TERMINO and CAMPO_EXTRA.bol_vigente = '1'
       INNER JOIN
        GEPR_TINFORM_ADICIONAL_CLIENTE
            ON GEPR_TINFORM_ADICIONAL_CLIENTE .OID_IAC=GEPR_TTERMINO_POR_IAC.OID_IAC
        INNER JOIN SAPR_TFORMULARIO
            ON      SAPR_TFORMULARIO.OID_IAC_INDIVIDUAL=GEPR_TINFORM_ADICIONAL_CLIENTE .OID_IAC AND SAPR_TFORMULARIO.DES_COD_EXTERNO= 'ACCREDITATION'
)
SELECT T.OID_TERMINO as IDENTIFICADOR,
    T.cod_termino as CODIGO,
    T.des_termino as DESCRICAO,
    T.bol_vigente as BOL_VIGENTE
FROM TERM T