WITH SECTOR AS (
    SELECT  
     M.OID_MAQUINA
    ,M.COD_IDENTIFICACION
    ,S.DES_SECTOR
    ,M.BOL_ACTIVO
    ,S.OID_CLIENTE
    ,P.OID_DELEGACION

  FROM
    SAPR_TMAQUINA M 
    INNER JOIN GEPR_TSECTOR S ON M.OID_SECTOR = S.OID_SECTOR
    INNER JOIN GEPR_TPLANTA P ON P.OID_PLANTA = S.OID_PLANTA     
    INNER JOIN GEPR_TPUNTO_SERVICIO P ON  P.OID_MAQUINA = M.OID_MAQUINA
    INNER JOIN GEPR_TSUBCLIENTE S ON S.OID_SUBCLIENTE = P.OID_SUBCLIENTE   
	GROUP BY  M.OID_MAQUINA    ,M.COD_IDENTIFICACION    ,S.DES_SECTOR    ,M.BOL_ACTIVO    ,S.OID_CLIENTE    ,P.OID_DELEGACION
     )
    SELECT 
     M.OID_MAQUINA  AS IDENTIFICADOR
    ,M.OID_CLIENTE AS IDENTIFICADOR_PAI
    ,M.COD_IDENTIFICACION AS CODIGO
    ,M.DES_SECTOR AS DESCRICAO
    ,M.OID_DELEGACION AS OID_DELEGACION    
     FROM SECTOR M
    