
SELECT
  
	 P.OID_PLANTA AS IDENTIFICADOR
	,P.OID_DELEGACION AS IDENTIFICADOR_PAI
	,P.COD_PLANTA AS CODIGO
	,P.DES_PLANTA AS DESCRICAO
	,P.BOL_ACTIVO AS VIGENTE
	,P.COD_MIGRACION	
	,P.GMT_CREACION
	,P.DES_USUARIO_CREACION
	,P.GMT_MODIFICACION
	,P.DES_USUARIO_MODIFICACION

FROM
   GEPR_TPLANTA P