SELECT
   C.OID_TIPO_CONTENEDOR  AS IDENTIFICADOR
	,C.COD_TIPO_CONTENEDOR  AS CODIGO
	,C.DES_TIPO_CONTENEDOR  AS DESCRICAO
    ,C.NEC_CANTIDAD AS NEC_CANTIDAD
    ,UM.NUM_VALOR_UNIDAD AS NUM_VALOR_UNIDAD
    , UM.COD_UNIDAD_MEDIDA as COD_UNIDAD_MEDIDA
	,UM.OID_UNIDAD_MEDIDA AS OID_UNIDAD_MEDIDA
	,UM.DES_UNIDAD_MEDIDA AS DES_UNIDAD_MEDIDA
    , UM.COD_TIPO_UNIDAD_MEDIDA as COD_TIPO_UNIDAD_MEDIDA
	, C.BOL_LLEVA_PRECINTO
FROM
	SAPR_TTIPO_CONTENEDOR C
    LEFT JOIN GEPR_TUNIDAD_MEDIDA UM ON UM.OID_UNIDAD_MEDIDA = C.OID_UNIDAD_MEDIDA