
SELECT

	 D.OID_DELEGACION AS IDENTIFICADOR
	,D.COD_DELEGACION AS CODIGO
	,D.DES_DELEGACION AS DESCRICAO
	,D.BOL_VIGENTE AS VIGENTE
	,D.OID_PAIS
	,D.COD_PAIS
	,D.NEC_GMT_MINUTOS
	,D.FYH_VERANO_INICIO
	,D.FYH_VERANO_FIN
	,D.NEC_VERANO_AJUSTE
	,D.DES_ZONA
	,D.GMT_CREACION
	,D.DES_USUARIO_CREACION
	,D.GMT_MODIFICACION
	,D.DES_USUARIO_MODIFICACION
	
FROM
   GEPR_TDELEGACION D